module Telnyx
  module Resources
    class PhoneNumbers
      class Messaging
        def retrieve: (
          String id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::PhoneNumbers::MessagingRetrieveResponse

        def update: (
          String id,
          ?messaging_product: String,
          ?messaging_profile_id: String,
          ?tags: ::Array[String],
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::PhoneNumbers::MessagingUpdateResponse

        def list: (
          ?filter_messaging_profile_id: String,
          ?filter_phone_number: String,
          ?filter_phone_number_contains: String,
          ?filter_type: Telnyx::Models::PhoneNumbers::MessagingListParams::filter_type,
          ?page_number: Integer,
          ?page_size: Integer,
          ?sort_phone_number: Telnyx::Models::PhoneNumbers::MessagingListParams::sort_phone_number,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::PhoneNumberWithMessagingSettings]

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
