module Telnyx
  module Models
    module Reputation
      type number_retrieve_response =
        { data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data }

      class NumberRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data?

        def data=: (
          Telnyx::Models::Reputation::NumberRetrieveResponse::Data
        ) -> Telnyx::Models::Reputation::NumberRetrieveResponse::Data

        def initialize: (
          ?data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data
        ) -> void

        def to_hash: -> {
          data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data
        }

        type data =
          {
            id: String,
            created_at: Time,
            enterprise_id: String,
            phone_number: String,
            reputation_data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?,
            updated_at: Time
          }

        class Data < Telnyx::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader enterprise_id: String?

          def enterprise_id=: (String) -> String

          attr_reader phone_number: String?

          def phone_number=: (String) -> String

          attr_reader reputation_data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?

          def reputation_data=: (
            Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?
          ) -> Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?

          attr_reader updated_at: Time?

          def updated_at=: (Time) -> Time

          def initialize: (
            ?id: String,
            ?created_at: Time,
            ?enterprise_id: String,
            ?phone_number: String,
            ?reputation_data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?,
            ?updated_at: Time
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Time,
            enterprise_id: String,
            phone_number: String,
            reputation_data: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data?,
            updated_at: Time
          }

          type reputation_data =
            (Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData
            | top)?

          module ReputationData
            extend Telnyx::Internal::Type::Union

            type reputation_data =
              {
                connection_score: Integer?,
                engagement_score: Integer?,
                last_refreshed_at: Time?,
                maturity_score: Integer?,
                sentiment_score: Integer?,
                spam_category: String?,
                spam_risk: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData::spam_risk?
              }

            class ReputationData < Telnyx::Internal::Type::BaseModel
              attr_accessor connection_score: Integer?

              attr_accessor engagement_score: Integer?

              attr_accessor last_refreshed_at: Time?

              attr_accessor maturity_score: Integer?

              attr_accessor sentiment_score: Integer?

              attr_accessor spam_category: String?

              attr_accessor spam_risk: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData::spam_risk?

              def initialize: (
                ?connection_score: Integer?,
                ?engagement_score: Integer?,
                ?last_refreshed_at: Time?,
                ?maturity_score: Integer?,
                ?sentiment_score: Integer?,
                ?spam_category: String?,
                ?spam_risk: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData::spam_risk?
              ) -> void

              def to_hash: -> {
                connection_score: Integer?,
                engagement_score: Integer?,
                last_refreshed_at: Time?,
                maturity_score: Integer?,
                sentiment_score: Integer?,
                spam_category: String?,
                spam_risk: Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData::spam_risk?
              }

              type spam_risk = :low | :medium | :high

              module SpamRisk
                extend Telnyx::Internal::Type::Enum

                LOW: :low
                MEDIUM: :medium
                HIGH: :high

                def self?.values: -> ::Array[Telnyx::Models::Reputation::NumberRetrieveResponse::Data::ReputationData::ReputationData::spam_risk]
              end
            end

            def self?.variants: -> ::Array[Telnyx::Models::Reputation::NumberRetrieveResponse::Data::reputation_data]
          end
        end
      end
    end
  end
end
