module Telnyx
  module Models
    module Reputation
      type number_retrieve_response =
        { data: Telnyx::ReputationPhoneNumberWithReputationData }

      class NumberRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::ReputationPhoneNumberWithReputationData?

        def data=: (
          Telnyx::ReputationPhoneNumberWithReputationData
        ) -> Telnyx::ReputationPhoneNumberWithReputationData

        def initialize: (
          ?data: Telnyx::ReputationPhoneNumberWithReputationData
        ) -> void

        def to_hash: -> {
          data: Telnyx::ReputationPhoneNumberWithReputationData
        }
      end
    end
  end
end
