module Telnyx
  module Models
    module AI
      module Collections
        type source_create_params =
          { uuid: String } & Telnyx::Internal::Type::request_parameters

        class SourceCreateParams < Telnyx::Models::AI::Collections::SourceRequest
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          def uuid: -> String

          def uuid=: (String _) -> String

          def initialize: (
            uuid: String,
            ?request_options: Telnyx::request_opts
          ) -> void

          def to_hash: -> {
            uuid: String,
            request_options: Telnyx::RequestOptions
          }
        end
      end
    end
  end
end
