module Telnyx
  module Models
    module MessagingTollfree
      module Verification
        type request_create_params =
          {  } & Telnyx::Internal::Type::request_parameters

        class RequestCreateParams < Telnyx::Models::MessagingTollfree::Verification::TfVerificationRequest
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          def initialize: (?request_options: Telnyx::request_opts) -> void

          def to_hash: -> { request_options: Telnyx::RequestOptions }
        end
      end
    end
  end
end
