module Telnyx
  module Models
    module MessagingTollfree
      class VerificationRequestEgress = Verification::VerificationRequestEgress

      module Verification
        type verification_request_egress =
          {
            id: String,
            additional_information: String,
            :business_addr1 => String,
            business_city: String,
            business_contact_email: String,
            business_contact_first_name: String,
            business_contact_last_name: String,
            business_contact_phone: String,
            business_name: String,
            business_state: String,
            business_zip: String,
            corporate_website: String,
            isv_reseller: String,
            message_volume: Telnyx::Models::MessagingTollfree::Verification::volume,
            opt_in_workflow: String,
            opt_in_workflow_image_urls: ::Array[Telnyx::MessagingTollfree::Verification::URL],
            phone_numbers: ::Array[Telnyx::MessagingTollfree::Verification::TfPhoneNumber],
            production_message_content: String,
            use_case: Telnyx::Models::MessagingTollfree::Verification::use_case_categories,
            use_case_summary: String,
            verification_request_id: String,
            age_gated_content: bool,
            :business_addr2 => String,
            business_registration_country: String,
            business_registration_number: String,
            business_registration_type: String,
            doing_business_as: String,
            entity_type: Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type,
            help_message_response: String,
            opt_in_confirmation_response: String,
            opt_in_keywords: String,
            privacy_policy_url: String,
            terms_and_condition_url: String,
            verification_status: Telnyx::Models::MessagingTollfree::Verification::tf_verification_status,
            webhook_url: String
          }

        class VerificationRequestEgress < Telnyx::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor additional_information: String

          attr_accessor business_addr1: String

          attr_accessor business_city: String

          attr_accessor business_contact_email: String

          attr_accessor business_contact_first_name: String

          attr_accessor business_contact_last_name: String

          attr_accessor business_contact_phone: String

          attr_accessor business_name: String

          attr_accessor business_state: String

          attr_accessor business_zip: String

          attr_accessor corporate_website: String

          attr_accessor isv_reseller: String

          attr_accessor message_volume: Telnyx::Models::MessagingTollfree::Verification::volume

          attr_accessor opt_in_workflow: String

          attr_accessor opt_in_workflow_image_urls: ::Array[Telnyx::MessagingTollfree::Verification::URL]

          attr_accessor phone_numbers: ::Array[Telnyx::MessagingTollfree::Verification::TfPhoneNumber]

          attr_accessor production_message_content: String

          attr_accessor use_case: Telnyx::Models::MessagingTollfree::Verification::use_case_categories

          attr_accessor use_case_summary: String

          attr_accessor verification_request_id: String

          attr_reader age_gated_content: bool?

          def age_gated_content=: (bool) -> bool

          attr_reader business_addr2: String?

          def business_addr2=: (String) -> String

          attr_reader business_registration_country: String?

          def business_registration_country=: (String) -> String

          attr_reader business_registration_number: String?

          def business_registration_number=: (String) -> String

          attr_reader business_registration_type: String?

          def business_registration_type=: (String) -> String

          attr_reader doing_business_as: String?

          def doing_business_as=: (String) -> String

          attr_reader entity_type: Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type?

          def entity_type=: (
            Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type
          ) -> Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type

          attr_reader help_message_response: String?

          def help_message_response=: (String) -> String

          attr_reader opt_in_confirmation_response: String?

          def opt_in_confirmation_response=: (String) -> String

          attr_reader opt_in_keywords: String?

          def opt_in_keywords=: (String) -> String

          attr_reader privacy_policy_url: String?

          def privacy_policy_url=: (String) -> String

          attr_reader terms_and_condition_url: String?

          def terms_and_condition_url=: (String) -> String

          attr_reader verification_status: Telnyx::Models::MessagingTollfree::Verification::tf_verification_status?

          def verification_status=: (
            Telnyx::Models::MessagingTollfree::Verification::tf_verification_status
          ) -> Telnyx::Models::MessagingTollfree::Verification::tf_verification_status

          attr_reader webhook_url: String?

          def webhook_url=: (String) -> String

          def initialize: (
            id: String,
            additional_information: String,
            business_addr1: String,
            business_city: String,
            business_contact_email: String,
            business_contact_first_name: String,
            business_contact_last_name: String,
            business_contact_phone: String,
            business_name: String,
            business_state: String,
            business_zip: String,
            corporate_website: String,
            isv_reseller: String,
            message_volume: Telnyx::Models::MessagingTollfree::Verification::volume,
            opt_in_workflow: String,
            opt_in_workflow_image_urls: ::Array[Telnyx::MessagingTollfree::Verification::URL],
            phone_numbers: ::Array[Telnyx::MessagingTollfree::Verification::TfPhoneNumber],
            production_message_content: String,
            use_case: Telnyx::Models::MessagingTollfree::Verification::use_case_categories,
            use_case_summary: String,
            verification_request_id: String,
            ?age_gated_content: bool,
            ?business_addr2: String,
            ?business_registration_country: String,
            ?business_registration_number: String,
            ?business_registration_type: String,
            ?doing_business_as: String,
            ?entity_type: Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type,
            ?help_message_response: String,
            ?opt_in_confirmation_response: String,
            ?opt_in_keywords: String,
            ?privacy_policy_url: String,
            ?terms_and_condition_url: String,
            ?verification_status: Telnyx::Models::MessagingTollfree::Verification::tf_verification_status,
            ?webhook_url: String
          ) -> void

          def to_hash: -> {
            id: String,
            additional_information: String,
            :business_addr1 => String,
            business_city: String,
            business_contact_email: String,
            business_contact_first_name: String,
            business_contact_last_name: String,
            business_contact_phone: String,
            business_name: String,
            business_state: String,
            business_zip: String,
            corporate_website: String,
            isv_reseller: String,
            message_volume: Telnyx::Models::MessagingTollfree::Verification::volume,
            opt_in_workflow: String,
            opt_in_workflow_image_urls: ::Array[Telnyx::MessagingTollfree::Verification::URL],
            phone_numbers: ::Array[Telnyx::MessagingTollfree::Verification::TfPhoneNumber],
            production_message_content: String,
            use_case: Telnyx::Models::MessagingTollfree::Verification::use_case_categories,
            use_case_summary: String,
            verification_request_id: String,
            age_gated_content: bool,
            :business_addr2 => String,
            business_registration_country: String,
            business_registration_number: String,
            business_registration_type: String,
            doing_business_as: String,
            entity_type: Telnyx::Models::MessagingTollfree::Verification::toll_free_verification_entity_type,
            help_message_response: String,
            opt_in_confirmation_response: String,
            opt_in_keywords: String,
            privacy_policy_url: String,
            terms_and_condition_url: String,
            verification_status: Telnyx::Models::MessagingTollfree::Verification::tf_verification_status,
            webhook_url: String
          }
        end
      end
    end
  end
end
