module Telnyx
  module Models
    module Number10dlc
      type campaign_appeal_response = { appealed_at: Time }

      class CampaignAppealResponse < Telnyx::Internal::Type::BaseModel
        attr_reader appealed_at: Time?

        def appealed_at=: (Time) -> Time

        def initialize: (?appealed_at: Time) -> void

        def to_hash: -> { appealed_at: Time }
      end
    end
  end
end
