module Telnyx
  module Models
    module Number10dlc
      type phone_number_assignment_by_profile_retrieve_phone_numbers_params =
        { page: Integer, records_per_page: Integer }
        & Telnyx::Internal::Type::request_parameters

      class PhoneNumberAssignmentByProfileRetrievePhoneNumbersParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_reader page: Integer?

        def page=: (Integer) -> Integer

        attr_reader records_per_page: Integer?

        def records_per_page=: (Integer) -> Integer

        def initialize: (
          ?page: Integer,
          ?records_per_page: Integer,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          page: Integer,
          records_per_page: Integer,
          request_options: Telnyx::RequestOptions
        }
      end
    end
  end
end
