# typed: strong

module Telnyx
  module Models
    # Campaign is generated by the 10DLC registry once the corresponding campaign
    # request is approved. Each campaign is assigned a unique identifier -
    # **campaignId**. Once a campaign is activated, limited information is published
    # to the NetNumber OSR service for consumption by members of the ecosystem. When a
    # campaign is suspended(reversible) or expired(non-reversible), campaign data is
    # deleted from the OSR service. Most attributes of campaignare immutable,
    # including **usecase**, **vertical**, **brandId** and **cspId**.
    module CampaignBuilderCreateResponse
      extend Telnyx::Internal::Type::Union

      Variants = T.type_alias { T.any(T.anything, Telnyx::TelnyxCampaignCsp) }

      sig do
        override.returns(
          T::Array[Telnyx::Models::CampaignBuilderCreateResponse::Variants]
        )
      end
      def self.variants
      end
    end
  end
end
