# typed: strong

module Telnyx
  module Models
    class UacInboundRequest < Telnyx::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(Telnyx::UacInboundRequest, Telnyx::Internal::AnyHash)
        end

      # This setting allows you to set the format with which the caller's number (ANI)
      # is sent for inbound phone calls.
      sig do
        returns(T.nilable(Telnyx::UacInboundRequest::AniNumberFormat::OrSymbol))
      end
      attr_reader :ani_number_format

      sig do
        params(
          ani_number_format:
            Telnyx::UacInboundRequest::AniNumberFormat::OrSymbol
        ).void
      end
      attr_writer :ani_number_format

      # When set, this will limit the total number of inbound calls to phone numbers
      # associated with this connection.
      sig { returns(T.nilable(Integer)) }
      attr_reader :channel_limit

      sig { params(channel_limit: Integer).void }
      attr_writer :channel_limit

      # Defines the list of codecs that Telnyx will send for inbound calls to a specific
      # number on your portal account, in priority order. This only works when the
      # Connection the number is assigned to uses Media Handling mode: default. OPUS and
      # H.264 codecs are available only when using TCP or TLS transport for SIP.
      sig { returns(T.nilable(T::Array[String])) }
      attr_reader :codecs

      sig { params(codecs: T::Array[String]).void }
      attr_writer :codecs

      # Default routing method to be used when a number is associated with the
      # connection. Must be one of the routing method types or left blank, other values
      # are not allowed.
      sig do
        returns(
          T.nilable(Telnyx::UacInboundRequest::DefaultRoutingMethod::OrSymbol)
        )
      end
      attr_reader :default_routing_method

      sig do
        params(
          default_routing_method:
            Telnyx::UacInboundRequest::DefaultRoutingMethod::OrSymbol
        ).void
      end
      attr_writer :default_routing_method

      sig do
        returns(
          T.nilable(Telnyx::UacInboundRequest::DnisNumberFormat::OrSymbol)
        )
      end
      attr_reader :dnis_number_format

      sig do
        params(
          dnis_number_format:
            Telnyx::UacInboundRequest::DnisNumberFormat::OrSymbol
        ).void
      end
      attr_writer :dnis_number_format

      # Generate ringback tone through 183 session progress message with early media.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :generate_ringback_tone

      sig { params(generate_ringback_tone: T::Boolean).void }
      attr_writer :generate_ringback_tone

      # When set, inbound phone calls will receive ISUP parameters via SIP headers.
      # (Only when available and only when using TCP or TLS transport.)
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :isup_headers_enabled

      sig { params(isup_headers_enabled: T::Boolean).void }
      attr_writer :isup_headers_enabled

      # Enable PRACK messages as defined in RFC3262.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :prack_enabled

      sig { params(prack_enabled: T::Boolean).void }
      attr_writer :prack_enabled

      # When enabled the SIP Connection will receive the Identity header with
      # Shaken/Stir data in the SIP INVITE message of inbound calls, even when using UDP
      # transport.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :shaken_stir_enabled

      sig { params(shaken_stir_enabled: T::Boolean).void }
      attr_writer :shaken_stir_enabled

      # When enabled, allows multiple devices to ring simultaneously on incoming calls.
      sig do
        returns(
          T.nilable(Telnyx::UacInboundRequest::SimultaneousRinging::OrSymbol)
        )
      end
      attr_reader :simultaneous_ringing

      sig do
        params(
          simultaneous_ringing:
            Telnyx::UacInboundRequest::SimultaneousRinging::OrSymbol
        ).void
      end
      attr_writer :simultaneous_ringing

      # Defaults to true.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :sip_compact_headers_enabled

      sig { params(sip_compact_headers_enabled: T::Boolean).void }
      attr_writer :sip_compact_headers_enabled

      # Time(sec) before aborting if connection is not made.
      sig { returns(T.nilable(Integer)) }
      attr_reader :timeout_1xx_secs

      sig { params(timeout_1xx_secs: Integer).void }
      attr_writer :timeout_1xx_secs

      # Time(sec) before aborting if call is unanswered (min: 1, max: 600).
      sig { returns(T.nilable(Integer)) }
      attr_reader :timeout_2xx_secs

      sig { params(timeout_2xx_secs: Integer).void }
      attr_writer :timeout_2xx_secs

      # Inbound settings that can be supplied when creating or updating a UAC
      # connection. The SIP subdomain fields returned in UAC connection responses are
      # generated by Telnyx and are not accepted as request parameters.
      sig do
        params(
          ani_number_format:
            Telnyx::UacInboundRequest::AniNumberFormat::OrSymbol,
          channel_limit: Integer,
          codecs: T::Array[String],
          default_routing_method:
            Telnyx::UacInboundRequest::DefaultRoutingMethod::OrSymbol,
          dnis_number_format:
            Telnyx::UacInboundRequest::DnisNumberFormat::OrSymbol,
          generate_ringback_tone: T::Boolean,
          isup_headers_enabled: T::Boolean,
          prack_enabled: T::Boolean,
          shaken_stir_enabled: T::Boolean,
          simultaneous_ringing:
            Telnyx::UacInboundRequest::SimultaneousRinging::OrSymbol,
          sip_compact_headers_enabled: T::Boolean,
          timeout_1xx_secs: Integer,
          timeout_2xx_secs: Integer
        ).returns(T.attached_class)
      end
      def self.new(
        # This setting allows you to set the format with which the caller's number (ANI)
        # is sent for inbound phone calls.
        ani_number_format: nil,
        # When set, this will limit the total number of inbound calls to phone numbers
        # associated with this connection.
        channel_limit: nil,
        # Defines the list of codecs that Telnyx will send for inbound calls to a specific
        # number on your portal account, in priority order. This only works when the
        # Connection the number is assigned to uses Media Handling mode: default. OPUS and
        # H.264 codecs are available only when using TCP or TLS transport for SIP.
        codecs: nil,
        # Default routing method to be used when a number is associated with the
        # connection. Must be one of the routing method types or left blank, other values
        # are not allowed.
        default_routing_method: nil,
        dnis_number_format: nil,
        # Generate ringback tone through 183 session progress message with early media.
        generate_ringback_tone: nil,
        # When set, inbound phone calls will receive ISUP parameters via SIP headers.
        # (Only when available and only when using TCP or TLS transport.)
        isup_headers_enabled: nil,
        # Enable PRACK messages as defined in RFC3262.
        prack_enabled: nil,
        # When enabled the SIP Connection will receive the Identity header with
        # Shaken/Stir data in the SIP INVITE message of inbound calls, even when using UDP
        # transport.
        shaken_stir_enabled: nil,
        # When enabled, allows multiple devices to ring simultaneously on incoming calls.
        simultaneous_ringing: nil,
        # Defaults to true.
        sip_compact_headers_enabled: nil,
        # Time(sec) before aborting if connection is not made.
        timeout_1xx_secs: nil,
        # Time(sec) before aborting if call is unanswered (min: 1, max: 600).
        timeout_2xx_secs: nil
      )
      end

      sig do
        override.returns(
          {
            ani_number_format:
              Telnyx::UacInboundRequest::AniNumberFormat::OrSymbol,
            channel_limit: Integer,
            codecs: T::Array[String],
            default_routing_method:
              Telnyx::UacInboundRequest::DefaultRoutingMethod::OrSymbol,
            dnis_number_format:
              Telnyx::UacInboundRequest::DnisNumberFormat::OrSymbol,
            generate_ringback_tone: T::Boolean,
            isup_headers_enabled: T::Boolean,
            prack_enabled: T::Boolean,
            shaken_stir_enabled: T::Boolean,
            simultaneous_ringing:
              Telnyx::UacInboundRequest::SimultaneousRinging::OrSymbol,
            sip_compact_headers_enabled: T::Boolean,
            timeout_1xx_secs: Integer,
            timeout_2xx_secs: Integer
          }
        )
      end
      def to_hash
      end

      # This setting allows you to set the format with which the caller's number (ANI)
      # is sent for inbound phone calls.
      module AniNumberFormat
        extend Telnyx::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Telnyx::UacInboundRequest::AniNumberFormat)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PLUS_E_164 =
          T.let(
            :"+E.164",
            Telnyx::UacInboundRequest::AniNumberFormat::TaggedSymbol
          )
        E_164 =
          T.let(
            :"E.164",
            Telnyx::UacInboundRequest::AniNumberFormat::TaggedSymbol
          )
        PLUS_E_164_NATIONAL =
          T.let(
            :"+E.164-national",
            Telnyx::UacInboundRequest::AniNumberFormat::TaggedSymbol
          )
        E_164_NATIONAL =
          T.let(
            :"E.164-national",
            Telnyx::UacInboundRequest::AniNumberFormat::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Telnyx::UacInboundRequest::AniNumberFormat::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # Default routing method to be used when a number is associated with the
      # connection. Must be one of the routing method types or left blank, other values
      # are not allowed.
      module DefaultRoutingMethod
        extend Telnyx::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Telnyx::UacInboundRequest::DefaultRoutingMethod)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        SEQUENTIAL =
          T.let(
            :sequential,
            Telnyx::UacInboundRequest::DefaultRoutingMethod::TaggedSymbol
          )
        ROUND_ROBIN =
          T.let(
            :"round-robin",
            Telnyx::UacInboundRequest::DefaultRoutingMethod::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[
              Telnyx::UacInboundRequest::DefaultRoutingMethod::TaggedSymbol
            ]
          )
        end
        def self.values
        end
      end

      module DnisNumberFormat
        extend Telnyx::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Telnyx::UacInboundRequest::DnisNumberFormat)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PLUS_E164 =
          T.let(
            :"+e164",
            Telnyx::UacInboundRequest::DnisNumberFormat::TaggedSymbol
          )
        E164 =
          T.let(
            :e164,
            Telnyx::UacInboundRequest::DnisNumberFormat::TaggedSymbol
          )
        NATIONAL =
          T.let(
            :national,
            Telnyx::UacInboundRequest::DnisNumberFormat::TaggedSymbol
          )
        SIP_USERNAME =
          T.let(
            :sip_username,
            Telnyx::UacInboundRequest::DnisNumberFormat::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Telnyx::UacInboundRequest::DnisNumberFormat::TaggedSymbol]
          )
        end
        def self.values
        end
      end

      # When enabled, allows multiple devices to ring simultaneously on incoming calls.
      module SimultaneousRinging
        extend Telnyx::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Telnyx::UacInboundRequest::SimultaneousRinging)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        DISABLED =
          T.let(
            :disabled,
            Telnyx::UacInboundRequest::SimultaneousRinging::TaggedSymbol
          )
        ENABLED =
          T.let(
            :enabled,
            Telnyx::UacInboundRequest::SimultaneousRinging::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[
              Telnyx::UacInboundRequest::SimultaneousRinging::TaggedSymbol
            ]
          )
        end
        def self.values
        end
      end
    end
  end
end
