module Telnyx
  module Models
    module Messaging10dlc
      type campaign_get_operation_status_response = ::Hash[Symbol, top]

      CampaignGetOperationStatusResponse: Telnyx::Internal::Type::Converter
    end
  end
end
