module Telnyx
  module Models
    module Messaging10dlc
      type campaign_get_sharing_status_response =
        {
          shared_by_me: Telnyx::Messaging10dlc::CampaignSharingStatus,
          shared_with_me: Telnyx::Messaging10dlc::CampaignSharingStatus
        }

      class CampaignGetSharingStatusResponse < Telnyx::Internal::Type::BaseModel
        attr_reader shared_by_me: Telnyx::Messaging10dlc::CampaignSharingStatus?

        def shared_by_me=: (
          Telnyx::Messaging10dlc::CampaignSharingStatus
        ) -> Telnyx::Messaging10dlc::CampaignSharingStatus

        attr_reader shared_with_me: Telnyx::Messaging10dlc::CampaignSharingStatus?

        def shared_with_me=: (
          Telnyx::Messaging10dlc::CampaignSharingStatus
        ) -> Telnyx::Messaging10dlc::CampaignSharingStatus

        def initialize: (
          ?shared_by_me: Telnyx::Messaging10dlc::CampaignSharingStatus,
          ?shared_with_me: Telnyx::Messaging10dlc::CampaignSharingStatus
        ) -> void

        def to_hash: -> {
          shared_by_me: Telnyx::Messaging10dlc::CampaignSharingStatus,
          shared_with_me: Telnyx::Messaging10dlc::CampaignSharingStatus
        }
      end
    end
  end
end
