module Telnyx
  module Models
    module Messaging10dlc
      type partner_campaign_retrieve_sharing_status_response =
        ::Hash[Symbol, Telnyx::Messaging10dlc::CampaignSharingStatus]

      PartnerCampaignRetrieveSharingStatusResponse: Telnyx::Internal::Type::Converter
    end
  end
end
