module Telnyx
  module Models
    module Messaging10dlc
      type telnyx_downstream_campaign =
        {
          tcr_brand_id: String,
          tcr_campaign_id: String,
          age_gated: bool,
          assigned_phone_numbers_count: Float,
          brand_display_name: String,
          campaign_status: Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status,
          created_at: String,
          description: String,
          direct_lending: bool,
          embedded_link: bool,
          embedded_link_sample: String,
          embedded_phone: bool,
          failure_reasons: String,
          help_keywords: String,
          help_message: String,
          is_number_pooling_enabled: bool,
          message_flow: String,
          number_pool: bool,
          optin_keywords: String,
          optin_message: String,
          optout_keywords: String,
          optout_message: String,
          privacy_policy_link: String,
          :sample1 => String,
          :sample2 => String,
          :sample3 => String,
          :sample4 => String,
          :sample5 => String,
          subscriber_optin: bool,
          subscriber_optout: bool,
          sub_usecases: ::Array[String],
          terms_and_conditions: bool,
          terms_and_conditions_link: String,
          updated_at: String,
          usecase: String,
          webhook_failover_url: String,
          webhook_url: String
        }

      class TelnyxDownstreamCampaign < Telnyx::Internal::Type::BaseModel
        attr_accessor tcr_brand_id: String

        attr_accessor tcr_campaign_id: String

        attr_reader age_gated: bool?

        def age_gated=: (bool) -> bool

        attr_reader assigned_phone_numbers_count: Float?

        def assigned_phone_numbers_count=: (Float) -> Float

        attr_reader brand_display_name: String?

        def brand_display_name=: (String) -> String

        attr_reader campaign_status: Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status?

        def campaign_status=: (
          Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status
        ) -> Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status

        attr_reader created_at: String?

        def created_at=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader direct_lending: bool?

        def direct_lending=: (bool) -> bool

        attr_reader embedded_link: bool?

        def embedded_link=: (bool) -> bool

        attr_reader embedded_link_sample: String?

        def embedded_link_sample=: (String) -> String

        attr_reader embedded_phone: bool?

        def embedded_phone=: (bool) -> bool

        attr_reader failure_reasons: String?

        def failure_reasons=: (String) -> String

        attr_reader help_keywords: String?

        def help_keywords=: (String) -> String

        attr_reader help_message: String?

        def help_message=: (String) -> String

        attr_reader is_number_pooling_enabled: bool?

        def is_number_pooling_enabled=: (bool) -> bool

        attr_reader message_flow: String?

        def message_flow=: (String) -> String

        attr_reader number_pool: bool?

        def number_pool=: (bool) -> bool

        attr_reader optin_keywords: String?

        def optin_keywords=: (String) -> String

        attr_reader optin_message: String?

        def optin_message=: (String) -> String

        attr_reader optout_keywords: String?

        def optout_keywords=: (String) -> String

        attr_reader optout_message: String?

        def optout_message=: (String) -> String

        attr_reader privacy_policy_link: String?

        def privacy_policy_link=: (String) -> String

        attr_reader sample1: String?

        def sample1=: (String) -> String

        attr_reader sample2: String?

        def sample2=: (String) -> String

        attr_reader sample3: String?

        def sample3=: (String) -> String

        attr_reader sample4: String?

        def sample4=: (String) -> String

        attr_reader sample5: String?

        def sample5=: (String) -> String

        attr_reader subscriber_optin: bool?

        def subscriber_optin=: (bool) -> bool

        attr_reader subscriber_optout: bool?

        def subscriber_optout=: (bool) -> bool

        attr_reader sub_usecases: ::Array[String]?

        def sub_usecases=: (::Array[String]) -> ::Array[String]

        attr_reader terms_and_conditions: bool?

        def terms_and_conditions=: (bool) -> bool

        attr_reader terms_and_conditions_link: String?

        def terms_and_conditions_link=: (String) -> String

        attr_reader updated_at: String?

        def updated_at=: (String) -> String

        attr_reader usecase: String?

        def usecase=: (String) -> String

        attr_reader webhook_failover_url: String?

        def webhook_failover_url=: (String) -> String

        attr_reader webhook_url: String?

        def webhook_url=: (String) -> String

        def initialize: (
          tcr_brand_id: String,
          tcr_campaign_id: String,
          ?age_gated: bool,
          ?assigned_phone_numbers_count: Float,
          ?brand_display_name: String,
          ?campaign_status: Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status,
          ?created_at: String,
          ?description: String,
          ?direct_lending: bool,
          ?embedded_link: bool,
          ?embedded_link_sample: String,
          ?embedded_phone: bool,
          ?failure_reasons: String,
          ?help_keywords: String,
          ?help_message: String,
          ?is_number_pooling_enabled: bool,
          ?message_flow: String,
          ?number_pool: bool,
          ?optin_keywords: String,
          ?optin_message: String,
          ?optout_keywords: String,
          ?optout_message: String,
          ?privacy_policy_link: String,
          ?sample1: String,
          ?sample2: String,
          ?sample3: String,
          ?sample4: String,
          ?sample5: String,
          ?subscriber_optin: bool,
          ?subscriber_optout: bool,
          ?sub_usecases: ::Array[String],
          ?terms_and_conditions: bool,
          ?terms_and_conditions_link: String,
          ?updated_at: String,
          ?usecase: String,
          ?webhook_failover_url: String,
          ?webhook_url: String
        ) -> void

        def to_hash: -> {
          tcr_brand_id: String,
          tcr_campaign_id: String,
          age_gated: bool,
          assigned_phone_numbers_count: Float,
          brand_display_name: String,
          campaign_status: Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status,
          created_at: String,
          description: String,
          direct_lending: bool,
          embedded_link: bool,
          embedded_link_sample: String,
          embedded_phone: bool,
          failure_reasons: String,
          help_keywords: String,
          help_message: String,
          is_number_pooling_enabled: bool,
          message_flow: String,
          number_pool: bool,
          optin_keywords: String,
          optin_message: String,
          optout_keywords: String,
          optout_message: String,
          privacy_policy_link: String,
          :sample1 => String,
          :sample2 => String,
          :sample3 => String,
          :sample4 => String,
          :sample5 => String,
          subscriber_optin: bool,
          subscriber_optout: bool,
          sub_usecases: ::Array[String],
          terms_and_conditions: bool,
          terms_and_conditions_link: String,
          updated_at: String,
          usecase: String,
          webhook_failover_url: String,
          webhook_url: String
        }

        type campaign_status =
          :TCR_PENDING
          | :TCR_SUSPENDED
          | :TCR_EXPIRED
          | :TCR_ACCEPTED
          | :TCR_FAILED
          | :TELNYX_ACCEPTED
          | :TELNYX_FAILED
          | :MNO_PENDING
          | :MNO_ACCEPTED
          | :MNO_REJECTED
          | :MNO_PROVISIONED
          | :MNO_PROVISIONING_FAILED

        module CampaignStatus
          extend Telnyx::Internal::Type::Enum

          TCR_PENDING: :TCR_PENDING
          TCR_SUSPENDED: :TCR_SUSPENDED
          TCR_EXPIRED: :TCR_EXPIRED
          TCR_ACCEPTED: :TCR_ACCEPTED
          TCR_FAILED: :TCR_FAILED
          TELNYX_ACCEPTED: :TELNYX_ACCEPTED
          TELNYX_FAILED: :TELNYX_FAILED
          MNO_PENDING: :MNO_PENDING
          MNO_ACCEPTED: :MNO_ACCEPTED
          MNO_REJECTED: :MNO_REJECTED
          MNO_PROVISIONED: :MNO_PROVISIONED
          MNO_PROVISIONING_FAILED: :MNO_PROVISIONING_FAILED

          def self?.values: -> ::Array[Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::campaign_status]
        end
      end
    end
  end
end
