module Telnyx
  module Models
    module Messaging10dlc
      type vertical =
        :AGRICULTURE
        | :COMMUNICATION
        | :CONSTRUCTION
        | :EDUCATION
        | :ENERGY
        | :ENTERTAINMENT
        | :FINANCIAL
        | :GAMBLING
        | :GOVERNMENT
        | :HEALTHCARE
        | :HOSPITALITY
        | :HUMAN_RESOURCES
        | :INSURANCE
        | :LEGAL
        | :MANUFACTURING
        | :NGO
        | :POLITICAL
        | :POSTAL
        | :PROFESSIONAL
        | :REAL_ESTATE
        | :RETAIL
        | :TECHNOLOGY
        | :TRANSPORTATION

      module Vertical
        extend Telnyx::Internal::Type::Enum

        AGRICULTURE: :AGRICULTURE
        COMMUNICATION: :COMMUNICATION
        CONSTRUCTION: :CONSTRUCTION
        EDUCATION: :EDUCATION
        ENERGY: :ENERGY
        ENTERTAINMENT: :ENTERTAINMENT
        FINANCIAL: :FINANCIAL
        GAMBLING: :GAMBLING
        GOVERNMENT: :GOVERNMENT
        HEALTHCARE: :HEALTHCARE
        HOSPITALITY: :HOSPITALITY
        HUMAN_RESOURCES: :HUMAN_RESOURCES
        INSURANCE: :INSURANCE
        LEGAL: :LEGAL
        MANUFACTURING: :MANUFACTURING
        NGO: :NGO
        POLITICAL: :POLITICAL
        POSTAL: :POSTAL
        PROFESSIONAL: :PROFESSIONAL
        REAL_ESTATE: :REAL_ESTATE
        RETAIL: :RETAIL
        TECHNOLOGY: :TECHNOLOGY
        TRANSPORTATION: :TRANSPORTATION

        def self?.values: -> ::Array[Telnyx::Models::Messaging10dlc::vertical]
      end
    end
  end
end
