module Telnyx
  module Models
    module Dir
      type comment_create_response =
        { data: Telnyx::Models::Dir::CommentCreateResponse::Data }

      class CommentCreateResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: Telnyx::Models::Dir::CommentCreateResponse::Data

        def initialize: (
          data: Telnyx::Models::Dir::CommentCreateResponse::Data
        ) -> void

        def to_hash: -> {
          data: Telnyx::Models::Dir::CommentCreateResponse::Data
        }

        type data =
          {
            id: String,
            author_name: String?,
            author_role: Telnyx::Models::Dir::CommentCreateResponse::Data::author_role,
            comment_type: Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type,
            content: String,
            created_at: Time,
            entity_type: Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type,
            visibility: Telnyx::Models::Dir::CommentCreateResponse::Data::visibility
          }

        class Data < Telnyx::Internal::Type::BaseModel
          attr_reader comment_type: Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type?

          def comment_type=: (
            Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type
          ) -> Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type

          attr_reader content: String?

          def content=: (String) -> String

          attr_reader id: String?

          def id=: (String) -> String

          attr_accessor author_name: String?

          attr_reader author_role: Telnyx::Models::Dir::CommentCreateResponse::Data::author_role?

          def author_role=: (
            Telnyx::Models::Dir::CommentCreateResponse::Data::author_role
          ) -> Telnyx::Models::Dir::CommentCreateResponse::Data::author_role

          attr_reader created_at: Time?

          def created_at=: (Time) -> Time

          attr_reader entity_type: Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type?

          def entity_type=: (
            Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type
          ) -> Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type

          attr_reader visibility: Telnyx::Models::Dir::CommentCreateResponse::Data::visibility?

          def visibility=: (
            Telnyx::Models::Dir::CommentCreateResponse::Data::visibility
          ) -> Telnyx::Models::Dir::CommentCreateResponse::Data::visibility

          def initialize: (
            ?id: String,
            ?author_name: String?,
            ?author_role: Telnyx::Models::Dir::CommentCreateResponse::Data::author_role,
            ?comment_type: Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type,
            ?content: String,
            ?created_at: Time,
            ?entity_type: Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type,
            ?visibility: Telnyx::Models::Dir::CommentCreateResponse::Data::visibility
          ) -> void

          def to_hash: -> {
            id: String,
            author_name: String?,
            author_role: Telnyx::Models::Dir::CommentCreateResponse::Data::author_role,
            comment_type: Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type,
            content: String,
            created_at: Time,
            entity_type: Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type,
            visibility: Telnyx::Models::Dir::CommentCreateResponse::Data::visibility
          }

          type author_role = :customer | :admin

          module AuthorRole
            extend Telnyx::Internal::Type::Enum

            CUSTOMER: :customer
            ADMIN: :admin

            def self?.values: -> ::Array[Telnyx::Models::Dir::CommentCreateResponse::Data::author_role]
          end

          type comment_type =
            :vetting_comment
            | :rejection_reason
            | :internal_note
            | :notification
            | :status_update
            | :customer_inquiry
            | :admin_response

          module CommentType
            extend Telnyx::Internal::Type::Enum

            VETTING_COMMENT: :vetting_comment
            REJECTION_REASON: :rejection_reason
            INTERNAL_NOTE: :internal_note
            NOTIFICATION: :notification
            STATUS_UPDATE: :status_update
            CUSTOMER_INQUIRY: :customer_inquiry
            ADMIN_RESPONSE: :admin_response

            def self?.values: -> ::Array[Telnyx::Models::Dir::CommentCreateResponse::Data::comment_type]
          end

          type entity_type = :dir

          module EntityType
            extend Telnyx::Internal::Type::Enum

            DIR: :dir

            def self?.values: -> ::Array[Telnyx::Models::Dir::CommentCreateResponse::Data::entity_type]
          end

          type visibility = :customer

          module Visibility
            extend Telnyx::Internal::Type::Enum

            CUSTOMER: :customer

            def self?.values: -> ::Array[Telnyx::Models::Dir::CommentCreateResponse::Data::visibility]
          end
        end
      end
    end
  end
end
