module Telnyx
  module Models
    module Dir
      type phone_number_add_response =
        { data: ::Array[Telnyx::Dir::DirPhoneNumber] }

      class PhoneNumberAddResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: ::Array[Telnyx::Dir::DirPhoneNumber]

        def initialize: (data: ::Array[Telnyx::Dir::DirPhoneNumber]) -> void

        def to_hash: -> { data: ::Array[Telnyx::Dir::DirPhoneNumber] }
      end
    end
  end
end
