module Telnyx
  module Models
    module Dir
      type reference_input =
        {
          email: String,
          full_name: String,
          :phone_e164 => String,
          timezone: String,
          job_title: String?,
          organization: String?,
          relationship_to_registrant: String?
        }

      class ReferenceInput < Telnyx::Internal::Type::BaseModel
        attr_accessor email: String

        attr_accessor full_name: String

        attr_accessor phone_e164: String

        attr_accessor timezone: String

        attr_accessor job_title: String?

        attr_accessor organization: String?

        attr_accessor relationship_to_registrant: String?

        def initialize: (
          email: String,
          full_name: String,
          phone_e164: String,
          timezone: String,
          ?job_title: String?,
          ?organization: String?,
          ?relationship_to_registrant: String?
        ) -> void

        def to_hash: -> {
          email: String,
          full_name: String,
          :phone_e164 => String,
          timezone: String,
          job_title: String?,
          organization: String?,
          relationship_to_registrant: String?
        }
      end
    end
  end
end
