module Telnyx
  module Models
    module Messages
      type rc_send_response =
        { data: Telnyx::Models::Messages::RcSendResponse::Data }

      class RcSendResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Models::Messages::RcSendResponse::Data?

        def data=: (
          Telnyx::Models::Messages::RcSendResponse::Data
        ) -> Telnyx::Models::Messages::RcSendResponse::Data

        def initialize: (
          ?data: Telnyx::Models::Messages::RcSendResponse::Data
        ) -> void

        def to_hash: -> { data: Telnyx::Models::Messages::RcSendResponse::Data }

        type data =
          {
            id: String,
            body: Telnyx::RcsAgentMessage,
            direction: String,
            encoding: String,
            from: Telnyx::Models::Messages::RcSendResponse::Data::From,
            messaging_profile_id: String,
            organization_id: String,
            received_at: Time,
            record_type: String,
            to: ::Array[Telnyx::RcsToItem],
            type: String
          }

        class Data < Telnyx::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader body: Telnyx::RcsAgentMessage?

          def body=: (Telnyx::RcsAgentMessage) -> Telnyx::RcsAgentMessage

          attr_reader direction: String?

          def direction=: (String) -> String

          attr_reader encoding: String?

          def encoding=: (String) -> String

          attr_reader from: Telnyx::Models::Messages::RcSendResponse::Data::From?

          def from=: (
            Telnyx::Models::Messages::RcSendResponse::Data::From
          ) -> Telnyx::Models::Messages::RcSendResponse::Data::From

          attr_reader messaging_profile_id: String?

          def messaging_profile_id=: (String) -> String

          attr_reader organization_id: String?

          def organization_id=: (String) -> String

          attr_reader received_at: Time?

          def received_at=: (Time) -> Time

          attr_reader record_type: String?

          def record_type=: (String) -> String

          attr_reader to: ::Array[Telnyx::RcsToItem]?

          def to=: (::Array[Telnyx::RcsToItem]) -> ::Array[Telnyx::RcsToItem]

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: String,
            ?body: Telnyx::RcsAgentMessage,
            ?direction: String,
            ?encoding: String,
            ?from: Telnyx::Models::Messages::RcSendResponse::Data::From,
            ?messaging_profile_id: String,
            ?organization_id: String,
            ?received_at: Time,
            ?record_type: String,
            ?to: ::Array[Telnyx::RcsToItem],
            ?type: String
          ) -> void

          def to_hash: -> {
            id: String,
            body: Telnyx::RcsAgentMessage,
            direction: String,
            encoding: String,
            from: Telnyx::Models::Messages::RcSendResponse::Data::From,
            messaging_profile_id: String,
            organization_id: String,
            received_at: Time,
            record_type: String,
            to: ::Array[Telnyx::RcsToItem],
            type: String
          }

          type from = { agent_id: String, agent_name: String, carrier: String }

          class From < Telnyx::Internal::Type::BaseModel
            attr_reader agent_id: String?

            def agent_id=: (String) -> String

            attr_reader agent_name: String?

            def agent_name=: (String) -> String

            attr_reader carrier: String?

            def carrier=: (String) -> String

            def initialize: (
              ?agent_id: String,
              ?agent_name: String,
              ?carrier: String
            ) -> void

            def to_hash: -> {
              agent_id: String,
              agent_name: String,
              carrier: String
            }
          end
        end
      end
    end
  end
end
