module Telnyx
  module Internal
    module Type
      module BasePage[Elem]
        def next_page?: -> bool

        def next_page: -> instance

        def auto_paging_each: { (Elem arg0) -> void } -> void

        def to_enum: -> Enumerable[Elem]

        alias enum_for to_enum

        def initialize: (
          client: Telnyx::Internal::Transport::BaseClient,
          req: Telnyx::Internal::Transport::BaseClient::request_components,
          headers: ::Hash[String, String],
          page_data: top
        ) -> void
      end
    end
  end
end
