inherit_from: .rubocop_todo.yml


AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  NewCops: disable

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/MethodLength:
  # There's ~2 long methods in `TelnyxClient`. If we want to truncate those a
  # little, we could move this to be closer to ~30 (but the default of 10 is
  # probably too short).
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes
