module Telnyx
  module Models
    module Verifications
      type by_phone_number_list_response =
        {
          data: ::Array[Telnyx::Verification],
          meta: Telnyx::Verifications::VerifyMeta
        }

      class ByPhoneNumberListResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: ::Array[Telnyx::Verification]

        attr_accessor meta: Telnyx::Verifications::VerifyMeta

        def initialize: (
          data: ::Array[Telnyx::Verification],
          meta: Telnyx::Verifications::VerifyMeta
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::Verification],
          meta: Telnyx::Verifications::VerifyMeta
        }
      end
    end
  end
end
