module Telnyx
  module Models
    module Legacy
      module Reporting
        module BatchDetailRecords
          type messaging_delete_response =
            {
              data: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data
            }

          class MessagingDeleteResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data?

            def data=: (
              Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data
            ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data

            def initialize: (
              ?data: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data
            ) -> void

            def to_hash: -> {
              data: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data
            }

            type data =
              {
                id: String,
                connections: ::Array[Integer],
                created_at: Time,
                directions: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction],
                end_date: Time,
                filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter],
                profiles: ::Array[String],
                record_type: String,
                record_types: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type],
                report_name: String,
                report_url: String,
                start_date: Time,
                status: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status,
                updated_at: Time
              }

            class Data < Telnyx::Internal::Type::BaseModel
              attr_reader id: String?

              def id=: (String) -> String

              attr_reader connections: ::Array[Integer]?

              def connections=: (::Array[Integer]) -> ::Array[Integer]

              attr_reader created_at: Time?

              def created_at=: (Time) -> Time

              attr_reader directions: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction]?

              def directions=: (
                ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction]
              ) -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction]

              attr_reader end_date: Time?

              def end_date=: (Time) -> Time

              attr_reader filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter]?

              def filters=: (
                ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter]
              ) -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter]

              attr_reader profiles: ::Array[String]?

              def profiles=: (::Array[String]) -> ::Array[String]

              attr_reader record_type: String?

              def record_type=: (String) -> String

              attr_reader record_types: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type]?

              def record_types=: (
                ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type]
              ) -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type]

              attr_reader report_name: String?

              def report_name=: (String) -> String

              attr_reader report_url: String?

              def report_url=: (String) -> String

              attr_reader start_date: Time?

              def start_date=: (Time) -> Time

              attr_reader status: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status?

              def status=: (
                Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status
              ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status

              attr_reader updated_at: Time?

              def updated_at=: (Time) -> Time

              def initialize: (
                ?id: String,
                ?connections: ::Array[Integer],
                ?created_at: Time,
                ?directions: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction],
                ?end_date: Time,
                ?filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter],
                ?profiles: ::Array[String],
                ?record_type: String,
                ?record_types: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type],
                ?report_name: String,
                ?report_url: String,
                ?start_date: Time,
                ?status: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status,
                ?updated_at: Time
              ) -> void

              def to_hash: -> {
                id: String,
                connections: ::Array[Integer],
                created_at: Time,
                directions: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction],
                end_date: Time,
                filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter],
                profiles: ::Array[String],
                record_type: String,
                record_types: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type],
                report_name: String,
                report_url: String,
                start_date: Time,
                status: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status,
                updated_at: Time
              }

              type direction = :INBOUND | :OUTBOUND

              module Direction
                extend Telnyx::Internal::Type::Enum

                INBOUND: :INBOUND
                OUTBOUND: :OUTBOUND

                def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::direction]
              end

              type filter =
                {
                  billing_group: String,
                  cld: String,
                  cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter,
                  cli: String,
                  cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter,
                  filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type,
                  tags_list: String
                }

              class Filter < Telnyx::Internal::Type::BaseModel
                attr_reader billing_group: String?

                def billing_group=: (String) -> String

                attr_reader cld: String?

                def cld=: (String) -> String

                attr_reader cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter?

                def cld_filter=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter

                attr_reader cli: String?

                def cli=: (String) -> String

                attr_reader cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter?

                def cli_filter=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter

                attr_reader filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type?

                def filter_type=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type

                attr_reader tags_list: String?

                def tags_list=: (String) -> String

                def initialize: (
                  ?billing_group: String,
                  ?cld: String,
                  ?cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter,
                  ?cli: String,
                  ?cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter,
                  ?filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type,
                  ?tags_list: String
                ) -> void

                def to_hash: -> {
                  billing_group: String,
                  cld: String,
                  cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter,
                  cli: String,
                  cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter,
                  filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type,
                  tags_list: String
                }

                type cld_filter = :contains | :starts_with | :ends_with

                module CldFilter
                  extend Telnyx::Internal::Type::Enum

                  CONTAINS: :contains
                  STARTS_WITH: :starts_with
                  ENDS_WITH: :ends_with

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cld_filter]
                end

                type cli_filter = :contains | :starts_with | :ends_with

                module CliFilter
                  extend Telnyx::Internal::Type::Enum

                  CONTAINS: :contains
                  STARTS_WITH: :starts_with
                  ENDS_WITH: :ends_with

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::cli_filter]
                end

                type filter_type = :and | :or

                module FilterType
                  extend Telnyx::Internal::Type::Enum

                  AND: :and
                  OR: :or

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::Filter::filter_type]
                end
              end

              type record_type = :INCOMPLETE | :COMPLETED | :ERRORS

              module RecordType
                extend Telnyx::Internal::Type::Enum

                INCOMPLETE: :INCOMPLETE
                COMPLETED: :COMPLETED
                ERRORS: :ERRORS

                def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::record_type]
              end

              type status = :PENDING | :COMPLETE | :FAILED | :EXPIRED

              module Status
                extend Telnyx::Internal::Type::Enum

                PENDING: :PENDING
                COMPLETE: :COMPLETE
                FAILED: :FAILED
                EXPIRED: :EXPIRED

                def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::MessagingDeleteResponse::Data::status]
              end
            end
          end
        end
      end
    end
  end
end
