module Telnyx
  module Models
    module Legacy
      module Reporting
        module BatchDetailRecords
          type speech_to_text_list_response =
            {
              data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]
            }

          class SpeechToTextListResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]?

            def data=: (
              ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]
            ) -> ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]

            def initialize: (
              ?data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]
            ) -> void

            def to_hash: -> {
              data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::SttDetailReportResponse]
            }
          end
        end
      end
    end
  end
end
