module Telnyx
  module Models
    module Legacy
      module Reporting
        module BatchDetailRecords
          type voice_list_response =
            {
              data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse],
              meta: Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312
            }

          class VoiceListResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse]?

            def data=: (
              ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse]
            ) -> ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse]

            attr_reader meta: Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312?

            def meta=: (
              Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312
            ) -> Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312

            def initialize: (
              ?data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse],
              ?meta: Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312
            ) -> void

            def to_hash: -> {
              data: ::Array[Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse],
              meta: Telnyx::Legacy::Reporting::BatchDetailRecords::BatchCsvPaginationMeta705dfa7312
            }
          end
        end
      end
    end
  end
end
