module Telnyx
  module Models
    module Legacy
      module Reporting
        module BatchDetailRecords
          type voice_create_response =
            {
              data: Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse
            }

          class VoiceCreateResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse?

            def data=: (
              Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse
            ) -> Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse

            def initialize: (
              ?data: Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse
            ) -> void

            def to_hash: -> {
              data: Telnyx::Legacy::Reporting::BatchDetailRecords::CdrDetailedReqResponse
            }
          end
        end
      end
    end
  end
end
