module Telnyx
  module Models
    module Legacy
      module Reporting
        module BatchDetailRecords
          type voice_list_response =
            {
              data: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data],
              meta: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta
            }

          class VoiceListResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data]?

            def data=: (
              ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data]
            ) -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data]

            attr_reader meta: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta?

            def meta=: (
              Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta
            ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta

            def initialize: (
              ?data: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data],
              ?meta: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta
            ) -> void

            def to_hash: -> {
              data: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data],
              meta: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Meta
            }

            type data =
              {
                id: String,
                call_types: ::Array[Integer],
                connections: ::Array[Integer],
                created_at: String,
                end_time: String,
                filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter],
                managed_accounts: ::Array[String],
                record_type: String,
                record_types: ::Array[Integer],
                report_name: String,
                report_url: String,
                retry_: Integer,
                source: String,
                start_time: String,
                status: Integer,
                timezone: String,
                updated_at: String
              }

            class Data < Telnyx::Internal::Type::BaseModel
              attr_reader id: String?

              def id=: (String) -> String

              attr_reader call_types: ::Array[Integer]?

              def call_types=: (::Array[Integer]) -> ::Array[Integer]

              attr_reader connections: ::Array[Integer]?

              def connections=: (::Array[Integer]) -> ::Array[Integer]

              attr_reader created_at: String?

              def created_at=: (String) -> String

              attr_reader end_time: String?

              def end_time=: (String) -> String

              attr_reader filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter]?

              def filters=: (
                ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter]
              ) -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter]

              attr_reader managed_accounts: ::Array[String]?

              def managed_accounts=: (::Array[String]) -> ::Array[String]

              attr_reader record_type: String?

              def record_type=: (String) -> String

              attr_reader record_types: ::Array[Integer]?

              def record_types=: (::Array[Integer]) -> ::Array[Integer]

              attr_reader report_name: String?

              def report_name=: (String) -> String

              attr_reader report_url: String?

              def report_url=: (String) -> String

              attr_reader retry_: Integer?

              def retry_=: (Integer) -> Integer

              attr_reader source: String?

              def source=: (String) -> String

              attr_reader start_time: String?

              def start_time=: (String) -> String

              attr_reader status: Integer?

              def status=: (Integer) -> Integer

              attr_reader timezone: String?

              def timezone=: (String) -> String

              attr_reader updated_at: String?

              def updated_at=: (String) -> String

              def initialize: (
                ?id: String,
                ?call_types: ::Array[Integer],
                ?connections: ::Array[Integer],
                ?created_at: String,
                ?end_time: String,
                ?filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter],
                ?managed_accounts: ::Array[String],
                ?record_type: String,
                ?record_types: ::Array[Integer],
                ?report_name: String,
                ?report_url: String,
                ?retry_: Integer,
                ?source: String,
                ?start_time: String,
                ?status: Integer,
                ?timezone: String,
                ?updated_at: String
              ) -> void

              def to_hash: -> {
                id: String,
                call_types: ::Array[Integer],
                connections: ::Array[Integer],
                created_at: String,
                end_time: String,
                filters: ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter],
                managed_accounts: ::Array[String],
                record_type: String,
                record_types: ::Array[Integer],
                report_name: String,
                report_url: String,
                retry_: Integer,
                source: String,
                start_time: String,
                status: Integer,
                timezone: String,
                updated_at: String
              }

              type filter =
                {
                  billing_group: String,
                  cld: String,
                  cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter,
                  cli: String,
                  cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter,
                  filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type,
                  tags_list: String
                }

              class Filter < Telnyx::Internal::Type::BaseModel
                attr_reader billing_group: String?

                def billing_group=: (String) -> String

                attr_reader cld: String?

                def cld=: (String) -> String

                attr_reader cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter?

                def cld_filter=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter

                attr_reader cli: String?

                def cli=: (String) -> String

                attr_reader cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter?

                def cli_filter=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter

                attr_reader filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type?

                def filter_type=: (
                  Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type
                ) -> Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type

                attr_reader tags_list: String?

                def tags_list=: (String) -> String

                def initialize: (
                  ?billing_group: String,
                  ?cld: String,
                  ?cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter,
                  ?cli: String,
                  ?cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter,
                  ?filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type,
                  ?tags_list: String
                ) -> void

                def to_hash: -> {
                  billing_group: String,
                  cld: String,
                  cld_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter,
                  cli: String,
                  cli_filter: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter,
                  filter_type: Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type,
                  tags_list: String
                }

                type cld_filter = :contains | :starts_with | :ends_with

                module CldFilter
                  extend Telnyx::Internal::Type::Enum

                  CONTAINS: :contains
                  STARTS_WITH: :starts_with
                  ENDS_WITH: :ends_with

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cld_filter]
                end

                type cli_filter = :contains | :starts_with | :ends_with

                module CliFilter
                  extend Telnyx::Internal::Type::Enum

                  CONTAINS: :contains
                  STARTS_WITH: :starts_with
                  ENDS_WITH: :ends_with

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::cli_filter]
                end

                type filter_type = :and | :or

                module FilterType
                  extend Telnyx::Internal::Type::Enum

                  AND: :and
                  OR: :or

                  def self?.values: -> ::Array[Telnyx::Models::Legacy::Reporting::BatchDetailRecords::VoiceListResponse::Data::Filter::filter_type]
                end
              end
            end

            type meta =
              {
                page_number: Integer,
                page_size: Integer,
                total_pages: Integer,
                total_results: Integer
              }

            class Meta < Telnyx::Internal::Type::BaseModel
              attr_reader page_number: Integer?

              def page_number=: (Integer) -> Integer

              attr_reader page_size: Integer?

              def page_size=: (Integer) -> Integer

              attr_reader total_pages: Integer?

              def total_pages=: (Integer) -> Integer

              attr_reader total_results: Integer?

              def total_results=: (Integer) -> Integer

              def initialize: (
                ?page_number: Integer,
                ?page_size: Integer,
                ?total_pages: Integer,
                ?total_results: Integer
              ) -> void

              def to_hash: -> {
                page_number: Integer,
                page_size: Integer,
                total_pages: Integer,
                total_results: Integer
              }
            end
          end
        end
      end
    end
  end
end
