module Telnyx
  module Resources
    class Campaign
      class Osr
        def get_attributes: (
          String campaign_id,
          ?request_options: Telnyx::request_opts
        ) -> top

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
