module Telnyx
  module Resources
    class Enterprises
      class Reputation
        attr_reader numbers: Telnyx::Resources::Enterprises::Reputation::Numbers

        attr_reader loa: Telnyx::Resources::Enterprises::Reputation::Loa

        attr_reader remediation: Telnyx::Resources::Enterprises::Reputation::Remediation

        def retrieve: (
          String enterprise_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Enterprises::EnterpriseReputationPublicWrapped

        def disable: (
          String enterprise_id,
          ?request_options: Telnyx::request_opts
        ) -> nil

        def enable: (
          String enterprise_id,
          loa_document_id: String,
          ?check_frequency: Telnyx::Models::Enterprises::reputation_check_frequency,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Enterprises::EnterpriseReputationPublicWrapped

        def update_frequency: (
          String enterprise_id,
          check_frequency: Telnyx::Models::Enterprises::reputation_check_frequency,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Enterprises::EnterpriseReputationPublicWrapped

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
