# frozen_string_literal: true

module Telnyx
  module Models
    module Messaging10dlc
      # @see Telnyx::Resources::Messaging10dlc::PartnerCampaigns#retrieve
      class TelnyxDownstreamCampaign < Telnyx::Internal::Type::BaseModel
        # @!attribute tcr_brand_id
        #   Unique identifier assigned to the brand by the registry.
        #
        #   @return [String]
        required :tcr_brand_id, String, api_name: :tcrBrandId

        # @!attribute tcr_campaign_id
        #   Unique identifier assigned to the campaign by the registry.
        #
        #   @return [String]
        required :tcr_campaign_id, String, api_name: :tcrCampaignId

        # @!attribute age_gated
        #   Age gated content in campaign.
        #
        #   @return [Boolean, nil]
        optional :age_gated, Telnyx::Internal::Type::Boolean, api_name: :ageGated

        # @!attribute assigned_phone_numbers_count
        #   Number of phone numbers associated with the campaign
        #
        #   @return [Float, nil]
        optional :assigned_phone_numbers_count, Float, api_name: :assignedPhoneNumbersCount

        # @!attribute brand_display_name
        #   Display or marketing name of the brand.
        #
        #   @return [String, nil]
        optional :brand_display_name, String, api_name: :brandDisplayName

        # @!attribute campaign_status
        #   Campaign status
        #
        #   @return [Symbol, Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::CampaignStatus, nil]
        optional :campaign_status,
                 enum: -> { Telnyx::Messaging10dlc::TelnyxDownstreamCampaign::CampaignStatus },
                 api_name: :campaignStatus

        # @!attribute created_at
        #   Date and time that the brand was created at.
        #
        #   @return [String, nil]
        optional :created_at, String, api_name: :createdAt

        # @!attribute description
        #   Summary description of this campaign.
        #
        #   @return [String, nil]
        optional :description, String

        # @!attribute direct_lending
        #   Direct lending or loan arrangement.
        #
        #   @return [Boolean, nil]
        optional :direct_lending, Telnyx::Internal::Type::Boolean, api_name: :directLending

        # @!attribute embedded_link
        #   Does message generated by the campaign include URL link in SMS?
        #
        #   @return [Boolean, nil]
        optional :embedded_link, Telnyx::Internal::Type::Boolean, api_name: :embeddedLink

        # @!attribute embedded_link_sample
        #   Sample of an embedded link that will be sent to subscribers.
        #
        #   @return [String, nil]
        optional :embedded_link_sample, String, api_name: :embeddedLinkSample

        # @!attribute embedded_phone
        #   Does message generated by the campaign include phone number in SMS?
        #
        #   @return [Boolean, nil]
        optional :embedded_phone, Telnyx::Internal::Type::Boolean, api_name: :embeddedPhone

        # @!attribute failure_reasons
        #   Failure reasons if campaign submission failed
        #
        #   @return [String, nil]
        optional :failure_reasons, String, api_name: :failureReasons

        # @!attribute help_keywords
        #   Subscriber help keywords. Multiple keywords are comma separated without space.
        #
        #   @return [String, nil]
        optional :help_keywords, String, api_name: :helpKeywords

        # @!attribute help_message
        #   Help message of the campaign.
        #
        #   @return [String, nil]
        optional :help_message, String, api_name: :helpMessage

        # @!attribute is_number_pooling_enabled
        #   Indicates whether the campaign has a T-Mobile number pool ID associated with it.
        #
        #   @return [Boolean, nil]
        optional :is_number_pooling_enabled,
                 Telnyx::Internal::Type::Boolean,
                 api_name: :isNumberPoolingEnabled

        # @!attribute message_flow
        #   Message flow description.
        #
        #   @return [String, nil]
        optional :message_flow, String, api_name: :messageFlow

        # @!attribute number_pool
        #   Does campaign utilize pool of phone numbers?
        #
        #   @return [Boolean, nil]
        optional :number_pool, Telnyx::Internal::Type::Boolean, api_name: :numberPool

        # @!attribute optin_keywords
        #   Subscriber opt-in keywords. Multiple keywords are comma separated without space.
        #
        #   @return [String, nil]
        optional :optin_keywords, String, api_name: :optinKeywords

        # @!attribute optin_message
        #   Subscriber opt-in message.
        #
        #   @return [String, nil]
        optional :optin_message, String, api_name: :optinMessage

        # @!attribute optout_keywords
        #   Subscriber opt-out keywords. Multiple keywords are comma separated without
        #   space.
        #
        #   @return [String, nil]
        optional :optout_keywords, String, api_name: :optoutKeywords

        # @!attribute optout_message
        #   Subscriber opt-out message.
        #
        #   @return [String, nil]
        optional :optout_message, String, api_name: :optoutMessage

        # @!attribute privacy_policy_link
        #   Link to the campaign's privacy policy.
        #
        #   @return [String, nil]
        optional :privacy_policy_link, String, api_name: :privacyPolicyLink

        # @!attribute sample1
        #   Message sample. Some campaign tiers require 1 or more message samples.
        #
        #   @return [String, nil]
        optional :sample1, String

        # @!attribute sample2
        #   Message sample. Some campaign tiers require 2 or more message samples.
        #
        #   @return [String, nil]
        optional :sample2, String

        # @!attribute sample3
        #   Message sample. Some campaign tiers require 3 or more message samples.
        #
        #   @return [String, nil]
        optional :sample3, String

        # @!attribute sample4
        #   Message sample. Some campaign tiers require 4 or more message samples.
        #
        #   @return [String, nil]
        optional :sample4, String

        # @!attribute sample5
        #   Message sample. Some campaign tiers require 5 or more message samples.
        #
        #   @return [String, nil]
        optional :sample5, String

        # @!attribute subscriber_optin
        #   Does campaign require subscriber to opt-in before SMS is sent to subscriber?
        #
        #   @return [Boolean, nil]
        optional :subscriber_optin, Telnyx::Internal::Type::Boolean, api_name: :subscriberOptin

        # @!attribute subscriber_optout
        #   Does campaign support subscriber opt-out keyword(s)?
        #
        #   @return [Boolean, nil]
        optional :subscriber_optout, Telnyx::Internal::Type::Boolean, api_name: :subscriberOptout

        # @!attribute sub_usecases
        #   Campaign sub-usecases. Must be of defined valid sub-usecase types. Use
        #   `/registry/enum/usecase` operation to retrieve list of valid sub-usecases
        #
        #   @return [Array<String>, nil]
        optional :sub_usecases, Telnyx::Internal::Type::ArrayOf[String], api_name: :subUsecases

        # @!attribute terms_and_conditions
        #   Is terms & conditions accepted?
        #
        #   @return [Boolean, nil]
        optional :terms_and_conditions, Telnyx::Internal::Type::Boolean, api_name: :termsAndConditions

        # @!attribute terms_and_conditions_link
        #   Link to the campaign's terms and conditions.
        #
        #   @return [String, nil]
        optional :terms_and_conditions_link, String, api_name: :termsAndConditionsLink

        # @!attribute updated_at
        #   Date and time that the brand was last updated at.
        #
        #   @return [String, nil]
        optional :updated_at, String, api_name: :updatedAt

        # @!attribute usecase
        #   Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase`
        #   operation to retrieve usecases available for given brand.
        #
        #   @return [String, nil]
        optional :usecase, String

        # @!attribute webhook_failover_url
        #   Failover webhook to which campaign status updates are sent.
        #
        #   @return [String, nil]
        optional :webhook_failover_url, String, api_name: :webhookFailoverURL

        # @!attribute webhook_url
        #   Webhook to which campaign status updates are sent.
        #
        #   @return [String, nil]
        optional :webhook_url, String, api_name: :webhookURL

        # @!method initialize(tcr_brand_id:, tcr_campaign_id:, age_gated: nil, assigned_phone_numbers_count: nil, brand_display_name: nil, campaign_status: nil, created_at: nil, description: nil, direct_lending: nil, embedded_link: nil, embedded_link_sample: nil, embedded_phone: nil, failure_reasons: nil, help_keywords: nil, help_message: nil, is_number_pooling_enabled: nil, message_flow: nil, number_pool: nil, optin_keywords: nil, optin_message: nil, optout_keywords: nil, optout_message: nil, privacy_policy_link: nil, sample1: nil, sample2: nil, sample3: nil, sample4: nil, sample5: nil, subscriber_optin: nil, subscriber_optout: nil, sub_usecases: nil, terms_and_conditions: nil, terms_and_conditions_link: nil, updated_at: nil, usecase: nil, webhook_failover_url: nil, webhook_url: nil)
        #   Some parameter documentations has been truncated, see
        #   {Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign} for more details.
        #
        #   Campaign is generated by the 10DLC registry once the corresponding campaign
        #   request is approved. Each campaign is assigned a unique identifier -
        #   **campaignId**. Once a campaign is activated, limited information is published
        #   to the NetNumber OSR service for consumption by members of the ecosystem. When a
        #   campaign is suspended(reversible) or expired(non-reversible), campaign data is
        #   deleted from the OSR service.
        #
        #   @param tcr_brand_id [String] Unique identifier assigned to the brand by the registry.
        #
        #   @param tcr_campaign_id [String] Unique identifier assigned to the campaign by the registry.
        #
        #   @param age_gated [Boolean] Age gated content in campaign.
        #
        #   @param assigned_phone_numbers_count [Float] Number of phone numbers associated with the campaign
        #
        #   @param brand_display_name [String] Display or marketing name of the brand.
        #
        #   @param campaign_status [Symbol, Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign::CampaignStatus] Campaign status
        #
        #   @param created_at [String] Date and time that the brand was created at.
        #
        #   @param description [String] Summary description of this campaign.
        #
        #   @param direct_lending [Boolean] Direct lending or loan arrangement.
        #
        #   @param embedded_link [Boolean] Does message generated by the campaign include URL link in SMS?
        #
        #   @param embedded_link_sample [String] Sample of an embedded link that will be sent to subscribers.
        #
        #   @param embedded_phone [Boolean] Does message generated by the campaign include phone number in SMS?
        #
        #   @param failure_reasons [String] Failure reasons if campaign submission failed
        #
        #   @param help_keywords [String] Subscriber help keywords. Multiple keywords are comma separated without space.
        #
        #   @param help_message [String] Help message of the campaign.
        #
        #   @param is_number_pooling_enabled [Boolean] Indicates whether the campaign has a T-Mobile number pool ID associated with it.
        #
        #   @param message_flow [String] Message flow description.
        #
        #   @param number_pool [Boolean] Does campaign utilize pool of phone numbers?
        #
        #   @param optin_keywords [String] Subscriber opt-in keywords. Multiple keywords are comma separated without space.
        #
        #   @param optin_message [String] Subscriber opt-in message.
        #
        #   @param optout_keywords [String] Subscriber opt-out keywords. Multiple keywords are comma separated without space
        #
        #   @param optout_message [String] Subscriber opt-out message.
        #
        #   @param privacy_policy_link [String] Link to the campaign's privacy policy.
        #
        #   @param sample1 [String] Message sample. Some campaign tiers require 1 or more message samples.
        #
        #   @param sample2 [String] Message sample. Some campaign tiers require 2 or more message samples.
        #
        #   @param sample3 [String] Message sample. Some campaign tiers require 3 or more message samples.
        #
        #   @param sample4 [String] Message sample. Some campaign tiers require 4 or more message samples.
        #
        #   @param sample5 [String] Message sample. Some campaign tiers require 5 or more message samples.
        #
        #   @param subscriber_optin [Boolean] Does campaign require subscriber to opt-in before SMS is sent to subscriber?
        #
        #   @param subscriber_optout [Boolean] Does campaign support subscriber opt-out keyword(s)?
        #
        #   @param sub_usecases [Array<String>] Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registr
        #
        #   @param terms_and_conditions [Boolean] Is terms & conditions accepted?
        #
        #   @param terms_and_conditions_link [String] Link to the campaign's terms and conditions.
        #
        #   @param updated_at [String] Date and time that the brand was last updated at.
        #
        #   @param usecase [String] Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` o
        #
        #   @param webhook_failover_url [String] Failover webhook to which campaign status updates are sent.
        #
        #   @param webhook_url [String] Webhook to which campaign status updates are sent.

        # Campaign status
        #
        # @see Telnyx::Models::Messaging10dlc::TelnyxDownstreamCampaign#campaign_status
        module CampaignStatus
          extend Telnyx::Internal::Type::Enum

          TCR_PENDING = :TCR_PENDING
          TCR_SUSPENDED = :TCR_SUSPENDED
          TCR_EXPIRED = :TCR_EXPIRED
          TCR_ACCEPTED = :TCR_ACCEPTED
          TCR_FAILED = :TCR_FAILED
          TELNYX_ACCEPTED = :TELNYX_ACCEPTED
          TELNYX_FAILED = :TELNYX_FAILED
          MNO_PENDING = :MNO_PENDING
          MNO_ACCEPTED = :MNO_ACCEPTED
          MNO_REJECTED = :MNO_REJECTED
          MNO_PROVISIONED = :MNO_PROVISIONED
          MNO_PROVISIONING_FAILED = :MNO_PROVISIONING_FAILED

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
