module Telnyx
  module Resources
    class Messaging10dlc
      class CampaignBuilder
        class Brand
          def qualify_by_usecase: (
            String usecase,
            brand_id: String,
            ?request_options: Telnyx::request_opts
          ) -> Telnyx::Models::Messaging10dlc::CampaignBuilder::BrandQualifyByUsecaseResponse

          def initialize: (client: Telnyx::Client) -> void
        end
      end
    end
  end
end
