module Telnyx
  module Resources
    class Number10dlc
      class CampaignBuilder
        attr_reader brand: Telnyx::Resources::Number10dlc::CampaignBuilder::Brand

        def submit: (
          brand_id: String,
          description: String,
          usecase: String,
          ?age_gated: bool,
          ?auto_renewal: bool,
          ?direct_lending: bool,
          ?embedded_link: bool,
          ?embedded_link_sample: String,
          ?embedded_phone: bool,
          ?help_keywords: String,
          ?help_message: String,
          ?message_flow: String,
          ?mno_ids: ::Array[Integer],
          ?number_pool: bool,
          ?optin_keywords: String,
          ?optin_message: String,
          ?optout_keywords: String,
          ?optout_message: String,
          ?privacy_policy_link: String,
          ?reference_id: String,
          ?reseller_id: String,
          ?sample1: String,
          ?sample2: String,
          ?sample3: String,
          ?sample4: String,
          ?sample5: String,
          ?subscriber_help: bool,
          ?subscriber_optin: bool,
          ?subscriber_optout: bool,
          ?sub_usecases: ::Array[String],
          ?tag: ::Array[String],
          ?terms_and_conditions: bool,
          ?terms_and_conditions_link: String,
          ?webhook_failover_url: String,
          ?webhook_url: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Number10dlc::TelnyxCampaignCsp

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
