module Telnyx
  module Resources
    class Number10dlc
      class PartnerCampaign
        def retrieve_shared_by_me: (
          ?page: Integer,
          ?records_per_page: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Number10dlc::PartnerCampaignRetrieveSharedByMeResponse

        def retrieve_sharing: (
          String campaign_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Number10dlc::partner_campaign_retrieve_sharing_response

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
