module Telnyx
  module Resources
    class Number10dlc
      class PartnerCampaigns
        def retrieve: (
          String campaign_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::TelnyxDownstreamCampaign

        def update: (
          String campaign_id,
          ?webhook_failover_url: String,
          ?webhook_url: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::TelnyxDownstreamCampaign

        def list: (
          ?page: Integer,
          ?records_per_page: Integer,
          ?sort: Telnyx::Models::Number10dlc::PartnerCampaignListParams::sort,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Number10dlc::PartnerCampaignListResponse

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
