module Telnyx
  module Models
    module Rcs
      type brand_organization_type =
        :PRIVATE_PROFIT | :PUBLIC_PROFIT | :NON_PROFIT | :GOVERNMENT | :UNKNOWN

      module BrandOrganizationType
        extend Telnyx::Internal::Type::Enum

        PRIVATE_PROFIT: :PRIVATE_PROFIT
        PUBLIC_PROFIT: :PUBLIC_PROFIT
        NON_PROFIT: :NON_PROFIT
        GOVERNMENT: :GOVERNMENT
        UNKNOWN: :UNKNOWN

        def self?.values: -> ::Array[Telnyx::Models::Rcs::brand_organization_type]
      end
    end
  end
end
