module Telnyx
  module Models
    module Rcs
      type brand_update_params =
        {
          id: String,
          addresses: ::Hash[Symbol, Telnyx::Rcs::BrandAddress],
          contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          display_name: String,
          identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          legal_name: String,
          organization_type: Telnyx::Models::Rcs::brand_organization_type,
          profile_id: String,
          website_url: String
        }
        & Telnyx::Internal::Type::request_parameters

      class BrandUpdateParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader addresses: ::Hash[Symbol, Telnyx::Rcs::BrandAddress]?

        def addresses=: (
          ::Hash[Symbol, Telnyx::Rcs::BrandAddress]
        ) -> ::Hash[Symbol, Telnyx::Rcs::BrandAddress]

        attr_reader contacts: Telnyx::Rcs::BrandUpdateParams::Contacts?

        def contacts=: (
          Telnyx::Rcs::BrandUpdateParams::Contacts
        ) -> Telnyx::Rcs::BrandUpdateParams::Contacts

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_reader identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers?

        def identifiers=: (
          Telnyx::Rcs::BrandUpdateParams::Identifiers
        ) -> Telnyx::Rcs::BrandUpdateParams::Identifiers

        attr_reader legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type?

        def legal_entity_type=: (
          Telnyx::Models::Rcs::brand_legal_entity_type
        ) -> Telnyx::Models::Rcs::brand_legal_entity_type

        attr_reader legal_name: String?

        def legal_name=: (String) -> String

        attr_reader organization_type: Telnyx::Models::Rcs::brand_organization_type?

        def organization_type=: (
          Telnyx::Models::Rcs::brand_organization_type
        ) -> Telnyx::Models::Rcs::brand_organization_type

        attr_reader profile_id: String?

        def profile_id=: (String) -> String

        attr_reader website_url: String?

        def website_url=: (String) -> String

        def initialize: (
          id: String,
          ?addresses: ::Hash[Symbol, Telnyx::Rcs::BrandAddress],
          ?contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          ?display_name: String,
          ?identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          ?legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          ?legal_name: String,
          ?organization_type: Telnyx::Models::Rcs::brand_organization_type,
          ?profile_id: String,
          ?website_url: String,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          addresses: ::Hash[Symbol, Telnyx::Rcs::BrandAddress],
          contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          display_name: String,
          identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          legal_name: String,
          organization_type: Telnyx::Models::Rcs::brand_organization_type,
          profile_id: String,
          website_url: String,
          request_options: Telnyx::RequestOptions
        }

        type contacts =
          { brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand }

        class Contacts < Telnyx::Internal::Type::BaseModel
          attr_accessor brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand

          def initialize: (
            brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand
          ) -> void

          def to_hash: -> {
            brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand
          }

          type brand = {  }

          class Brand < Telnyx::Models::Rcs::BrandContact
            def initialize: -> void

            def to_hash: -> {  }
          end
        end

        type identifiers =
          {
            ein: Telnyx::Rcs::EinBrandIdentifier,
            stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          }

        class Identifiers < Telnyx::Internal::Type::BaseModel
          attr_accessor ein: Telnyx::Rcs::EinBrandIdentifier

          attr_reader stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier?

          def stock_symbol=: (
            Telnyx::Rcs::StockSymbolBrandIdentifier
          ) -> Telnyx::Rcs::StockSymbolBrandIdentifier

          def initialize: (
            ein: Telnyx::Rcs::EinBrandIdentifier,
            ?stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          ) -> void

          def to_hash: -> {
            ein: Telnyx::Rcs::EinBrandIdentifier,
            stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          }
        end
      end
    end
  end
end
