module Telnyx
  module Models
    module Rcs
      type brand_update_params =
        {
          id: String,
          addresses: ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address],
          contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          display_name: String,
          identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          legal_name: String,
          organization_type: Telnyx::Models::Rcs::brand_organization_type,
          profile_id: String,
          website_url: String
        }
        & Telnyx::Internal::Type::request_parameters

      class BrandUpdateParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader addresses: ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address]?

        def addresses=: (
          ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address]
        ) -> ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address]

        attr_reader contacts: Telnyx::Rcs::BrandUpdateParams::Contacts?

        def contacts=: (
          Telnyx::Rcs::BrandUpdateParams::Contacts
        ) -> Telnyx::Rcs::BrandUpdateParams::Contacts

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_reader identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers?

        def identifiers=: (
          Telnyx::Rcs::BrandUpdateParams::Identifiers
        ) -> Telnyx::Rcs::BrandUpdateParams::Identifiers

        attr_reader legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type?

        def legal_entity_type=: (
          Telnyx::Models::Rcs::brand_legal_entity_type
        ) -> Telnyx::Models::Rcs::brand_legal_entity_type

        attr_reader legal_name: String?

        def legal_name=: (String) -> String

        attr_reader organization_type: Telnyx::Models::Rcs::brand_organization_type?

        def organization_type=: (
          Telnyx::Models::Rcs::brand_organization_type
        ) -> Telnyx::Models::Rcs::brand_organization_type

        attr_reader profile_id: String?

        def profile_id=: (String) -> String

        attr_reader website_url: String?

        def website_url=: (String) -> String

        def initialize: (
          id: String,
          ?addresses: ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address],
          ?contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          ?display_name: String,
          ?identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          ?legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          ?legal_name: String,
          ?organization_type: Telnyx::Models::Rcs::brand_organization_type,
          ?profile_id: String,
          ?website_url: String,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          addresses: ::Hash[Symbol, Telnyx::Rcs::BrandUpdateParams::Address],
          contacts: Telnyx::Rcs::BrandUpdateParams::Contacts,
          display_name: String,
          identifiers: Telnyx::Rcs::BrandUpdateParams::Identifiers,
          legal_entity_type: Telnyx::Models::Rcs::brand_legal_entity_type,
          legal_name: String,
          organization_type: Telnyx::Models::Rcs::brand_organization_type,
          profile_id: String,
          website_url: String,
          request_options: Telnyx::RequestOptions
        }

        type address =
          {
            administrative_area: String,
            city: String,
            country_code: String,
            :line_1 => String,
            postal_code: String,
            :line_2 => String?
          }

        class Address < Telnyx::Internal::Type::BaseModel
          attr_accessor administrative_area: String

          attr_accessor city: String

          attr_accessor country_code: String

          attr_accessor line_1: String

          attr_accessor postal_code: String

          attr_accessor line_2: String?

          def initialize: (
            administrative_area: String,
            city: String,
            country_code: String,
            line_1: String,
            postal_code: String,
            ?line_2: String?
          ) -> void

          def to_hash: -> {
            administrative_area: String,
            city: String,
            country_code: String,
            :line_1 => String,
            postal_code: String,
            :line_2 => String?
          }
        end

        type contacts =
          { brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand }

        class Contacts < Telnyx::Internal::Type::BaseModel
          attr_accessor brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand

          def initialize: (
            brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand
          ) -> void

          def to_hash: -> {
            brand: Telnyx::Rcs::BrandUpdateParams::Contacts::Brand
          }

          type brand =
            {
              contact_type: Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type
            }

          class Brand < Telnyx::Models::Rcs::BrandContact
            def contact_type: -> Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type?

            def contact_type=: (
              Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type _
            ) -> Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type

            def initialize: (
              ?contact_type: Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type
            ) -> void

            def to_hash: -> {
              contact_type: Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type
            }

            type contact_type = :BRAND

            module ContactType
              extend Telnyx::Internal::Type::Enum

              BRAND: :BRAND

              def self?.values: -> ::Array[Telnyx::Models::Rcs::BrandUpdateParams::Contacts::Brand::contact_type]
            end
          end
        end

        type identifiers =
          {
            ein: Telnyx::Rcs::EinBrandIdentifier,
            stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          }

        class Identifiers < Telnyx::Internal::Type::BaseModel
          attr_accessor ein: Telnyx::Rcs::EinBrandIdentifier

          attr_reader stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier?

          def stock_symbol=: (
            Telnyx::Rcs::StockSymbolBrandIdentifier
          ) -> Telnyx::Rcs::StockSymbolBrandIdentifier

          def initialize: (
            ein: Telnyx::Rcs::EinBrandIdentifier,
            ?stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          ) -> void

          def to_hash: -> {
            ein: Telnyx::Rcs::EinBrandIdentifier,
            stock_symbol: Telnyx::Rcs::StockSymbolBrandIdentifier
          }
        end
      end
    end
  end
end
