module Telnyx
  module Models
    module ExternalConnections
      type civic_address_list_response =
        { data: ::Array[Telnyx::ExternalConnections::CivicAddress] }

      class CivicAddressListResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::ExternalConnections::CivicAddress]?

        def data=: (
          ::Array[Telnyx::ExternalConnections::CivicAddress]
        ) -> ::Array[Telnyx::ExternalConnections::CivicAddress]

        def initialize: (
          ?data: ::Array[Telnyx::ExternalConnections::CivicAddress]
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::ExternalConnections::CivicAddress]
        }
      end
    end
  end
end
