module Telnyx
  module Models
    class ExternalConnectionPhoneNumber = ExternalConnections::ExternalConnectionPhoneNumber

    module ExternalConnections
      type external_connection_phone_number =
        {
          acquired_capabilities: ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability],
          civic_address_id: String,
          displayed_country_code: String,
          location_id: String,
          number_id: String,
          telephone_number: String,
          ticket_id: String
        }

      class ExternalConnectionPhoneNumber < Telnyx::Internal::Type::BaseModel
        attr_reader acquired_capabilities: ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability]?

        def acquired_capabilities=: (
          ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability]
        ) -> ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability]

        attr_reader civic_address_id: String?

        def civic_address_id=: (String) -> String

        attr_reader displayed_country_code: String?

        def displayed_country_code=: (String) -> String

        attr_reader location_id: String?

        def location_id=: (String) -> String

        attr_reader number_id: String?

        def number_id=: (String) -> String

        attr_reader telephone_number: String?

        def telephone_number=: (String) -> String

        attr_reader ticket_id: String?

        def ticket_id=: (String) -> String

        def initialize: (
          ?acquired_capabilities: ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability],
          ?civic_address_id: String,
          ?displayed_country_code: String,
          ?location_id: String,
          ?number_id: String,
          ?telephone_number: String,
          ?ticket_id: String
        ) -> void

        def to_hash: -> {
          acquired_capabilities: ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability],
          civic_address_id: String,
          displayed_country_code: String,
          location_id: String,
          number_id: String,
          telephone_number: String,
          ticket_id: String
        }

        type acquired_capability =
          :FirstPartyAppAssignment
          | :InboundCalling
          | :Office365
          | :OutboundCalling
          | :UserAssignment

        module AcquiredCapability
          extend Telnyx::Internal::Type::Enum

          FIRST_PARTY_APP_ASSIGNMENT: :FirstPartyAppAssignment
          INBOUND_CALLING: :InboundCalling
          OFFICE365: :Office365
          OUTBOUND_CALLING: :OutboundCalling
          USER_ASSIGNMENT: :UserAssignment

          def self?.values: -> ::Array[Telnyx::Models::ExternalConnections::ExternalConnectionPhoneNumber::acquired_capability]
        end
      end
    end
  end
end
