module Telnyx
  module Models
    module ExternalConnections
      type location =
        {
          id: String,
          additional_info: String,
          description: String,
          is_default: bool
        }

      class Location < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader additional_info: String?

        def additional_info=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader is_default: bool?

        def is_default=: (bool) -> bool

        def initialize: (
          ?id: String,
          ?additional_info: String,
          ?description: String,
          ?is_default: bool
        ) -> void

        def to_hash: -> {
          id: String,
          additional_info: String,
          description: String,
          is_default: bool
        }
      end
    end
  end
end
