module Telnyx
  module Models
    module ExternalConnections
      type log_message_retrieve_response =
        { log_messages: ::Array[Telnyx::ExternalConnections::LogMessage] }

      class LogMessageRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader log_messages: ::Array[Telnyx::ExternalConnections::LogMessage]?

        def log_messages=: (
          ::Array[Telnyx::ExternalConnections::LogMessage]
        ) -> ::Array[Telnyx::ExternalConnections::LogMessage]

        def initialize: (
          ?log_messages: ::Array[Telnyx::ExternalConnections::LogMessage]
        ) -> void

        def to_hash: -> {
          log_messages: ::Array[Telnyx::ExternalConnections::LogMessage]
        }
      end
    end
  end
end
