module Telnyx
  module Models
    module ExternalConnections
      type phone_number_retrieve_response =
        { data: Telnyx::ExternalConnections::ExternalConnectionPhoneNumber }

      class PhoneNumberRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::ExternalConnections::ExternalConnectionPhoneNumber?

        def data=: (
          Telnyx::ExternalConnections::ExternalConnectionPhoneNumber
        ) -> Telnyx::ExternalConnections::ExternalConnectionPhoneNumber

        def initialize: (
          ?data: Telnyx::ExternalConnections::ExternalConnectionPhoneNumber
        ) -> void

        def to_hash: -> {
          data: Telnyx::ExternalConnections::ExternalConnectionPhoneNumber
        }
      end
    end
  end
end
