module Telnyx
  module Models
    module Queues
      type call_retrieve_response = { data: Telnyx::Queues::QueueCall }

      class CallRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Queues::QueueCall?

        def data=: (Telnyx::Queues::QueueCall) -> Telnyx::Queues::QueueCall

        def initialize: (?data: Telnyx::Queues::QueueCall) -> void

        def to_hash: -> { data: Telnyx::Queues::QueueCall }
      end
    end
  end
end
