module Telnyx
  module Models
    module Queues
      type call_remove_params =
        { queue_name: String, call_control_id: String }
        & Telnyx::Internal::Type::request_parameters

      class CallRemoveParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor queue_name: String

        attr_accessor call_control_id: String

        def initialize: (
          queue_name: String,
          call_control_id: String,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          queue_name: String,
          call_control_id: String,
          request_options: Telnyx::RequestOptions
        }
      end
    end
  end
end
