module Telnyx
  module Models
    module Porting
      type event_retrieve_response =
        { data: Telnyx::Models::Porting::EventRetrieveResponse::data }

      class EventRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Models::Porting::EventRetrieveResponse::data?

        def data=: (
          Telnyx::Models::Porting::EventRetrieveResponse::data
        ) -> Telnyx::Models::Porting::EventRetrieveResponse::data

        def initialize: (
          ?data: Telnyx::Models::Porting::EventRetrieveResponse::data
        ) -> void

        def to_hash: -> {
          data: Telnyx::Models::Porting::EventRetrieveResponse::data
        }

        type data =
          Telnyx::Porting::PortingEventDeletedPayload
          | Telnyx::Porting::PortingEventMessagingChangedPayload
          | Telnyx::Porting::PortingEventStatusChangedEvent
          | Telnyx::Porting::PortingEventNewCommentEvent
          | Telnyx::Porting::PortingEventSplitEvent
          | Telnyx::Porting::PortingEventWithoutWebhook

        module Data
          extend Telnyx::Internal::Type::Union

          def self?.variants: -> ::Array[Telnyx::Models::Porting::EventRetrieveResponse::data]
        end
      end
    end
  end
end
