module Telnyx
  module Models
    module Porting
      type event_list_response =
        Telnyx::Porting::PortingEventDeletedPayload
        | Telnyx::Porting::PortingEventMessagingChangedPayload
        | Telnyx::Porting::PortingEventStatusChangedEvent
        | Telnyx::Porting::PortingEventNewCommentEvent
        | Telnyx::Porting::PortingEventSplitEvent
        | Telnyx::Porting::PortingEventWithoutWebhook

      module EventListResponse
        extend Telnyx::Internal::Type::Union

        def self?.variants: -> ::Array[Telnyx::Models::Porting::event_list_response]
      end
    end
  end
end
