module Telnyx
  module Models
    module ManagedAccounts
      type action_disable_response = { data: Telnyx::ManagedAccount }

      class ActionDisableResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::ManagedAccount?

        def data=: (Telnyx::ManagedAccount) -> Telnyx::ManagedAccount

        def initialize: (?data: Telnyx::ManagedAccount) -> void

        def to_hash: -> { data: Telnyx::ManagedAccount }
      end
    end
  end
end
