module Telnyx
  module Models
    module Texml
      module Accounts
        type conference_retrieve_conferences_response =
          {
            conferences: ::Array[Telnyx::Texml::Accounts::ConferenceResource],
            end_: Integer,
            first_page_uri: String,
            next_page_uri: String,
            page: Integer,
            page_size: Integer,
            start: Integer,
            uri: String
          }

        class ConferenceRetrieveConferencesResponse < Telnyx::Internal::Type::BaseModel
          attr_reader conferences: ::Array[Telnyx::Texml::Accounts::ConferenceResource]?

          def conferences=: (
            ::Array[Telnyx::Texml::Accounts::ConferenceResource]
          ) -> ::Array[Telnyx::Texml::Accounts::ConferenceResource]

          attr_reader end_: Integer?

          def end_=: (Integer) -> Integer

          attr_reader first_page_uri: String?

          def first_page_uri=: (String) -> String

          attr_reader next_page_uri: String?

          def next_page_uri=: (String) -> String

          attr_reader page: Integer?

          def page=: (Integer) -> Integer

          attr_reader page_size: Integer?

          def page_size=: (Integer) -> Integer

          attr_reader start: Integer?

          def start=: (Integer) -> Integer

          attr_reader uri: String?

          def uri=: (String) -> String

          def initialize: (
            ?conferences: ::Array[Telnyx::Texml::Accounts::ConferenceResource],
            ?end_: Integer,
            ?first_page_uri: String,
            ?next_page_uri: String,
            ?page: Integer,
            ?page_size: Integer,
            ?start: Integer,
            ?uri: String
          ) -> void

          def to_hash: -> {
            conferences: ::Array[Telnyx::Texml::Accounts::ConferenceResource],
            end_: Integer,
            first_page_uri: String,
            next_page_uri: String,
            page: Integer,
            page_size: Integer,
            start: Integer,
            uri: String
          }
        end
      end
    end
  end
end
