module Telnyx
  module Models
    module Texml
      module Accounts
        module Calls
          type twiml_recording_channels = 1 | 2

          module TwimlRecordingChannels
            extend Telnyx::Internal::Type::Enum

            CHANNEL_1: 1
            CHANNEL_2: 2

            def self?.values: -> ::Array[Telnyx::Models::Texml::Accounts::Calls::twiml_recording_channels]
          end
        end
      end
    end
  end
end
