module Telnyx
  module Models
    module Calls
      type action_start_ai_assistant_response =
        { data: Telnyx::Calls::CallControlCommandResultWithConversationID }

      class ActionStartAIAssistantResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Calls::CallControlCommandResultWithConversationID?

        def data=: (
          Telnyx::Calls::CallControlCommandResultWithConversationID
        ) -> Telnyx::Calls::CallControlCommandResultWithConversationID

        def initialize: (
          ?data: Telnyx::Calls::CallControlCommandResultWithConversationID
        ) -> void

        def to_hash: -> {
          data: Telnyx::Calls::CallControlCommandResultWithConversationID
        }
      end
    end
  end
end
