module Telnyx
  module Models
    module Calls
      type action_answer_params =
        {
          call_control_id: String,
          assistant: Telnyx::Calls::ActionAnswerParams::Assistant,
          billing_group_id: String,
          client_state: String,
          command_id: String,
          custom_headers: ::Array[Telnyx::CustomSipHeader],
          preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          record: Telnyx::Models::Calls::ActionAnswerParams::record,
          record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          record_custom_file_name: String,
          record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          record_max_length: Integer,
          record_timeout_secs: Integer,
          record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          send_silence_when_idle: bool,
          sip_headers: ::Array[Telnyx::SipHeader],
          sound_modifications: Telnyx::SoundModifications,
          stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          stream_codec: Telnyx::Models::stream_codec,
          stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          stream_url: String,
          transcription: bool,
          transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          webhook_url: String,
          webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          webhook_urls: ::Hash[Symbol, String],
          webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method
        }
        & Telnyx::Internal::Type::request_parameters

      class ActionAnswerParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor call_control_id: String

        attr_reader assistant: Telnyx::Calls::ActionAnswerParams::Assistant?

        def assistant=: (
          Telnyx::Calls::ActionAnswerParams::Assistant
        ) -> Telnyx::Calls::ActionAnswerParams::Assistant

        attr_reader billing_group_id: String?

        def billing_group_id=: (String) -> String

        attr_reader client_state: String?

        def client_state=: (String) -> String

        attr_reader command_id: String?

        def command_id=: (String) -> String

        attr_reader custom_headers: ::Array[Telnyx::CustomSipHeader]?

        def custom_headers=: (
          ::Array[Telnyx::CustomSipHeader]
        ) -> ::Array[Telnyx::CustomSipHeader]

        attr_reader preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs?

        def preferred_codecs=: (
          Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs
        ) -> Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs

        attr_reader record: Telnyx::Models::Calls::ActionAnswerParams::record?

        def record=: (
          Telnyx::Models::Calls::ActionAnswerParams::record
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record

        attr_reader record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels?

        def record_channels=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_channels
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_channels

        attr_reader record_custom_file_name: String?

        def record_custom_file_name=: (String) -> String

        attr_reader record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format?

        def record_format=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_format
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_format

        attr_reader record_max_length: Integer?

        def record_max_length=: (Integer) -> Integer

        attr_reader record_timeout_secs: Integer?

        def record_timeout_secs=: (Integer) -> Integer

        attr_reader record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track?

        def record_track=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_track
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_track

        attr_reader record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim?

        def record_trim=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_trim
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_trim

        attr_reader send_silence_when_idle: bool?

        def send_silence_when_idle=: (bool) -> bool

        attr_reader sip_headers: ::Array[Telnyx::SipHeader]?

        def sip_headers=: (
          ::Array[Telnyx::SipHeader]
        ) -> ::Array[Telnyx::SipHeader]

        attr_reader sound_modifications: Telnyx::SoundModifications?

        def sound_modifications=: (
          Telnyx::SoundModifications
        ) -> Telnyx::SoundModifications

        attr_reader stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec?

        def stream_bidirectional_codec=: (
          Telnyx::Models::stream_bidirectional_codec
        ) -> Telnyx::Models::stream_bidirectional_codec

        attr_reader stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode?

        def stream_bidirectional_mode=: (
          Telnyx::Models::stream_bidirectional_mode
        ) -> Telnyx::Models::stream_bidirectional_mode

        attr_reader stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs?

        def stream_bidirectional_target_legs=: (
          Telnyx::Models::stream_bidirectional_target_legs
        ) -> Telnyx::Models::stream_bidirectional_target_legs

        attr_reader stream_codec: Telnyx::Models::stream_codec?

        def stream_codec=: (
          Telnyx::Models::stream_codec
        ) -> Telnyx::Models::stream_codec

        attr_reader stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track?

        def stream_track=: (
          Telnyx::Models::Calls::ActionAnswerParams::stream_track
        ) -> Telnyx::Models::Calls::ActionAnswerParams::stream_track

        attr_reader stream_url: String?

        def stream_url=: (String) -> String

        attr_reader transcription: bool?

        def transcription=: (bool) -> bool

        attr_reader transcription_config: Telnyx::Calls::TranscriptionStartRequest?

        def transcription_config=: (
          Telnyx::Calls::TranscriptionStartRequest
        ) -> Telnyx::Calls::TranscriptionStartRequest

        attr_reader webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]?

        def webhook_retries_policies=: (
          ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]
        ) -> ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]

        attr_reader webhook_url: String?

        def webhook_url=: (String) -> String

        attr_reader webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method?

        def webhook_url_method=: (
          Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method
        ) -> Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method

        attr_reader webhook_urls: ::Hash[Symbol, String]?

        def webhook_urls=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method?

        def webhook_urls_method=: (
          Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method
        ) -> Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method

        def initialize: (
          call_control_id: String,
          ?assistant: Telnyx::Calls::ActionAnswerParams::Assistant,
          ?billing_group_id: String,
          ?client_state: String,
          ?command_id: String,
          ?custom_headers: ::Array[Telnyx::CustomSipHeader],
          ?preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          ?record: Telnyx::Models::Calls::ActionAnswerParams::record,
          ?record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          ?record_custom_file_name: String,
          ?record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          ?record_max_length: Integer,
          ?record_timeout_secs: Integer,
          ?record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          ?record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          ?send_silence_when_idle: bool,
          ?sip_headers: ::Array[Telnyx::SipHeader],
          ?sound_modifications: Telnyx::SoundModifications,
          ?stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          ?stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          ?stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          ?stream_codec: Telnyx::Models::stream_codec,
          ?stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          ?stream_url: String,
          ?transcription: bool,
          ?transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          ?webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          ?webhook_url: String,
          ?webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          ?webhook_urls: ::Hash[Symbol, String],
          ?webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          call_control_id: String,
          assistant: Telnyx::Calls::ActionAnswerParams::Assistant,
          billing_group_id: String,
          client_state: String,
          command_id: String,
          custom_headers: ::Array[Telnyx::CustomSipHeader],
          preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          record: Telnyx::Models::Calls::ActionAnswerParams::record,
          record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          record_custom_file_name: String,
          record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          record_max_length: Integer,
          record_timeout_secs: Integer,
          record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          send_silence_when_idle: bool,
          sip_headers: ::Array[Telnyx::SipHeader],
          sound_modifications: Telnyx::SoundModifications,
          stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          stream_codec: Telnyx::Models::stream_codec,
          stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          stream_url: String,
          transcription: bool,
          transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          webhook_url: String,
          webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          webhook_urls: ::Hash[Symbol, String],
          webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method,
          request_options: Telnyx::RequestOptions
        }

        type assistant =
          {
            id: String,
            dynamic_variables: ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable],
            external_llm: top,
            fallback_config: top,
            greeting: String,
            instructions: String,
            llm_api_key_ref: String,
            mcp_servers: ::Array[top],
            model: String,
            name: String,
            observability_settings: top,
            openai_api_key_ref: String,
            tools: ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]
          }

        class Assistant < Telnyx::Internal::Type::BaseModel
          attr_accessor id: String

          attr_reader dynamic_variables: ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable]?

          def dynamic_variables=: (
            ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable]
          ) -> ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable]

          attr_reader external_llm: top?

          def external_llm=: (top) -> top

          attr_reader fallback_config: top?

          def fallback_config=: (top) -> top

          attr_reader greeting: String?

          def greeting=: (String) -> String

          attr_reader instructions: String?

          def instructions=: (String) -> String

          attr_reader llm_api_key_ref: String?

          def llm_api_key_ref=: (String) -> String

          attr_reader mcp_servers: ::Array[top]?

          def mcp_servers=: (::Array[top]) -> ::Array[top]

          attr_reader model: String?

          def model=: (String) -> String

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader observability_settings: top?

          def observability_settings=: (top) -> top

          attr_reader openai_api_key_ref: String?

          def openai_api_key_ref=: (String) -> String

          attr_reader tools: ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]?

          def tools=: (
            ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]
          ) -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]

          def initialize: (
            id: String,
            ?dynamic_variables: ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable],
            ?external_llm: top,
            ?fallback_config: top,
            ?greeting: String,
            ?instructions: String,
            ?llm_api_key_ref: String,
            ?mcp_servers: ::Array[top],
            ?model: String,
            ?name: String,
            ?observability_settings: top,
            ?openai_api_key_ref: String,
            ?tools: ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]
          ) -> void

          def to_hash: -> {
            id: String,
            dynamic_variables: ::Hash[Symbol, Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable],
            external_llm: top,
            fallback_config: top,
            greeting: String,
            instructions: String,
            llm_api_key_ref: String,
            mcp_servers: ::Array[top],
            model: String,
            name: String,
            observability_settings: top,
            openai_api_key_ref: String,
            tools: ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]
          }

          type dynamic_variable = String | Float | bool

          module DynamicVariable
            extend Telnyx::Internal::Type::Union

            def self?.variants: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::dynamic_variable]
          end

          type tool =
            Telnyx::Calls::ActionAnswerParams::Assistant::Tool::BookAppointment
            | Telnyx::Calls::ActionAnswerParams::Assistant::Tool::CheckAvailability
            | Telnyx::AI::WebhookTool
            | Telnyx::AI::HangupTool
            | Telnyx::AI::TransferTool
            | Telnyx::Calls::ActionAnswerParams::Assistant::Tool::Retrieval

          module Tool
            extend Telnyx::Internal::Type::Union

            type book_appointment =
              {
                book_appointment: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::BookAppointment::BookAppointment,
                type: :book_appointment
              }

            class BookAppointment < Telnyx::Internal::Type::BaseModel
              attr_accessor book_appointment: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::BookAppointment::BookAppointment

              attr_accessor type: :book_appointment

              def initialize: (
                book_appointment: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::BookAppointment::BookAppointment,
                ?type: :book_appointment
              ) -> void

              def to_hash: -> {
                book_appointment: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::BookAppointment::BookAppointment,
                type: :book_appointment
              }

              type book_appointment =
                {
                  api_key_ref: String,
                  event_type_id: Integer,
                  attendee_name: String,
                  attendee_timezone: String
                }

              class BookAppointment < Telnyx::Internal::Type::BaseModel
                attr_accessor api_key_ref: String

                attr_accessor event_type_id: Integer

                attr_reader attendee_name: String?

                def attendee_name=: (String) -> String

                attr_reader attendee_timezone: String?

                def attendee_timezone=: (String) -> String

                def initialize: (
                  api_key_ref: String,
                  event_type_id: Integer,
                  ?attendee_name: String,
                  ?attendee_timezone: String
                ) -> void

                def to_hash: -> {
                  api_key_ref: String,
                  event_type_id: Integer,
                  attendee_name: String,
                  attendee_timezone: String
                }
              end
            end

            type check_availability =
              {
                check_availability: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::CheckAvailability::CheckAvailability,
                type: :check_availability
              }

            class CheckAvailability < Telnyx::Internal::Type::BaseModel
              attr_accessor check_availability: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::CheckAvailability::CheckAvailability

              attr_accessor type: :check_availability

              def initialize: (
                check_availability: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::CheckAvailability::CheckAvailability,
                ?type: :check_availability
              ) -> void

              def to_hash: -> {
                check_availability: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::CheckAvailability::CheckAvailability,
                type: :check_availability
              }

              type check_availability =
                { api_key_ref: String, event_type_id: Integer }

              class CheckAvailability < Telnyx::Internal::Type::BaseModel
                attr_accessor api_key_ref: String

                attr_accessor event_type_id: Integer

                def initialize: (
                  api_key_ref: String,
                  event_type_id: Integer
                ) -> void

                def to_hash: -> { api_key_ref: String, event_type_id: Integer }
              end
            end

            type retrieval =
              {
                retrieval: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::Retrieval::Retrieval,
                type: :retrieval
              }

            class Retrieval < Telnyx::Internal::Type::BaseModel
              attr_accessor retrieval: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::Retrieval::Retrieval

              attr_accessor type: :retrieval

              def initialize: (
                retrieval: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::Retrieval::Retrieval,
                ?type: :retrieval
              ) -> void

              def to_hash: -> {
                retrieval: Telnyx::Calls::ActionAnswerParams::Assistant::Tool::Retrieval::Retrieval,
                type: :retrieval
              }

              type retrieval =
                { bucket_ids: ::Array[String], max_num_results: Integer }

              class Retrieval < Telnyx::Internal::Type::BaseModel
                attr_accessor bucket_ids: ::Array[String]

                attr_reader max_num_results: Integer?

                def max_num_results=: (Integer) -> Integer

                def initialize: (
                  bucket_ids: ::Array[String],
                  ?max_num_results: Integer
                ) -> void

                def to_hash: -> {
                  bucket_ids: ::Array[String],
                  max_num_results: Integer
                }
              end
            end

            def self?.variants: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::Assistant::tool]
          end
        end

        type preferred_codecs = :"G722,PCMU,PCMA,G729,OPUS,VP8,H264"

        module PreferredCodecs
          extend Telnyx::Internal::Type::Enum

          G722_PCMU_PCMA_G729_OPUS_VP8_H264: :"G722,PCMU,PCMA,G729,OPUS,VP8,H264"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs]
        end

        type record = :"record-from-answer"

        module Record
          extend Telnyx::Internal::Type::Enum

          RECORD_FROM_ANSWER: :"record-from-answer"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record]
        end

        type record_channels = :single | :dual

        module RecordChannels
          extend Telnyx::Internal::Type::Enum

          SINGLE: :single
          DUAL: :dual

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_channels]
        end

        type record_format = :wav | :mp3

        module RecordFormat
          extend Telnyx::Internal::Type::Enum

          WAV: :wav
          MP3: :mp3

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_format]
        end

        type record_track = :both | :inbound | :outbound

        module RecordTrack
          extend Telnyx::Internal::Type::Enum

          BOTH: :both
          INBOUND: :inbound
          OUTBOUND: :outbound

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_track]
        end

        type record_trim = :"trim-silence"

        module RecordTrim
          extend Telnyx::Internal::Type::Enum

          TRIM_SILENCE: :"trim-silence"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_trim]
        end

        type stream_track = :inbound_track | :outbound_track | :both_tracks

        module StreamTrack
          extend Telnyx::Internal::Type::Enum

          INBOUND_TRACK: :inbound_track
          OUTBOUND_TRACK: :outbound_track
          BOTH_TRACKS: :both_tracks

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::stream_track]
        end

        type webhook_retries_policy = { retries_ms: ::Array[Integer] }

        class WebhookRetriesPolicy < Telnyx::Internal::Type::BaseModel
          attr_reader retries_ms: ::Array[Integer]?

          def retries_ms=: (::Array[Integer]) -> ::Array[Integer]

          def initialize: (?retries_ms: ::Array[Integer]) -> void

          def to_hash: -> { retries_ms: ::Array[Integer] }
        end

        type webhook_url_method = :POST | :GET

        module WebhookURLMethod
          extend Telnyx::Internal::Type::Enum

          POST: :POST
          GET: :GET

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method]
        end

        type webhook_urls_method = :POST | :GET

        module WebhookURLsMethod
          extend Telnyx::Internal::Type::Enum

          POST: :POST
          GET: :GET

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method]
        end
      end
    end
  end
end
