module Telnyx
  module Models
    module Calls
      type action_start_ai_assistant_params =
        {
          assistant: Telnyx::Calls::ActionStartAIAssistantParams::Assistant,
          client_state: String,
          command_id: String,
          greeting: String,
          interruption_settings: Telnyx::Calls::InterruptionSettings,
          transcription: Telnyx::Calls::TranscriptionConfig,
          voice: String,
          voice_settings: Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings
        }
        & Telnyx::Internal::Type::request_parameters

      class ActionStartAIAssistantParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_reader assistant: Telnyx::Calls::ActionStartAIAssistantParams::Assistant?

        def assistant=: (
          Telnyx::Calls::ActionStartAIAssistantParams::Assistant
        ) -> Telnyx::Calls::ActionStartAIAssistantParams::Assistant

        attr_reader client_state: String?

        def client_state=: (String) -> String

        attr_reader command_id: String?

        def command_id=: (String) -> String

        attr_reader greeting: String?

        def greeting=: (String) -> String

        attr_reader interruption_settings: Telnyx::Calls::InterruptionSettings?

        def interruption_settings=: (
          Telnyx::Calls::InterruptionSettings
        ) -> Telnyx::Calls::InterruptionSettings

        attr_reader transcription: Telnyx::Calls::TranscriptionConfig?

        def transcription=: (
          Telnyx::Calls::TranscriptionConfig
        ) -> Telnyx::Calls::TranscriptionConfig

        attr_reader voice: String?

        def voice=: (String) -> String

        attr_reader voice_settings: Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings?

        def voice_settings=: (
          Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings
        ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings

        def initialize: (
          ?assistant: Telnyx::Calls::ActionStartAIAssistantParams::Assistant,
          ?client_state: String,
          ?command_id: String,
          ?greeting: String,
          ?interruption_settings: Telnyx::Calls::InterruptionSettings,
          ?transcription: Telnyx::Calls::TranscriptionConfig,
          ?voice: String,
          ?voice_settings: Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          assistant: Telnyx::Calls::ActionStartAIAssistantParams::Assistant,
          client_state: String,
          command_id: String,
          greeting: String,
          interruption_settings: Telnyx::Calls::InterruptionSettings,
          transcription: Telnyx::Calls::TranscriptionConfig,
          voice: String,
          voice_settings: Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings,
          request_options: Telnyx::RequestOptions
        }

        type assistant =
          { id: String, instructions: String, openai_api_key_ref: String }

        class Assistant < Telnyx::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader instructions: String?

          def instructions=: (String) -> String

          attr_reader openai_api_key_ref: String?

          def openai_api_key_ref=: (String) -> String

          def initialize: (
            ?id: String,
            ?instructions: String,
            ?openai_api_key_ref: String
          ) -> void

          def to_hash: -> {
            id: String,
            instructions: String,
            openai_api_key_ref: String
          }
        end

        type voice_settings =
          Telnyx::Calls::ElevenLabsVoiceSettings
          | Telnyx::Calls::TelnyxVoiceSettings
          | Telnyx::Calls::AwsVoiceSettings
          | Telnyx::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure
          | Telnyx::Calls::ActionStartAIAssistantParams::VoiceSettings::Rime
          | Telnyx::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble

        module VoiceSettings
          extend Telnyx::Internal::Type::Union

          type azure =
            {
              type: :azure,
              api_key_ref: String,
              deployment_id: String,
              effect: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect,
              gender: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender,
              region: String
            }

          class Azure < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :azure

            attr_reader api_key_ref: String?

            def api_key_ref=: (String) -> String

            attr_reader deployment_id: String?

            def deployment_id=: (String) -> String

            attr_reader effect: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect?

            def effect=: (
              Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect
            ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect

            attr_reader gender: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender?

            def gender=: (
              Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender
            ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender

            attr_reader region: String?

            def region=: (String) -> String

            def initialize: (
              ?api_key_ref: String,
              ?deployment_id: String,
              ?effect: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect,
              ?gender: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender,
              ?region: String,
              ?type: :azure
            ) -> void

            def to_hash: -> {
              type: :azure,
              api_key_ref: String,
              deployment_id: String,
              effect: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect,
              gender: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender,
              region: String
            }

            type effect = :eq_car | :eq_telecomhp8k

            module Effect
              extend Telnyx::Internal::Type::Enum

              EQ_CAR: :eq_car
              EQ_TELECOMHP8K: :eq_telecomhp8k

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::effect]
            end

            type gender = :Male | :Female

            module Gender
              extend Telnyx::Internal::Type::Enum

              MALE: :Male
              FEMALE: :Female

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Azure::gender]
            end
          end

          type rime = { type: :rime, voice_speed: Float }

          class Rime < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :rime

            attr_reader voice_speed: Float?

            def voice_speed=: (Float) -> Float

            def initialize: (?voice_speed: Float, ?type: :rime) -> void

            def to_hash: -> { type: :rime, voice_speed: Float }
          end

          type resemble =
            {
              type: :resemble,
              format_: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_,
              precision: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision,
              sample_rate: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate
            }

          class Resemble < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :resemble

            attr_reader format_: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_?

            def format_=: (
              Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_
            ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_

            attr_reader precision: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision?

            def precision=: (
              Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision
            ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision

            attr_reader sample_rate: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate?

            def sample_rate=: (
              Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate
            ) -> Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate

            def initialize: (
              ?format_: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_,
              ?precision: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision,
              ?sample_rate: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate,
              ?type: :resemble
            ) -> void

            def to_hash: -> {
              type: :resemble,
              format_: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_,
              precision: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision,
              sample_rate: Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate
            }

            type format_ = :wav | :mp3

            module Format
              extend Telnyx::Internal::Type::Enum

              WAV: :wav
              MP3: :mp3

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::format_]
            end

            type precision = :PCM_16 | :PCM_24 | :PCM_32 | :MULAW

            module Precision
              extend Telnyx::Internal::Type::Enum

              PCM_16: :PCM_16
              PCM_24: :PCM_24
              PCM_32: :PCM_32
              MULAW: :MULAW

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::precision]
            end

            type sample_rate =
              :"8000" | :"16000" | :"22050" | :"32000" | :"44100" | :"48000"

            module SampleRate
              extend Telnyx::Internal::Type::Enum

              SAMPLE_RATE_8000: :"8000"
              SAMPLE_RATE_16000: :"16000"
              SAMPLE_RATE_22050: :"22050"
              SAMPLE_RATE_32000: :"32000"
              SAMPLE_RATE_44100: :"44100"
              SAMPLE_RATE_48000: :"48000"

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::VoiceSettings::Resemble::sample_rate]
            end
          end

          def self?.variants: -> ::Array[Telnyx::Models::Calls::ActionStartAIAssistantParams::voice_settings]
        end
      end
    end
  end
end
