module Telnyx
  module Models
    module Calls
      type action_answer_params =
        {
          call_control_id: String,
          assistant: Telnyx::CallAssistantRequest,
          billing_group_id: String,
          client_state: String,
          command_id: String,
          conversation_relay_config: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig,
          custom_headers: ::Array[Telnyx::CustomSipHeader],
          deepfake_detection: Telnyx::Calls::ActionAnswerParams::DeepfakeDetection,
          preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          record: Telnyx::Models::Calls::ActionAnswerParams::record,
          record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          record_custom_file_name: String,
          record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          record_max_length: Integer,
          record_timeout_secs: Integer,
          record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          send_silence_when_idle: bool,
          sip_headers: ::Array[Telnyx::SipHeader],
          sound_modifications: Telnyx::SoundModifications,
          stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          stream_codec: Telnyx::Models::stream_codec,
          stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          stream_url: String,
          transcription: bool,
          transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          webhook_url: String,
          webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          webhook_urls: ::Hash[Symbol, String],
          webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method
        }
        & Telnyx::Internal::Type::request_parameters

      class ActionAnswerParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor call_control_id: String

        attr_reader assistant: Telnyx::CallAssistantRequest?

        def assistant=: (
          Telnyx::CallAssistantRequest
        ) -> Telnyx::CallAssistantRequest

        attr_reader billing_group_id: String?

        def billing_group_id=: (String) -> String

        attr_reader client_state: String?

        def client_state=: (String) -> String

        attr_reader command_id: String?

        def command_id=: (String) -> String

        attr_reader conversation_relay_config: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig?

        def conversation_relay_config=: (
          Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig
        ) -> Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig

        attr_reader custom_headers: ::Array[Telnyx::CustomSipHeader]?

        def custom_headers=: (
          ::Array[Telnyx::CustomSipHeader]
        ) -> ::Array[Telnyx::CustomSipHeader]

        attr_reader deepfake_detection: Telnyx::Calls::ActionAnswerParams::DeepfakeDetection?

        def deepfake_detection=: (
          Telnyx::Calls::ActionAnswerParams::DeepfakeDetection
        ) -> Telnyx::Calls::ActionAnswerParams::DeepfakeDetection

        attr_reader preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs?

        def preferred_codecs=: (
          Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs
        ) -> Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs

        attr_reader record: Telnyx::Models::Calls::ActionAnswerParams::record?

        def record=: (
          Telnyx::Models::Calls::ActionAnswerParams::record
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record

        attr_reader record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels?

        def record_channels=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_channels
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_channels

        attr_reader record_custom_file_name: String?

        def record_custom_file_name=: (String) -> String

        attr_reader record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format?

        def record_format=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_format
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_format

        attr_reader record_max_length: Integer?

        def record_max_length=: (Integer) -> Integer

        attr_reader record_timeout_secs: Integer?

        def record_timeout_secs=: (Integer) -> Integer

        attr_reader record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track?

        def record_track=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_track
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_track

        attr_reader record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim?

        def record_trim=: (
          Telnyx::Models::Calls::ActionAnswerParams::record_trim
        ) -> Telnyx::Models::Calls::ActionAnswerParams::record_trim

        attr_reader send_silence_when_idle: bool?

        def send_silence_when_idle=: (bool) -> bool

        attr_reader sip_headers: ::Array[Telnyx::SipHeader]?

        def sip_headers=: (
          ::Array[Telnyx::SipHeader]
        ) -> ::Array[Telnyx::SipHeader]

        attr_reader sound_modifications: Telnyx::SoundModifications?

        def sound_modifications=: (
          Telnyx::SoundModifications
        ) -> Telnyx::SoundModifications

        attr_reader stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec?

        def stream_bidirectional_codec=: (
          Telnyx::Models::stream_bidirectional_codec
        ) -> Telnyx::Models::stream_bidirectional_codec

        attr_reader stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode?

        def stream_bidirectional_mode=: (
          Telnyx::Models::stream_bidirectional_mode
        ) -> Telnyx::Models::stream_bidirectional_mode

        attr_reader stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs?

        def stream_bidirectional_target_legs=: (
          Telnyx::Models::stream_bidirectional_target_legs
        ) -> Telnyx::Models::stream_bidirectional_target_legs

        attr_reader stream_codec: Telnyx::Models::stream_codec?

        def stream_codec=: (
          Telnyx::Models::stream_codec
        ) -> Telnyx::Models::stream_codec

        attr_reader stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track?

        def stream_track=: (
          Telnyx::Models::Calls::ActionAnswerParams::stream_track
        ) -> Telnyx::Models::Calls::ActionAnswerParams::stream_track

        attr_reader stream_url: String?

        def stream_url=: (String) -> String

        attr_reader transcription: bool?

        def transcription=: (bool) -> bool

        attr_reader transcription_config: Telnyx::Calls::TranscriptionStartRequest?

        def transcription_config=: (
          Telnyx::Calls::TranscriptionStartRequest
        ) -> Telnyx::Calls::TranscriptionStartRequest

        attr_reader webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]?

        def webhook_retries_policies=: (
          ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]
        ) -> ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy]

        attr_reader webhook_url: String?

        def webhook_url=: (String) -> String

        attr_reader webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method?

        def webhook_url_method=: (
          Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method
        ) -> Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method

        attr_reader webhook_urls: ::Hash[Symbol, String]?

        def webhook_urls=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method?

        def webhook_urls_method=: (
          Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method
        ) -> Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method

        def initialize: (
          call_control_id: String,
          ?assistant: Telnyx::CallAssistantRequest,
          ?billing_group_id: String,
          ?client_state: String,
          ?command_id: String,
          ?conversation_relay_config: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig,
          ?custom_headers: ::Array[Telnyx::CustomSipHeader],
          ?deepfake_detection: Telnyx::Calls::ActionAnswerParams::DeepfakeDetection,
          ?preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          ?record: Telnyx::Models::Calls::ActionAnswerParams::record,
          ?record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          ?record_custom_file_name: String,
          ?record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          ?record_max_length: Integer,
          ?record_timeout_secs: Integer,
          ?record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          ?record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          ?send_silence_when_idle: bool,
          ?sip_headers: ::Array[Telnyx::SipHeader],
          ?sound_modifications: Telnyx::SoundModifications,
          ?stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          ?stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          ?stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          ?stream_codec: Telnyx::Models::stream_codec,
          ?stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          ?stream_url: String,
          ?transcription: bool,
          ?transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          ?webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          ?webhook_url: String,
          ?webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          ?webhook_urls: ::Hash[Symbol, String],
          ?webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          call_control_id: String,
          assistant: Telnyx::CallAssistantRequest,
          billing_group_id: String,
          client_state: String,
          command_id: String,
          conversation_relay_config: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig,
          custom_headers: ::Array[Telnyx::CustomSipHeader],
          deepfake_detection: Telnyx::Calls::ActionAnswerParams::DeepfakeDetection,
          preferred_codecs: Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs,
          record: Telnyx::Models::Calls::ActionAnswerParams::record,
          record_channels: Telnyx::Models::Calls::ActionAnswerParams::record_channels,
          record_custom_file_name: String,
          record_format: Telnyx::Models::Calls::ActionAnswerParams::record_format,
          record_max_length: Integer,
          record_timeout_secs: Integer,
          record_track: Telnyx::Models::Calls::ActionAnswerParams::record_track,
          record_trim: Telnyx::Models::Calls::ActionAnswerParams::record_trim,
          send_silence_when_idle: bool,
          sip_headers: ::Array[Telnyx::SipHeader],
          sound_modifications: Telnyx::SoundModifications,
          stream_bidirectional_codec: Telnyx::Models::stream_bidirectional_codec,
          stream_bidirectional_mode: Telnyx::Models::stream_bidirectional_mode,
          stream_bidirectional_target_legs: Telnyx::Models::stream_bidirectional_target_legs,
          stream_codec: Telnyx::Models::stream_codec,
          stream_track: Telnyx::Models::Calls::ActionAnswerParams::stream_track,
          stream_url: String,
          transcription: bool,
          transcription_config: Telnyx::Calls::TranscriptionStartRequest,
          webhook_retries_policies: ::Hash[Symbol, Telnyx::Calls::ActionAnswerParams::WebhookRetriesPolicy],
          webhook_url: String,
          webhook_url_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method,
          webhook_urls: ::Hash[Symbol, String],
          webhook_urls_method: Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method,
          request_options: Telnyx::RequestOptions
        }

        type conversation_relay_config =
          {
            url: String,
            custom_parameters: ::Hash[Symbol, top],
            dtmf_detection: bool,
            greeting: String,
            interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible,
            interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting,
            interruption_settings: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings,
            language: String,
            languages: ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language],
            provider: String,
            structured_provider: ::Hash[Symbol, top],
            transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine,
            transcription_engine_config: ::Hash[Symbol, top],
            tts_provider: String,
            voice: String,
            voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings
          }

        class ConversationRelayConfig < Telnyx::Internal::Type::BaseModel
          attr_accessor url: String

          attr_reader custom_parameters: ::Hash[Symbol, top]?

          def custom_parameters=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader dtmf_detection: bool?

          def dtmf_detection=: (bool) -> bool

          attr_reader greeting: String?

          def greeting=: (String) -> String

          attr_reader interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible?

          def interruptible=: (
            Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible
          ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible

          attr_reader interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting?

          def interruptible_greeting=: (
            Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting
          ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting

          attr_reader interruption_settings: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings?

          def interruption_settings=: (
            Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings
          ) -> Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings

          attr_reader language: String?

          def language=: (String) -> String

          attr_reader languages: ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language]?

          def languages=: (
            ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language]
          ) -> ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language]

          attr_reader provider: String?

          def provider=: (String) -> String

          attr_reader structured_provider: ::Hash[Symbol, top]?

          def structured_provider=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine?

          def transcription_engine=: (
            Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine
          ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine

          attr_reader transcription_engine_config: ::Hash[Symbol, top]?

          def transcription_engine_config=: (
            ::Hash[Symbol, top]
          ) -> ::Hash[Symbol, top]

          attr_reader tts_provider: String?

          def tts_provider=: (String) -> String

          attr_reader voice: String?

          def voice=: (String) -> String

          attr_reader voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings?

          def voice_settings=: (
            Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings
          ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings

          def initialize: (
            url: String,
            ?custom_parameters: ::Hash[Symbol, top],
            ?dtmf_detection: bool,
            ?greeting: String,
            ?interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible,
            ?interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting,
            ?interruption_settings: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings,
            ?language: String,
            ?languages: ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language],
            ?provider: String,
            ?structured_provider: ::Hash[Symbol, top],
            ?transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine,
            ?transcription_engine_config: ::Hash[Symbol, top],
            ?tts_provider: String,
            ?voice: String,
            ?voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings
          ) -> void

          def to_hash: -> {
            url: String,
            custom_parameters: ::Hash[Symbol, top],
            dtmf_detection: bool,
            greeting: String,
            interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible,
            interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting,
            interruption_settings: Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings,
            language: String,
            languages: ::Array[Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language],
            provider: String,
            structured_provider: ::Hash[Symbol, top],
            transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine,
            transcription_engine_config: ::Hash[Symbol, top],
            tts_provider: String,
            voice: String,
            voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings
          }

          type interruptible = :none | :any | :speech | :dtmf

          module Interruptible
            extend Telnyx::Internal::Type::Enum

            NONE: :none
            ANY: :any
            SPEECH: :speech
            DTMF: :dtmf

            def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible]
          end

          type interruptible_greeting = :none | :any | :speech | :dtmf

          module InterruptibleGreeting
            extend Telnyx::Internal::Type::Enum

            NONE: :none
            ANY: :any
            SPEECH: :speech
            DTMF: :dtmf

            def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::interruptible_greeting]
          end

          type interruption_settings =
            {
              enable: bool,
              interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible,
              interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting,
              welcome_greeting_interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible
            }

          class InterruptionSettings < Telnyx::Internal::Type::BaseModel
            attr_reader enable: bool?

            def enable=: (bool) -> bool

            attr_reader interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible?

            def interruptible=: (
              Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible
            ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible

            attr_reader interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting?

            def interruptible_greeting=: (
              Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting
            ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting

            attr_reader welcome_greeting_interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible?

            def welcome_greeting_interruptible=: (
              Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible
            ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible

            def initialize: (
              ?enable: bool,
              ?interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible,
              ?interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting,
              ?welcome_greeting_interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible
            ) -> void

            def to_hash: -> {
              enable: bool,
              interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible,
              interruptible_greeting: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting,
              welcome_greeting_interruptible: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible
            }

            type interruptible = :none | :any | :speech | :dtmf

            module Interruptible
              extend Telnyx::Internal::Type::Enum

              NONE: :none
              ANY: :any
              SPEECH: :speech
              DTMF: :dtmf

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible]
            end

            type interruptible_greeting = :none | :any | :speech | :dtmf

            module InterruptibleGreeting
              extend Telnyx::Internal::Type::Enum

              NONE: :none
              ANY: :any
              SPEECH: :speech
              DTMF: :dtmf

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::interruptible_greeting]
            end

            type welcome_greeting_interruptible = :none | :any | :speech | :dtmf

            module WelcomeGreetingInterruptible
              extend Telnyx::Internal::Type::Enum

              NONE: :none
              ANY: :any
              SPEECH: :speech
              DTMF: :dtmf

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::InterruptionSettings::welcome_greeting_interruptible]
            end
          end

          type language =
            {
              language: String,
              speech_model: String,
              transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine,
              transcription_engine_config: ::Hash[Symbol, top],
              transcription_provider: String,
              tts_provider: String,
              voice: String,
              voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings
            }

          class Language < Telnyx::Internal::Type::BaseModel
            attr_accessor language: String

            attr_reader speech_model: String?

            def speech_model=: (String) -> String

            attr_reader transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine?

            def transcription_engine=: (
              Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine
            ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine

            attr_reader transcription_engine_config: ::Hash[Symbol, top]?

            def transcription_engine_config=: (
              ::Hash[Symbol, top]
            ) -> ::Hash[Symbol, top]

            attr_reader transcription_provider: String?

            def transcription_provider=: (String) -> String

            attr_reader tts_provider: String?

            def tts_provider=: (String) -> String

            attr_reader voice: String?

            def voice=: (String) -> String

            attr_reader voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings?

            def voice_settings=: (
              Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings
            ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings

            def initialize: (
              language: String,
              ?speech_model: String,
              ?transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine,
              ?transcription_engine_config: ::Hash[Symbol, top],
              ?transcription_provider: String,
              ?tts_provider: String,
              ?voice: String,
              ?voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings
            ) -> void

            def to_hash: -> {
              language: String,
              speech_model: String,
              transcription_engine: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine,
              transcription_engine_config: ::Hash[Symbol, top],
              transcription_provider: String,
              tts_provider: String,
              voice: String,
              voice_settings: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings
            }

            type transcription_engine =
              :Google
              | :Telnyx
              | :Deepgram
              | :Azure
              | :xAI
              | :AssemblyAI
              | :Speechmatics
              | :Soniox
              | :A
              | :B

            module TranscriptionEngine
              extend Telnyx::Internal::Type::Enum

              GOOGLE: :Google
              TELNYX: :Telnyx
              DEEPGRAM: :Deepgram
              AZURE: :Azure
              X_AI: :xAI
              ASSEMBLY_AI: :AssemblyAI
              SPEECHMATICS: :Speechmatics
              SONIOX: :Soniox
              A: :A
              B: :B

              def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::transcription_engine]
            end

            type voice_settings =
              Telnyx::Calls::ElevenLabsVoiceSettings
              | Telnyx::Calls::TelnyxVoiceSettings
              | Telnyx::Calls::AwsVoiceSettings
              | Telnyx::MinimaxVoiceSettings
              | Telnyx::AzureVoiceSettings
              | Telnyx::RimeVoiceSettings
              | Telnyx::ResembleVoiceSettings
              | Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld
              | Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Xai

            module VoiceSettings
              extend Telnyx::Internal::Type::Union

              type inworld =
                {
                  type: :inworld,
                  delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode
                }

              class Inworld < Telnyx::Internal::Type::BaseModel
                attr_accessor type: :inworld

                attr_reader delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode?

                def delivery_mode=: (
                  Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode
                ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode

                def initialize: (
                  ?delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode,
                  ?type: :inworld
                ) -> void

                def to_hash: -> {
                  type: :inworld,
                  delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode
                }

                type delivery_mode = :STABLE | :BALANCED | :CREATIVE

                module DeliveryMode
                  extend Telnyx::Internal::Type::Enum

                  STABLE: :STABLE
                  BALANCED: :BALANCED
                  CREATIVE: :CREATIVE

                  def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::VoiceSettings::Inworld::delivery_mode]
                end
              end

              type xai = { type: :xai, language: String }

              class Xai < Telnyx::Internal::Type::BaseModel
                attr_accessor type: :xai

                attr_reader language: String?

                def language=: (String) -> String

                def initialize: (?language: String, ?type: :xai) -> void

                def to_hash: -> { type: :xai, language: String }
              end

              def self?.variants: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::Language::voice_settings]
            end
          end

          type transcription_engine =
            :Google
            | :Telnyx
            | :Deepgram
            | :Azure
            | :xAI
            | :AssemblyAI
            | :Speechmatics
            | :Soniox
            | :A
            | :B

          module TranscriptionEngine
            extend Telnyx::Internal::Type::Enum

            GOOGLE: :Google
            TELNYX: :Telnyx
            DEEPGRAM: :Deepgram
            AZURE: :Azure
            X_AI: :xAI
            ASSEMBLY_AI: :AssemblyAI
            SPEECHMATICS: :Speechmatics
            SONIOX: :Soniox
            A: :A
            B: :B

            def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::transcription_engine]
          end

          type voice_settings =
            Telnyx::Calls::ElevenLabsVoiceSettings
            | Telnyx::Calls::TelnyxVoiceSettings
            | Telnyx::Calls::AwsVoiceSettings
            | Telnyx::MinimaxVoiceSettings
            | Telnyx::AzureVoiceSettings
            | Telnyx::RimeVoiceSettings
            | Telnyx::ResembleVoiceSettings
            | Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld
            | Telnyx::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Xai

          module VoiceSettings
            extend Telnyx::Internal::Type::Union

            type inworld =
              {
                type: :inworld,
                delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode
              }

            class Inworld < Telnyx::Internal::Type::BaseModel
              attr_accessor type: :inworld

              attr_reader delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode?

              def delivery_mode=: (
                Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode
              ) -> Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode

              def initialize: (
                ?delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode,
                ?type: :inworld
              ) -> void

              def to_hash: -> {
                type: :inworld,
                delivery_mode: Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode
              }

              type delivery_mode = :STABLE | :BALANCED | :CREATIVE

              module DeliveryMode
                extend Telnyx::Internal::Type::Enum

                STABLE: :STABLE
                BALANCED: :BALANCED
                CREATIVE: :CREATIVE

                def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::VoiceSettings::Inworld::delivery_mode]
              end
            end

            type xai = { type: :xai, language: String }

            class Xai < Telnyx::Internal::Type::BaseModel
              attr_accessor type: :xai

              attr_reader language: String?

              def language=: (String) -> String

              def initialize: (?language: String, ?type: :xai) -> void

              def to_hash: -> { type: :xai, language: String }
            end

            def self?.variants: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::ConversationRelayConfig::voice_settings]
          end
        end

        type deepfake_detection =
          { enabled: bool, rtp_timeout: Integer, timeout: Integer }

        class DeepfakeDetection < Telnyx::Internal::Type::BaseModel
          attr_accessor enabled: bool

          attr_reader rtp_timeout: Integer?

          def rtp_timeout=: (Integer) -> Integer

          attr_reader timeout: Integer?

          def timeout=: (Integer) -> Integer

          def initialize: (
            enabled: bool,
            ?rtp_timeout: Integer,
            ?timeout: Integer
          ) -> void

          def to_hash: -> {
            enabled: bool,
            rtp_timeout: Integer,
            timeout: Integer
          }
        end

        type preferred_codecs = :"G722,PCMU,PCMA,G729,OPUS,VP8,H264"

        module PreferredCodecs
          extend Telnyx::Internal::Type::Enum

          G722_PCMU_PCMA_G729_OPUS_VP8_H264: :"G722,PCMU,PCMA,G729,OPUS,VP8,H264"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::preferred_codecs]
        end

        type record = :"record-from-answer"

        module Record
          extend Telnyx::Internal::Type::Enum

          RECORD_FROM_ANSWER: :"record-from-answer"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record]
        end

        type record_channels = :single | :dual

        module RecordChannels
          extend Telnyx::Internal::Type::Enum

          SINGLE: :single
          DUAL: :dual

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_channels]
        end

        type record_format = :wav | :mp3

        module RecordFormat
          extend Telnyx::Internal::Type::Enum

          WAV: :wav
          MP3: :mp3

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_format]
        end

        type record_track = :both | :inbound | :outbound

        module RecordTrack
          extend Telnyx::Internal::Type::Enum

          BOTH: :both
          INBOUND: :inbound
          OUTBOUND: :outbound

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_track]
        end

        type record_trim = :"trim-silence"

        module RecordTrim
          extend Telnyx::Internal::Type::Enum

          TRIM_SILENCE: :"trim-silence"

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::record_trim]
        end

        type stream_track = :inbound_track | :outbound_track | :both_tracks

        module StreamTrack
          extend Telnyx::Internal::Type::Enum

          INBOUND_TRACK: :inbound_track
          OUTBOUND_TRACK: :outbound_track
          BOTH_TRACKS: :both_tracks

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::stream_track]
        end

        type webhook_retries_policy = { retries_ms: ::Array[Integer] }

        class WebhookRetriesPolicy < Telnyx::Internal::Type::BaseModel
          attr_reader retries_ms: ::Array[Integer]?

          def retries_ms=: (::Array[Integer]) -> ::Array[Integer]

          def initialize: (?retries_ms: ::Array[Integer]) -> void

          def to_hash: -> { retries_ms: ::Array[Integer] }
        end

        type webhook_url_method = :POST | :GET

        module WebhookURLMethod
          extend Telnyx::Internal::Type::Enum

          POST: :POST
          GET: :GET

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::webhook_url_method]
        end

        type webhook_urls_method = :POST | :GET

        module WebhookURLsMethod
          extend Telnyx::Internal::Type::Enum

          POST: :POST
          GET: :GET

          def self?.values: -> ::Array[Telnyx::Models::Calls::ActionAnswerParams::webhook_urls_method]
        end
      end
    end
  end
end
