module Telnyx
  module Models
    module Calls
      type deepgram_nova2_config =
        {
          transcription_engine: Telnyx::Models::Calls::DeepgramNova2Config::transcription_engine,
          transcription_model: Telnyx::Models::Calls::DeepgramNova2Config::transcription_model,
          keywords_boosting: ::Hash[Symbol, Float],
          language: Telnyx::Models::Calls::DeepgramNova2Config::language
        }

      class DeepgramNova2Config < Telnyx::Internal::Type::BaseModel
        attr_accessor transcription_engine: Telnyx::Models::Calls::DeepgramNova2Config::transcription_engine

        attr_accessor transcription_model: Telnyx::Models::Calls::DeepgramNova2Config::transcription_model

        attr_reader keywords_boosting: ::Hash[Symbol, Float]?

        def keywords_boosting=: (::Hash[Symbol, Float]) -> ::Hash[Symbol, Float]

        attr_reader language: Telnyx::Models::Calls::DeepgramNova2Config::language?

        def language=: (
          Telnyx::Models::Calls::DeepgramNova2Config::language
        ) -> Telnyx::Models::Calls::DeepgramNova2Config::language

        def initialize: (
          transcription_engine: Telnyx::Models::Calls::DeepgramNova2Config::transcription_engine,
          transcription_model: Telnyx::Models::Calls::DeepgramNova2Config::transcription_model,
          ?keywords_boosting: ::Hash[Symbol, Float],
          ?language: Telnyx::Models::Calls::DeepgramNova2Config::language
        ) -> void

        def to_hash: -> {
          transcription_engine: Telnyx::Models::Calls::DeepgramNova2Config::transcription_engine,
          transcription_model: Telnyx::Models::Calls::DeepgramNova2Config::transcription_model,
          keywords_boosting: ::Hash[Symbol, Float],
          language: Telnyx::Models::Calls::DeepgramNova2Config::language
        }

        type transcription_engine = :Deepgram

        module TranscriptionEngine
          extend Telnyx::Internal::Type::Enum

          DEEPGRAM: :Deepgram

          def self?.values: -> ::Array[Telnyx::Models::Calls::DeepgramNova2Config::transcription_engine]
        end

        type transcription_model = :"deepgram/nova-2"

        module TranscriptionModel
          extend Telnyx::Internal::Type::Enum

          DEEPGRAM_NOVA_2: :"deepgram/nova-2"

          def self?.values: -> ::Array[Telnyx::Models::Calls::DeepgramNova2Config::transcription_model]
        end

        type language =
          :bg
          | :ca
          | :"zh-CN"
          | :"zh-Hans"
          | :"zh-TW"
          | :"zh-Hant"
          | :"zh-HK"
          | :cs
          | :"da-DK"
          | :"nl-BE"
          | :"en-US"
          | :"en-AU"
          | :"en-GB"
          | :"en-NZ"
          | :"en-IN"
          | :et
          | :fi
          | :fr
          | :"fr-CA"
          | :"de-CH"
          | :el
          | :hi
          | :hu
          | :id
          | :it
          | :ja
          | :"ko-KR"
          | :lv
          | :lt
          | :ms
          | :no
          | :pl
          | :"pt-BR"
          | :"pt-PT"
          | :ro
          | :ru
          | :sk
          | :"es-419"
          | :"sv-SE"
          | :"th-TH"
          | :tr
          | :uk
          | :vi
          | :auto_detect

        module Language
          extend Telnyx::Internal::Type::Enum

          BG: :bg
          CA: :ca
          ZH_CN: :"zh-CN"
          ZH_HANS: :"zh-Hans"
          ZH_TW: :"zh-TW"
          ZH_HANT: :"zh-Hant"
          ZH_HK: :"zh-HK"
          CS: :cs
          DA_DK: :"da-DK"
          NL_BE: :"nl-BE"
          EN_US: :"en-US"
          EN_AU: :"en-AU"
          EN_GB: :"en-GB"
          EN_NZ: :"en-NZ"
          EN_IN: :"en-IN"
          ET: :et
          FI: :fi
          FR: :fr
          FR_CA: :"fr-CA"
          DE_CH: :"de-CH"
          EL: :el
          HI: :hi
          HU: :hu
          ID: :id
          IT: :it
          JA: :ja
          KO_KR: :"ko-KR"
          LV: :lv
          LT: :lt
          MS: :ms
          NO: :no
          PL: :pl
          PT_BR: :"pt-BR"
          PT_PT: :"pt-PT"
          RO: :ro
          RU: :ru
          SK: :sk
          ES_419: :"es-419"
          SV_SE: :"sv-SE"
          TH_TH: :"th-TH"
          TR: :tr
          UK: :uk
          VI: :vi
          AUTO_DETECT: :auto_detect

          def self?.values: -> ::Array[Telnyx::Models::Calls::DeepgramNova2Config::language]
        end
      end
    end
  end
end
