module Telnyx
  module Models
    module Calls
      type pay_prompt_value =
        String | ::Array[Telnyx::Calls::PayPromptValue::PayPromptList]

      module PayPromptValue
        extend Telnyx::Internal::Type::Union

        type pay_prompt_list =
          {
            text: String,
            attempt: String,
            card_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type,
            error_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type
          }

        class PayPromptList < Telnyx::Internal::Type::BaseModel
          attr_accessor text: String

          attr_reader attempt: String?

          def attempt=: (String) -> String

          attr_reader card_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type?

          def card_type=: (
            Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type
          ) -> Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type

          attr_reader error_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type?

          def error_type=: (
            Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type
          ) -> Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type

          def initialize: (
            text: String,
            ?attempt: String,
            ?card_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type,
            ?error_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type
          ) -> void

          def to_hash: -> {
            text: String,
            attempt: String,
            card_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type,
            error_type: Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type
          }

          type card_type =
            :visa | :mastercard | :amex | :discover | :"diners-club" | :jcb

          module CardType
            extend Telnyx::Internal::Type::Enum

            VISA: :visa
            MASTERCARD: :mastercard
            AMEX: :amex
            DISCOVER: :discover
            DINERS_CLUB: :"diners-club"
            JCB: :jcb

            def self?.values: -> ::Array[Telnyx::Models::Calls::PayPromptValue::PayPromptList::card_type]
          end

          type error_type =
            :timeout
            | :"invalid-card-number"
            | :"invalid-date"
            | :"invalid-security-code"
            | :"invalid-postal-code"
            | :"invalid-bank-routing-number"
            | :"invalid-bank-account-number"
            | :"input-matching-failed"

          module ErrorType
            extend Telnyx::Internal::Type::Enum

            TIMEOUT: :timeout
            INVALID_CARD_NUMBER: :"invalid-card-number"
            INVALID_DATE: :"invalid-date"
            INVALID_SECURITY_CODE: :"invalid-security-code"
            INVALID_POSTAL_CODE: :"invalid-postal-code"
            INVALID_BANK_ROUTING_NUMBER: :"invalid-bank-routing-number"
            INVALID_BANK_ACCOUNT_NUMBER: :"invalid-bank-account-number"
            INPUT_MATCHING_FAILED: :"input-matching-failed"

            def self?.values: -> ::Array[Telnyx::Models::Calls::PayPromptValue::PayPromptList::error_type]
          end
        end

        def self?.variants: -> ::Array[Telnyx::Models::Calls::pay_prompt_value]

        PayPromptListArray: Telnyx::Internal::Type::Converter
      end
    end
  end
end
