module Telnyx
  module Models
    module EmailDomains
      type email_webhook_event =
        :"email.scheduled"
        | :"email.sandbox"
        | :"email.queued"
        | :"email.sending"
        | :"email.sent"
        | :"email.delivered"
        | :"email.deferred"
        | :"email.bounced"
        | :"email.failed"
        | :"email.complained"
        | :"email.opened"
        | :"email.clicked"
        | :"email.unsubscribed"
        | :"email.received"
        | :"email_domain.created"
        | :"email_domain.verified"
        | :"email_domain.degraded"
        | :"email_domain.suspended"
        | :"email_domain.deleted"

      module EmailWebhookEvent
        extend Telnyx::Internal::Type::Enum

        EMAIL_SCHEDULED: :"email.scheduled"
        EMAIL_SANDBOX: :"email.sandbox"
        EMAIL_QUEUED: :"email.queued"
        EMAIL_SENDING: :"email.sending"
        EMAIL_SENT: :"email.sent"
        EMAIL_DELIVERED: :"email.delivered"
        EMAIL_DEFERRED: :"email.deferred"
        EMAIL_BOUNCED: :"email.bounced"
        EMAIL_FAILED: :"email.failed"
        EMAIL_COMPLAINED: :"email.complained"
        EMAIL_OPENED: :"email.opened"
        EMAIL_CLICKED: :"email.clicked"
        EMAIL_UNSUBSCRIBED: :"email.unsubscribed"
        EMAIL_RECEIVED: :"email.received"
        EMAIL_DOMAIN_CREATED: :"email_domain.created"
        EMAIL_DOMAIN_VERIFIED: :"email_domain.verified"
        EMAIL_DOMAIN_DEGRADED: :"email_domain.degraded"
        EMAIL_DOMAIN_SUSPENDED: :"email_domain.suspended"
        EMAIL_DOMAIN_DELETED: :"email_domain.deleted"

        def self?.values: -> ::Array[Telnyx::Models::EmailDomains::email_webhook_event]
      end
    end
  end
end
