module Telnyx
  module Models
    module MessagingProfiles
      type action_regenerate_secret_response =
        { data: Telnyx::MessagingMessagingProfile }

      class ActionRegenerateSecretResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::MessagingMessagingProfile?

        def data=: (
          Telnyx::MessagingMessagingProfile
        ) -> Telnyx::MessagingMessagingProfile

        def initialize: (?data: Telnyx::MessagingMessagingProfile) -> void

        def to_hash: -> { data: Telnyx::MessagingMessagingProfile }
      end
    end
  end
end
