module Telnyx
  module Models
    module MessagingProfiles
      type autoresp_config_list_response =
        {
          data: ::Array[Telnyx::MessagingProfiles::AutoRespConfig],
          meta: Telnyx::MessagingPaginationMeta
        }

      class AutorespConfigListResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: ::Array[Telnyx::MessagingProfiles::AutoRespConfig]

        attr_accessor meta: Telnyx::MessagingPaginationMeta

        def initialize: (
          data: ::Array[Telnyx::MessagingProfiles::AutoRespConfig],
          meta: Telnyx::MessagingPaginationMeta
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::MessagingProfiles::AutoRespConfig],
          meta: Telnyx::MessagingPaginationMeta
        }
      end
    end
  end
end
