module Telnyx
  module Resources
    class Messaging10dlc
      class Brand
        attr_reader external_vetting: Telnyx::Resources::Messaging10dlc::Brand::ExternalVetting

        def create: (
          country: String,
          display_name: String,
          email: String,
          entity_type: Telnyx::Models::Messaging10dlc::entity_type,
          vertical: Telnyx::Models::Messaging10dlc::vertical,
          ?business_contact_email: String,
          ?city: String,
          ?company_name: String,
          ?ein: String,
          ?first_name: String,
          ?ip_address: String,
          ?is_reseller: bool,
          ?last_name: String,
          ?mobile_phone: String,
          ?mock: bool,
          ?phone: String,
          ?postal_code: String,
          ?state: String,
          ?stock_exchange: Telnyx::Models::Messaging10dlc::stock_exchange,
          ?stock_symbol: String,
          ?street: String,
          ?webhook_failover_url: String,
          ?webhook_url: String,
          ?website: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Messaging10dlc::TelnyxBrand

        def retrieve: (
          String brand_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Messaging10dlc::BrandRetrieveResponse

        def update: (
          String brand_id,
          country: String,
          display_name: String,
          email: String,
          entity_type: Telnyx::Models::Messaging10dlc::entity_type,
          vertical: Telnyx::Models::Messaging10dlc::vertical,
          ?alt_business_id: String,
          ?alt_business_id_type: Telnyx::Models::Messaging10dlc::alt_business_id_type,
          ?business_contact_email: String,
          ?city: String,
          ?company_name: String,
          ?ein: String,
          ?first_name: String,
          ?identity_status: Telnyx::Models::Messaging10dlc::brand_identity_status,
          ?ip_address: String,
          ?is_reseller: bool,
          ?last_name: String,
          ?phone: String,
          ?postal_code: String,
          ?state: String,
          ?stock_exchange: Telnyx::Models::Messaging10dlc::stock_exchange,
          ?stock_symbol: String,
          ?street: String,
          ?webhook_failover_url: String,
          ?webhook_url: String,
          ?website: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Messaging10dlc::TelnyxBrand

        def list: (
          ?brand_id: String,
          ?country: String,
          ?display_name: String,
          ?entity_type: String,
          ?page: Integer,
          ?records_per_page: Integer,
          ?sort: Telnyx::Models::Messaging10dlc::BrandListParams::sort,
          ?state: String,
          ?tcr_brand_id: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::PerPagePaginationV2[Telnyx::Models::Messaging10dlc::BrandListResponse]

        def delete: (
          String brand_id,
          ?request_options: Telnyx::request_opts
        ) -> nil

        def get_feedback: (
          String brand_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Messaging10dlc::BrandGetFeedbackResponse

        def resend_2fa_email: (
          String brand_id,
          ?request_options: Telnyx::request_opts
        ) -> nil

        def retrieve_sms_otp_status: (
          String reference_id,
          ?brand_id: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Messaging10dlc::BrandRetrieveSMSOtpStatusResponse

        def revet: (
          String brand_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Messaging10dlc::TelnyxBrand

        def trigger_sms_otp: (
          String brand_id,
          pin_sms: String,
          success_sms: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Messaging10dlc::BrandTriggerSMSOtpResponse

        def verify_sms_otp: (
          String brand_id,
          otp_pin: String,
          ?request_options: Telnyx::request_opts
        ) -> nil

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
