module Telnyx
  module Models
    module Messaging10dlc
      module Campaign
        type osr_get_attributes_response = ::Hash[Symbol, top]

        OsrGetAttributesResponse: Telnyx::Internal::Type::Converter
      end
    end
  end
end
