module Telnyx
  module Resources
    class NumberReservations
      class Actions
        def extend_: (
          String number_reservation_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::NumberReservations::ActionExtendResponse

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
