module Telnyx
  module Models
    module AI
      module Assistants
        type canary_deploy_response =
          {
            assistant_id: String,
            created_at: Time,
            rules: ::Array[Telnyx::AI::Assistants::RuleOutput],
            updated_at: Time
          }

        class CanaryDeployResponse < Telnyx::Internal::Type::BaseModel
          attr_accessor assistant_id: String

          attr_accessor created_at: Time

          attr_accessor rules: ::Array[Telnyx::AI::Assistants::RuleOutput]

          attr_accessor updated_at: Time

          def initialize: (
            assistant_id: String,
            created_at: Time,
            rules: ::Array[Telnyx::AI::Assistants::RuleOutput],
            updated_at: Time
          ) -> void

          def to_hash: -> {
            assistant_id: String,
            created_at: Time,
            rules: ::Array[Telnyx::AI::Assistants::RuleOutput],
            updated_at: Time
          }
        end
      end
    end
  end
end
