module Telnyx
  module Models
    module AI
      module Assistants
        type canary_deploy =
          { rules: ::Array[Telnyx::AI::Assistants::RuleInput] }

        class CanaryDeploy < Telnyx::Internal::Type::BaseModel
          attr_reader rules: ::Array[Telnyx::AI::Assistants::RuleInput]?

          def rules=: (
            ::Array[Telnyx::AI::Assistants::RuleInput]
          ) -> ::Array[Telnyx::AI::Assistants::RuleInput]

          def initialize: (
            ?rules: ::Array[Telnyx::AI::Assistants::RuleInput]
          ) -> void

          def to_hash: -> { rules: ::Array[Telnyx::AI::Assistants::RuleInput] }
        end
      end
    end
  end
end
