module Telnyx
  module Models
    module AI
      module Assistants
        type clause =
          {
            attribute: String,
            operator: Telnyx::Models::AI::Assistants::Clause::operator,
            values: ::Array[String]
          }

        class Clause < Telnyx::Internal::Type::BaseModel
          attr_accessor attribute: String

          attr_accessor operator: Telnyx::Models::AI::Assistants::Clause::operator

          attr_accessor values: ::Array[String]

          def initialize: (
            attribute: String,
            operator: Telnyx::Models::AI::Assistants::Clause::operator,
            values: ::Array[String]
          ) -> void

          def to_hash: -> {
            attribute: String,
            operator: Telnyx::Models::AI::Assistants::Clause::operator,
            values: ::Array[String]
          }

          type operator = :in | :not_in | :starts_with

          module Operator
            extend Telnyx::Internal::Type::Enum

            IN: :in
            NOT_IN: :not_in
            STARTS_WITH: :starts_with

            def self?.values: -> ::Array[Telnyx::Models::AI::Assistants::Clause::operator]
          end
        end
      end
    end
  end
end
