module Telnyx
  module Models
    module AI
      module Assistants
        type event_status = :pending | :in_progress | :completed | :failed

        module EventStatus
          extend Telnyx::Internal::Type::Enum

          PENDING: :pending
          IN_PROGRESS: :in_progress
          COMPLETED: :completed
          FAILED: :failed

          def self?.values: -> ::Array[Telnyx::Models::AI::Assistants::event_status]
        end
      end
    end
  end
end
