module Telnyx
  module Models
    module Storage
      module Buckets
        type ssl_certificate_retrieve_response =
          { data: Telnyx::Storage::Buckets::BucketsSslCertificate }

        class SslCertificateRetrieveResponse < Telnyx::Internal::Type::BaseModel
          attr_reader data: Telnyx::Storage::Buckets::BucketsSslCertificate?

          def data=: (
            Telnyx::Storage::Buckets::BucketsSslCertificate
          ) -> Telnyx::Storage::Buckets::BucketsSslCertificate

          def initialize: (
            ?data: Telnyx::Storage::Buckets::BucketsSslCertificate
          ) -> void

          def to_hash: -> {
            data: Telnyx::Storage::Buckets::BucketsSslCertificate
          }
        end
      end
    end
  end
end
