module Telnyx
  module Models
    module AI
      type assistant_a2_a_agent =
        {
          name: String,
          url: String,
          async: bool,
          headers: ::Array[Telnyx::AI::AssistantA2AAgent::Header],
          messages: ::Array[Telnyx::Models::AI::AssistantA2AAgent::message],
          poll_interval_ms: Integer,
          timeout_ms: Integer
        }

      class AssistantA2AAgent < Telnyx::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor url: String

        attr_reader async: bool?

        def async=: (bool) -> bool

        attr_reader headers: ::Array[Telnyx::AI::AssistantA2AAgent::Header]?

        def headers=: (
          ::Array[Telnyx::AI::AssistantA2AAgent::Header]
        ) -> ::Array[Telnyx::AI::AssistantA2AAgent::Header]

        attr_reader messages: ::Array[Telnyx::Models::AI::AssistantA2AAgent::message]?

        def messages=: (
          ::Array[Telnyx::Models::AI::AssistantA2AAgent::message]
        ) -> ::Array[Telnyx::Models::AI::AssistantA2AAgent::message]

        attr_reader poll_interval_ms: Integer?

        def poll_interval_ms=: (Integer) -> Integer

        attr_reader timeout_ms: Integer?

        def timeout_ms=: (Integer) -> Integer

        def initialize: (
          name: String,
          url: String,
          ?async: bool,
          ?headers: ::Array[Telnyx::AI::AssistantA2AAgent::Header],
          ?messages: ::Array[Telnyx::Models::AI::AssistantA2AAgent::message],
          ?poll_interval_ms: Integer,
          ?timeout_ms: Integer
        ) -> void

        def to_hash: -> {
          name: String,
          url: String,
          async: bool,
          headers: ::Array[Telnyx::AI::AssistantA2AAgent::Header],
          messages: ::Array[Telnyx::Models::AI::AssistantA2AAgent::message],
          poll_interval_ms: Integer,
          timeout_ms: Integer
        }

        type header = { name: String, value: String }

        class Header < Telnyx::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor value: String

          def initialize: (name: String, value: String) -> void

          def to_hash: -> { name: String, value: String }
        end

        type message =
          Telnyx::AI::AssistantA2AAgent::Message::A2AAgentRequestStartMessage
          | Telnyx::AI::AssistantA2AAgent::Message::A2AAgentRequestResponseDelayedMessage

        module Message
          extend Telnyx::Internal::Type::Union

          type a2_a_agent_request_start_message =
            { content: String, type: :request_start, timing_ms: Integer }

          class A2AAgentRequestStartMessage < Telnyx::Internal::Type::BaseModel
            attr_accessor content: String

            attr_accessor type: :request_start

            attr_reader timing_ms: Integer?

            def timing_ms=: (Integer) -> Integer

            def initialize: (
              content: String,
              ?timing_ms: Integer,
              ?type: :request_start
            ) -> void

            def to_hash: -> {
              content: String,
              type: :request_start,
              timing_ms: Integer
            }
          end

          type a2_a_agent_request_response_delayed_message =
            {
              content: String,
              timing_ms: Integer,
              type: :request_response_delayed
            }

          class A2AAgentRequestResponseDelayedMessage < Telnyx::Internal::Type::BaseModel
            attr_accessor content: String

            attr_accessor timing_ms: Integer

            attr_accessor type: :request_response_delayed

            def initialize: (
              content: String,
              timing_ms: Integer,
              ?type: :request_response_delayed
            ) -> void

            def to_hash: -> {
              content: String,
              timing_ms: Integer,
              type: :request_response_delayed
            }
          end

          def self?.variants: -> ::Array[Telnyx::Models::AI::AssistantA2AAgent::message]
        end
      end
    end
  end
end
