module Telnyx
  module Models
    module AI
      type assistant_clone_response =
        {
          id: String,
          created_at: Time,
          instructions: String,
          model: String,
          name: String,
          description: String,
          dynamic_variables: ::Hash[Symbol, top],
          dynamic_variables_webhook_url: String,
          enabled_features: ::Array[Telnyx::Models::AI::enabled_features],
          greeting: String,
          import_metadata: Telnyx::AI::ImportMetadata,
          insight_settings: Telnyx::AI::InsightSettings,
          llm_api_key_ref: String,
          messaging_settings: Telnyx::AI::MessagingSettings,
          privacy_settings: Telnyx::AI::PrivacySettings,
          telephony_settings: Telnyx::AI::TelephonySettings,
          tools: ::Array[Telnyx::Models::AI::assistant_tool],
          transcription: Telnyx::AI::TranscriptionSettings,
          voice_settings: Telnyx::AI::VoiceSettings
        }

      class AssistantCloneResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor instructions: String

        attr_accessor model: String

        attr_accessor name: String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader dynamic_variables: ::Hash[Symbol, top]?

        def dynamic_variables=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader dynamic_variables_webhook_url: String?

        def dynamic_variables_webhook_url=: (String) -> String

        attr_reader enabled_features: ::Array[Telnyx::Models::AI::enabled_features]?

        def enabled_features=: (
          ::Array[Telnyx::Models::AI::enabled_features]
        ) -> ::Array[Telnyx::Models::AI::enabled_features]

        attr_reader greeting: String?

        def greeting=: (String) -> String

        attr_reader import_metadata: Telnyx::AI::ImportMetadata?

        def import_metadata=: (
          Telnyx::AI::ImportMetadata
        ) -> Telnyx::AI::ImportMetadata

        attr_reader insight_settings: Telnyx::AI::InsightSettings?

        def insight_settings=: (
          Telnyx::AI::InsightSettings
        ) -> Telnyx::AI::InsightSettings

        attr_reader llm_api_key_ref: String?

        def llm_api_key_ref=: (String) -> String

        attr_reader messaging_settings: Telnyx::AI::MessagingSettings?

        def messaging_settings=: (
          Telnyx::AI::MessagingSettings
        ) -> Telnyx::AI::MessagingSettings

        attr_reader privacy_settings: Telnyx::AI::PrivacySettings?

        def privacy_settings=: (
          Telnyx::AI::PrivacySettings
        ) -> Telnyx::AI::PrivacySettings

        attr_reader telephony_settings: Telnyx::AI::TelephonySettings?

        def telephony_settings=: (
          Telnyx::AI::TelephonySettings
        ) -> Telnyx::AI::TelephonySettings

        attr_reader tools: ::Array[Telnyx::Models::AI::assistant_tool]?

        def tools=: (
          ::Array[Telnyx::Models::AI::assistant_tool]
        ) -> ::Array[Telnyx::Models::AI::assistant_tool]

        attr_reader transcription: Telnyx::AI::TranscriptionSettings?

        def transcription=: (
          Telnyx::AI::TranscriptionSettings
        ) -> Telnyx::AI::TranscriptionSettings

        attr_reader voice_settings: Telnyx::AI::VoiceSettings?

        def voice_settings=: (
          Telnyx::AI::VoiceSettings
        ) -> Telnyx::AI::VoiceSettings

        def initialize: (
          id: String,
          created_at: Time,
          instructions: String,
          model: String,
          name: String,
          ?description: String,
          ?dynamic_variables: ::Hash[Symbol, top],
          ?dynamic_variables_webhook_url: String,
          ?enabled_features: ::Array[Telnyx::Models::AI::enabled_features],
          ?greeting: String,
          ?import_metadata: Telnyx::AI::ImportMetadata,
          ?insight_settings: Telnyx::AI::InsightSettings,
          ?llm_api_key_ref: String,
          ?messaging_settings: Telnyx::AI::MessagingSettings,
          ?privacy_settings: Telnyx::AI::PrivacySettings,
          ?telephony_settings: Telnyx::AI::TelephonySettings,
          ?tools: ::Array[Telnyx::Models::AI::assistant_tool],
          ?transcription: Telnyx::AI::TranscriptionSettings,
          ?voice_settings: Telnyx::AI::VoiceSettings
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          instructions: String,
          model: String,
          name: String,
          description: String,
          dynamic_variables: ::Hash[Symbol, top],
          dynamic_variables_webhook_url: String,
          enabled_features: ::Array[Telnyx::Models::AI::enabled_features],
          greeting: String,
          import_metadata: Telnyx::AI::ImportMetadata,
          insight_settings: Telnyx::AI::InsightSettings,
          llm_api_key_ref: String,
          messaging_settings: Telnyx::AI::MessagingSettings,
          privacy_settings: Telnyx::AI::PrivacySettings,
          telephony_settings: Telnyx::AI::TelephonySettings,
          tools: ::Array[Telnyx::Models::AI::assistant_tool],
          transcription: Telnyx::AI::TranscriptionSettings,
          voice_settings: Telnyx::AI::VoiceSettings
        }
      end
    end
  end
end
