module Telnyx
  module Models
    module AI
      type audio_transcribe_response =
        {
          text: String,
          duration: Float,
          segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
        }

      class AudioTranscribeResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor text: String

        attr_reader duration: Float?

        def duration=: (Float) -> Float

        attr_reader segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]?

        def segments=: (
          ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]
        ) -> ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]

        attr_reader words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]?

        def words=: (
          ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
        ) -> ::Array[Telnyx::AI::AudioTranscriptionResponseWord]

        def initialize: (
          text: String,
          ?duration: Float,
          ?segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          ?words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
        ) -> void

        def to_hash: -> {
          text: String,
          duration: Float,
          segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
        }

        type segment =
          {
            id: Float,
            end_: Float,
            start: Float,
            text: String,
            speakers: ::Array[Integer],
            words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
          }

        class Segment < Telnyx::Internal::Type::BaseModel
          attr_accessor id: Float

          attr_accessor end_: Float

          attr_accessor start: Float

          attr_accessor text: String

          attr_reader speakers: ::Array[Integer]?

          def speakers=: (::Array[Integer]) -> ::Array[Integer]

          attr_reader words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]?

          def words=: (
            ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
          ) -> ::Array[Telnyx::AI::AudioTranscriptionResponseWord]

          def initialize: (
            id: Float,
            end_: Float,
            start: Float,
            text: String,
            ?speakers: ::Array[Integer],
            ?words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
          ) -> void

          def to_hash: -> {
            id: Float,
            end_: Float,
            start: Float,
            text: String,
            speakers: ::Array[Integer],
            words: ::Array[Telnyx::AI::AudioTranscriptionResponseWord]
          }
        end
      end
    end
  end
end
