module Telnyx
  module Models
    module AI
      type audio_transcribe_response =
        {
          text: String,
          duration: Float,
          segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          words: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]
        }

      class AudioTranscribeResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor text: String

        attr_reader duration: Float?

        def duration=: (Float) -> Float

        attr_reader segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]?

        def segments=: (
          ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]
        ) -> ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment]

        attr_reader words: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]?

        def words=: (
          ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]
        ) -> ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]

        def initialize: (
          text: String,
          ?duration: Float,
          ?segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          ?words: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]
        ) -> void

        def to_hash: -> {
          text: String,
          duration: Float,
          segments: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Segment],
          words: ::Array[Telnyx::Models::AI::AudioTranscribeResponse::Word]
        }

        type segment = { id: Float, end_: Float, start: Float, text: String }

        class Segment < Telnyx::Internal::Type::BaseModel
          attr_accessor id: Float

          attr_accessor end_: Float

          attr_accessor start: Float

          attr_accessor text: String

          def initialize: (
            id: Float,
            end_: Float,
            start: Float,
            text: String
          ) -> void

          def to_hash: -> { id: Float, end_: Float, start: Float, text: String }
        end

        type word =
          {
            end_: Float,
            start: Float,
            word: String,
            confidence: Float,
            speaker: Integer
          }

        class Word < Telnyx::Internal::Type::BaseModel
          attr_accessor end_: Float

          attr_accessor start: Float

          attr_accessor word: String

          attr_reader confidence: Float?

          def confidence=: (Float) -> Float

          attr_reader speaker: Integer?

          def speaker=: (Integer) -> Integer

          def initialize: (
            end_: Float,
            start: Float,
            word: String,
            ?confidence: Float,
            ?speaker: Integer
          ) -> void

          def to_hash: -> {
            end_: Float,
            start: Float,
            word: String,
            confidence: Float,
            speaker: Integer
          }
        end
      end
    end
  end
end
