module Telnyx
  module Models
    module AI
      type collection_retrieve_documents_response =
        {
          id: String,
          chunk_index: Integer,
          chunk_total: Integer,
          ingested_at: Time,
          metadata: ::Hash[Symbol, top],
          organization_id: String,
          record_created_at: Time,
          record_id: String,
          record_type: String,
          region: String,
          score: Float,
          text: String,
          user_id: String
        }

      class CollectionRetrieveDocumentsResponse < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader chunk_index: Integer?

        def chunk_index=: (Integer) -> Integer

        attr_reader chunk_total: Integer?

        def chunk_total=: (Integer) -> Integer

        attr_reader ingested_at: Time?

        def ingested_at=: (Time) -> Time

        attr_reader metadata: ::Hash[Symbol, top]?

        def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader organization_id: String?

        def organization_id=: (String) -> String

        attr_reader record_created_at: Time?

        def record_created_at=: (Time) -> Time

        attr_reader record_id: String?

        def record_id=: (String) -> String

        attr_reader record_type: String?

        def record_type=: (String) -> String

        attr_reader region: String?

        def region=: (String) -> String

        attr_reader score: Float?

        def score=: (Float) -> Float

        attr_reader text: String?

        def text=: (String) -> String

        attr_reader user_id: String?

        def user_id=: (String) -> String

        def initialize: (
          ?id: String,
          ?chunk_index: Integer,
          ?chunk_total: Integer,
          ?ingested_at: Time,
          ?metadata: ::Hash[Symbol, top],
          ?organization_id: String,
          ?record_created_at: Time,
          ?record_id: String,
          ?record_type: String,
          ?region: String,
          ?score: Float,
          ?text: String,
          ?user_id: String
        ) -> void

        def to_hash: -> {
          id: String,
          chunk_index: Integer,
          chunk_total: Integer,
          ingested_at: Time,
          metadata: ::Hash[Symbol, top],
          organization_id: String,
          record_created_at: Time,
          record_id: String,
          record_type: String,
          region: String,
          score: Float,
          text: String,
          user_id: String
        }
      end
    end
  end
end
