module Telnyx
  module Models
    module AI
      type fallback_config_req =
        {
          external_llm: Telnyx::AI::ExternalLlmReq,
          llm_api_key_ref: String,
          model: String
        }

      class FallbackConfigReq < Telnyx::Internal::Type::BaseModel
        attr_reader external_llm: Telnyx::AI::ExternalLlmReq?

        def external_llm=: (
          Telnyx::AI::ExternalLlmReq
        ) -> Telnyx::AI::ExternalLlmReq

        attr_reader llm_api_key_ref: String?

        def llm_api_key_ref=: (String) -> String

        attr_reader model: String?

        def model=: (String) -> String

        def initialize: (
          ?external_llm: Telnyx::AI::ExternalLlmReq,
          ?llm_api_key_ref: String,
          ?model: String
        ) -> void

        def to_hash: -> {
          external_llm: Telnyx::AI::ExternalLlmReq,
          llm_api_key_ref: String,
          model: String
        }
      end
    end
  end
end
