module Telnyx
  module Models
    module AI
      type inference_embedding_interruption_settings =
        { enable: bool, start_speaking_plan: Telnyx::AI::StartSpeakingPlan }

      class InferenceEmbeddingInterruptionSettings < Telnyx::Internal::Type::BaseModel
        attr_reader enable: bool?

        def enable=: (bool) -> bool

        attr_reader start_speaking_plan: Telnyx::AI::StartSpeakingPlan?

        def start_speaking_plan=: (
          Telnyx::AI::StartSpeakingPlan
        ) -> Telnyx::AI::StartSpeakingPlan

        def initialize: (
          ?enable: bool,
          ?start_speaking_plan: Telnyx::AI::StartSpeakingPlan
        ) -> void

        def to_hash: -> {
          enable: bool,
          start_speaking_plan: Telnyx::AI::StartSpeakingPlan
        }
      end
    end
  end
end
