module Telnyx
  module Models
    module AI
      type voice_settings =
        {
          voice: String,
          api_key_ref: String,
          background_audio: Telnyx::Models::AI::VoiceSettings::background_audio,
          voice_speed: Float
        }

      class VoiceSettings < Telnyx::Internal::Type::BaseModel
        attr_accessor voice: String

        attr_reader api_key_ref: String?

        def api_key_ref=: (String) -> String

        attr_reader background_audio: Telnyx::Models::AI::VoiceSettings::background_audio?

        def background_audio=: (
          Telnyx::Models::AI::VoiceSettings::background_audio
        ) -> Telnyx::Models::AI::VoiceSettings::background_audio

        attr_reader voice_speed: Float?

        def voice_speed=: (Float) -> Float

        def initialize: (
          voice: String,
          ?api_key_ref: String,
          ?background_audio: Telnyx::Models::AI::VoiceSettings::background_audio,
          ?voice_speed: Float
        ) -> void

        def to_hash: -> {
          voice: String,
          api_key_ref: String,
          background_audio: Telnyx::Models::AI::VoiceSettings::background_audio,
          voice_speed: Float
        }

        type background_audio =
          Telnyx::AI::VoiceSettings::BackgroundAudio::PredefinedMedia
          | Telnyx::AI::VoiceSettings::BackgroundAudio::MediaURL
          | Telnyx::AI::VoiceSettings::BackgroundAudio::MediaName

        module BackgroundAudio
          extend Telnyx::Internal::Type::Union

          type predefined_media =
            {
              type: :predefined_media,
              value: Telnyx::Models::AI::VoiceSettings::BackgroundAudio::PredefinedMedia::value
            }

          class PredefinedMedia < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :predefined_media

            attr_accessor value: Telnyx::Models::AI::VoiceSettings::BackgroundAudio::PredefinedMedia::value

            def initialize: (
              value: Telnyx::Models::AI::VoiceSettings::BackgroundAudio::PredefinedMedia::value,
              ?type: :predefined_media
            ) -> void

            def to_hash: -> {
              type: :predefined_media,
              value: Telnyx::Models::AI::VoiceSettings::BackgroundAudio::PredefinedMedia::value
            }

            type value = :silence | :office

            module Value
              extend Telnyx::Internal::Type::Enum

              SILENCE: :silence
              OFFICE: :office

              def self?.values: -> ::Array[Telnyx::Models::AI::VoiceSettings::BackgroundAudio::PredefinedMedia::value]
            end
          end

          type media_url = { type: :media_url, value: String }

          class MediaURL < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :media_url

            attr_accessor value: String

            def initialize: (value: String, ?type: :media_url) -> void

            def to_hash: -> { type: :media_url, value: String }
          end

          type media_name = { type: :media_name, value: String }

          class MediaName < Telnyx::Internal::Type::BaseModel
            attr_accessor type: :media_name

            attr_accessor value: String

            def initialize: (value: String, ?type: :media_name) -> void

            def to_hash: -> { type: :media_name, value: String }
          end

          def self?.variants: -> ::Array[Telnyx::Models::AI::VoiceSettings::background_audio]
        end
      end
    end
  end
end
