module Telnyx
  module Models
    module AI
      type webhook_tool =
        {
          type: Telnyx::Models::AI::WebhookTool::type_,
          webhook: Telnyx::AI::WebhookTool::Webhook
        }

      class WebhookTool < Telnyx::Internal::Type::BaseModel
        attr_accessor type: Telnyx::Models::AI::WebhookTool::type_

        attr_accessor webhook: Telnyx::AI::WebhookTool::Webhook

        def initialize: (
          type: Telnyx::Models::AI::WebhookTool::type_,
          webhook: Telnyx::AI::WebhookTool::Webhook
        ) -> void

        def to_hash: -> {
          type: Telnyx::Models::AI::WebhookTool::type_,
          webhook: Telnyx::AI::WebhookTool::Webhook
        }

        type type_ = :webhook

        module Type
          extend Telnyx::Internal::Type::Enum

          WEBHOOK: :webhook

          def self?.values: -> ::Array[Telnyx::Models::AI::WebhookTool::type_]
        end

        type webhook =
          {
            description: String,
            name: String,
            url: String,
            body_parameters: Telnyx::AI::WebhookTool::Webhook::BodyParameters,
            headers: ::Array[Telnyx::AI::WebhookTool::Webhook::Header],
            method_: Telnyx::Models::AI::WebhookTool::Webhook::method_,
            path_parameters: Telnyx::AI::WebhookTool::Webhook::PathParameters,
            query_parameters: Telnyx::AI::WebhookTool::Webhook::QueryParameters
          }

        class Webhook < Telnyx::Internal::Type::BaseModel
          attr_accessor description: String

          attr_accessor name: String

          attr_accessor url: String

          attr_reader body_parameters: Telnyx::AI::WebhookTool::Webhook::BodyParameters?

          def body_parameters=: (
            Telnyx::AI::WebhookTool::Webhook::BodyParameters
          ) -> Telnyx::AI::WebhookTool::Webhook::BodyParameters

          attr_reader headers: ::Array[Telnyx::AI::WebhookTool::Webhook::Header]?

          def headers=: (
            ::Array[Telnyx::AI::WebhookTool::Webhook::Header]
          ) -> ::Array[Telnyx::AI::WebhookTool::Webhook::Header]

          attr_reader method_: Telnyx::Models::AI::WebhookTool::Webhook::method_?

          def method_=: (
            Telnyx::Models::AI::WebhookTool::Webhook::method_
          ) -> Telnyx::Models::AI::WebhookTool::Webhook::method_

          attr_reader path_parameters: Telnyx::AI::WebhookTool::Webhook::PathParameters?

          def path_parameters=: (
            Telnyx::AI::WebhookTool::Webhook::PathParameters
          ) -> Telnyx::AI::WebhookTool::Webhook::PathParameters

          attr_reader query_parameters: Telnyx::AI::WebhookTool::Webhook::QueryParameters?

          def query_parameters=: (
            Telnyx::AI::WebhookTool::Webhook::QueryParameters
          ) -> Telnyx::AI::WebhookTool::Webhook::QueryParameters

          def initialize: (
            description: String,
            name: String,
            url: String,
            ?body_parameters: Telnyx::AI::WebhookTool::Webhook::BodyParameters,
            ?headers: ::Array[Telnyx::AI::WebhookTool::Webhook::Header],
            ?method_: Telnyx::Models::AI::WebhookTool::Webhook::method_,
            ?path_parameters: Telnyx::AI::WebhookTool::Webhook::PathParameters,
            ?query_parameters: Telnyx::AI::WebhookTool::Webhook::QueryParameters
          ) -> void

          def to_hash: -> {
            description: String,
            name: String,
            url: String,
            body_parameters: Telnyx::AI::WebhookTool::Webhook::BodyParameters,
            headers: ::Array[Telnyx::AI::WebhookTool::Webhook::Header],
            method_: Telnyx::Models::AI::WebhookTool::Webhook::method_,
            path_parameters: Telnyx::AI::WebhookTool::Webhook::PathParameters,
            query_parameters: Telnyx::AI::WebhookTool::Webhook::QueryParameters
          }

          type body_parameters =
            {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_
            }

          class BodyParameters < Telnyx::Internal::Type::BaseModel
            attr_reader properties: top?

            def properties=: (top) -> top

            attr_reader required: ::Array[String]?

            def required=: (::Array[String]) -> ::Array[String]

            attr_reader type: Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_?

            def type=: (
              Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_
            ) -> Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_

            def initialize: (
              ?properties: top,
              ?required: ::Array[String],
              ?type: Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_
            ) -> void

            def to_hash: -> {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_
            }

            type type_ = :object

            module Type
              extend Telnyx::Internal::Type::Enum

              OBJECT: :object

              def self?.values: -> ::Array[Telnyx::Models::AI::WebhookTool::Webhook::BodyParameters::type_]
            end
          end

          type header = { name: String, value: String }

          class Header < Telnyx::Internal::Type::BaseModel
            attr_reader name: String?

            def name=: (String) -> String

            attr_reader value: String?

            def value=: (String) -> String

            def initialize: (?name: String, ?value: String) -> void

            def to_hash: -> { name: String, value: String }
          end

          type method_ = :GET | :POST | :PUT | :DELETE | :PATCH

          module Method
            extend Telnyx::Internal::Type::Enum

            GET: :GET
            POST: :POST
            PUT: :PUT
            DELETE: :DELETE
            PATCH: :PATCH

            def self?.values: -> ::Array[Telnyx::Models::AI::WebhookTool::Webhook::method_]
          end

          type path_parameters =
            {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_
            }

          class PathParameters < Telnyx::Internal::Type::BaseModel
            attr_reader properties: top?

            def properties=: (top) -> top

            attr_reader required: ::Array[String]?

            def required=: (::Array[String]) -> ::Array[String]

            attr_reader type: Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_?

            def type=: (
              Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_
            ) -> Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_

            def initialize: (
              ?properties: top,
              ?required: ::Array[String],
              ?type: Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_
            ) -> void

            def to_hash: -> {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_
            }

            type type_ = :object

            module Type
              extend Telnyx::Internal::Type::Enum

              OBJECT: :object

              def self?.values: -> ::Array[Telnyx::Models::AI::WebhookTool::Webhook::PathParameters::type_]
            end
          end

          type query_parameters =
            {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_
            }

          class QueryParameters < Telnyx::Internal::Type::BaseModel
            attr_reader properties: top?

            def properties=: (top) -> top

            attr_reader required: ::Array[String]?

            def required=: (::Array[String]) -> ::Array[String]

            attr_reader type: Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_?

            def type=: (
              Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_
            ) -> Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_

            def initialize: (
              ?properties: top,
              ?required: ::Array[String],
              ?type: Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_
            ) -> void

            def to_hash: -> {
              properties: top,
              required: ::Array[String],
              type: Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_
            }

            type type_ = :object

            module Type
              extend Telnyx::Internal::Type::Enum

              OBJECT: :object

              def self?.values: -> ::Array[Telnyx::Models::AI::WebhookTool::Webhook::QueryParameters::type_]
            end
          end
        end
      end
    end
  end
end
