module Telnyx
  module Resources
    class PortingOrders
      class Comments
        def create: (
          String id,
          ?body: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::PortingOrders::CommentCreateResponse

        def list: (
          String id,
          ?page_number: Integer,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::PortingOrders::CommentListResponse]

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
