module Telnyx
  module Models
    type access_ip_range_list_response =
      {
        data: ::Array[Telnyx::AccessIPRange],
        meta: Telnyx::PaginationMetaCloudflareIPListSync
      }

    class AccessIPRangeListResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::AccessIPRange]

      attr_accessor meta: Telnyx::PaginationMetaCloudflareIPListSync

      def initialize: (
        data: ::Array[Telnyx::AccessIPRange],
        meta: Telnyx::PaginationMetaCloudflareIPListSync
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::AccessIPRange],
        meta: Telnyx::PaginationMetaCloudflareIPListSync
      }
    end
  end
end
