module Telnyx
  module Models
    type advanced_order_retrieve_response =
      {
        id: String,
        area_code: String,
        comments: String,
        country_code: String,
        customer_reference: String,
        features: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature],
        orders: ::Array[String],
        phone_number_type: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type],
        quantity: Integer,
        requirement_group_id: String,
        status: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]
      }

    class AdvancedOrderRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader area_code: String?

      def area_code=: (String) -> String

      attr_reader comments: String?

      def comments=: (String) -> String

      attr_reader country_code: String?

      def country_code=: (String) -> String

      attr_reader customer_reference: String?

      def customer_reference=: (String) -> String

      attr_reader features: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature]?

      def features=: (
        ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature]
      ) -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature]

      attr_reader orders: ::Array[String]?

      def orders=: (::Array[String]) -> ::Array[String]

      attr_reader phone_number_type: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type]?

      def phone_number_type=: (
        ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type]
      ) -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type]

      attr_reader quantity: Integer?

      def quantity=: (Integer) -> Integer

      attr_reader requirement_group_id: String?

      def requirement_group_id=: (String) -> String

      attr_reader status: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]?

      def status=: (
        ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]
      ) -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]

      def initialize: (
        ?id: String,
        ?area_code: String,
        ?comments: String,
        ?country_code: String,
        ?customer_reference: String,
        ?features: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature],
        ?orders: ::Array[String],
        ?phone_number_type: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type],
        ?quantity: Integer,
        ?requirement_group_id: String,
        ?status: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]
      ) -> void

      def to_hash: -> {
        id: String,
        area_code: String,
        comments: String,
        country_code: String,
        customer_reference: String,
        features: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature],
        orders: ::Array[String],
        phone_number_type: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type],
        quantity: Integer,
        requirement_group_id: String,
        status: ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]
      }

      type feature = :sms | :mms | :voice | :fax | :emergency

      module Feature
        extend Telnyx::Internal::Type::Enum

        SMS: :sms
        MMS: :mms
        VOICE: :voice
        FAX: :fax
        EMERGENCY: :emergency

        def self?.values: -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::feature]
      end

      type phone_number_type =
        :local | :mobile | :toll_free | :shared_cost | :national | :landline

      module PhoneNumberType
        extend Telnyx::Internal::Type::Enum

        LOCAL: :local
        MOBILE: :mobile
        TOLL_FREE: :toll_free
        SHARED_COST: :shared_cost
        NATIONAL: :national
        LANDLINE: :landline

        def self?.values: -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::phone_number_type]
      end

      type status = :pending | :processing | :ordered

      module Status
        extend Telnyx::Internal::Type::Enum

        PENDING: :pending
        PROCESSING: :processing
        ORDERED: :ordered

        def self?.values: -> ::Array[Telnyx::Models::AdvancedOrderRetrieveResponse::status]
      end
    end
  end
end
