module Telnyx
  module Models
    type ai_retrieve_models_response =
      { data: ::Array[Telnyx::ModelMetadata], object: String }

    class AIRetrieveModelsResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::ModelMetadata]

      attr_reader object: String?

      def object=: (String) -> String

      def initialize: (
        data: ::Array[Telnyx::ModelMetadata],
        ?object: String
      ) -> void

      def to_hash: -> { data: ::Array[Telnyx::ModelMetadata], object: String }
    end
  end
end
