module Telnyx
  module Models
    type authentication_provider_update_response =
      { data: Telnyx::AuthenticationProvider }

    class AuthenticationProviderUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::AuthenticationProvider?

      def data=: (
        Telnyx::AuthenticationProvider
      ) -> Telnyx::AuthenticationProvider

      def initialize: (?data: Telnyx::AuthenticationProvider) -> void

      def to_hash: -> { data: Telnyx::AuthenticationProvider }
    end
  end
end
