module Telnyx
  module Models
    type available_phone_number_block_list_response =
      {
        data: ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data],
        meta: Telnyx::AvailablePhoneNumbersMetadata
      }

    class AvailablePhoneNumberBlockListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data]?

      def data=: (
        ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data]
      ) -> ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data]

      attr_reader meta: Telnyx::AvailablePhoneNumbersMetadata?

      def meta=: (
        Telnyx::AvailablePhoneNumbersMetadata
      ) -> Telnyx::AvailablePhoneNumbersMetadata

      def initialize: (
        ?data: ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data],
        ?meta: Telnyx::AvailablePhoneNumbersMetadata
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data],
        meta: Telnyx::AvailablePhoneNumbersMetadata
      }

      type data =
        {
          cost_information: Telnyx::CostInformation,
          features: ::Array[Telnyx::Feature],
          phone_number: String,
          range: Integer,
          record_type: Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type,
          region_information: ::Array[Telnyx::RegionInformation]
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader cost_information: Telnyx::CostInformation?

        def cost_information=: (
          Telnyx::CostInformation
        ) -> Telnyx::CostInformation

        attr_reader features: ::Array[Telnyx::Feature]?

        def features=: (::Array[Telnyx::Feature]) -> ::Array[Telnyx::Feature]

        attr_reader phone_number: String?

        def phone_number=: (String) -> String

        attr_reader range: Integer?

        def range=: (Integer) -> Integer

        attr_reader record_type: Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type?

        def record_type=: (
          Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type
        ) -> Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type

        attr_reader region_information: ::Array[Telnyx::RegionInformation]?

        def region_information=: (
          ::Array[Telnyx::RegionInformation]
        ) -> ::Array[Telnyx::RegionInformation]

        def initialize: (
          ?cost_information: Telnyx::CostInformation,
          ?features: ::Array[Telnyx::Feature],
          ?phone_number: String,
          ?range: Integer,
          ?record_type: Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type,
          ?region_information: ::Array[Telnyx::RegionInformation]
        ) -> void

        def to_hash: -> {
          cost_information: Telnyx::CostInformation,
          features: ::Array[Telnyx::Feature],
          phone_number: String,
          range: Integer,
          record_type: Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type,
          region_information: ::Array[Telnyx::RegionInformation]
        }

        type record_type = :available_phone_number_block

        module RecordType
          extend Telnyx::Internal::Type::Enum

          AVAILABLE_PHONE_NUMBER_BLOCK: :available_phone_number_block

          def self?.values: -> ::Array[Telnyx::Models::AvailablePhoneNumberBlockListResponse::Data::record_type]
        end
      end
    end
  end
end
