module Telnyx
  module Models
    type billing_group_list_response =
      { data: ::Array[Telnyx::BillingGroup], meta: Telnyx::PaginationMeta }

    class BillingGroupListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::BillingGroup]?

      def data=: (
        ::Array[Telnyx::BillingGroup]
      ) -> ::Array[Telnyx::BillingGroup]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::BillingGroup],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::BillingGroup],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
