module Telnyx
  module Models
    type call_recording_error_webhook_event =
      { data: Telnyx::CallRecordingError }

    class CallRecordingErrorWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallRecordingError?

      def data=: (Telnyx::CallRecordingError) -> Telnyx::CallRecordingError

      def initialize: (?data: Telnyx::CallRecordingError) -> void

      def to_hash: -> { data: Telnyx::CallRecordingError }
    end
  end
end
