module Telnyx
  module Models
    type call_ai_gather_message_history_updated_webhook_event =
      { data: Telnyx::CallAIGatherMessageHistoryUpdated }

    class CallAIGatherMessageHistoryUpdatedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallAIGatherMessageHistoryUpdated?

      def data=: (
        Telnyx::CallAIGatherMessageHistoryUpdated
      ) -> Telnyx::CallAIGatherMessageHistoryUpdated

      def initialize: (?data: Telnyx::CallAIGatherMessageHistoryUpdated) -> void

      def to_hash: -> { data: Telnyx::CallAIGatherMessageHistoryUpdated }
    end
  end
end
