module Telnyx
  module Models
    type call_refer_failed_webhook_event = { data: Telnyx::CallReferFailed }

    class CallReferFailedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallReferFailed?

      def data=: (Telnyx::CallReferFailed) -> Telnyx::CallReferFailed

      def initialize: (?data: Telnyx::CallReferFailed) -> void

      def to_hash: -> { data: Telnyx::CallReferFailed }
    end
  end
end
