module Telnyx
  module Models
    type call_speak_ended_webhook_event =
      { data: Telnyx::CallSpeakEndedWebhookEvent::Data }

    class CallSpeakEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallSpeakEndedWebhookEvent::Data?

      def data=: (
        Telnyx::CallSpeakEndedWebhookEvent::Data
      ) -> Telnyx::CallSpeakEndedWebhookEvent::Data

      def initialize: (?data: Telnyx::CallSpeakEndedWebhookEvent::Data) -> void

      def to_hash: -> { data: Telnyx::CallSpeakEndedWebhookEvent::Data }

      type data =
        {
          id: String,
          event_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type,
          occurred_at: Time,
          payload: Telnyx::CallSpeakEndedWebhookEvent::Data::Payload,
          record_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader event_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type?

        def event_type=: (
          Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type
        ) -> Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type

        attr_reader occurred_at: Time?

        def occurred_at=: (Time) -> Time

        attr_reader payload: Telnyx::CallSpeakEndedWebhookEvent::Data::Payload?

        def payload=: (
          Telnyx::CallSpeakEndedWebhookEvent::Data::Payload
        ) -> Telnyx::CallSpeakEndedWebhookEvent::Data::Payload

        attr_reader record_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type?

        def record_type=: (
          Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type
        ) -> Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type

        def initialize: (
          ?id: String,
          ?event_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type,
          ?occurred_at: Time,
          ?payload: Telnyx::CallSpeakEndedWebhookEvent::Data::Payload,
          ?record_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type
        ) -> void

        def to_hash: -> {
          id: String,
          event_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type,
          occurred_at: Time,
          payload: Telnyx::CallSpeakEndedWebhookEvent::Data::Payload,
          record_type: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type
        }

        type event_type = :"call.speak.ended"

        module EventType
          extend Telnyx::Internal::Type::Enum

          CALL_SPEAK_ENDED: :"call.speak.ended"

          def self?.values: -> ::Array[Telnyx::Models::CallSpeakEndedWebhookEvent::Data::event_type]
        end

        type payload =
          {
            call_control_id: String,
            call_leg_id: String,
            call_session_id: String,
            client_state: String,
            connection_id: String,
            status: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status
          }

        class Payload < Telnyx::Internal::Type::BaseModel
          attr_reader call_control_id: String?

          def call_control_id=: (String) -> String

          attr_reader call_leg_id: String?

          def call_leg_id=: (String) -> String

          attr_reader call_session_id: String?

          def call_session_id=: (String) -> String

          attr_reader client_state: String?

          def client_state=: (String) -> String

          attr_reader connection_id: String?

          def connection_id=: (String) -> String

          attr_reader status: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status?

          def status=: (
            Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status
          ) -> Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status

          def initialize: (
            ?call_control_id: String,
            ?call_leg_id: String,
            ?call_session_id: String,
            ?client_state: String,
            ?connection_id: String,
            ?status: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status
          ) -> void

          def to_hash: -> {
            call_control_id: String,
            call_leg_id: String,
            call_session_id: String,
            client_state: String,
            connection_id: String,
            status: Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status
          }

          type status = :completed | :call_hangup | :cancelled_amd

          module Status
            extend Telnyx::Internal::Type::Enum

            COMPLETED: :completed
            CALL_HANGUP: :call_hangup
            CANCELLED_AMD: :cancelled_amd

            def self?.values: -> ::Array[Telnyx::Models::CallSpeakEndedWebhookEvent::Data::Payload::status]
          end
        end

        type record_type = :event

        module RecordType
          extend Telnyx::Internal::Type::Enum

          EVENT: :event

          def self?.values: -> ::Array[Telnyx::Models::CallSpeakEndedWebhookEvent::Data::record_type]
        end
      end
    end
  end
end
