module Telnyx
  module Models
    type call_refer_started_webhook_event = { data: Telnyx::CallReferStarted }

    class CallReferStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallReferStarted?

      def data=: (Telnyx::CallReferStarted) -> Telnyx::CallReferStarted

      def initialize: (?data: Telnyx::CallReferStarted) -> void

      def to_hash: -> { data: Telnyx::CallReferStarted }
    end
  end
end
