module Telnyx
  module Models
    type call_reason_list_response =
      { id: String, description: String, reason: String }

    class CallReasonListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader description: String?

      def description=: (String) -> String

      attr_reader reason: String?

      def reason=: (String) -> String

      attr_reader id: String?

      def id=: (String) -> String

      def initialize: (
        ?id: String,
        ?description: String,
        ?reason: String
      ) -> void

      def to_hash: -> { id: String, description: String, reason: String }
    end
  end
end
