module Telnyx
  module Models
    type call_answered_webhook_event = { data: Telnyx::CallAnswered }

    class CallAnsweredWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallAnswered?

      def data=: (Telnyx::CallAnswered) -> Telnyx::CallAnswered

      def initialize: (?data: Telnyx::CallAnswered) -> void

      def to_hash: -> { data: Telnyx::CallAnswered }
    end
  end
end
