module Telnyx
  module Models
    type call_streaming_failed =
      {
        id: String,
        event_type: Telnyx::Models::CallStreamingFailed::event_type,
        occurred_at: Time,
        payload: Telnyx::CallStreamingFailed::Payload,
        record_type: Telnyx::Models::CallStreamingFailed::record_type
      }

    class CallStreamingFailed < Telnyx::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader event_type: Telnyx::Models::CallStreamingFailed::event_type?

      def event_type=: (
        Telnyx::Models::CallStreamingFailed::event_type
      ) -> Telnyx::Models::CallStreamingFailed::event_type

      attr_reader occurred_at: Time?

      def occurred_at=: (Time) -> Time

      attr_reader payload: Telnyx::CallStreamingFailed::Payload?

      def payload=: (
        Telnyx::CallStreamingFailed::Payload
      ) -> Telnyx::CallStreamingFailed::Payload

      attr_reader record_type: Telnyx::Models::CallStreamingFailed::record_type?

      def record_type=: (
        Telnyx::Models::CallStreamingFailed::record_type
      ) -> Telnyx::Models::CallStreamingFailed::record_type

      def initialize: (
        ?id: String,
        ?event_type: Telnyx::Models::CallStreamingFailed::event_type,
        ?occurred_at: Time,
        ?payload: Telnyx::CallStreamingFailed::Payload,
        ?record_type: Telnyx::Models::CallStreamingFailed::record_type
      ) -> void

      def to_hash: -> {
        id: String,
        event_type: Telnyx::Models::CallStreamingFailed::event_type,
        occurred_at: Time,
        payload: Telnyx::CallStreamingFailed::Payload,
        record_type: Telnyx::Models::CallStreamingFailed::record_type
      }

      type event_type = :"streaming.failed"

      module EventType
        extend Telnyx::Internal::Type::Enum

        STREAMING_FAILED: :"streaming.failed"

        def self?.values: -> ::Array[Telnyx::Models::CallStreamingFailed::event_type]
      end

      type payload =
        {
          call_control_id: String,
          call_leg_id: String,
          call_session_id: String,
          client_state: String,
          connection_id: String,
          failure_reason: String,
          stream_id: String,
          stream_params: Telnyx::CallStreamingFailed::Payload::StreamParams,
          stream_type: Telnyx::Models::CallStreamingFailed::Payload::stream_type
        }

      class Payload < Telnyx::Internal::Type::BaseModel
        attr_reader call_control_id: String?

        def call_control_id=: (String) -> String

        attr_reader call_leg_id: String?

        def call_leg_id=: (String) -> String

        attr_reader call_session_id: String?

        def call_session_id=: (String) -> String

        attr_reader client_state: String?

        def client_state=: (String) -> String

        attr_reader connection_id: String?

        def connection_id=: (String) -> String

        attr_reader failure_reason: String?

        def failure_reason=: (String) -> String

        attr_reader stream_id: String?

        def stream_id=: (String) -> String

        attr_reader stream_params: Telnyx::CallStreamingFailed::Payload::StreamParams?

        def stream_params=: (
          Telnyx::CallStreamingFailed::Payload::StreamParams
        ) -> Telnyx::CallStreamingFailed::Payload::StreamParams

        attr_reader stream_type: Telnyx::Models::CallStreamingFailed::Payload::stream_type?

        def stream_type=: (
          Telnyx::Models::CallStreamingFailed::Payload::stream_type
        ) -> Telnyx::Models::CallStreamingFailed::Payload::stream_type

        def initialize: (
          ?call_control_id: String,
          ?call_leg_id: String,
          ?call_session_id: String,
          ?client_state: String,
          ?connection_id: String,
          ?failure_reason: String,
          ?stream_id: String,
          ?stream_params: Telnyx::CallStreamingFailed::Payload::StreamParams,
          ?stream_type: Telnyx::Models::CallStreamingFailed::Payload::stream_type
        ) -> void

        def to_hash: -> {
          call_control_id: String,
          call_leg_id: String,
          call_session_id: String,
          client_state: String,
          connection_id: String,
          failure_reason: String,
          stream_id: String,
          stream_params: Telnyx::CallStreamingFailed::Payload::StreamParams,
          stream_type: Telnyx::Models::CallStreamingFailed::Payload::stream_type
        }

        type stream_params =
          {
            stream_url: String,
            track: Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track
          }

        class StreamParams < Telnyx::Internal::Type::BaseModel
          attr_reader stream_url: String?

          def stream_url=: (String) -> String

          attr_reader track: Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track?

          def track=: (
            Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track
          ) -> Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track

          def initialize: (
            ?stream_url: String,
            ?track: Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track
          ) -> void

          def to_hash: -> {
            stream_url: String,
            track: Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track
          }

          type track = :inbound_track | :outbound_track | :both_tracks

          module Track
            extend Telnyx::Internal::Type::Enum

            INBOUND_TRACK: :inbound_track
            OUTBOUND_TRACK: :outbound_track
            BOTH_TRACKS: :both_tracks

            def self?.values: -> ::Array[Telnyx::Models::CallStreamingFailed::Payload::StreamParams::track]
          end
        end

        type stream_type = :websocket | :dialogflow

        module StreamType
          extend Telnyx::Internal::Type::Enum

          WEBSOCKET: :websocket
          DIALOGFLOW: :dialogflow

          def self?.values: -> ::Array[Telnyx::Models::CallStreamingFailed::Payload::stream_type]
        end
      end

      type record_type = :event

      module RecordType
        extend Telnyx::Internal::Type::Enum

        EVENT: :event

        def self?.values: -> ::Array[Telnyx::Models::CallStreamingFailed::record_type]
      end
    end
  end
end
