module Telnyx
  module Models
    type call_playback_ended_webhook_event = { data: Telnyx::CallPlaybackEnded }

    class CallPlaybackEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallPlaybackEnded?

      def data=: (Telnyx::CallPlaybackEnded) -> Telnyx::CallPlaybackEnded

      def initialize: (?data: Telnyx::CallPlaybackEnded) -> void

      def to_hash: -> { data: Telnyx::CallPlaybackEnded }
    end
  end
end
