module Telnyx
  module Models
    type call_machine_greeting_ended_webhook_event =
      { data: Telnyx::CallMachineGreetingEnded }

    class CallMachineGreetingEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallMachineGreetingEnded?

      def data=: (
        Telnyx::CallMachineGreetingEnded
      ) -> Telnyx::CallMachineGreetingEnded

      def initialize: (?data: Telnyx::CallMachineGreetingEnded) -> void

      def to_hash: -> { data: Telnyx::CallMachineGreetingEnded }
    end
  end
end
