module Telnyx
  module Models
    type call_speak_started_webhook_event = { data: Telnyx::CallSpeakStarted }

    class CallSpeakStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallSpeakStarted?

      def data=: (Telnyx::CallSpeakStarted) -> Telnyx::CallSpeakStarted

      def initialize: (?data: Telnyx::CallSpeakStarted) -> void

      def to_hash: -> { data: Telnyx::CallSpeakStarted }
    end
  end
end
