module Telnyx
  module Models
    type call_siprec_stopped_webhook_event = { data: Telnyx::CallSiprecStopped }

    class CallSiprecStoppedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallSiprecStopped?

      def data=: (Telnyx::CallSiprecStopped) -> Telnyx::CallSiprecStopped

      def initialize: (?data: Telnyx::CallSiprecStopped) -> void

      def to_hash: -> { data: Telnyx::CallSiprecStopped }
    end
  end
end
