module Telnyx
  module Models
    type call_enqueued_webhook_event = { data: Telnyx::CallEnqueued }

    class CallEnqueuedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallEnqueued?

      def data=: (Telnyx::CallEnqueued) -> Telnyx::CallEnqueued

      def initialize: (?data: Telnyx::CallEnqueued) -> void

      def to_hash: -> { data: Telnyx::CallEnqueued }
    end
  end
end
