module Telnyx
  module Models
    type campaign_status_update =
      {
        brand_id: String,
        campaign_id: String,
        create_date: String,
        csp_id: String,
        description: String,
        is_t_mobile_registered: bool,
        status: Telnyx::Models::CampaignStatusUpdate::status,
        type: Telnyx::Models::CampaignStatusUpdate::type_
      }

    class CampaignStatusUpdate < Telnyx::Internal::Type::BaseModel
      attr_reader brand_id: String?

      def brand_id=: (String) -> String

      attr_reader campaign_id: String?

      def campaign_id=: (String) -> String

      attr_reader create_date: String?

      def create_date=: (String) -> String

      attr_reader csp_id: String?

      def csp_id=: (String) -> String

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader is_t_mobile_registered: bool?

      def is_t_mobile_registered=: (bool) -> bool

      attr_reader status: Telnyx::Models::CampaignStatusUpdate::status?

      def status=: (
        Telnyx::Models::CampaignStatusUpdate::status
      ) -> Telnyx::Models::CampaignStatusUpdate::status

      attr_reader type: Telnyx::Models::CampaignStatusUpdate::type_?

      def type=: (
        Telnyx::Models::CampaignStatusUpdate::type_
      ) -> Telnyx::Models::CampaignStatusUpdate::type_

      def initialize: (
        ?brand_id: String,
        ?campaign_id: String,
        ?create_date: String,
        ?csp_id: String,
        ?description: String,
        ?is_t_mobile_registered: bool,
        ?status: Telnyx::Models::CampaignStatusUpdate::status,
        ?type: Telnyx::Models::CampaignStatusUpdate::type_
      ) -> void

      def to_hash: -> {
        brand_id: String,
        campaign_id: String,
        create_date: String,
        csp_id: String,
        description: String,
        is_t_mobile_registered: bool,
        status: Telnyx::Models::CampaignStatusUpdate::status,
        type: Telnyx::Models::CampaignStatusUpdate::type_
      }

      type status = :ACCEPTED | :REJECTED | :DORMANT | :success | :failed

      module Status
        extend Telnyx::Internal::Type::Enum

        ACCEPTED: :ACCEPTED
        REJECTED: :REJECTED
        DORMANT: :DORMANT
        SUCCESS: :success
        FAILED: :failed

        def self?.values: -> ::Array[Telnyx::Models::CampaignStatusUpdate::status]
      end

      type type_ =
        :TELNYX_EVENT
        | :REGISTRATION
        | :MNO_REVIEW
        | :TELNYX_REVIEW
        | :NUMBER_POOL_PROVISIONED
        | :NUMBER_POOL_DEPROVISIONED
        | :TCR_EVENT
        | :VERIFIED

      module Type
        extend Telnyx::Internal::Type::Enum

        TELNYX_EVENT: :TELNYX_EVENT
        REGISTRATION: :REGISTRATION
        MNO_REVIEW: :MNO_REVIEW
        TELNYX_REVIEW: :TELNYX_REVIEW
        NUMBER_POOL_PROVISIONED: :NUMBER_POOL_PROVISIONED
        NUMBER_POOL_DEPROVISIONED: :NUMBER_POOL_DEPROVISIONED
        TCR_EVENT: :TCR_EVENT
        VERIFIED: :VERIFIED

        def self?.values: -> ::Array[Telnyx::Models::CampaignStatusUpdate::type_]
      end
    end
  end
end
