module Telnyx
  module Models
    type campaign_builder_create_response = top | Telnyx::TelnyxCampaignCsp

    module CampaignBuilderCreateResponse
      extend Telnyx::Internal::Type::Union

      def self?.variants: -> ::Array[Telnyx::Models::campaign_builder_create_response]
    end
  end
end
