module Telnyx
  module Models
    type comment_create_response =
      { data: Telnyx::Models::CommentCreateResponse::Data }

    class CommentCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::CommentCreateResponse::Data?

      def data=: (
        Telnyx::Models::CommentCreateResponse::Data
      ) -> Telnyx::Models::CommentCreateResponse::Data

      def initialize: (
        ?data: Telnyx::Models::CommentCreateResponse::Data
      ) -> void

      def to_hash: -> { data: Telnyx::Models::CommentCreateResponse::Data }

      type data = {  }

      class Data < Telnyx::Models::Comment
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
