module Telnyx
  module Models
    type comment_mark_as_read_response =
      { data: Telnyx::Models::CommentMarkAsReadResponse::Data }

    class CommentMarkAsReadResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::CommentMarkAsReadResponse::Data?

      def data=: (
        Telnyx::Models::CommentMarkAsReadResponse::Data
      ) -> Telnyx::Models::CommentMarkAsReadResponse::Data

      def initialize: (
        ?data: Telnyx::Models::CommentMarkAsReadResponse::Data
      ) -> void

      def to_hash: -> { data: Telnyx::Models::CommentMarkAsReadResponse::Data }

      type data = {  }

      class Data < Telnyx::Models::Comment
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
