module Telnyx
  module Models
    type conference_participant_speak_ended_webhook_event =
      { data: Telnyx::ConferenceParticipantSpeakEnded }

    class ConferenceParticipantSpeakEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceParticipantSpeakEnded?

      def data=: (
        Telnyx::ConferenceParticipantSpeakEnded
      ) -> Telnyx::ConferenceParticipantSpeakEnded

      def initialize: (?data: Telnyx::ConferenceParticipantSpeakEnded) -> void

      def to_hash: -> { data: Telnyx::ConferenceParticipantSpeakEnded }
    end
  end
end
