module Telnyx
  module Models
    type conference_participant_playback_ended_webhook_event =
      { data: Telnyx::ConferenceParticipantPlaybackEnded }

    class ConferenceParticipantPlaybackEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceParticipantPlaybackEnded?

      def data=: (
        Telnyx::ConferenceParticipantPlaybackEnded
      ) -> Telnyx::ConferenceParticipantPlaybackEnded

      def initialize: (
        ?data: Telnyx::ConferenceParticipantPlaybackEnded
      ) -> void

      def to_hash: -> { data: Telnyx::ConferenceParticipantPlaybackEnded }
    end
  end
end
