module Telnyx
  module Models
    type conference_created_webhook_event = { data: Telnyx::ConferenceCreated }

    class ConferenceCreatedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceCreated?

      def data=: (Telnyx::ConferenceCreated) -> Telnyx::ConferenceCreated

      def initialize: (?data: Telnyx::ConferenceCreated) -> void

      def to_hash: -> { data: Telnyx::ConferenceCreated }
    end
  end
end
