module Telnyx
  module Models
    type conference_ended_webhook_event = { data: Telnyx::ConferenceEnded }

    class ConferenceEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceEnded?

      def data=: (Telnyx::ConferenceEnded) -> Telnyx::ConferenceEnded

      def initialize: (?data: Telnyx::ConferenceEnded) -> void

      def to_hash: -> { data: Telnyx::ConferenceEnded }
    end
  end
end
