module Telnyx
  module Models
    type conference_update_participant_response =
      { data: Telnyx::ConferenceParticipant }

    class ConferenceUpdateParticipantResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceParticipant?

      def data=: (
        Telnyx::ConferenceParticipant
      ) -> Telnyx::ConferenceParticipant

      def initialize: (?data: Telnyx::ConferenceParticipant) -> void

      def to_hash: -> { data: Telnyx::ConferenceParticipant }
    end
  end
end
