module Telnyx
  module Models
    type conference_participant_speak_started_webhook_event =
      { data: Telnyx::ConferenceParticipantSpeakStarted }

    class ConferenceParticipantSpeakStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceParticipantSpeakStarted?

      def data=: (
        Telnyx::ConferenceParticipantSpeakStarted
      ) -> Telnyx::ConferenceParticipantSpeakStarted

      def initialize: (?data: Telnyx::ConferenceParticipantSpeakStarted) -> void

      def to_hash: -> { data: Telnyx::ConferenceParticipantSpeakStarted }
    end
  end
end
