module Telnyx
  module Models
    type conference_recording_saved_webhook_event =
      { data: Telnyx::ConferenceRecordingSavedWebhookEvent::Data }

    class ConferenceRecordingSavedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceRecordingSavedWebhookEvent::Data?

      def data=: (
        Telnyx::ConferenceRecordingSavedWebhookEvent::Data
      ) -> Telnyx::ConferenceRecordingSavedWebhookEvent::Data

      def initialize: (
        ?data: Telnyx::ConferenceRecordingSavedWebhookEvent::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::ConferenceRecordingSavedWebhookEvent::Data
      }

      type data =
        {
          id: String,
          event_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type,
          payload: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload,
          record_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader event_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type?

        def event_type=: (
          Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type
        ) -> Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type

        attr_reader payload: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload?

        def payload=: (
          Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload
        ) -> Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload

        attr_reader record_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type?

        def record_type=: (
          Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type
        ) -> Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type

        def initialize: (
          ?id: String,
          ?event_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type,
          ?payload: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload,
          ?record_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type
        ) -> void

        def to_hash: -> {
          id: String,
          event_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type,
          payload: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload,
          record_type: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type
        }

        type event_type = :"conference.recording.saved"

        module EventType
          extend Telnyx::Internal::Type::Enum

          CONFERENCE_RECORDING_SAVED: :"conference.recording.saved"

          def self?.values: -> ::Array[Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::event_type]
        end

        type payload =
          {
            call_control_id: String,
            call_session_id: String,
            channels: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels,
            client_state: String,
            conference_id: String,
            connection_id: String,
            format_: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_,
            public_recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs,
            recording_ended_at: Time,
            recording_id: String,
            recording_started_at: Time,
            recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs
          }

        class Payload < Telnyx::Internal::Type::BaseModel
          attr_reader call_control_id: String?

          def call_control_id=: (String) -> String

          attr_reader call_session_id: String?

          def call_session_id=: (String) -> String

          attr_reader channels: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels?

          def channels=: (
            Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels
          ) -> Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels

          attr_reader client_state: String?

          def client_state=: (String) -> String

          attr_reader conference_id: String?

          def conference_id=: (String) -> String

          attr_reader connection_id: String?

          def connection_id=: (String) -> String

          attr_reader format_: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_?

          def format_=: (
            Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_
          ) -> Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_

          attr_reader public_recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs?

          def public_recording_urls=: (
            Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs
          ) -> Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs

          attr_reader recording_ended_at: Time?

          def recording_ended_at=: (Time) -> Time

          attr_reader recording_id: String?

          def recording_id=: (String) -> String

          attr_reader recording_started_at: Time?

          def recording_started_at=: (Time) -> Time

          attr_reader recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs?

          def recording_urls=: (
            Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs
          ) -> Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs

          def initialize: (
            ?call_control_id: String,
            ?call_session_id: String,
            ?channels: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels,
            ?client_state: String,
            ?conference_id: String,
            ?connection_id: String,
            ?format_: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_,
            ?public_recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs,
            ?recording_ended_at: Time,
            ?recording_id: String,
            ?recording_started_at: Time,
            ?recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs
          ) -> void

          def to_hash: -> {
            call_control_id: String,
            call_session_id: String,
            channels: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels,
            client_state: String,
            conference_id: String,
            connection_id: String,
            format_: Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_,
            public_recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::PublicRecordingURLs,
            recording_ended_at: Time,
            recording_id: String,
            recording_started_at: Time,
            recording_urls: Telnyx::ConferenceRecordingSavedWebhookEvent::Data::Payload::RecordingURLs
          }

          type channels = :single | :dual

          module Channels
            extend Telnyx::Internal::Type::Enum

            SINGLE: :single
            DUAL: :dual

            def self?.values: -> ::Array[Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::channels]
          end

          type format_ = :wav | :mp3

          module Format
            extend Telnyx::Internal::Type::Enum

            WAV: :wav
            MP3: :mp3

            def self?.values: -> ::Array[Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::Payload::format_]
          end

          type public_recording_urls = { :mp3 => String?, wav: String? }

          class PublicRecordingURLs < Telnyx::Internal::Type::BaseModel
            attr_accessor mp3: String?

            attr_accessor wav: String?

            def initialize: (?mp3: String?, ?wav: String?) -> void

            def to_hash: -> { :mp3 => String?, wav: String? }
          end

          type recording_urls = { :mp3 => String?, wav: String? }

          class RecordingURLs < Telnyx::Internal::Type::BaseModel
            attr_accessor mp3: String?

            attr_accessor wav: String?

            def initialize: (?mp3: String?, ?wav: String?) -> void

            def to_hash: -> { :mp3 => String?, wav: String? }
          end
        end

        type record_type = :event

        module RecordType
          extend Telnyx::Internal::Type::Enum

          EVENT: :event

          def self?.values: -> ::Array[Telnyx::Models::ConferenceRecordingSavedWebhookEvent::Data::record_type]
        end
      end
    end
  end
end
