module Telnyx
  module Models
    type conference_participant_playback_started_webhook_event =
      { data: Telnyx::ConferenceParticipantPlaybackStarted }

    class ConferenceParticipantPlaybackStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceParticipantPlaybackStarted?

      def data=: (
        Telnyx::ConferenceParticipantPlaybackStarted
      ) -> Telnyx::ConferenceParticipantPlaybackStarted

      def initialize: (
        ?data: Telnyx::ConferenceParticipantPlaybackStarted
      ) -> void

      def to_hash: -> { data: Telnyx::ConferenceParticipantPlaybackStarted }
    end
  end
end
