module Telnyx
  module Models
    type conference_speak_ended_webhook_event =
      { data: Telnyx::ConferenceSpeakEnded }

    class ConferenceSpeakEndedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ConferenceSpeakEnded?

      def data=: (Telnyx::ConferenceSpeakEnded) -> Telnyx::ConferenceSpeakEnded

      def initialize: (?data: Telnyx::ConferenceSpeakEnded) -> void

      def to_hash: -> { data: Telnyx::ConferenceSpeakEnded }
    end
  end
end
