module Telnyx
  module Models
    type conference_list_participants_params =
      {
        filter: Telnyx::ConferenceListParticipantsParams::Filter,
        page_number: Integer,
        page_size: Integer,
        region: Telnyx::Models::ConferenceListParticipantsParams::region
      }
      & Telnyx::Internal::Type::request_parameters

    class ConferenceListParticipantsParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_reader filter: Telnyx::ConferenceListParticipantsParams::Filter?

      def filter=: (
        Telnyx::ConferenceListParticipantsParams::Filter
      ) -> Telnyx::ConferenceListParticipantsParams::Filter

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader region: Telnyx::Models::ConferenceListParticipantsParams::region?

      def region=: (
        Telnyx::Models::ConferenceListParticipantsParams::region
      ) -> Telnyx::Models::ConferenceListParticipantsParams::region

      def initialize: (
        ?filter: Telnyx::ConferenceListParticipantsParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?region: Telnyx::Models::ConferenceListParticipantsParams::region,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        filter: Telnyx::ConferenceListParticipantsParams::Filter,
        page_number: Integer,
        page_size: Integer,
        region: Telnyx::Models::ConferenceListParticipantsParams::region,
        request_options: Telnyx::RequestOptions
      }

      type filter = { muted: bool, on_hold: bool, whispering: bool }

      class Filter < Telnyx::Internal::Type::BaseModel
        attr_reader muted: bool?

        def muted=: (bool) -> bool

        attr_reader on_hold: bool?

        def on_hold=: (bool) -> bool

        attr_reader whispering: bool?

        def whispering=: (bool) -> bool

        def initialize: (
          ?muted: bool,
          ?on_hold: bool,
          ?whispering: bool
        ) -> void

        def to_hash: -> { muted: bool, on_hold: bool, whispering: bool }
      end

      type region = :Australia | :Europe | :"Middle East" | :US

      module Region
        extend Telnyx::Internal::Type::Enum

        AUSTRALIA: :Australia
        EUROPE: :Europe
        MIDDLE_EAST: :"Middle East"
        US: :US

        def self?.values: -> ::Array[Telnyx::Models::ConferenceListParticipantsParams::region]
      end
    end
  end
end
