module Telnyx
  module Models
    type connection_noise_suppression_details =
      {
        attenuation_limit: Integer,
        engine: Telnyx::Models::ConnectionNoiseSuppressionDetails::engine
      }

    class ConnectionNoiseSuppressionDetails < Telnyx::Internal::Type::BaseModel
      attr_reader attenuation_limit: Integer?

      def attenuation_limit=: (Integer) -> Integer

      attr_reader engine: Telnyx::Models::ConnectionNoiseSuppressionDetails::engine?

      def engine=: (
        Telnyx::Models::ConnectionNoiseSuppressionDetails::engine
      ) -> Telnyx::Models::ConnectionNoiseSuppressionDetails::engine

      def initialize: (
        ?attenuation_limit: Integer,
        ?engine: Telnyx::Models::ConnectionNoiseSuppressionDetails::engine
      ) -> void

      def to_hash: -> {
        attenuation_limit: Integer,
        engine: Telnyx::Models::ConnectionNoiseSuppressionDetails::engine
      }

      type engine =
        :denoiser
        | :deep_filter_net
        | :deep_filter_net_large
        | :krisp_viva_tel
        | :krisp_viva_tel_lite
        | :krisp_viva_promodel
        | :krisp_viva_ss

      module Engine
        extend Telnyx::Internal::Type::Enum

        DENOISER: :denoiser
        DEEP_FILTER_NET: :deep_filter_net
        DEEP_FILTER_NET_LARGE: :deep_filter_net_large
        KRISP_VIVA_TEL: :krisp_viva_tel
        KRISP_VIVA_TEL_LITE: :krisp_viva_tel_lite
        KRISP_VIVA_PROMODEL: :krisp_viva_promodel
        KRISP_VIVA_SS: :krisp_viva_ss

        def self?.values: -> ::Array[Telnyx::Models::ConnectionNoiseSuppressionDetails::engine]
      end
    end
  end
end
