module Telnyx
  module Models
    type cost_information =
      { currency: String, monthly_cost: String, upfront_cost: String }

    class CostInformation < Telnyx::Internal::Type::BaseModel
      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader monthly_cost: String?

      def monthly_cost=: (String) -> String

      attr_reader upfront_cost: String?

      def upfront_cost=: (String) -> String

      def initialize: (
        ?currency: String,
        ?monthly_cost: String,
        ?upfront_cost: String
      ) -> void

      def to_hash: -> {
        currency: String,
        monthly_cost: String,
        upfront_cost: String
      }
    end
  end
end
