module Telnyx
  module Models
    type country_coverage_retrieve_country_response =
      { data: Telnyx::CountryCoverageAPI }

    class CountryCoverageRetrieveCountryResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CountryCoverageAPI?

      def data=: (Telnyx::CountryCoverageAPI) -> Telnyx::CountryCoverageAPI

      def initialize: (?data: Telnyx::CountryCoverageAPI) -> void

      def to_hash: -> { data: Telnyx::CountryCoverageAPI }
    end
  end
end
