module Telnyx
  module Models
    type credential_connection_create_response =
      { data: Telnyx::CredentialConnection }

    class CredentialConnectionCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CredentialConnection?

      def data=: (Telnyx::CredentialConnection) -> Telnyx::CredentialConnection

      def initialize: (?data: Telnyx::CredentialConnection) -> void

      def to_hash: -> { data: Telnyx::CredentialConnection }
    end
  end
end
