module Telnyx
  module Models
    type custom_storage_credential_update_response =
      {
        connection_id: String,
        data: Telnyx::CustomStorageConfiguration,
        record_type: Telnyx::Models::CustomStorageCredentialUpdateResponse::record_type
      }

    class CustomStorageCredentialUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor connection_id: String

      attr_accessor data: Telnyx::CustomStorageConfiguration

      attr_accessor record_type: Telnyx::Models::CustomStorageCredentialUpdateResponse::record_type

      def initialize: (
        connection_id: String,
        data: Telnyx::CustomStorageConfiguration,
        record_type: Telnyx::Models::CustomStorageCredentialUpdateResponse::record_type
      ) -> void

      def to_hash: -> {
        connection_id: String,
        data: Telnyx::CustomStorageConfiguration,
        record_type: Telnyx::Models::CustomStorageCredentialUpdateResponse::record_type
      }

      type record_type = :custom_storage_credentials

      module RecordType
        extend Telnyx::Internal::Type::Enum

        CUSTOM_STORAGE_CREDENTIALS: :custom_storage_credentials

        def self?.values: -> ::Array[Telnyx::Models::CustomStorageCredentialUpdateResponse::record_type]
      end
    end
  end
end
