module Telnyx
  module Models
    type dir_list_document_types_response =
      {
        data: ::Array[Telnyx::Models::DirListDocumentTypesResponse::Data],
        meta: Telnyx::Models::DirListDocumentTypesResponse::Meta
      }

    class DirListDocumentTypesResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::Models::DirListDocumentTypesResponse::Data]

      attr_accessor meta: Telnyx::Models::DirListDocumentTypesResponse::Meta

      def initialize: (
        data: ::Array[Telnyx::Models::DirListDocumentTypesResponse::Data],
        meta: Telnyx::Models::DirListDocumentTypesResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Models::DirListDocumentTypesResponse::Data],
        meta: Telnyx::Models::DirListDocumentTypesResponse::Meta
      }

      type data = { description: String, short_name: String }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader description: String?

        def description=: (String) -> String

        attr_reader short_name: String?

        def short_name=: (String) -> String

        def initialize: (?description: String, ?short_name: String) -> void

        def to_hash: -> { description: String, short_name: String }
      end

      type meta =
        {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_accessor page_number: Integer

        attr_accessor page_size: Integer

        attr_accessor total_pages: Integer

        attr_accessor total_results: Integer

        def initialize: (
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        ) -> void

        def to_hash: -> {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }
      end
    end
  end
end
