module Telnyx
  module Models
    type document_delete_response = { data: Telnyx::DocServiceDocument }

    class DocumentDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::DocServiceDocument?

      def data=: (Telnyx::DocServiceDocument) -> Telnyx::DocServiceDocument

      def initialize: (?data: Telnyx::DocServiceDocument) -> void

      def to_hash: -> { data: Telnyx::DocServiceDocument }
    end
  end
end
