module Telnyx
  module Models
    type dynamic_emergency_endpoint_delete_response =
      { data: Telnyx::DynamicEmergencyEndpoint }

    class DynamicEmergencyEndpointDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::DynamicEmergencyEndpoint?

      def data=: (
        Telnyx::DynamicEmergencyEndpoint
      ) -> Telnyx::DynamicEmergencyEndpoint

      def initialize: (?data: Telnyx::DynamicEmergencyEndpoint) -> void

      def to_hash: -> { data: Telnyx::DynamicEmergencyEndpoint }
    end
  end
end
