module Telnyx
  module Models
    type email_validation_checks =
      {
        disposable: Telnyx::EmailValidationCheck,
        mx: Telnyx::EmailValidationCheck,
        role_based: Telnyx::EmailValidationCheck,
        syntax: Telnyx::EmailValidationCheck,
        typo: Telnyx::EmailValidationChecks::Typo
      }

    class EmailValidationChecks < Telnyx::Internal::Type::BaseModel
      attr_accessor disposable: Telnyx::EmailValidationCheck

      attr_accessor mx: Telnyx::EmailValidationCheck

      attr_accessor role_based: Telnyx::EmailValidationCheck

      attr_accessor syntax: Telnyx::EmailValidationCheck

      attr_accessor typo: Telnyx::EmailValidationChecks::Typo

      def initialize: (
        disposable: Telnyx::EmailValidationCheck,
        mx: Telnyx::EmailValidationCheck,
        role_based: Telnyx::EmailValidationCheck,
        syntax: Telnyx::EmailValidationCheck,
        typo: Telnyx::EmailValidationChecks::Typo
      ) -> void

      def to_hash: -> {
        disposable: Telnyx::EmailValidationCheck,
        mx: Telnyx::EmailValidationCheck,
        role_based: Telnyx::EmailValidationCheck,
        syntax: Telnyx::EmailValidationCheck,
        typo: Telnyx::EmailValidationChecks::Typo
      }

      type typo = { suggestion: String }

      class Typo < Telnyx::Models::EmailValidationCheck
        def suggestion: -> String?

        def suggestion=: (String _) -> String

        def initialize: (?suggestion: String) -> void

        def to_hash: -> { suggestion: String }
      end
    end
  end
end
