module Telnyx
  module Models
    type email_message_list_response =
      {
        data: ::Array[Telnyx::EmailInboxes::EmailMessage],
        meta: Telnyx::EmailInboxes::EmailPaginationMeta
      }

    class EmailMessageListResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::EmailInboxes::EmailMessage]

      attr_accessor meta: Telnyx::EmailInboxes::EmailPaginationMeta

      def initialize: (
        data: ::Array[Telnyx::EmailInboxes::EmailMessage],
        meta: Telnyx::EmailInboxes::EmailPaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::EmailInboxes::EmailMessage],
        meta: Telnyx::EmailInboxes::EmailPaginationMeta
      }
    end
  end
end
