module Telnyx
  module Models
    type email_block_retrieve_events_response =
      {
        id: String,
        actor: String,
        event_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::event_type,
        occurred_at: Time,
        reason: String,
        record_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::record_type,
        source: String,
        meta: ::Hash[Symbol, top]?
      }

    class EmailBlockRetrieveEventsResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor actor: String

      attr_accessor event_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::event_type

      attr_accessor occurred_at: Time

      attr_accessor reason: String

      attr_accessor record_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::record_type

      attr_accessor source: String

      attr_accessor meta: ::Hash[Symbol, top]?

      def initialize: (
        id: String,
        actor: String,
        event_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::event_type,
        occurred_at: Time,
        reason: String,
        record_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::record_type,
        source: String,
        ?meta: ::Hash[Symbol, top]?
      ) -> void

      def to_hash: -> {
        id: String,
        actor: String,
        event_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::event_type,
        occurred_at: Time,
        reason: String,
        record_type: Telnyx::Models::EmailBlockRetrieveEventsResponse::record_type,
        source: String,
        meta: ::Hash[Symbol, top]?
      }

      type event_type = :created | :removed | :expired | :override_used

      module EventType
        extend Telnyx::Internal::Type::Enum

        CREATED: :created
        REMOVED: :removed
        EXPIRED: :expired
        OVERRIDE_USED: :override_used

        def self?.values: -> ::Array[Telnyx::Models::EmailBlockRetrieveEventsResponse::event_type]
      end

      type record_type = :email_block_event

      module RecordType
        extend Telnyx::Internal::Type::Enum

        EMAIL_BLOCK_EVENT: :email_block_event

        def self?.values: -> ::Array[Telnyx::Models::EmailBlockRetrieveEventsResponse::record_type]
      end
    end
  end
end
