module Telnyx
  module Models
    type email_message_detail_response =
      { data: Telnyx::EmailMessageDetailResponse::Data }

    class EmailMessageDetailResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::EmailMessageDetailResponse::Data

      def initialize: (data: Telnyx::EmailMessageDetailResponse::Data) -> void

      def to_hash: -> { data: Telnyx::EmailMessageDetailResponse::Data }

      type data = { html_body: String?, text_body: String? }

      class Data < Telnyx::Models::EmailInboxes::EmailMessage
        def html_body: -> String?

        def html_body=: (String? _) -> String?

        def text_body: -> String?

        def text_body=: (String? _) -> String?

        def initialize: (html_body: String?, text_body: String?) -> void

        def to_hash: -> { html_body: String?, text_body: String? }
      end
    end
  end
end
