module Telnyx
  module Models
    type email_template_render_response =
      { data: Telnyx::Models::EmailTemplateRenderResponse::Data }

    class EmailTemplateRenderResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::Models::EmailTemplateRenderResponse::Data

      def initialize: (
        data: Telnyx::Models::EmailTemplateRenderResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::EmailTemplateRenderResponse::Data
      }

      type data = {  }

      class Data < Telnyx::Models::EmailTemplate
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
