module Telnyx
  module Models
    type email_validation_create_response =
      { data: Telnyx::Models::EmailValidationCreateResponse::Data }

    class EmailValidationCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::Models::EmailValidationCreateResponse::Data

      def initialize: (
        data: Telnyx::Models::EmailValidationCreateResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::EmailValidationCreateResponse::Data
      }

      type data =
        {
          checks: Telnyx::EmailValidationChecks,
          email: String,
          record_type: Telnyx::Models::EmailValidationCreateResponse::Data::record_type,
          risk_score: Float,
          valid: bool,
          did_you_mean: String
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_accessor checks: Telnyx::EmailValidationChecks

        attr_accessor email: String

        attr_accessor record_type: Telnyx::Models::EmailValidationCreateResponse::Data::record_type

        attr_accessor risk_score: Float

        attr_accessor valid: bool

        attr_reader did_you_mean: String?

        def did_you_mean=: (String) -> String

        def initialize: (
          checks: Telnyx::EmailValidationChecks,
          email: String,
          record_type: Telnyx::Models::EmailValidationCreateResponse::Data::record_type,
          risk_score: Float,
          valid: bool,
          ?did_you_mean: String
        ) -> void

        def to_hash: -> {
          checks: Telnyx::EmailValidationChecks,
          email: String,
          record_type: Telnyx::Models::EmailValidationCreateResponse::Data::record_type,
          risk_score: Float,
          valid: bool,
          did_you_mean: String
        }

        type record_type = :email_validation

        module RecordType
          extend Telnyx::Internal::Type::Enum

          EMAIL_VALIDATION: :email_validation

          def self?.values: -> ::Array[Telnyx::Models::EmailValidationCreateResponse::Data::record_type]
        end
      end
    end
  end
end
