module Telnyx
  module Models
    type enterprise_create_response = { data: Telnyx::EnterprisePublic }

    class EnterpriseCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::EnterprisePublic

      def initialize: (data: Telnyx::EnterprisePublic) -> void

      def to_hash: -> { data: Telnyx::EnterprisePublic }
    end
  end
end
