module Telnyx
  module Models
    type enterprise_update_params =
      {
        enterprise_id: String,
        billing_address: Telnyx::BillingAddress,
        billing_contact: Telnyx::BillingContact,
        corporate_registration_number: String,
        customer_reference: String,
        doing_business_as: String,
        dun_bradstreet_number: String,
        fein: String,
        industry: String,
        legal_name: String,
        number_of_employees: Telnyx::Models::EnterpriseUpdateParams::number_of_employees,
        organization_contact: Telnyx::OrganizationContact,
        organization_legal_type: Telnyx::Models::EnterpriseUpdateParams::organization_legal_type,
        organization_physical_address: Telnyx::PhysicalAddress,
        primary_business_domain_sic_code: String,
        professional_license_number: String,
        website: String
      }
      & Telnyx::Internal::Type::request_parameters

    class EnterpriseUpdateParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor enterprise_id: String

      attr_reader billing_address: Telnyx::BillingAddress?

      def billing_address=: (Telnyx::BillingAddress) -> Telnyx::BillingAddress

      attr_reader billing_contact: Telnyx::BillingContact?

      def billing_contact=: (Telnyx::BillingContact) -> Telnyx::BillingContact

      attr_reader corporate_registration_number: String?

      def corporate_registration_number=: (String) -> String

      attr_reader customer_reference: String?

      def customer_reference=: (String) -> String

      attr_reader doing_business_as: String?

      def doing_business_as=: (String) -> String

      attr_reader dun_bradstreet_number: String?

      def dun_bradstreet_number=: (String) -> String

      attr_reader fein: String?

      def fein=: (String) -> String

      attr_reader industry: String?

      def industry=: (String) -> String

      attr_reader legal_name: String?

      def legal_name=: (String) -> String

      attr_reader number_of_employees: Telnyx::Models::EnterpriseUpdateParams::number_of_employees?

      def number_of_employees=: (
        Telnyx::Models::EnterpriseUpdateParams::number_of_employees
      ) -> Telnyx::Models::EnterpriseUpdateParams::number_of_employees

      attr_reader organization_contact: Telnyx::OrganizationContact?

      def organization_contact=: (
        Telnyx::OrganizationContact
      ) -> Telnyx::OrganizationContact

      attr_reader organization_legal_type: Telnyx::Models::EnterpriseUpdateParams::organization_legal_type?

      def organization_legal_type=: (
        Telnyx::Models::EnterpriseUpdateParams::organization_legal_type
      ) -> Telnyx::Models::EnterpriseUpdateParams::organization_legal_type

      attr_reader organization_physical_address: Telnyx::PhysicalAddress?

      def organization_physical_address=: (
        Telnyx::PhysicalAddress
      ) -> Telnyx::PhysicalAddress

      attr_reader primary_business_domain_sic_code: String?

      def primary_business_domain_sic_code=: (String) -> String

      attr_reader professional_license_number: String?

      def professional_license_number=: (String) -> String

      attr_reader website: String?

      def website=: (String) -> String

      def initialize: (
        enterprise_id: String,
        ?billing_address: Telnyx::BillingAddress,
        ?billing_contact: Telnyx::BillingContact,
        ?corporate_registration_number: String,
        ?customer_reference: String,
        ?doing_business_as: String,
        ?dun_bradstreet_number: String,
        ?fein: String,
        ?industry: String,
        ?legal_name: String,
        ?number_of_employees: Telnyx::Models::EnterpriseUpdateParams::number_of_employees,
        ?organization_contact: Telnyx::OrganizationContact,
        ?organization_legal_type: Telnyx::Models::EnterpriseUpdateParams::organization_legal_type,
        ?organization_physical_address: Telnyx::PhysicalAddress,
        ?primary_business_domain_sic_code: String,
        ?professional_license_number: String,
        ?website: String,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        enterprise_id: String,
        billing_address: Telnyx::BillingAddress,
        billing_contact: Telnyx::BillingContact,
        corporate_registration_number: String,
        customer_reference: String,
        doing_business_as: String,
        dun_bradstreet_number: String,
        fein: String,
        industry: String,
        legal_name: String,
        number_of_employees: Telnyx::Models::EnterpriseUpdateParams::number_of_employees,
        organization_contact: Telnyx::OrganizationContact,
        organization_legal_type: Telnyx::Models::EnterpriseUpdateParams::organization_legal_type,
        organization_physical_address: Telnyx::PhysicalAddress,
        primary_business_domain_sic_code: String,
        professional_license_number: String,
        website: String,
        request_options: Telnyx::RequestOptions
      }

      type number_of_employees =
        :"1-10"
        | :"11-50"
        | :"51-200"
        | :"201-500"
        | :"501-2000"
        | :"2001-10000"
        | :"10001+"

      module NumberOfEmployees
        extend Telnyx::Internal::Type::Enum

        NUMBER_OF_EMPLOYEES_1_10: :"1-10"
        NUMBER_OF_EMPLOYEES_11_50: :"11-50"
        NUMBER_OF_EMPLOYEES_51_200: :"51-200"
        NUMBER_OF_EMPLOYEES_201_500: :"201-500"
        NUMBER_OF_EMPLOYEES_501_2000: :"501-2000"
        NUMBER_OF_EMPLOYEES_2001_10000: :"2001-10000"
        NUMBER_OF_EMPLOYEES_10001_PLUS: :"10001+"

        def self?.values: -> ::Array[Telnyx::Models::EnterpriseUpdateParams::number_of_employees]
      end

      type organization_legal_type =
        :corporation | :llc | :partnership | :nonprofit | :other

      module OrganizationLegalType
        extend Telnyx::Internal::Type::Enum

        CORPORATION: :corporation
        LLC: :llc
        PARTNERSHIP: :partnership
        NONPROFIT: :nonprofit
        OTHER: :other

        def self?.values: -> ::Array[Telnyx::Models::EnterpriseUpdateParams::organization_legal_type]
      end
    end
  end
end
