module Telnyx
  module Models
    type enterprise_update_params =
      {
        enterprise_id: String,
        billing_address: Telnyx::BillingAddress,
        billing_contact: Telnyx::BillingContact,
        corporate_registration_number: String?,
        customer_reference: String,
        doing_business_as: String,
        dun_bradstreet_number: String?,
        fein: String,
        industry: Telnyx::Models::EnterpriseUpdateParams::industry,
        jurisdiction_of_incorporation: String,
        legal_name: String,
        number_of_employees: String,
        organization_contact: Telnyx::OrganizationContact,
        organization_legal_type: String,
        organization_physical_address: Telnyx::PhysicalAddress,
        primary_business_domain_sic_code: String?,
        professional_license_number: String?,
        website: String
      }
      & Telnyx::Internal::Type::request_parameters

    class EnterpriseUpdateParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor enterprise_id: String

      attr_reader billing_address: Telnyx::BillingAddress?

      def billing_address=: (Telnyx::BillingAddress) -> Telnyx::BillingAddress

      attr_reader billing_contact: Telnyx::BillingContact?

      def billing_contact=: (Telnyx::BillingContact) -> Telnyx::BillingContact

      attr_accessor corporate_registration_number: String?

      attr_reader customer_reference: String?

      def customer_reference=: (String) -> String

      attr_reader doing_business_as: String?

      def doing_business_as=: (String) -> String

      attr_accessor dun_bradstreet_number: String?

      attr_reader fein: String?

      def fein=: (String) -> String

      attr_reader industry: Telnyx::Models::EnterpriseUpdateParams::industry?

      def industry=: (
        Telnyx::Models::EnterpriseUpdateParams::industry
      ) -> Telnyx::Models::EnterpriseUpdateParams::industry

      attr_reader jurisdiction_of_incorporation: String?

      def jurisdiction_of_incorporation=: (String) -> String

      attr_reader legal_name: String?

      def legal_name=: (String) -> String

      attr_reader number_of_employees: String?

      def number_of_employees=: (String) -> String

      attr_reader organization_contact: Telnyx::OrganizationContact?

      def organization_contact=: (
        Telnyx::OrganizationContact
      ) -> Telnyx::OrganizationContact

      attr_reader organization_legal_type: String?

      def organization_legal_type=: (String) -> String

      attr_reader organization_physical_address: Telnyx::PhysicalAddress?

      def organization_physical_address=: (
        Telnyx::PhysicalAddress
      ) -> Telnyx::PhysicalAddress

      attr_accessor primary_business_domain_sic_code: String?

      attr_accessor professional_license_number: String?

      attr_reader website: String?

      def website=: (String) -> String

      def initialize: (
        enterprise_id: String,
        ?billing_address: Telnyx::BillingAddress,
        ?billing_contact: Telnyx::BillingContact,
        ?corporate_registration_number: String?,
        ?customer_reference: String,
        ?doing_business_as: String,
        ?dun_bradstreet_number: String?,
        ?fein: String,
        ?industry: Telnyx::Models::EnterpriseUpdateParams::industry,
        ?jurisdiction_of_incorporation: String,
        ?legal_name: String,
        ?number_of_employees: String,
        ?organization_contact: Telnyx::OrganizationContact,
        ?organization_legal_type: String,
        ?organization_physical_address: Telnyx::PhysicalAddress,
        ?primary_business_domain_sic_code: String?,
        ?professional_license_number: String?,
        ?website: String,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        enterprise_id: String,
        billing_address: Telnyx::BillingAddress,
        billing_contact: Telnyx::BillingContact,
        corporate_registration_number: String?,
        customer_reference: String,
        doing_business_as: String,
        dun_bradstreet_number: String?,
        fein: String,
        industry: Telnyx::Models::EnterpriseUpdateParams::industry,
        jurisdiction_of_incorporation: String,
        legal_name: String,
        number_of_employees: String,
        organization_contact: Telnyx::OrganizationContact,
        organization_legal_type: String,
        organization_physical_address: Telnyx::PhysicalAddress,
        primary_business_domain_sic_code: String?,
        professional_license_number: String?,
        website: String,
        request_options: Telnyx::RequestOptions
      }

      type industry =
        :accounting
        | :finance
        | :billing
        | :collections
        | :business
        | :charity
        | :nonprofit
        | :communications
        | :telecom
        | :"customer service"
        | :support
        | :delivery
        | :shipping
        | :logistics
        | :education
        | :financial
        | :banking
        | :government
        | :public
        | :healthcare
        | :health
        | :pharmacy
        | :medical
        | :insurance
        | :legal
        | :law
        | :notifications
        | :scheduling
        | :"real estate"
        | :property
        | :retail
        | :ecommerce
        | :sales
        | :marketing
        | :software
        | :technology
        | :tech
        | :media
        | :surveys
        | :"market research"
        | :travel
        | :hospitality
        | :hotel

      module Industry
        extend Telnyx::Internal::Type::Enum

        ACCOUNTING: :accounting
        FINANCE: :finance
        BILLING: :billing
        COLLECTIONS: :collections
        BUSINESS: :business
        CHARITY: :charity
        NONPROFIT: :nonprofit
        COMMUNICATIONS: :communications
        TELECOM: :telecom
        CUSTOMER_SERVICE: :"customer service"
        SUPPORT: :support
        DELIVERY: :delivery
        SHIPPING: :shipping
        LOGISTICS: :logistics
        EDUCATION: :education
        FINANCIAL: :financial
        BANKING: :banking
        GOVERNMENT: :government
        PUBLIC: :public
        HEALTHCARE: :healthcare
        HEALTH: :health
        PHARMACY: :pharmacy
        MEDICAL: :medical
        INSURANCE: :insurance
        LEGAL: :legal
        LAW: :law
        NOTIFICATIONS: :notifications
        SCHEDULING: :scheduling
        REAL_ESTATE: :"real estate"
        PROPERTY: :property
        RETAIL: :retail
        ECOMMERCE: :ecommerce
        SALES: :sales
        MARKETING: :marketing
        SOFTWARE: :software
        TECHNOLOGY: :technology
        TECH: :tech
        MEDIA: :media
        SURVEYS: :surveys
        MARKET_RESEARCH: :"market research"
        TRAVEL: :travel
        HOSPITALITY: :hospitality
        HOTEL: :hotel

        def self?.values: -> ::Array[Telnyx::Models::EnterpriseUpdateParams::industry]
      end
    end
  end
end
