module Telnyx
  module Models
    type enterprise_retrieve_response =
      { data: Telnyx::Models::EnterpriseRetrieveResponse::Data }

    class EnterpriseRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::EnterpriseRetrieveResponse::Data?

      def data=: (
        Telnyx::Models::EnterpriseRetrieveResponse::Data
      ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data

      def initialize: (
        ?data: Telnyx::Models::EnterpriseRetrieveResponse::Data
      ) -> void

      def to_hash: -> { data: Telnyx::Models::EnterpriseRetrieveResponse::Data }

      type data =
        {
          id: String,
          billing_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress,
          billing_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact,
          corporate_registration_number: String?,
          country_code: String,
          created_at: Time,
          customer_reference: String?,
          doing_business_as: String,
          dun_bradstreet_number: String?,
          fein: String?,
          industry: String?,
          legal_name: String,
          number_of_employees: Telnyx::Models::EnterpriseRetrieveResponse::Data::number_of_employees?,
          organization_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact,
          organization_legal_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_legal_type?,
          organization_physical_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress,
          organization_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type,
          primary_business_domain_sic_code: String?,
          professional_license_number: String?,
          role_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type,
          updated_at: Time,
          website: String?
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader billing_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress?

        def billing_address=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress

        attr_reader billing_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact?

        def billing_contact=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact

        attr_accessor corporate_registration_number: String?

        attr_reader country_code: String?

        def country_code=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_accessor customer_reference: String?

        attr_reader doing_business_as: String?

        def doing_business_as=: (String) -> String

        attr_accessor dun_bradstreet_number: String?

        attr_accessor fein: String?

        attr_accessor industry: String?

        attr_reader legal_name: String?

        def legal_name=: (String) -> String

        attr_accessor number_of_employees: Telnyx::Models::EnterpriseRetrieveResponse::Data::number_of_employees?

        attr_reader organization_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact?

        def organization_contact=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact

        attr_accessor organization_legal_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_legal_type?

        attr_reader organization_physical_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress?

        def organization_physical_address=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress

        attr_reader organization_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type?

        def organization_type=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type

        attr_accessor primary_business_domain_sic_code: String?

        attr_accessor professional_license_number: String?

        attr_reader role_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type?

        def role_type=: (
          Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type
        ) -> Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        attr_accessor website: String?

        def initialize: (
          ?id: String,
          ?billing_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress,
          ?billing_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact,
          ?corporate_registration_number: String?,
          ?country_code: String,
          ?created_at: Time,
          ?customer_reference: String?,
          ?doing_business_as: String,
          ?dun_bradstreet_number: String?,
          ?fein: String?,
          ?industry: String?,
          ?legal_name: String,
          ?number_of_employees: Telnyx::Models::EnterpriseRetrieveResponse::Data::number_of_employees?,
          ?organization_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact,
          ?organization_legal_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_legal_type?,
          ?organization_physical_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress,
          ?organization_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type,
          ?primary_business_domain_sic_code: String?,
          ?professional_license_number: String?,
          ?role_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type,
          ?updated_at: Time,
          ?website: String?
        ) -> void

        def to_hash: -> {
          id: String,
          billing_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingAddress,
          billing_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::BillingContact,
          corporate_registration_number: String?,
          country_code: String,
          created_at: Time,
          customer_reference: String?,
          doing_business_as: String,
          dun_bradstreet_number: String?,
          fein: String?,
          industry: String?,
          legal_name: String,
          number_of_employees: Telnyx::Models::EnterpriseRetrieveResponse::Data::number_of_employees?,
          organization_contact: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationContact,
          organization_legal_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_legal_type?,
          organization_physical_address: Telnyx::Models::EnterpriseRetrieveResponse::Data::OrganizationPhysicalAddress,
          organization_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type,
          primary_business_domain_sic_code: String?,
          professional_license_number: String?,
          role_type: Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type,
          updated_at: Time,
          website: String?
        }

        type billing_address =
          {
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            extended_address: String?
          }

        class BillingAddress < Telnyx::Internal::Type::BaseModel
          attr_accessor administrative_area: String

          attr_accessor city: String

          attr_accessor country: String

          attr_accessor postal_code: String

          attr_accessor street_address: String

          attr_accessor extended_address: String?

          def initialize: (
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            ?extended_address: String?
          ) -> void

          def to_hash: -> {
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            extended_address: String?
          }
        end

        type billing_contact =
          {
            email: String,
            first_name: String,
            last_name: String,
            phone_number: String
          }

        class BillingContact < Telnyx::Internal::Type::BaseModel
          attr_accessor email: String

          attr_accessor first_name: String

          attr_accessor last_name: String

          attr_accessor phone_number: String

          def initialize: (
            email: String,
            first_name: String,
            last_name: String,
            phone_number: String
          ) -> void

          def to_hash: -> {
            email: String,
            first_name: String,
            last_name: String,
            phone_number: String
          }
        end

        type number_of_employees =
          :"1-10"
          | :"11-50"
          | :"51-200"
          | :"201-500"
          | :"501-2000"
          | :"2001-10000"
          | :"10001+"

        module NumberOfEmployees
          extend Telnyx::Internal::Type::Enum

          NUMBER_OF_EMPLOYEES_1_10: :"1-10"
          NUMBER_OF_EMPLOYEES_11_50: :"11-50"
          NUMBER_OF_EMPLOYEES_51_200: :"51-200"
          NUMBER_OF_EMPLOYEES_201_500: :"201-500"
          NUMBER_OF_EMPLOYEES_501_2000: :"501-2000"
          NUMBER_OF_EMPLOYEES_2001_10000: :"2001-10000"
          NUMBER_OF_EMPLOYEES_10001: :"10001+"

          def self?.values: -> ::Array[Telnyx::Models::EnterpriseRetrieveResponse::Data::number_of_employees]
        end

        type organization_contact =
          {
            email: String,
            first_name: String,
            job_title: String,
            last_name: String,
            phone: String
          }

        class OrganizationContact < Telnyx::Internal::Type::BaseModel
          attr_accessor email: String

          attr_accessor first_name: String

          attr_accessor job_title: String

          attr_accessor last_name: String

          attr_accessor phone: String

          def initialize: (
            email: String,
            first_name: String,
            job_title: String,
            last_name: String,
            phone: String
          ) -> void

          def to_hash: -> {
            email: String,
            first_name: String,
            job_title: String,
            last_name: String,
            phone: String
          }
        end

        type organization_legal_type =
          :corporation | :llc | :partnership | :nonprofit | :other

        module OrganizationLegalType
          extend Telnyx::Internal::Type::Enum

          CORPORATION: :corporation
          LLC: :llc
          PARTNERSHIP: :partnership
          NONPROFIT: :nonprofit
          OTHER: :other

          def self?.values: -> ::Array[Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_legal_type]
        end

        type organization_physical_address =
          {
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            extended_address: String?
          }

        class OrganizationPhysicalAddress < Telnyx::Internal::Type::BaseModel
          attr_accessor administrative_area: String

          attr_accessor city: String

          attr_accessor country: String

          attr_accessor postal_code: String

          attr_accessor street_address: String

          attr_accessor extended_address: String?

          def initialize: (
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            ?extended_address: String?
          ) -> void

          def to_hash: -> {
            administrative_area: String,
            city: String,
            country: String,
            postal_code: String,
            street_address: String,
            extended_address: String?
          }
        end

        type organization_type = :commercial | :government | :non_profit

        module OrganizationType
          extend Telnyx::Internal::Type::Enum

          COMMERCIAL: :commercial
          GOVERNMENT: :government
          NON_PROFIT: :non_profit

          def self?.values: -> ::Array[Telnyx::Models::EnterpriseRetrieveResponse::Data::organization_type]
        end

        type role_type = :enterprise | :bpo

        module RoleType
          extend Telnyx::Internal::Type::Enum

          ENTERPRISE: :enterprise
          BPO: :bpo

          def self?.values: -> ::Array[Telnyx::Models::EnterpriseRetrieveResponse::Data::role_type]
        end
      end
    end
  end
end
