module Telnyx
  module Models
    type enterprise_retrieve_response = { data: Telnyx::EnterprisePublic }

    class EnterpriseRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::EnterprisePublic?

      def data=: (Telnyx::EnterprisePublic) -> Telnyx::EnterprisePublic

      def initialize: (?data: Telnyx::EnterprisePublic) -> void

      def to_hash: -> { data: Telnyx::EnterprisePublic }
    end
  end
end
