module Telnyx
  module Models
    type fax_sending_started_webhook_event =
      {
        id: String,
        event_type: Telnyx::Models::FaxSendingStartedWebhookEvent::event_type,
        payload: Telnyx::FaxSendingStartedWebhookEvent::Payload,
        record_type: Telnyx::Models::FaxSendingStartedWebhookEvent::record_type
      }

    class FaxSendingStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader event_type: Telnyx::Models::FaxSendingStartedWebhookEvent::event_type?

      def event_type=: (
        Telnyx::Models::FaxSendingStartedWebhookEvent::event_type
      ) -> Telnyx::Models::FaxSendingStartedWebhookEvent::event_type

      attr_reader payload: Telnyx::FaxSendingStartedWebhookEvent::Payload?

      def payload=: (
        Telnyx::FaxSendingStartedWebhookEvent::Payload
      ) -> Telnyx::FaxSendingStartedWebhookEvent::Payload

      attr_reader record_type: Telnyx::Models::FaxSendingStartedWebhookEvent::record_type?

      def record_type=: (
        Telnyx::Models::FaxSendingStartedWebhookEvent::record_type
      ) -> Telnyx::Models::FaxSendingStartedWebhookEvent::record_type

      def initialize: (
        ?id: String,
        ?event_type: Telnyx::Models::FaxSendingStartedWebhookEvent::event_type,
        ?payload: Telnyx::FaxSendingStartedWebhookEvent::Payload,
        ?record_type: Telnyx::Models::FaxSendingStartedWebhookEvent::record_type
      ) -> void

      def to_hash: -> {
        id: String,
        event_type: Telnyx::Models::FaxSendingStartedWebhookEvent::event_type,
        payload: Telnyx::FaxSendingStartedWebhookEvent::Payload,
        record_type: Telnyx::Models::FaxSendingStartedWebhookEvent::record_type
      }

      type event_type = :"fax.sending.started"

      module EventType
        extend Telnyx::Internal::Type::Enum

        FAX_SENDING_STARTED: :"fax.sending.started"

        def self?.values: -> ::Array[Telnyx::Models::FaxSendingStartedWebhookEvent::event_type]
      end

      type payload =
        {
          client_state: String,
          connection_id: String,
          direction: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction,
          fax_id: String,
          from: String,
          media_name: String,
          original_media_url: String,
          status: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status,
          to: String,
          user_id: String
        }

      class Payload < Telnyx::Internal::Type::BaseModel
        attr_reader client_state: String?

        def client_state=: (String) -> String

        attr_reader connection_id: String?

        def connection_id=: (String) -> String

        attr_reader direction: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction?

        def direction=: (
          Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction
        ) -> Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction

        attr_reader fax_id: String?

        def fax_id=: (String) -> String

        attr_reader from: String?

        def from=: (String) -> String

        attr_reader media_name: String?

        def media_name=: (String) -> String

        attr_reader original_media_url: String?

        def original_media_url=: (String) -> String

        attr_reader status: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status?

        def status=: (
          Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status
        ) -> Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status

        attr_reader to: String?

        def to=: (String) -> String

        attr_reader user_id: String?

        def user_id=: (String) -> String

        def initialize: (
          ?client_state: String,
          ?connection_id: String,
          ?direction: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction,
          ?fax_id: String,
          ?from: String,
          ?media_name: String,
          ?original_media_url: String,
          ?status: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status,
          ?to: String,
          ?user_id: String
        ) -> void

        def to_hash: -> {
          client_state: String,
          connection_id: String,
          direction: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction,
          fax_id: String,
          from: String,
          media_name: String,
          original_media_url: String,
          status: Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status,
          to: String,
          user_id: String
        }

        type direction = :inbound | :outbound

        module Direction
          extend Telnyx::Internal::Type::Enum

          INBOUND: :inbound
          OUTBOUND: :outbound

          def self?.values: -> ::Array[Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::direction]
        end

        type status = :sending

        module Status
          extend Telnyx::Internal::Type::Enum

          SENDING: :sending

          def self?.values: -> ::Array[Telnyx::Models::FaxSendingStartedWebhookEvent::Payload::status]
        end
      end

      type record_type = :event

      module RecordType
        extend Telnyx::Internal::Type::Enum

        EVENT: :event

        def self?.values: -> ::Array[Telnyx::Models::FaxSendingStartedWebhookEvent::record_type]
      end
    end
  end
end
