module Telnyx
  module Models
    type fqdn_list_response =
      { data: ::Array[Telnyx::Fqdn], meta: Telnyx::ConnectionsPaginationMeta }

    class FqdnListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::Fqdn]?

      def data=: (::Array[Telnyx::Fqdn]) -> ::Array[Telnyx::Fqdn]

      attr_reader meta: Telnyx::ConnectionsPaginationMeta?

      def meta=: (
        Telnyx::ConnectionsPaginationMeta
      ) -> Telnyx::ConnectionsPaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::Fqdn],
        ?meta: Telnyx::ConnectionsPaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Fqdn],
        meta: Telnyx::ConnectionsPaginationMeta
      }
    end
  end
end
