module Telnyx
  module Models
    type fqdn_create_response = { data: Telnyx::Fqdn }

    class FqdnCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Fqdn?

      def data=: (Telnyx::Fqdn) -> Telnyx::Fqdn

      def initialize: (?data: Telnyx::Fqdn) -> void

      def to_hash: -> { data: Telnyx::Fqdn }
    end
  end
end
