module Telnyx
  module Models
    type global_ip_health_check_delete_response =
      { data: Telnyx::GlobalIPHealthCheck }

    class GlobalIPHealthCheckDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::GlobalIPHealthCheck?

      def data=: (Telnyx::GlobalIPHealthCheck) -> Telnyx::GlobalIPHealthCheck

      def initialize: (?data: Telnyx::GlobalIPHealthCheck) -> void

      def to_hash: -> { data: Telnyx::GlobalIPHealthCheck }
    end
  end
end
