module Telnyx
  module Models
    type global_ip_health_check_list_response =
      {
        global_ip_id: String,
        health_check_params: ::Hash[Symbol, top],
        health_check_type: String
      }

    class GlobalIPHealthCheckListResponse < Telnyx::Models::Record
      def global_ip_id: -> String?

      def global_ip_id=: (String _) -> String

      def health_check_params: -> ::Hash[Symbol, top]?

      def health_check_params=: (::Hash[Symbol, top] _) -> ::Hash[Symbol, top]

      def health_check_type: -> String?

      def health_check_type=: (String _) -> String

      def initialize: (
        ?global_ip_id: String,
        ?health_check_params: ::Hash[Symbol, top],
        ?health_check_type: String
      ) -> void

      def to_hash: -> {
        global_ip_id: String,
        health_check_params: ::Hash[Symbol, top],
        health_check_type: String
      }
    end
  end
end
