module Telnyx
  module Models
    type inbound_message_webhook_event = { data: Telnyx::InboundMessage }

    class InboundMessageWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::InboundMessage?

      def data=: (Telnyx::InboundMessage) -> Telnyx::InboundMessage

      def initialize: (?data: Telnyx::InboundMessage) -> void

      def to_hash: -> { data: Telnyx::InboundMessage }
    end
  end
end
