module Telnyx
  module Models
    type integration_secret_list_response =
      {
        data: ::Array[Telnyx::IntegrationSecret],
        meta: Telnyx::Models::IntegrationSecretListResponse::Meta
      }

    class IntegrationSecretListResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::IntegrationSecret]

      attr_accessor meta: Telnyx::Models::IntegrationSecretListResponse::Meta

      def initialize: (
        data: ::Array[Telnyx::IntegrationSecret],
        meta: Telnyx::Models::IntegrationSecretListResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::IntegrationSecret],
        meta: Telnyx::Models::IntegrationSecretListResponse::Meta
      }

      type meta =
        {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_accessor page_number: Integer

        attr_accessor page_size: Integer

        attr_accessor total_pages: Integer

        attr_accessor total_results: Integer

        def initialize: (
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        ) -> void

        def to_hash: -> {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }
      end
    end
  end
end
