module Telnyx
  module Models
    type invoice_list_response =
      {
        file_id: String,
        invoice_id: String,
        paid: bool,
        period_end: Date,
        period_start: Date,
        url: String
      }

    class InvoiceListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader invoice_id: String?

      def invoice_id=: (String) -> String

      attr_reader paid: bool?

      def paid=: (bool) -> bool

      attr_reader period_end: Date?

      def period_end=: (Date) -> Date

      attr_reader period_start: Date?

      def period_start=: (Date) -> Date

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        ?file_id: String,
        ?invoice_id: String,
        ?paid: bool,
        ?period_end: Date,
        ?period_start: Date,
        ?url: String
      ) -> void

      def to_hash: -> {
        file_id: String,
        invoice_id: String,
        paid: bool,
        period_end: Date,
        period_start: Date,
        url: String
      }
    end
  end
end
