module Telnyx
  module Models
    type inworld_voice_settings =
      { type: Telnyx::Models::InworldVoiceSettings::type_ }

    class InworldVoiceSettings < Telnyx::Internal::Type::BaseModel
      attr_accessor type: Telnyx::Models::InworldVoiceSettings::type_

      def initialize: (
        type: Telnyx::Models::InworldVoiceSettings::type_
      ) -> void

      def to_hash: -> { type: Telnyx::Models::InworldVoiceSettings::type_ }

      type type_ = :inworld

      module Type
        extend Telnyx::Internal::Type::Enum

        INWORLD: :inworld

        def self?.values: -> ::Array[Telnyx::Models::InworldVoiceSettings::type_]
      end
    end
  end
end
