module Telnyx
  module Models
    type ledger_billing_group_report_create_response =
      { data: Telnyx::LedgerBillingGroupReport }

    class LedgerBillingGroupReportCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::LedgerBillingGroupReport?

      def data=: (
        Telnyx::LedgerBillingGroupReport
      ) -> Telnyx::LedgerBillingGroupReport

      def initialize: (?data: Telnyx::LedgerBillingGroupReport) -> void

      def to_hash: -> { data: Telnyx::LedgerBillingGroupReport }
    end
  end
end
