module Telnyx
  module Models
    type message_send_short_code_response =
      { data: Telnyx::MessagingOutboundMessagePayload }

    class MessageSendShortCodeResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::MessagingOutboundMessagePayload?

      def data=: (
        Telnyx::MessagingOutboundMessagePayload
      ) -> Telnyx::MessagingOutboundMessagePayload

      def initialize: (?data: Telnyx::MessagingOutboundMessagePayload) -> void

      def to_hash: -> { data: Telnyx::MessagingOutboundMessagePayload }
    end
  end
end
