module Telnyx
  module Models
    type message_send_short_code_params =
      {
        from: String,
        to: String,
        auto_detect: bool,
        encoding: Telnyx::Models::MessageSendShortCodeParams::encoding,
        media_urls: ::Array[String],
        subject: String,
        text: String,
        type: Telnyx::Models::MessageSendShortCodeParams::type_,
        use_profile_webhooks: bool,
        webhook_failover_url: String,
        webhook_url: String
      }
      & Telnyx::Internal::Type::request_parameters

    class MessageSendShortCodeParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor from: String

      attr_accessor to: String

      attr_reader auto_detect: bool?

      def auto_detect=: (bool) -> bool

      attr_reader encoding: Telnyx::Models::MessageSendShortCodeParams::encoding?

      def encoding=: (
        Telnyx::Models::MessageSendShortCodeParams::encoding
      ) -> Telnyx::Models::MessageSendShortCodeParams::encoding

      attr_reader media_urls: ::Array[String]?

      def media_urls=: (::Array[String]) -> ::Array[String]

      attr_reader subject: String?

      def subject=: (String) -> String

      attr_reader text: String?

      def text=: (String) -> String

      attr_reader type: Telnyx::Models::MessageSendShortCodeParams::type_?

      def type=: (
        Telnyx::Models::MessageSendShortCodeParams::type_
      ) -> Telnyx::Models::MessageSendShortCodeParams::type_

      attr_reader use_profile_webhooks: bool?

      def use_profile_webhooks=: (bool) -> bool

      attr_reader webhook_failover_url: String?

      def webhook_failover_url=: (String) -> String

      attr_reader webhook_url: String?

      def webhook_url=: (String) -> String

      def initialize: (
        from: String,
        to: String,
        ?auto_detect: bool,
        ?encoding: Telnyx::Models::MessageSendShortCodeParams::encoding,
        ?media_urls: ::Array[String],
        ?subject: String,
        ?text: String,
        ?type: Telnyx::Models::MessageSendShortCodeParams::type_,
        ?use_profile_webhooks: bool,
        ?webhook_failover_url: String,
        ?webhook_url: String,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        from: String,
        to: String,
        auto_detect: bool,
        encoding: Telnyx::Models::MessageSendShortCodeParams::encoding,
        media_urls: ::Array[String],
        subject: String,
        text: String,
        type: Telnyx::Models::MessageSendShortCodeParams::type_,
        use_profile_webhooks: bool,
        webhook_failover_url: String,
        webhook_url: String,
        request_options: Telnyx::RequestOptions
      }

      type encoding = :auto | :gsm7 | :ucs2

      module Encoding
        extend Telnyx::Internal::Type::Enum

        AUTO: :auto
        GSM7: :gsm7
        UCS2: :ucs2

        def self?.values: -> ::Array[Telnyx::Models::MessageSendShortCodeParams::encoding]
      end

      type type_ = :SMS | :MMS

      module Type
        extend Telnyx::Internal::Type::Enum

        SMS: :SMS
        MMS: :MMS

        def self?.values: -> ::Array[Telnyx::Models::MessageSendShortCodeParams::type_]
      end
    end
  end
end
