module Telnyx
  module Models
    type messaging_hosted_number_order_list_response =
      {
        data: ::Array[Telnyx::MessagingHostedNumberOrder],
        meta: Telnyx::PaginationMeta
      }

    class MessagingHostedNumberOrderListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::MessagingHostedNumberOrder]?

      def data=: (
        ::Array[Telnyx::MessagingHostedNumberOrder]
      ) -> ::Array[Telnyx::MessagingHostedNumberOrder]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::MessagingHostedNumberOrder],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::MessagingHostedNumberOrder],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
