module Telnyx
  module Models
    type message_retrieve_group_messages_response =
      { data: ::Array[Telnyx::MessagingOutboundMessagePayload] }

    class MessageRetrieveGroupMessagesResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::MessagingOutboundMessagePayload]?

      def data=: (
        ::Array[Telnyx::MessagingOutboundMessagePayload]
      ) -> ::Array[Telnyx::MessagingOutboundMessagePayload]

      def initialize: (
        ?data: ::Array[Telnyx::MessagingOutboundMessagePayload]
      ) -> void

      def to_hash: -> { data: ::Array[Telnyx::MessagingOutboundMessagePayload] }
    end
  end
end
