module Telnyx
  module Models
    type messaging_optout_list_response =
      {
        data: ::Array[Telnyx::Models::MessagingOptoutListResponse::Data],
        meta: Telnyx::Models::MessagingOptoutListResponse::Meta
      }

    class MessagingOptoutListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::Models::MessagingOptoutListResponse::Data]?

      def data=: (
        ::Array[Telnyx::Models::MessagingOptoutListResponse::Data]
      ) -> ::Array[Telnyx::Models::MessagingOptoutListResponse::Data]

      attr_reader meta: Telnyx::Models::MessagingOptoutListResponse::Meta?

      def meta=: (
        Telnyx::Models::MessagingOptoutListResponse::Meta
      ) -> Telnyx::Models::MessagingOptoutListResponse::Meta

      def initialize: (
        ?data: ::Array[Telnyx::Models::MessagingOptoutListResponse::Data],
        ?meta: Telnyx::Models::MessagingOptoutListResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Models::MessagingOptoutListResponse::Data],
        meta: Telnyx::Models::MessagingOptoutListResponse::Meta
      }

      type data =
        {
          created_at: Time,
          from: String,
          keyword: String?,
          messaging_profile_id: String?,
          to: String
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader from: String?

        def from=: (String) -> String

        attr_accessor keyword: String?

        attr_accessor messaging_profile_id: String?

        attr_reader to: String?

        def to=: (String) -> String

        def initialize: (
          ?created_at: Time,
          ?from: String,
          ?keyword: String?,
          ?messaging_profile_id: String?,
          ?to: String
        ) -> void

        def to_hash: -> {
          created_at: Time,
          from: String,
          keyword: String?,
          messaging_profile_id: String?,
          to: String
        }
      end

      type meta =
        {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_accessor page_number: Integer

        attr_accessor page_size: Integer

        attr_accessor total_pages: Integer

        attr_accessor total_results: Integer

        def initialize: (
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        ) -> void

        def to_hash: -> {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }
      end
    end
  end
end
