module Telnyx
  module Models
    type netapps_location =
      { code: String, name: String, pop: String, region: String, site: String }

    class NetappsLocation < Telnyx::Internal::Type::BaseModel
      attr_reader code: String?

      def code=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader pop: String?

      def pop=: (String) -> String

      attr_reader region: String?

      def region=: (String) -> String

      attr_reader site: String?

      def site=: (String) -> String

      def initialize: (
        ?code: String,
        ?name: String,
        ?pop: String,
        ?region: String,
        ?site: String
      ) -> void

      def to_hash: -> {
        code: String,
        name: String,
        pop: String,
        region: String,
        site: String
      }
    end
  end
end
