module Telnyx
  module Models
    type network_list_interfaces_response = {  }

    class NetworkListInterfacesResponse < Telnyx::Models::Record
      def initialize: -> void

      def to_hash: -> {  }
    end
  end
end
