module Telnyx
  module Models
    type network_create = { name: String }

    class NetworkCreate < Telnyx::Models::Record
      def name: -> String

      def name=: (String _) -> String

      def initialize: (name: String) -> void

      def to_hash: -> { name: String }
    end
  end
end
