module Telnyx
  module Models
    type network_list_response = { name: String }

    class NetworkListResponse < Telnyx::Models::Record
      def name: -> String?

      def name=: (String _) -> String

      def initialize: (?name: String) -> void

      def to_hash: -> { name: String }
    end
  end
end
