module Telnyx
  module Models
    type network_interface_region = { region_code: String }

    class NetworkInterfaceRegion < Telnyx::Internal::Type::BaseModel
      attr_reader region_code: String?

      def region_code=: (String) -> String

      def initialize: (?region_code: String) -> void

      def to_hash: -> { region_code: String }
    end
  end
end
