module Telnyx
  module Models
    type network_update_response =
      { data: Telnyx::Models::NetworkUpdateResponse::Data }

    class NetworkUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::NetworkUpdateResponse::Data?

      def data=: (
        Telnyx::Models::NetworkUpdateResponse::Data
      ) -> Telnyx::Models::NetworkUpdateResponse::Data

      def initialize: (
        ?data: Telnyx::Models::NetworkUpdateResponse::Data
      ) -> void

      def to_hash: -> { data: Telnyx::Models::NetworkUpdateResponse::Data }

      type data = { name: String, record_type: String }

      class Data < Telnyx::Models::Record
        def name: -> String?

        def name=: (String _) -> String

        def record_type: -> String?

        def record_type=: (String _) -> String

        def initialize: (?name: String, ?record_type: String) -> void

        def to_hash: -> { name: String, record_type: String }
      end
    end
  end
end
