module Telnyx
  module Models
    type network_create_response = { data: Telnyx::Network }

    class NetworkCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Network?

      def data=: (Telnyx::Network) -> Telnyx::Network

      def initialize: (?data: Telnyx::Network) -> void

      def to_hash: -> { data: Telnyx::Network }
    end
  end
end
