module Telnyx
  module Models
    type network_list_params =
      {
        filter: Telnyx::NetworkListParams::Filter,
        page: Telnyx::NetworkListParams::Page
      }
      & Telnyx::Internal::Type::request_parameters

    class NetworkListParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_reader filter: Telnyx::NetworkListParams::Filter?

      def filter=: (
        Telnyx::NetworkListParams::Filter
      ) -> Telnyx::NetworkListParams::Filter

      attr_reader page: Telnyx::NetworkListParams::Page?

      def page=: (
        Telnyx::NetworkListParams::Page
      ) -> Telnyx::NetworkListParams::Page

      def initialize: (
        ?filter: Telnyx::NetworkListParams::Filter,
        ?page: Telnyx::NetworkListParams::Page,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        filter: Telnyx::NetworkListParams::Filter,
        page: Telnyx::NetworkListParams::Page,
        request_options: Telnyx::RequestOptions
      }

      type filter = { name: String }

      class Filter < Telnyx::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?name: String) -> void

        def to_hash: -> { name: String }
      end

      type page = { number: Integer, size: Integer }

      class Page < Telnyx::Internal::Type::BaseModel
        attr_reader number: Integer?

        def number=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        def initialize: (?number: Integer, ?size: Integer) -> void

        def to_hash: -> { number: Integer, size: Integer }
      end
    end
  end
end
