module Telnyx
  module Models
    type notification_setting_create_response =
      { data: Telnyx::NotificationSetting }

    class NotificationSettingCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::NotificationSetting?

      def data=: (Telnyx::NotificationSetting) -> Telnyx::NotificationSetting

      def initialize: (?data: Telnyx::NotificationSetting) -> void

      def to_hash: -> { data: Telnyx::NotificationSetting }
    end
  end
end
