module Telnyx
  module Models
    type notification_channel_delete_response =
      { data: Telnyx::NotificationChannel }

    class NotificationChannelDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::NotificationChannel?

      def data=: (Telnyx::NotificationChannel) -> Telnyx::NotificationChannel

      def initialize: (?data: Telnyx::NotificationChannel) -> void

      def to_hash: -> { data: Telnyx::NotificationChannel }
    end
  end
end
