module Telnyx
  module Models
    type notification_profile_create_response =
      { data: Telnyx::NotificationProfile }

    class NotificationProfileCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::NotificationProfile?

      def data=: (Telnyx::NotificationProfile) -> Telnyx::NotificationProfile

      def initialize: (?data: Telnyx::NotificationProfile) -> void

      def to_hash: -> { data: Telnyx::NotificationProfile }
    end
  end
end
