module Telnyx
  module Models
    type notification_channel_list_response =
      {
        data: ::Array[Telnyx::NotificationChannel],
        meta: Telnyx::PaginationMeta
      }

    class NotificationChannelListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::NotificationChannel]?

      def data=: (
        ::Array[Telnyx::NotificationChannel]
      ) -> ::Array[Telnyx::NotificationChannel]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::NotificationChannel],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::NotificationChannel],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
