module Telnyx
  module Models
    type number_block_order_list_response =
      { data: ::Array[Telnyx::NumberBlockOrder], meta: Telnyx::PaginationMeta }

    class NumberBlockOrderListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::NumberBlockOrder]?

      def data=: (
        ::Array[Telnyx::NumberBlockOrder]
      ) -> ::Array[Telnyx::NumberBlockOrder]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::NumberBlockOrder],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::NumberBlockOrder],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
