module Telnyx
  module Models
    type number_block_order_list_params =
      {
        filter: Telnyx::NumberBlockOrderListParams::Filter,
        page_number: Integer,
        page_size: Integer
      }
      & Telnyx::Internal::Type::request_parameters

    class NumberBlockOrderListParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_reader filter: Telnyx::NumberBlockOrderListParams::Filter?

      def filter=: (
        Telnyx::NumberBlockOrderListParams::Filter
      ) -> Telnyx::NumberBlockOrderListParams::Filter

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      def initialize: (
        ?filter: Telnyx::NumberBlockOrderListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        filter: Telnyx::NumberBlockOrderListParams::Filter,
        page_number: Integer,
        page_size: Integer,
        request_options: Telnyx::RequestOptions
      }

      type filter =
        {
          created_at: Telnyx::NumberBlockOrderListParams::Filter::CreatedAt,
          phone_numbers_starting_number: String,
          status: String
        }

      class Filter < Telnyx::Internal::Type::BaseModel
        attr_reader created_at: Telnyx::NumberBlockOrderListParams::Filter::CreatedAt?

        def created_at=: (
          Telnyx::NumberBlockOrderListParams::Filter::CreatedAt
        ) -> Telnyx::NumberBlockOrderListParams::Filter::CreatedAt

        attr_reader phone_numbers_starting_number: String?

        def phone_numbers_starting_number=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        def initialize: (
          ?created_at: Telnyx::NumberBlockOrderListParams::Filter::CreatedAt,
          ?phone_numbers_starting_number: String,
          ?status: String
        ) -> void

        def to_hash: -> {
          created_at: Telnyx::NumberBlockOrderListParams::Filter::CreatedAt,
          phone_numbers_starting_number: String,
          status: String
        }

        type created_at = { gt: String, lt: String }

        class CreatedAt < Telnyx::Internal::Type::BaseModel
          attr_reader gt: String?

          def gt=: (String) -> String

          attr_reader lt: String?

          def lt=: (String) -> String

          def initialize: (?gt: String, ?lt: String) -> void

          def to_hash: -> { gt: String, lt: String }
        end
      end
    end
  end
end
