module Telnyx
  module Models
    type oauth_client_retrieve_response = { data: Telnyx::OAuthClient }

    class OAuthClientRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::OAuthClient?

      def data=: (Telnyx::OAuthClient) -> Telnyx::OAuthClient

      def initialize: (?data: Telnyx::OAuthClient) -> void

      def to_hash: -> { data: Telnyx::OAuthClient }
    end
  end
end
