module Telnyx
  module Models
    type oauth_grant_delete_response = { data: Telnyx::OAuthGrant }

    class OAuthGrantDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::OAuthGrant?

      def data=: (Telnyx::OAuthGrant) -> Telnyx::OAuthGrant

      def initialize: (?data: Telnyx::OAuthGrant) -> void

      def to_hash: -> { data: Telnyx::OAuthGrant }
    end
  end
end
