module Telnyx
  module Models
    type outbound_fqdn =
      {
        ani_override: String,
        ani_override_type: Telnyx::Models::OutboundFqdn::ani_override_type,
        call_parking_enabled: bool?,
        channel_limit: Integer,
        encrypted_media: Telnyx::Models::encrypted_media?,
        generate_ringback_tone: bool,
        instant_ringback_enabled: bool,
        ip_authentication_method: Telnyx::Models::OutboundFqdn::ip_authentication_method,
        ip_authentication_token: String,
        localization: String,
        outbound_voice_profile_id: String,
        :t38_reinvite_source => Telnyx::Models::OutboundFqdn::t38_reinvite_source,
        tech_prefix: String,
        :timeout_1xx_secs => Integer,
        :timeout_2xx_secs => Integer
      }

    class OutboundFqdn < Telnyx::Internal::Type::BaseModel
      attr_reader ani_override: String?

      def ani_override=: (String) -> String

      attr_reader ani_override_type: Telnyx::Models::OutboundFqdn::ani_override_type?

      def ani_override_type=: (
        Telnyx::Models::OutboundFqdn::ani_override_type
      ) -> Telnyx::Models::OutboundFqdn::ani_override_type

      attr_accessor call_parking_enabled: bool?

      attr_reader channel_limit: Integer?

      def channel_limit=: (Integer) -> Integer

      attr_accessor encrypted_media: Telnyx::Models::encrypted_media?

      attr_reader generate_ringback_tone: bool?

      def generate_ringback_tone=: (bool) -> bool

      attr_reader instant_ringback_enabled: bool?

      def instant_ringback_enabled=: (bool) -> bool

      attr_reader ip_authentication_method: Telnyx::Models::OutboundFqdn::ip_authentication_method?

      def ip_authentication_method=: (
        Telnyx::Models::OutboundFqdn::ip_authentication_method
      ) -> Telnyx::Models::OutboundFqdn::ip_authentication_method

      attr_reader ip_authentication_token: String?

      def ip_authentication_token=: (String) -> String

      attr_reader localization: String?

      def localization=: (String) -> String

      attr_reader outbound_voice_profile_id: String?

      def outbound_voice_profile_id=: (String) -> String

      attr_reader t38_reinvite_source: Telnyx::Models::OutboundFqdn::t38_reinvite_source?

      def t38_reinvite_source=: (
        Telnyx::Models::OutboundFqdn::t38_reinvite_source
      ) -> Telnyx::Models::OutboundFqdn::t38_reinvite_source

      attr_reader tech_prefix: String?

      def tech_prefix=: (String) -> String

      attr_reader timeout_1xx_secs: Integer?

      def timeout_1xx_secs=: (Integer) -> Integer

      attr_reader timeout_2xx_secs: Integer?

      def timeout_2xx_secs=: (Integer) -> Integer

      def initialize: (
        ?ani_override: String,
        ?ani_override_type: Telnyx::Models::OutboundFqdn::ani_override_type,
        ?call_parking_enabled: bool?,
        ?channel_limit: Integer,
        ?encrypted_media: Telnyx::Models::encrypted_media?,
        ?generate_ringback_tone: bool,
        ?instant_ringback_enabled: bool,
        ?ip_authentication_method: Telnyx::Models::OutboundFqdn::ip_authentication_method,
        ?ip_authentication_token: String,
        ?localization: String,
        ?outbound_voice_profile_id: String,
        ?t38_reinvite_source: Telnyx::Models::OutboundFqdn::t38_reinvite_source,
        ?tech_prefix: String,
        ?timeout_1xx_secs: Integer,
        ?timeout_2xx_secs: Integer
      ) -> void

      def to_hash: -> {
        ani_override: String,
        ani_override_type: Telnyx::Models::OutboundFqdn::ani_override_type,
        call_parking_enabled: bool?,
        channel_limit: Integer,
        encrypted_media: Telnyx::Models::encrypted_media?,
        generate_ringback_tone: bool,
        instant_ringback_enabled: bool,
        ip_authentication_method: Telnyx::Models::OutboundFqdn::ip_authentication_method,
        ip_authentication_token: String,
        localization: String,
        outbound_voice_profile_id: String,
        :t38_reinvite_source => Telnyx::Models::OutboundFqdn::t38_reinvite_source,
        tech_prefix: String,
        :timeout_1xx_secs => Integer,
        :timeout_2xx_secs => Integer
      }

      type ani_override_type = :always | :normal | :emergency

      module AniOverrideType
        extend Telnyx::Internal::Type::Enum

        ALWAYS: :always
        NORMAL: :normal
        EMERGENCY: :emergency

        def self?.values: -> ::Array[Telnyx::Models::OutboundFqdn::ani_override_type]
      end

      type ip_authentication_method =
        :"credential-authentication" | :"ip-authentication"

      module IPAuthenticationMethod
        extend Telnyx::Internal::Type::Enum

        CREDENTIAL_AUTHENTICATION: :"credential-authentication"
        IP_AUTHENTICATION: :"ip-authentication"

        def self?.values: -> ::Array[Telnyx::Models::OutboundFqdn::ip_authentication_method]
      end

      type t38_reinvite_source =
        :telnyx
        | :customer
        | :disabled
        | :passthru
        | :"caller-passthru"
        | :"callee-passthru"

      module T38ReinviteSource
        extend Telnyx::Internal::Type::Enum

        TELNYX: :telnyx
        CUSTOMER: :customer
        DISABLED: :disabled
        PASSTHRU: :passthru
        CALLER_PASSTHRU: :"caller-passthru"
        CALLEE_PASSTHRU: :"callee-passthru"

        def self?.values: -> ::Array[Telnyx::Models::OutboundFqdn::t38_reinvite_source]
      end
    end
  end
end
