module Telnyx
  module Models
    type outbound_voice_profile_retrieve_response =
      { data: Telnyx::OutboundVoiceProfile }

    class OutboundVoiceProfileRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::OutboundVoiceProfile?

      def data=: (Telnyx::OutboundVoiceProfile) -> Telnyx::OutboundVoiceProfile

      def initialize: (?data: Telnyx::OutboundVoiceProfile) -> void

      def to_hash: -> { data: Telnyx::OutboundVoiceProfile }
    end
  end
end
