module Telnyx
  module Models
    type outbound_voice_profile_list_response =
      {
        data: ::Array[Telnyx::OutboundVoiceProfile],
        meta: Telnyx::PaginationMeta
      }

    class OutboundVoiceProfileListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::OutboundVoiceProfile]?

      def data=: (
        ::Array[Telnyx::OutboundVoiceProfile]
      ) -> ::Array[Telnyx::OutboundVoiceProfile]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::OutboundVoiceProfile],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::OutboundVoiceProfile],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
