module Telnyx
  module Models
    type outbound_message =
      {
        id: String,
        event_type: Telnyx::Models::OutboundMessage::event_type,
        occurred_at: Time,
        payload: Telnyx::OutboundMessagePayload,
        record_type: Telnyx::Models::OutboundMessage::record_type
      }

    class OutboundMessage < Telnyx::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader event_type: Telnyx::Models::OutboundMessage::event_type?

      def event_type=: (
        Telnyx::Models::OutboundMessage::event_type
      ) -> Telnyx::Models::OutboundMessage::event_type

      attr_reader occurred_at: Time?

      def occurred_at=: (Time) -> Time

      attr_reader payload: Telnyx::OutboundMessagePayload?

      def payload=: (
        Telnyx::OutboundMessagePayload
      ) -> Telnyx::OutboundMessagePayload

      attr_reader record_type: Telnyx::Models::OutboundMessage::record_type?

      def record_type=: (
        Telnyx::Models::OutboundMessage::record_type
      ) -> Telnyx::Models::OutboundMessage::record_type

      def initialize: (
        ?id: String,
        ?event_type: Telnyx::Models::OutboundMessage::event_type,
        ?occurred_at: Time,
        ?payload: Telnyx::OutboundMessagePayload,
        ?record_type: Telnyx::Models::OutboundMessage::record_type
      ) -> void

      def to_hash: -> {
        id: String,
        event_type: Telnyx::Models::OutboundMessage::event_type,
        occurred_at: Time,
        payload: Telnyx::OutboundMessagePayload,
        record_type: Telnyx::Models::OutboundMessage::record_type
      }

      type event_type = :"message.sent" | :"message.finalized"

      module EventType
        extend Telnyx::Internal::Type::Enum

        MESSAGE_SENT: :"message.sent"
        MESSAGE_FINALIZED: :"message.finalized"

        def self?.values: -> ::Array[Telnyx::Models::OutboundMessage::event_type]
      end

      type record_type = :event

      module RecordType
        extend Telnyx::Internal::Type::Enum

        EVENT: :event

        def self?.values: -> ::Array[Telnyx::Models::OutboundMessage::record_type]
      end
    end
  end
end
