module Telnyx
  module Models
    type partner_campaign_retrieve_sharing_status_response =
      ::Hash[Symbol, Telnyx::Number10dlc::CampaignSharingStatus]

    PartnerCampaignRetrieveSharingStatusResponse: Telnyx::Internal::Type::Converter
  end
end
