module Telnyx
  module Models
    type phone_number_list_response =
      {
        data: ::Array[Telnyx::PhoneNumberDetailed],
        meta: Telnyx::PaginationMeta
      }

    class PhoneNumberListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::PhoneNumberDetailed]?

      def data=: (
        ::Array[Telnyx::PhoneNumberDetailed]
      ) -> ::Array[Telnyx::PhoneNumberDetailed]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::PhoneNumberDetailed],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::PhoneNumberDetailed],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
