module Telnyx
  module Models
    type porting_order_end_user_admin =
      {
        account_number: String?,
        auth_person_name: String?,
        billing_phone_number: String?,
        business_identifier: String?,
        entity_name: String?,
        pin_passcode: String?,
        tax_identifier: String?
      }

    class PortingOrderEndUserAdmin < Telnyx::Internal::Type::BaseModel
      attr_accessor account_number: String?

      attr_accessor auth_person_name: String?

      attr_accessor billing_phone_number: String?

      attr_accessor business_identifier: String?

      attr_accessor entity_name: String?

      attr_accessor pin_passcode: String?

      attr_accessor tax_identifier: String?

      def initialize: (
        ?account_number: String?,
        ?auth_person_name: String?,
        ?billing_phone_number: String?,
        ?business_identifier: String?,
        ?entity_name: String?,
        ?pin_passcode: String?,
        ?tax_identifier: String?
      ) -> void

      def to_hash: -> {
        account_number: String?,
        auth_person_name: String?,
        billing_phone_number: String?,
        business_identifier: String?,
        entity_name: String?,
        pin_passcode: String?,
        tax_identifier: String?
      }
    end
  end
end
