module Telnyx
  module Models
    type porting_order_update_response =
      {
        data: Telnyx::PortingOrder,
        meta: Telnyx::Models::PortingOrderUpdateResponse::Meta
      }

    class PortingOrderUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::PortingOrder?

      def data=: (Telnyx::PortingOrder) -> Telnyx::PortingOrder

      attr_reader meta: Telnyx::Models::PortingOrderUpdateResponse::Meta?

      def meta=: (
        Telnyx::Models::PortingOrderUpdateResponse::Meta
      ) -> Telnyx::Models::PortingOrderUpdateResponse::Meta

      def initialize: (
        ?data: Telnyx::PortingOrder,
        ?meta: Telnyx::Models::PortingOrderUpdateResponse::Meta
      ) -> void

      def to_hash: -> {
        data: Telnyx::PortingOrder,
        meta: Telnyx::Models::PortingOrderUpdateResponse::Meta
      }

      type meta = { phone_numbers_url: String }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_reader phone_numbers_url: String?

        def phone_numbers_url=: (String) -> String

        def initialize: (?phone_numbers_url: String) -> void

        def to_hash: -> { phone_numbers_url: String }
      end
    end
  end
end
