module Telnyx
  module Models
    type portout_list_response =
      { data: ::Array[Telnyx::PortoutDetails], meta: Telnyx::Metadata }

    class PortoutListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::PortoutDetails]?

      def data=: (
        ::Array[Telnyx::PortoutDetails]
      ) -> ::Array[Telnyx::PortoutDetails]

      attr_reader meta: Telnyx::Metadata?

      def meta=: (Telnyx::Metadata) -> Telnyx::Metadata

      def initialize: (
        ?data: ::Array[Telnyx::PortoutDetails],
        ?meta: Telnyx::Metadata
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::PortoutDetails],
        meta: Telnyx::Metadata
      }
    end
  end
end
