module Telnyx
  module Models
    type porting_order_end_user_location =
      {
        administrative_area: String?,
        country_code: String?,
        extended_address: String?,
        locality: String?,
        postal_code: String?,
        street_address: String?
      }

    class PortingOrderEndUserLocation < Telnyx::Internal::Type::BaseModel
      attr_accessor administrative_area: String?

      attr_accessor country_code: String?

      attr_accessor extended_address: String?

      attr_accessor locality: String?

      attr_accessor postal_code: String?

      attr_accessor street_address: String?

      def initialize: (
        ?administrative_area: String?,
        ?country_code: String?,
        ?extended_address: String?,
        ?locality: String?,
        ?postal_code: String?,
        ?street_address: String?
      ) -> void

      def to_hash: -> {
        administrative_area: String?,
        country_code: String?,
        extended_address: String?,
        locality: String?,
        postal_code: String?,
        street_address: String?
      }
    end
  end
end
