module Telnyx
  module Models
    type porting_order_documents = { invoice: String?, loa: String? }

    class PortingOrderDocuments < Telnyx::Internal::Type::BaseModel
      attr_accessor invoice: String?

      attr_accessor loa: String?

      def initialize: (?invoice: String?, ?loa: String?) -> void

      def to_hash: -> { invoice: String?, loa: String? }
    end
  end
end
