module Telnyx
  module Models
    type private_wireless_gateway_delete_response =
      { data: Telnyx::PrivateWirelessGateway }

    class PrivateWirelessGatewayDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::PrivateWirelessGateway?

      def data=: (
        Telnyx::PrivateWirelessGateway
      ) -> Telnyx::PrivateWirelessGateway

      def initialize: (?data: Telnyx::PrivateWirelessGateway) -> void

      def to_hash: -> { data: Telnyx::PrivateWirelessGateway }
    end
  end
end
