module Telnyx
  module Models
    type public_internet_gateway_delete_response =
      { data: Telnyx::Models::PublicInternetGatewayDeleteResponse::Data }

    class PublicInternetGatewayDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::PublicInternetGatewayDeleteResponse::Data?

      def data=: (
        Telnyx::Models::PublicInternetGatewayDeleteResponse::Data
      ) -> Telnyx::Models::PublicInternetGatewayDeleteResponse::Data

      def initialize: (
        ?data: Telnyx::Models::PublicInternetGatewayDeleteResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::PublicInternetGatewayDeleteResponse::Data
      }
    end
  end
end
