module Telnyx
  module Models
    type public_internet_gateway_list_params =
      {
        filter: Telnyx::PublicInternetGatewayListParams::Filter,
        page: Telnyx::PublicInternetGatewayListParams::Page
      }
      & Telnyx::Internal::Type::request_parameters

    class PublicInternetGatewayListParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_reader filter: Telnyx::PublicInternetGatewayListParams::Filter?

      def filter=: (
        Telnyx::PublicInternetGatewayListParams::Filter
      ) -> Telnyx::PublicInternetGatewayListParams::Filter

      attr_reader page: Telnyx::PublicInternetGatewayListParams::Page?

      def page=: (
        Telnyx::PublicInternetGatewayListParams::Page
      ) -> Telnyx::PublicInternetGatewayListParams::Page

      def initialize: (
        ?filter: Telnyx::PublicInternetGatewayListParams::Filter,
        ?page: Telnyx::PublicInternetGatewayListParams::Page,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        filter: Telnyx::PublicInternetGatewayListParams::Filter,
        page: Telnyx::PublicInternetGatewayListParams::Page,
        request_options: Telnyx::RequestOptions
      }

      type filter = { network_id: String }

      class Filter < Telnyx::Internal::Type::BaseModel
        attr_reader network_id: String?

        def network_id=: (String) -> String

        def initialize: (?network_id: String) -> void

        def to_hash: -> { network_id: String }
      end

      type page = { number: Integer, size: Integer }

      class Page < Telnyx::Internal::Type::BaseModel
        attr_reader number: Integer?

        def number=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        def initialize: (?number: Integer, ?size: Integer) -> void

        def to_hash: -> { number: Integer, size: Integer }
      end
    end
  end
end
