module Telnyx
  module Models
    type push_credential_response = { data: Telnyx::PushCredential }

    class PushCredentialResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::PushCredential?

      def data=: (Telnyx::PushCredential) -> Telnyx::PushCredential

      def initialize: (?data: Telnyx::PushCredential) -> void

      def to_hash: -> { data: Telnyx::PushCredential }
    end
  end
end
