module Telnyx
  module Models
    type queue_retrieve_response = { data: Telnyx::Queue }

    class QueueRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Queue?

      def data=: (Telnyx::Queue) -> Telnyx::Queue

      def initialize: (?data: Telnyx::Queue) -> void

      def to_hash: -> { data: Telnyx::Queue }
    end
  end
end
