module Telnyx
  module Models
    type report_list_wdrs_params =
      {
        id: String,
        end_date: String,
        imsi: String,
        mcc: String,
        mnc: String,
        page: Telnyx::ReportListWdrsParams::Page,
        phone_number: String,
        sim_card_id: String,
        sim_group_id: String,
        sim_group_name: String,
        sort: ::Array[String],
        start_date: String
      }
      & Telnyx::Internal::Type::request_parameters

    class ReportListWdrsParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_reader id: String?

      def id=: (String) -> String

      attr_reader end_date: String?

      def end_date=: (String) -> String

      attr_reader imsi: String?

      def imsi=: (String) -> String

      attr_reader mcc: String?

      def mcc=: (String) -> String

      attr_reader mnc: String?

      def mnc=: (String) -> String

      attr_reader page: Telnyx::ReportListWdrsParams::Page?

      def page=: (
        Telnyx::ReportListWdrsParams::Page
      ) -> Telnyx::ReportListWdrsParams::Page

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      attr_reader sim_card_id: String?

      def sim_card_id=: (String) -> String

      attr_reader sim_group_id: String?

      def sim_group_id=: (String) -> String

      attr_reader sim_group_name: String?

      def sim_group_name=: (String) -> String

      attr_reader sort: ::Array[String]?

      def sort=: (::Array[String]) -> ::Array[String]

      attr_reader start_date: String?

      def start_date=: (String) -> String

      def initialize: (
        ?id: String,
        ?end_date: String,
        ?imsi: String,
        ?mcc: String,
        ?mnc: String,
        ?page: Telnyx::ReportListWdrsParams::Page,
        ?phone_number: String,
        ?sim_card_id: String,
        ?sim_group_id: String,
        ?sim_group_name: String,
        ?sort: ::Array[String],
        ?start_date: String,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        end_date: String,
        imsi: String,
        mcc: String,
        mnc: String,
        page: Telnyx::ReportListWdrsParams::Page,
        phone_number: String,
        sim_card_id: String,
        sim_group_id: String,
        sim_group_name: String,
        sort: ::Array[String],
        start_date: String,
        request_options: Telnyx::RequestOptions
      }

      type page = { number: Integer, size: Integer }

      class Page < Telnyx::Internal::Type::BaseModel
        attr_reader number: Integer?

        def number=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        def initialize: (?number: Integer, ?size: Integer) -> void

        def to_hash: -> { number: Integer, size: Integer }
      end
    end
  end
end
