module Telnyx
  module Models
    type requirement_type_list_response =
      {
        data: ::Array[Telnyx::DocReqsRequirementType],
        meta: Telnyx::PaginationMeta
      }

    class RequirementTypeListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::DocReqsRequirementType]?

      def data=: (
        ::Array[Telnyx::DocReqsRequirementType]
      ) -> ::Array[Telnyx::DocReqsRequirementType]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::DocReqsRequirementType],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::DocReqsRequirementType],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
