module Telnyx
  module Models
    type requirement_type_retrieve_response =
      { data: Telnyx::DocReqsRequirementType }

    class RequirementTypeRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::DocReqsRequirementType?

      def data=: (
        Telnyx::DocReqsRequirementType
      ) -> Telnyx::DocReqsRequirementType

      def initialize: (?data: Telnyx::DocReqsRequirementType) -> void

      def to_hash: -> { data: Telnyx::DocReqsRequirementType }
    end
  end
end
