module Telnyx
  module Models
    type room_create_response = { data: Telnyx::Room }

    class RoomCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Room?

      def data=: (Telnyx::Room) -> Telnyx::Room

      def initialize: (?data: Telnyx::Room) -> void

      def to_hash: -> { data: Telnyx::Room }
    end
  end
end
