module Telnyx
  module Models
    type room_list_response =
      { data: ::Array[Telnyx::Room], meta: Telnyx::PaginationMeta }

    class RoomListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::Room]?

      def data=: (::Array[Telnyx::Room]) -> ::Array[Telnyx::Room]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::Room],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Room],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
