module Telnyx
  module Models
    type room_composition_list_response =
      { data: ::Array[Telnyx::RoomComposition], meta: Telnyx::PaginationMeta }

    class RoomCompositionListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::RoomComposition]?

      def data=: (
        ::Array[Telnyx::RoomComposition]
      ) -> ::Array[Telnyx::RoomComposition]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::RoomComposition],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::RoomComposition],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
