module Telnyx
  module Models
    type s3_configuration_data =
      {
        backend: Telnyx::Models::S3ConfigurationData::backend,
        aws_access_key_id: String,
        aws_secret_access_key: String,
        bucket: String,
        region: String
      }

    class S3ConfigurationData < Telnyx::Internal::Type::BaseModel
      attr_accessor backend: Telnyx::Models::S3ConfigurationData::backend

      attr_reader aws_access_key_id: String?

      def aws_access_key_id=: (String) -> String

      attr_reader aws_secret_access_key: String?

      def aws_secret_access_key=: (String) -> String

      attr_reader bucket: String?

      def bucket=: (String) -> String

      attr_reader region: String?

      def region=: (String) -> String

      def initialize: (
        backend: Telnyx::Models::S3ConfigurationData::backend,
        ?aws_access_key_id: String,
        ?aws_secret_access_key: String,
        ?bucket: String,
        ?region: String
      ) -> void

      def to_hash: -> {
        backend: Telnyx::Models::S3ConfigurationData::backend,
        aws_access_key_id: String,
        aws_secret_access_key: String,
        bucket: String,
        region: String
      }

      type backend = :s3

      module Backend
        extend Telnyx::Internal::Type::Enum

        S3: :s3

        def self?.values: -> ::Array[Telnyx::Models::S3ConfigurationData::backend]
      end
    end
  end
end
