module Telnyx
  module Models
    type short_code_update_response = { data: Telnyx::ShortCode }

    class ShortCodeUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::ShortCode?

      def data=: (Telnyx::ShortCode) -> Telnyx::ShortCode

      def initialize: (?data: Telnyx::ShortCode) -> void

      def to_hash: -> { data: Telnyx::ShortCode }
    end
  end
end
