module Telnyx
  module Models
    type speech_to_text_list_providers_response =
      {
        data: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data],
        meta: Telnyx::Models::SpeechToTextListProvidersResponse::Meta
      }

    class SpeechToTextListProvidersResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data]

      attr_accessor meta: Telnyx::Models::SpeechToTextListProvidersResponse::Meta

      def initialize: (
        data: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data],
        meta: Telnyx::Models::SpeechToTextListProvidersResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data],
        meta: Telnyx::Models::SpeechToTextListProvidersResponse::Meta
      }

      type data =
        {
          model: String,
          provider: String,
          service_types: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType]
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_accessor model: String

        attr_accessor provider: String

        attr_accessor service_types: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType]

        def initialize: (
          model: String,
          provider: String,
          service_types: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType]
        ) -> void

        def to_hash: -> {
          model: String,
          provider: String,
          service_types: ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType]
        }

        type service_type =
          {
            languages: ::Array[String],
            type: Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType::type_
          }

        class ServiceType < Telnyx::Internal::Type::BaseModel
          attr_accessor languages: ::Array[String]

          attr_accessor type: Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType::type_

          def initialize: (
            languages: ::Array[String],
            type: Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType::type_
          ) -> void

          def to_hash: -> {
            languages: ::Array[String],
            type: Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType::type_
          }

          type type_ = :streaming | :file_based | :in_call | :ai_assistant

          module Type
            extend Telnyx::Internal::Type::Enum

            STREAMING: :streaming
            FILE_BASED: :file_based
            IN_CALL: :in_call
            AI_ASSISTANT: :ai_assistant

            def self?.values: -> ::Array[Telnyx::Models::SpeechToTextListProvidersResponse::Data::ServiceType::type_]
          end
        end
      end

      type meta = { total: Integer }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_accessor total: Integer

        def initialize: (total: Integer) -> void

        def to_hash: -> { total: Integer }
      end
    end
  end
end
