module Telnyx
  module Models
    type spend_limit_response = { data: Telnyx::SpendLimit }

    class SpendLimitResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::SpendLimit

      def initialize: (data: Telnyx::SpendLimit) -> void

      def to_hash: -> { data: Telnyx::SpendLimit }
    end
  end
end
