module Telnyx
  module Models
    type streaming_started_webhook_event =
      { data: Telnyx::CallStreamingStarted }

    class StreamingStartedWebhookEvent < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::CallStreamingStarted?

      def data=: (Telnyx::CallStreamingStarted) -> Telnyx::CallStreamingStarted

      def initialize: (?data: Telnyx::CallStreamingStarted) -> void

      def to_hash: -> { data: Telnyx::CallStreamingStarted }
    end
  end
end
