module Telnyx
  module Models
    type sub_number_order_update_response = { data: Telnyx::SubNumberOrder }

    class SubNumberOrderUpdateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::SubNumberOrder?

      def data=: (Telnyx::SubNumberOrder) -> Telnyx::SubNumberOrder

      def initialize: (?data: Telnyx::SubNumberOrder) -> void

      def to_hash: -> { data: Telnyx::SubNumberOrder }
    end
  end
end
