module Telnyx
  module Models
    type terms_of_service_status_response =
      { data: Telnyx::Models::TermsOfServiceStatusResponse::Data }

    class TermsOfServiceStatusResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: Telnyx::Models::TermsOfServiceStatusResponse::Data

      def initialize: (
        data: Telnyx::Models::TermsOfServiceStatusResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::TermsOfServiceStatusResponse::Data
      }

      type data =
        {
          agreement_required: bool,
          current_terms_version: String,
          has_agreed: bool,
          product_type: Telnyx::Models::TermsOfServiceStatusResponse::Data::product_type,
          agreed_at: Time?,
          agreed_version: String?
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_accessor agreement_required: bool

        attr_accessor current_terms_version: String

        attr_accessor has_agreed: bool

        attr_accessor product_type: Telnyx::Models::TermsOfServiceStatusResponse::Data::product_type

        attr_accessor agreed_at: Time?

        attr_accessor agreed_version: String?

        def initialize: (
          agreement_required: bool,
          current_terms_version: String,
          has_agreed: bool,
          product_type: Telnyx::Models::TermsOfServiceStatusResponse::Data::product_type,
          ?agreed_at: Time?,
          ?agreed_version: String?
        ) -> void

        def to_hash: -> {
          agreement_required: bool,
          current_terms_version: String,
          has_agreed: bool,
          product_type: Telnyx::Models::TermsOfServiceStatusResponse::Data::product_type,
          agreed_at: Time?,
          agreed_version: String?
        }

        type product_type = :branded_calling | :number_reputation

        module ProductType
          extend Telnyx::Internal::Type::Enum

          BRANDED_CALLING: :branded_calling
          NUMBER_REPUTATION: :number_reputation

          def self?.values: -> ::Array[Telnyx::Models::TermsOfServiceStatusResponse::Data::product_type]
        end
      end
    end
  end
end
