module Telnyx
  module Models
    type terms_of_service_retrieve_info_response =
      {
        agreements: ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]
      }

    class TermsOfServiceRetrieveInfoResponse < Telnyx::Internal::Type::BaseModel
      attr_reader agreements: ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]?

      def agreements=: (
        ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]
      ) -> ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]

      def initialize: (
        ?agreements: ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]
      ) -> void

      def to_hash: -> {
        agreements: ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement]
      }

      type agreement =
        {
          current_version: String,
          description: String,
          effective_date: Date,
          product_type: Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type,
          terms_url: String
        }

      class Agreement < Telnyx::Internal::Type::BaseModel
        attr_reader current_version: String?

        def current_version=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader effective_date: Date?

        def effective_date=: (Date) -> Date

        attr_reader product_type: Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type?

        def product_type=: (
          Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type
        ) -> Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type

        attr_reader terms_url: String?

        def terms_url=: (String) -> String

        def initialize: (
          ?current_version: String,
          ?description: String,
          ?effective_date: Date,
          ?product_type: Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type,
          ?terms_url: String
        ) -> void

        def to_hash: -> {
          current_version: String,
          description: String,
          effective_date: Date,
          product_type: Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type,
          terms_url: String
        }

        type product_type = :branded_calling | :number_reputation

        module ProductType
          extend Telnyx::Internal::Type::Enum

          BRANDED_CALLING: :branded_calling
          NUMBER_REPUTATION: :number_reputation

          def self?.values: -> ::Array[Telnyx::Models::TermsOfServiceRetrieveInfoResponse::Agreement::product_type]
        end
      end
    end
  end
end
