module Telnyx
  module Models
    type uac_connection_retrieve_response = { data: Telnyx::UacConnection }

    class UacConnectionRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::UacConnection?

      def data=: (Telnyx::UacConnection) -> Telnyx::UacConnection

      def initialize: (?data: Telnyx::UacConnection) -> void

      def to_hash: -> { data: Telnyx::UacConnection }
    end
  end
end
