module Telnyx
  module Models
    type unsafe_unwrap_webhook_event =
      Telnyx::CallAIGatherEndedWebhookEvent
      | Telnyx::CallAIGatherMessageHistoryUpdatedWebhookEvent
      | Telnyx::CallAIGatherPartialResultsWebhookEvent
      | Telnyx::CustomerServiceRecordStatusChangedWebhookEvent
      | Telnyx::CallAnsweredWebhookEvent
      | Telnyx::CallBridgedWebhookEvent
      | Telnyx::CallConversationEndedWebhookEvent
      | Telnyx::CallConversationInsightsGeneratedWebhookEvent
      | Telnyx::CallDtmfReceivedWebhookEvent
      | Telnyx::CallEnqueuedWebhookEvent
      | Telnyx::CallForkStartedWebhookEvent
      | Telnyx::CallForkStoppedWebhookEvent
      | Telnyx::CallGatherEndedWebhookEvent
      | Telnyx::CallHangupWebhookEvent
      | Telnyx::CallInitiatedWebhookEvent
      | Telnyx::CallLeftQueueWebhookEvent
      | Telnyx::CallMachineDetectionEndedWebhookEvent
      | Telnyx::CallMachineGreetingEndedWebhookEvent
      | Telnyx::CallMachinePremiumDetectionEndedWebhookEvent
      | Telnyx::CallMachinePremiumGreetingEndedWebhookEvent
      | Telnyx::CallPlaybackEndedWebhookEvent
      | Telnyx::CallPlaybackStartedWebhookEvent
      | Telnyx::CallRecordingErrorWebhookEvent
      | Telnyx::CallRecordingSavedWebhookEvent
      | Telnyx::CallRecordingTranscriptionSavedWebhookEvent
      | Telnyx::CallReferCompletedWebhookEvent
      | Telnyx::CallReferFailedWebhookEvent
      | Telnyx::CallReferStartedWebhookEvent
      | Telnyx::CallSiprecFailedWebhookEvent
      | Telnyx::CallSiprecStartedWebhookEvent
      | Telnyx::CallSiprecStoppedWebhookEvent
      | Telnyx::CallSpeakEndedWebhookEvent
      | Telnyx::CallSpeakStartedWebhookEvent
      | Telnyx::CallStreamingFailedWebhookEvent
      | Telnyx::CallStreamingStartedWebhookEvent
      | Telnyx::CallStreamingStoppedWebhookEvent
      | Telnyx::UnsafeUnwrapWebhookEvent::CampaignStatusUpdateEvent
      | Telnyx::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent
      | Telnyx::ConferenceCreatedWebhookEvent
      | Telnyx::ConferenceEndedWebhookEvent
      | Telnyx::ConferenceFloorChangedWebhookEvent
      | Telnyx::ConferenceParticipantJoinedWebhookEvent
      | Telnyx::ConferenceParticipantLeftWebhookEvent
      | Telnyx::ConferenceParticipantPlaybackEndedWebhookEvent
      | Telnyx::ConferenceParticipantPlaybackStartedWebhookEvent
      | Telnyx::ConferenceParticipantSpeakEndedWebhookEvent
      | Telnyx::ConferenceParticipantSpeakStartedWebhookEvent
      | Telnyx::ConferencePlaybackEndedWebhookEvent
      | Telnyx::ConferencePlaybackStartedWebhookEvent
      | Telnyx::ConferenceRecordingSavedWebhookEvent
      | Telnyx::ConferenceSpeakEndedWebhookEvent
      | Telnyx::ConferenceSpeakStartedWebhookEvent
      | Telnyx::DeliveryUpdateWebhookEvent
      | Telnyx::FaxDeliveredWebhookEvent
      | Telnyx::FaxFailedWebhookEvent
      | Telnyx::FaxMediaProcessedWebhookEvent
      | Telnyx::FaxQueuedWebhookEvent
      | Telnyx::FaxSendingStartedWebhookEvent
      | Telnyx::InboundMessageWebhookEvent
      | Telnyx::NumberOrderStatusUpdateWebhookEvent
      | Telnyx::ReplacedLinkClickWebhookEvent
      | Telnyx::StreamingFailedWebhookEvent
      | Telnyx::StreamingStartedWebhookEvent
      | Telnyx::StreamingStoppedWebhookEvent
      | Telnyx::TranscriptionWebhookEvent

    module UnsafeUnwrapWebhookEvent
      extend Telnyx::Internal::Type::Union

      type campaign_status_update_event =
        {
          brand_id: String,
          campaign_id: String,
          create_date: String,
          csp_id: String,
          is_t_mobile_registered: bool
        }

      class CampaignStatusUpdateEvent < Telnyx::Internal::Type::BaseModel
        attr_reader brand_id: String?

        def brand_id=: (String) -> String

        attr_reader campaign_id: String?

        def campaign_id=: (String) -> String

        attr_reader create_date: String?

        def create_date=: (String) -> String

        attr_reader csp_id: String?

        def csp_id=: (String) -> String

        attr_reader is_t_mobile_registered: bool?

        def is_t_mobile_registered=: (bool) -> bool

        def initialize: (
          ?brand_id: String,
          ?campaign_id: String,
          ?create_date: String,
          ?csp_id: String,
          ?is_t_mobile_registered: bool
        ) -> void

        def to_hash: -> {
          brand_id: String,
          campaign_id: String,
          create_date: String,
          csp_id: String,
          is_t_mobile_registered: bool
        }
      end

      type campaign_suspended_event =
        {
          campaign_id: String,
          description: String,
          status: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status,
          type: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_
        }

      class CampaignSuspendedEvent < Telnyx::Internal::Type::BaseModel
        attr_reader campaign_id: String?

        def campaign_id=: (String) -> String

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader status: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status?

        def status=: (
          Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status
        ) -> Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status

        attr_reader type: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_?

        def type=: (
          Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_
        ) -> Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_

        def initialize: (
          ?campaign_id: String,
          ?description: String,
          ?status: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status,
          ?type: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_
        ) -> void

        def to_hash: -> {
          campaign_id: String,
          description: String,
          status: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status,
          type: Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_
        }

        type status = :DORMANT

        module Status
          extend Telnyx::Internal::Type::Enum

          DORMANT: :DORMANT

          def self?.values: -> ::Array[Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::status]
        end

        type type_ = :TELNYX_EVENT

        module Type
          extend Telnyx::Internal::Type::Enum

          TELNYX_EVENT: :TELNYX_EVENT

          def self?.values: -> ::Array[Telnyx::Models::UnsafeUnwrapWebhookEvent::CampaignSuspendedEvent::type_]
        end
      end

      def self?.variants: -> ::Array[Telnyx::Models::unsafe_unwrap_webhook_event]
    end
  end
end
