module Telnyx
  module Models
    type user_address_create_response = { data: Telnyx::UserAddress }

    class UserAddressCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::UserAddress?

      def data=: (Telnyx::UserAddress) -> Telnyx::UserAddress

      def initialize: (?data: Telnyx::UserAddress) -> void

      def to_hash: -> { data: Telnyx::UserAddress }
    end
  end
end
