module Telnyx
  module Models
    type verified_number_list_response =
      {
        data: ::Array[Telnyx::VerifiedNumber],
        meta: Telnyx::Models::VerifiedNumberListResponse::Meta
      }

    class VerifiedNumberListResponse < Telnyx::Internal::Type::BaseModel
      attr_accessor data: ::Array[Telnyx::VerifiedNumber]

      attr_accessor meta: Telnyx::Models::VerifiedNumberListResponse::Meta

      def initialize: (
        data: ::Array[Telnyx::VerifiedNumber],
        meta: Telnyx::Models::VerifiedNumberListResponse::Meta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::VerifiedNumber],
        meta: Telnyx::Models::VerifiedNumberListResponse::Meta
      }

      type meta =
        {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }

      class Meta < Telnyx::Internal::Type::BaseModel
        attr_reader page_number: Integer?

        def page_number=: (Integer) -> Integer

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        attr_reader total_pages: Integer?

        def total_pages=: (Integer) -> Integer

        attr_reader total_results: Integer?

        def total_results=: (Integer) -> Integer

        def initialize: (
          ?page_number: Integer,
          ?page_size: Integer,
          ?total_pages: Integer,
          ?total_results: Integer
        ) -> void

        def to_hash: -> {
          page_number: Integer,
          page_size: Integer,
          total_pages: Integer,
          total_results: Integer
        }
      end
    end
  end
end
