module Telnyx
  module Models
    type video_region =
      {
        height: Integer,
        max_columns: Integer,
        max_rows: Integer,
        video_sources: ::Array[String],
        width: Integer,
        x_pos: Integer,
        y_pos: Integer,
        z_pos: Integer
      }

    class VideoRegion < Telnyx::Internal::Type::BaseModel
      attr_reader height: Integer?

      def height=: (Integer) -> Integer

      attr_reader max_columns: Integer?

      def max_columns=: (Integer) -> Integer

      attr_reader max_rows: Integer?

      def max_rows=: (Integer) -> Integer

      attr_reader video_sources: ::Array[String]?

      def video_sources=: (::Array[String]) -> ::Array[String]

      attr_reader width: Integer?

      def width=: (Integer) -> Integer

      attr_reader x_pos: Integer?

      def x_pos=: (Integer) -> Integer

      attr_reader y_pos: Integer?

      def y_pos=: (Integer) -> Integer

      attr_reader z_pos: Integer?

      def z_pos=: (Integer) -> Integer

      def initialize: (
        ?height: Integer,
        ?max_columns: Integer,
        ?max_rows: Integer,
        ?video_sources: ::Array[String],
        ?width: Integer,
        ?x_pos: Integer,
        ?y_pos: Integer,
        ?z_pos: Integer
      ) -> void

      def to_hash: -> {
        height: Integer,
        max_columns: Integer,
        max_rows: Integer,
        video_sources: ::Array[String],
        width: Integer,
        x_pos: Integer,
        y_pos: Integer,
        z_pos: Integer
      }
    end
  end
end
