module Telnyx
  module Models
    type virtual_cross_connects_coverage_list_response =
      {
        available_bandwidth: ::Array[Float],
        cloud_provider: Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider,
        cloud_provider_region: String,
        location: Telnyx::NetappsLocation,
        record_type: String
      }

    class VirtualCrossConnectsCoverageListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader available_bandwidth: ::Array[Float]?

      def available_bandwidth=: (::Array[Float]) -> ::Array[Float]

      attr_reader cloud_provider: Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider?

      def cloud_provider=: (
        Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider
      ) -> Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider

      attr_reader cloud_provider_region: String?

      def cloud_provider_region=: (String) -> String

      attr_reader location: Telnyx::NetappsLocation?

      def location=: (Telnyx::NetappsLocation) -> Telnyx::NetappsLocation

      attr_reader record_type: String?

      def record_type=: (String) -> String

      def initialize: (
        ?available_bandwidth: ::Array[Float],
        ?cloud_provider: Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider,
        ?cloud_provider_region: String,
        ?location: Telnyx::NetappsLocation,
        ?record_type: String
      ) -> void

      def to_hash: -> {
        available_bandwidth: ::Array[Float],
        cloud_provider: Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider,
        cloud_provider_region: String,
        location: Telnyx::NetappsLocation,
        record_type: String
      }

      type cloud_provider = :aws | :azure | :gce

      module CloudProvider
        extend Telnyx::Internal::Type::Enum

        AWS: :aws
        AZURE: :azure
        GCE: :gce

        def self?.values: -> ::Array[Telnyx::Models::VirtualCrossConnectsCoverageListResponse::cloud_provider]
      end
    end
  end
end
