module Telnyx
  module Models
    type voice_sdk_call_report_list_response =
      {
        call_id: String,
        call_report_id: String,
        created_at: Time,
        flush_reason: ::Hash[Symbol, top],
        logs: Telnyx::Models::VoiceSDKCallReportListResponse::logs,
        organization_id: String,
        segment: Integer,
        stats: Telnyx::Models::VoiceSDKCallReportListResponse::stats,
        stored_at: Time,
        summary: ::Hash[Symbol, top],
        telnyx_leg_id: String,
        telnyx_session_id: String,
        user_agent: String,
        user_id: String,
        version: String,
        voice_sdk_id: String,
        voice_sdk_id_decoded: ::Hash[Symbol, top],
        voice_sdk_session_id: String
      }

    class VoiceSDKCallReportListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader call_id: String?

      def call_id=: (String) -> String

      attr_reader call_report_id: String?

      def call_report_id=: (String) -> String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_reader flush_reason: ::Hash[Symbol, top]?

      def flush_reason=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader logs: Telnyx::Models::VoiceSDKCallReportListResponse::logs?

      def logs=: (
        Telnyx::Models::VoiceSDKCallReportListResponse::logs
      ) -> Telnyx::Models::VoiceSDKCallReportListResponse::logs

      attr_reader organization_id: String?

      def organization_id=: (String) -> String

      attr_reader segment: Integer?

      def segment=: (Integer) -> Integer

      attr_reader stats: Telnyx::Models::VoiceSDKCallReportListResponse::stats?

      def stats=: (
        Telnyx::Models::VoiceSDKCallReportListResponse::stats
      ) -> Telnyx::Models::VoiceSDKCallReportListResponse::stats

      attr_reader stored_at: Time?

      def stored_at=: (Time) -> Time

      attr_reader summary: ::Hash[Symbol, top]?

      def summary=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader telnyx_leg_id: String?

      def telnyx_leg_id=: (String) -> String

      attr_reader telnyx_session_id: String?

      def telnyx_session_id=: (String) -> String

      attr_reader user_agent: String?

      def user_agent=: (String) -> String

      attr_reader user_id: String?

      def user_id=: (String) -> String

      attr_reader version: String?

      def version=: (String) -> String

      attr_reader voice_sdk_id: String?

      def voice_sdk_id=: (String) -> String

      attr_reader voice_sdk_id_decoded: ::Hash[Symbol, top]?

      def voice_sdk_id_decoded=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader voice_sdk_session_id: String?

      def voice_sdk_session_id=: (String) -> String

      def initialize: (
        ?call_id: String,
        ?call_report_id: String,
        ?created_at: Time,
        ?flush_reason: ::Hash[Symbol, top],
        ?logs: Telnyx::Models::VoiceSDKCallReportListResponse::logs,
        ?organization_id: String,
        ?segment: Integer,
        ?stats: Telnyx::Models::VoiceSDKCallReportListResponse::stats,
        ?stored_at: Time,
        ?summary: ::Hash[Symbol, top],
        ?telnyx_leg_id: String,
        ?telnyx_session_id: String,
        ?user_agent: String,
        ?user_id: String,
        ?version: String,
        ?voice_sdk_id: String,
        ?voice_sdk_id_decoded: ::Hash[Symbol, top],
        ?voice_sdk_session_id: String
      ) -> void

      def to_hash: -> {
        call_id: String,
        call_report_id: String,
        created_at: Time,
        flush_reason: ::Hash[Symbol, top],
        logs: Telnyx::Models::VoiceSDKCallReportListResponse::logs,
        organization_id: String,
        segment: Integer,
        stats: Telnyx::Models::VoiceSDKCallReportListResponse::stats,
        stored_at: Time,
        summary: ::Hash[Symbol, top],
        telnyx_leg_id: String,
        telnyx_session_id: String,
        user_agent: String,
        user_id: String,
        version: String,
        voice_sdk_id: String,
        voice_sdk_id_decoded: ::Hash[Symbol, top],
        voice_sdk_session_id: String
      }

      type logs =
        ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0]
        | Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries

      module Logs
        extend Telnyx::Internal::Type::Union

        type union_member0 =
          {
            context: ::Hash[Symbol, top],
            level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level,
            message: String,
            timestamp: Time
          }

        class UnionMember0 < Telnyx::Internal::Type::BaseModel
          attr_reader context: ::Hash[Symbol, top]?

          def context=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level?

          def level=: (
            Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level
          ) -> Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level

          attr_reader message: String?

          def message=: (String) -> String

          attr_reader timestamp: Time?

          def timestamp=: (Time) -> Time

          def initialize: (
            ?context: ::Hash[Symbol, top],
            ?level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level,
            ?message: String,
            ?timestamp: Time
          ) -> void

          def to_hash: -> {
            context: ::Hash[Symbol, top],
            level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level,
            message: String,
            timestamp: Time
          }

          type level = :debug | :info | :warn | :error

          module Level
            extend Telnyx::Internal::Type::Enum

            DEBUG: :debug
            INFO: :info
            WARN: :warn
            ERROR: :error

            def self?.values: -> ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::UnionMember0::level]
          end
        end

        type entries =
          {
            entries: ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]
          }

        class Entries < Telnyx::Internal::Type::BaseModel
          attr_reader entries: ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]?

          def entries=: (
            ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]
          ) -> ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]

          def initialize: (
            ?entries: ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]
          ) -> void

          def to_hash: -> {
            entries: ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry]
          }

          type entry =
            {
              context: ::Hash[Symbol, top],
              level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level,
              message: String,
              timestamp: Time
            }

          class Entry < Telnyx::Internal::Type::BaseModel
            attr_reader context: ::Hash[Symbol, top]?

            def context=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

            attr_reader level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level?

            def level=: (
              Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level
            ) -> Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level

            attr_reader message: String?

            def message=: (String) -> String

            attr_reader timestamp: Time?

            def timestamp=: (Time) -> Time

            def initialize: (
              ?context: ::Hash[Symbol, top],
              ?level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level,
              ?message: String,
              ?timestamp: Time
            ) -> void

            def to_hash: -> {
              context: ::Hash[Symbol, top],
              level: Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level,
              message: String,
              timestamp: Time
            }

            type level = :debug | :info | :warn | :error

            module Level
              extend Telnyx::Internal::Type::Enum

              DEBUG: :debug
              INFO: :info
              WARN: :warn
              ERROR: :error

              def self?.values: -> ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::Logs::Entries::Entry::level]
            end
          end
        end

        def self?.variants: -> ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::logs]

        UnionMember0Array: Telnyx::Internal::Type::Converter
      end

      type stats =
        ::Array[::Hash[Symbol, top]]
        | Telnyx::Models::VoiceSDKCallReportListResponse::Stats::UnionMember1

      module Stats
        extend Telnyx::Internal::Type::Union

        type union_member1 =
          {
            audio: ::Hash[Symbol, top],
            connection: ::Hash[Symbol, top],
            ice: ::Hash[Symbol, top],
            transport: ::Hash[Symbol, top]
          }

        class UnionMember1 < Telnyx::Internal::Type::BaseModel
          attr_reader audio: ::Hash[Symbol, top]?

          def audio=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader connection: ::Hash[Symbol, top]?

          def connection=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader ice: ::Hash[Symbol, top]?

          def ice=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader transport: ::Hash[Symbol, top]?

          def transport=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          def initialize: (
            ?audio: ::Hash[Symbol, top],
            ?connection: ::Hash[Symbol, top],
            ?ice: ::Hash[Symbol, top],
            ?transport: ::Hash[Symbol, top]
          ) -> void

          def to_hash: -> {
            audio: ::Hash[Symbol, top],
            connection: ::Hash[Symbol, top],
            ice: ::Hash[Symbol, top],
            transport: ::Hash[Symbol, top]
          }
        end

        def self?.variants: -> ::Array[Telnyx::Models::VoiceSDKCallReportListResponse::stats]

        UnionMember0Array: Telnyx::Internal::Type::Converter
      end
    end
  end
end
