module Telnyx
  module Models
    type voice_clone_create_from_upload_params =
      { upload_params: top } & Telnyx::Internal::Type::request_parameters

    class VoiceCloneCreateFromUploadParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor upload_params: top

      def initialize: (
        upload_params: top,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        upload_params: top,
        request_options: Telnyx::RequestOptions
      }
    end
  end
end
