module Telnyx
  module Models
    type voice_clone_create_params =
      { params: Telnyx::Models::VoiceCloneCreateParams::params }
      & Telnyx::Internal::Type::request_parameters

    class VoiceCloneCreateParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor params: Telnyx::Models::VoiceCloneCreateParams::params

      def initialize: (
        params: Telnyx::Models::VoiceCloneCreateParams::params,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        params: Telnyx::Models::VoiceCloneCreateParams::params,
        request_options: Telnyx::RequestOptions
      }

      type params =
        Telnyx::VoiceCloneCreateParams::Params::TelnyxDesignClone
        | Telnyx::VoiceCloneCreateParams::Params::MinimaxDesignClone

      module Params
        extend Telnyx::Internal::Type::Union

        type telnyx_design_clone =
          {
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::gender,
            language: String,
            name: String,
            voice_design_id: String,
            provider: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider
          }

        class TelnyxDesignClone < Telnyx::Internal::Type::BaseModel
          attr_accessor gender: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::gender

          attr_accessor language: String

          attr_accessor name: String

          attr_accessor voice_design_id: String

          attr_reader provider: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider?

          def provider=: (
            Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider
          ) -> Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider

          def initialize: (
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::gender,
            language: String,
            name: String,
            voice_design_id: String,
            ?provider: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider
          ) -> void

          def to_hash: -> {
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::gender,
            language: String,
            name: String,
            voice_design_id: String,
            provider: Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider
          }

          type gender = :male | :female | :neutral

          module Gender
            extend Telnyx::Internal::Type::Enum

            MALE: :male
            FEMALE: :female
            NEUTRAL: :neutral

            def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::gender]
          end

          type provider = :telnyx | :Telnyx

          module Provider
            extend Telnyx::Internal::Type::Enum

            TELNYX: :telnyx
            TELNYX_2: :Telnyx

            def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::Params::TelnyxDesignClone::provider]
          end
        end

        type minimax_design_clone =
          {
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::gender,
            language: String,
            name: String,
            provider: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::provider,
            voice_design_id: String
          }

        class MinimaxDesignClone < Telnyx::Internal::Type::BaseModel
          attr_accessor gender: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::gender

          attr_accessor language: String

          attr_accessor name: String

          attr_accessor provider: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::provider

          attr_accessor voice_design_id: String

          def initialize: (
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::gender,
            language: String,
            name: String,
            provider: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::provider,
            voice_design_id: String
          ) -> void

          def to_hash: -> {
            gender: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::gender,
            language: String,
            name: String,
            provider: Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::provider,
            voice_design_id: String
          }

          type gender = :male | :female | :neutral

          module Gender
            extend Telnyx::Internal::Type::Enum

            MALE: :male
            FEMALE: :female
            NEUTRAL: :neutral

            def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::gender]
          end

          type provider = :minimax | :Minimax

          module Provider
            extend Telnyx::Internal::Type::Enum

            MINIMAX: :minimax
            MINIMAX_2: :Minimax

            def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::Params::MinimaxDesignClone::provider]
          end
        end

        def self?.variants: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::params]
      end
    end
  end
end
