module Telnyx
  module Models
    type voice_clone_create_from_upload_response =
      { data: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data }

    class VoiceCloneCreateFromUploadResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data?

      def data=: (
        Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data
      ) -> Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data

      def initialize: (
        ?data: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data
      }

      type data =
        {
          id: String,
          created_at: Time,
          gender: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::gender?,
          label: String?,
          language: String?,
          name: String,
          record_type: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type,
          source_voice_design_id: String?,
          source_voice_design_version: Integer?,
          updated_at: Time
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_accessor gender: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::gender?

        attr_accessor label: String?

        attr_accessor language: String?

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader record_type: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type?

        def record_type=: (
          Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type
        ) -> Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type

        attr_accessor source_voice_design_id: String?

        attr_accessor source_voice_design_version: Integer?

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        def initialize: (
          ?id: String,
          ?created_at: Time,
          ?gender: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::gender?,
          ?label: String?,
          ?language: String?,
          ?name: String,
          ?record_type: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type,
          ?source_voice_design_id: String?,
          ?source_voice_design_version: Integer?,
          ?updated_at: Time
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          gender: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::gender?,
          label: String?,
          language: String?,
          name: String,
          record_type: Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type,
          source_voice_design_id: String?,
          source_voice_design_version: Integer?,
          updated_at: Time
        }

        type gender = :male | :female | :neutral

        module Gender
          extend Telnyx::Internal::Type::Enum

          MALE: :male
          FEMALE: :female
          NEUTRAL: :neutral

          def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::gender]
        end

        type record_type = :voice_clone

        module RecordType
          extend Telnyx::Internal::Type::Enum

          VOICE_CLONE: :voice_clone

          def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateFromUploadResponse::Data::record_type]
        end
      end
    end
  end
end
