module Telnyx
  module Models
    type voice_clone_create_from_design_params =
      {
        gender: Telnyx::Models::VoiceCloneCreateFromDesignParams::gender,
        language: String,
        name: String,
        voice_design_id: String,
        provider: Telnyx::Models::VoiceCloneCreateParams::provider
      }
      & Telnyx::Internal::Type::request_parameters

    class VoiceCloneCreateFromDesignParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      attr_accessor gender: Telnyx::Models::VoiceCloneCreateFromDesignParams::gender

      attr_accessor language: String

      attr_accessor name: String

      attr_accessor voice_design_id: String

      attr_reader provider: Telnyx::Models::VoiceCloneCreateParams::provider?

      def provider=: (
        Telnyx::Models::VoiceCloneCreateParams::provider
      ) -> Telnyx::Models::VoiceCloneCreateParams::provider

      def initialize: (
        gender: Telnyx::Models::VoiceCloneCreateFromDesignParams::gender,
        language: String,
        name: String,
        voice_design_id: String,
        ?provider: Telnyx::Models::VoiceCloneCreateParams::provider,
        ?request_options: Telnyx::request_opts
      ) -> void

      def to_hash: -> {
        gender: Telnyx::Models::VoiceCloneCreateFromDesignParams::gender,
        language: String,
        name: String,
        voice_design_id: String,
        provider: Telnyx::Models::VoiceCloneCreateParams::provider,
        request_options: Telnyx::RequestOptions
      }

      type gender = :male | :female | :neutral

      module Gender
        extend Telnyx::Internal::Type::Enum

        MALE: :male
        FEMALE: :female
        NEUTRAL: :neutral

        def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateFromDesignParams::gender]
      end

      type provider = :telnyx | :minimax | :Telnyx | :Minimax

      module Provider
        extend Telnyx::Internal::Type::Enum

        TELNYX: :telnyx
        TELNYX_2: :Telnyx
        MINIMAX: :minimax
        MINIMAX_2: :Minimax

        def self?.values: -> ::Array[Telnyx::Models::VoiceCloneCreateParams::provider]
      end
    end
  end
end
