module Telnyx
  module Models
    type voice_design_create_response = { data: Telnyx::VoiceDesignData }

    class VoiceDesignCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::VoiceDesignData?

      def data=: (Telnyx::VoiceDesignData) -> Telnyx::VoiceDesignData

      def initialize: (?data: Telnyx::VoiceDesignData) -> void

      def to_hash: -> { data: Telnyx::VoiceDesignData }
    end
  end
end
