module Telnyx
  module Models
    type webhook_api_version = :"1" | :"2"

    module WebhookAPIVersion
      extend Telnyx::Internal::Type::Enum

      WEBHOOK_API_VERSION_1: :"1"
      WEBHOOK_API_VERSION_2: :"2"

      def self?.values: -> ::Array[Telnyx::Models::webhook_api_version]
    end
  end
end
