module Telnyx
  module Models
    type webhook_delivery_retrieve_response = { data: Telnyx::WebhookDelivery }

    class WebhookDeliveryRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::WebhookDelivery?

      def data=: (Telnyx::WebhookDelivery) -> Telnyx::WebhookDelivery

      def initialize: (?data: Telnyx::WebhookDelivery) -> void

      def to_hash: -> { data: Telnyx::WebhookDelivery }
    end
  end
end
