module Telnyx
  module Models
    type webhook_delivery_retrieve_response =
      { data: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data }

    class WebhookDeliveryRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data?

      def data=: (
        Telnyx::Models::WebhookDeliveryRetrieveResponse::Data
      ) -> Telnyx::Models::WebhookDeliveryRetrieveResponse::Data

      def initialize: (
        ?data: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data
      }

      type data =
        {
          id: String,
          attempts: ::Array[Telnyx::Attempt],
          finished_at: Time,
          record_type: String,
          started_at: Time,
          status: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status,
          user_id: String,
          webhook: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader attempts: ::Array[Telnyx::Attempt]?

        def attempts=: (::Array[Telnyx::Attempt]) -> ::Array[Telnyx::Attempt]

        attr_reader finished_at: Time?

        def finished_at=: (Time) -> Time

        attr_reader record_type: String?

        def record_type=: (String) -> String

        attr_reader started_at: Time?

        def started_at=: (Time) -> Time

        attr_reader status: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status?

        def status=: (
          Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status
        ) -> Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status

        attr_reader user_id: String?

        def user_id=: (String) -> String

        attr_reader webhook: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook?

        def webhook=: (
          Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook
        ) -> Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook

        def initialize: (
          ?id: String,
          ?attempts: ::Array[Telnyx::Attempt],
          ?finished_at: Time,
          ?record_type: String,
          ?started_at: Time,
          ?status: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status,
          ?user_id: String,
          ?webhook: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook
        ) -> void

        def to_hash: -> {
          id: String,
          attempts: ::Array[Telnyx::Attempt],
          finished_at: Time,
          record_type: String,
          started_at: Time,
          status: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status,
          user_id: String,
          webhook: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook
        }

        type status = :delivered | :failed

        module Status
          extend Telnyx::Internal::Type::Enum

          DELIVERED: :delivered
          FAILED: :failed

          def self?.values: -> ::Array[Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::status]
        end

        type webhook =
          {
            id: String,
            event_type: String,
            occurred_at: Time,
            payload: ::Hash[Symbol, top],
            record_type: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type
          }

        class Webhook < Telnyx::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader event_type: String?

          def event_type=: (String) -> String

          attr_reader occurred_at: Time?

          def occurred_at=: (Time) -> Time

          attr_reader payload: ::Hash[Symbol, top]?

          def payload=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader record_type: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type?

          def record_type=: (
            Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type
          ) -> Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type

          def initialize: (
            ?id: String,
            ?event_type: String,
            ?occurred_at: Time,
            ?payload: ::Hash[Symbol, top],
            ?record_type: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type
          ) -> void

          def to_hash: -> {
            id: String,
            event_type: String,
            occurred_at: Time,
            payload: ::Hash[Symbol, top],
            record_type: Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type
          }

          type record_type = :event

          module RecordType
            extend Telnyx::Internal::Type::Enum

            EVENT: :event

            def self?.values: -> ::Array[Telnyx::Models::WebhookDeliveryRetrieveResponse::Data::Webhook::record_type]
          end
        end
      end
    end
  end
end
