module Telnyx
  module Models
    type whatsapp_media =
      { caption: String, filename: String, link: String, voice: bool }

    class WhatsappMedia < Telnyx::Internal::Type::BaseModel
      attr_reader caption: String?

      def caption=: (String) -> String

      attr_reader filename: String?

      def filename=: (String) -> String

      attr_reader link: String?

      def link=: (String) -> String

      attr_reader voice: bool?

      def voice=: (bool) -> bool

      def initialize: (
        ?caption: String,
        ?filename: String,
        ?link: String,
        ?voice: bool
      ) -> void

      def to_hash: -> {
        caption: String,
        filename: String,
        link: String,
        voice: bool
      }
    end
  end
end
