module Telnyx
  module Models
    type whatsapp_message_template_retrieve_response =
      { data: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data }

    class WhatsappMessageTemplateRetrieveResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data?

      def data=: (
        Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data
      ) -> Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data

      def initialize: (
        ?data: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data
      }

      type data =
        {
          id: String,
          category: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category,
          components: ::Array[top],
          created_at: Time,
          language: String,
          name: String,
          record_type: String,
          rejection_reason: String,
          status: String,
          template_id: String,
          updated_at: Time,
          whatsapp_business_account: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount
        }

      class Data < Telnyx::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader category: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category?

        def category=: (
          Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category
        ) -> Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category

        attr_reader components: ::Array[top]?

        def components=: (::Array[top]) -> ::Array[top]

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader language: String?

        def language=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader record_type: String?

        def record_type=: (String) -> String

        attr_reader rejection_reason: String?

        def rejection_reason=: (String) -> String

        attr_reader status: String?

        def status=: (String) -> String

        attr_reader template_id: String?

        def template_id=: (String) -> String

        attr_reader updated_at: Time?

        def updated_at=: (Time) -> Time

        attr_reader whatsapp_business_account: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount?

        def whatsapp_business_account=: (
          Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount
        ) -> Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount

        def initialize: (
          ?id: String,
          ?category: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category,
          ?components: ::Array[top],
          ?created_at: Time,
          ?language: String,
          ?name: String,
          ?record_type: String,
          ?rejection_reason: String,
          ?status: String,
          ?template_id: String,
          ?updated_at: Time,
          ?whatsapp_business_account: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount
        ) -> void

        def to_hash: -> {
          id: String,
          category: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category,
          components: ::Array[top],
          created_at: Time,
          language: String,
          name: String,
          record_type: String,
          rejection_reason: String,
          status: String,
          template_id: String,
          updated_at: Time,
          whatsapp_business_account: Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::WhatsappBusinessAccount
        }

        type category = :MARKETING | :UTILITY | :AUTHENTICATION

        module Category
          extend Telnyx::Internal::Type::Enum

          MARKETING: :MARKETING
          UTILITY: :UTILITY
          AUTHENTICATION: :AUTHENTICATION

          def self?.values: -> ::Array[Telnyx::Models::WhatsappMessageTemplateRetrieveResponse::Data::category]
        end

        type whatsapp_business_account = { id: String }

        class WhatsappBusinessAccount < Telnyx::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          def initialize: (?id: String) -> void

          def to_hash: -> { id: String }
        end
      end
    end
  end
end
