module Telnyx
  module Models
    type wireguard_peer_list_response =
      {
        data: ::Array[Telnyx::Models::WireguardPeerListResponse::Data],
        meta: Telnyx::PaginationMeta
      }

    class WireguardPeerListResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: ::Array[Telnyx::Models::WireguardPeerListResponse::Data]?

      def data=: (
        ::Array[Telnyx::Models::WireguardPeerListResponse::Data]
      ) -> ::Array[Telnyx::Models::WireguardPeerListResponse::Data]

      attr_reader meta: Telnyx::PaginationMeta?

      def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

      def initialize: (
        ?data: ::Array[Telnyx::Models::WireguardPeerListResponse::Data],
        ?meta: Telnyx::PaginationMeta
      ) -> void

      def to_hash: -> {
        data: ::Array[Telnyx::Models::WireguardPeerListResponse::Data],
        meta: Telnyx::PaginationMeta
      }
    end
  end
end
