module Telnyx
  module Models
    type wireguard_interface_create_response =
      { data: Telnyx::Models::WireguardInterfaceCreateResponse::Data }

    class WireguardInterfaceCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::Models::WireguardInterfaceCreateResponse::Data?

      def data=: (
        Telnyx::Models::WireguardInterfaceCreateResponse::Data
      ) -> Telnyx::Models::WireguardInterfaceCreateResponse::Data

      def initialize: (
        ?data: Telnyx::Models::WireguardInterfaceCreateResponse::Data
      ) -> void

      def to_hash: -> {
        data: Telnyx::Models::WireguardInterfaceCreateResponse::Data
      }
    end
  end
end
