module Telnyx
  module Models
    type wireless_blocklist_create_response =
      { data: Telnyx::WirelessWirelessBlocklist }

    class WirelessBlocklistCreateResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::WirelessWirelessBlocklist?

      def data=: (
        Telnyx::WirelessWirelessBlocklist
      ) -> Telnyx::WirelessWirelessBlocklist

      def initialize: (?data: Telnyx::WirelessWirelessBlocklist) -> void

      def to_hash: -> { data: Telnyx::WirelessWirelessBlocklist }
    end
  end
end
