module Telnyx
  module Models
    type wireguard_peer_list_response =
      { last_seen: String, private_key: String, wireguard_interface_id: String }

    class WireguardPeerListResponse < Telnyx::Models::Record
      def wireguard_interface_id: -> String?

      def wireguard_interface_id=: (String _) -> String

      def last_seen: -> String?

      def last_seen=: (String _) -> String

      def private_key: -> String?

      def private_key=: (String _) -> String

      def initialize: (
        ?last_seen: String,
        ?private_key: String,
        ?wireguard_interface_id: String
      ) -> void

      def to_hash: -> {
        last_seen: String,
        private_key: String,
        wireguard_interface_id: String
      }
    end
  end
end
