module Telnyx
  module Models
    type wireguard_interface_delete_response =
      { data: Telnyx::WireguardInterfaceRead }

    class WireguardInterfaceDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::WireguardInterfaceRead?

      def data=: (
        Telnyx::WireguardInterfaceRead
      ) -> Telnyx::WireguardInterfaceRead

      def initialize: (?data: Telnyx::WireguardInterfaceRead) -> void

      def to_hash: -> { data: Telnyx::WireguardInterfaceRead }
    end
  end
end
