module Telnyx
  module Models
    type wireguard_peer_delete_response = { data: Telnyx::WireguardPeer }

    class WireguardPeerDeleteResponse < Telnyx::Internal::Type::BaseModel
      attr_reader data: Telnyx::WireguardPeer?

      def data=: (Telnyx::WireguardPeer) -> Telnyx::WireguardPeer

      def initialize: (?data: Telnyx::WireguardPeer) -> void

      def to_hash: -> { data: Telnyx::WireguardPeer }
    end
  end
end
