module Telnyx
  module Models
    type wireguard_interface_list_response = {  }

    class WireguardInterfaceListResponse < Telnyx::Models::Record
      def initialize: -> void

      def to_hash: -> {  }
    end
  end
end
