module Telnyx
  module Resources
    class Rooms
      class Sessions
        attr_reader actions: Telnyx::Resources::Rooms::Sessions::Actions

        def retrieve: (
          String room_session_id,
          ?include_participants: bool,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Rooms::SessionRetrieveResponse

        def list_0: (
          ?filter: Telnyx::Rooms::SessionList0Params::Filter,
          ?include_participants: bool,
          ?page_number: Integer,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::RoomSession]

        def list_1: (
          String room_id,
          ?filter: Telnyx::Rooms::SessionList1Params::Filter,
          ?include_participants: bool,
          ?page_number: Integer,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::RoomSession]

        def retrieve_participants: (
          String room_session_id,
          ?filter: Telnyx::Rooms::SessionRetrieveParticipantsParams::Filter,
          ?page_number: Integer,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::RoomParticipant]

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
