# frozen_string_literal: true

module Telnyx
  module Models
    module Calls
      class AssistantMessage < Telnyx::Internal::Type::BaseModel
        # @!attribute role
        #   The role of the messages author, in this case `assistant`.
        #
        #   @return [Symbol, Telnyx::Models::Calls::AssistantMessage::Role]
        required :role, enum: -> { Telnyx::Calls::AssistantMessage::Role }

        # @!attribute content
        #   The contents of the assistant message. Required unless `tool_calls`
        #
        #   @return [String, nil]
        optional :content, String

        # @!attribute metadata
        #   Metadata to add to the message
        #
        #   @return [Hash{Symbol=>Object}, nil]
        optional :metadata, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

        # @!attribute tool_calls
        #   The tool calls generated by the model, such as function calls.
        #
        #   @return [Array<Telnyx::Models::Calls::AssistantMessage::ToolCall>, nil]
        optional :tool_calls, -> { Telnyx::Internal::Type::ArrayOf[Telnyx::Calls::AssistantMessage::ToolCall] }

        # @!method initialize(role:, content: nil, metadata: nil, tool_calls: nil)
        #   Messages sent by the model in response to user messages.
        #
        #   @param role [Symbol, Telnyx::Models::Calls::AssistantMessage::Role] The role of the messages author, in this case `assistant`.
        #
        #   @param content [String] The contents of the assistant message. Required unless `tool_calls`
        #
        #   @param metadata [Hash{Symbol=>Object}] Metadata to add to the message
        #
        #   @param tool_calls [Array<Telnyx::Models::Calls::AssistantMessage::ToolCall>] The tool calls generated by the model, such as function calls.

        # The role of the messages author, in this case `assistant`.
        #
        # @see Telnyx::Models::Calls::AssistantMessage#role
        module Role
          extend Telnyx::Internal::Type::Enum

          ASSISTANT = :assistant

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        class ToolCall < Telnyx::Internal::Type::BaseModel
          # @!attribute id
          #   The ID of the tool call.
          #
          #   @return [String]
          required :id, String

          # @!attribute function
          #   The function that the model called.
          #
          #   @return [Telnyx::Models::Calls::AssistantMessage::ToolCall::Function]
          required :function, -> { Telnyx::Calls::AssistantMessage::ToolCall::Function }

          # @!attribute type
          #   The type of the tool. Currently, only `function` is supported.
          #
          #   @return [Symbol, Telnyx::Models::Calls::AssistantMessage::ToolCall::Type]
          required :type, enum: -> { Telnyx::Calls::AssistantMessage::ToolCall::Type }

          # @!method initialize(id:, function:, type:)
          #   A call to a function tool created by the model.
          #
          #   @param id [String] The ID of the tool call.
          #
          #   @param function [Telnyx::Models::Calls::AssistantMessage::ToolCall::Function] The function that the model called.
          #
          #   @param type [Symbol, Telnyx::Models::Calls::AssistantMessage::ToolCall::Type] The type of the tool. Currently, only `function` is supported.

          # @see Telnyx::Models::Calls::AssistantMessage::ToolCall#function
          class Function < Telnyx::Internal::Type::BaseModel
            # @!attribute name
            #   The name of the function to call.
            #
            #   @return [String]
            required :name, String

            # @!method initialize(name:)
            #   The function that the model called.
            #
            #   @param name [String] The name of the function to call.
          end

          # The type of the tool. Currently, only `function` is supported.
          #
          # @see Telnyx::Models::Calls::AssistantMessage::ToolCall#type
          module Type
            extend Telnyx::Internal::Type::Enum

            FUNCTION = :function

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
