module Telnyx
  module Models
    module Conferences
      type action_hold_params =
        {
          audio_url: String,
          call_control_ids: ::Array[String],
          media_name: String,
          region: Telnyx::Models::Conferences::ActionHoldParams::region
        }
        & Telnyx::Internal::Type::request_parameters

      class ActionHoldParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_reader audio_url: String?

        def audio_url=: (String) -> String

        attr_reader call_control_ids: ::Array[String]?

        def call_control_ids=: (::Array[String]) -> ::Array[String]

        attr_reader media_name: String?

        def media_name=: (String) -> String

        attr_reader region: Telnyx::Models::Conferences::ActionHoldParams::region?

        def region=: (
          Telnyx::Models::Conferences::ActionHoldParams::region
        ) -> Telnyx::Models::Conferences::ActionHoldParams::region

        def initialize: (
          ?audio_url: String,
          ?call_control_ids: ::Array[String],
          ?media_name: String,
          ?region: Telnyx::Models::Conferences::ActionHoldParams::region,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          audio_url: String,
          call_control_ids: ::Array[String],
          media_name: String,
          region: Telnyx::Models::Conferences::ActionHoldParams::region,
          request_options: Telnyx::RequestOptions
        }

        type region = :Australia | :Europe | :"Middle East" | :US

        module Region
          extend Telnyx::Internal::Type::Enum

          AUSTRALIA: :Australia
          EUROPE: :Europe
          MIDDLE_EAST: :"Middle East"
          US: :US

          def self?.values: -> ::Array[Telnyx::Models::Conferences::ActionHoldParams::region]
        end
      end
    end
  end
end
