module Telnyx
  module Models
    module Conferences
      type action_stop_response =
        { data: Telnyx::Conferences::ConferenceCommandResult }

      class ActionStopResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Conferences::ConferenceCommandResult?

        def data=: (
          Telnyx::Conferences::ConferenceCommandResult
        ) -> Telnyx::Conferences::ConferenceCommandResult

        def initialize: (
          ?data: Telnyx::Conferences::ConferenceCommandResult
        ) -> void

        def to_hash: -> { data: Telnyx::Conferences::ConferenceCommandResult }
      end
    end
  end
end
