module Telnyx
  module Models
    module PhoneNumbers
      type csv_download_list_response =
        {
          data: ::Array[Telnyx::PhoneNumbers::CsvDownload],
          meta: Telnyx::PaginationMeta
        }

      class CsvDownloadListResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::PhoneNumbers::CsvDownload]?

        def data=: (
          ::Array[Telnyx::PhoneNumbers::CsvDownload]
        ) -> ::Array[Telnyx::PhoneNumbers::CsvDownload]

        attr_reader meta: Telnyx::PaginationMeta?

        def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

        def initialize: (
          ?data: ::Array[Telnyx::PhoneNumbers::CsvDownload],
          ?meta: Telnyx::PaginationMeta
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::PhoneNumbers::CsvDownload],
          meta: Telnyx::PaginationMeta
        }
      end
    end
  end
end
