module Telnyx
  module Models
    module PhoneNumbers
      type csv_download_create_response =
        { data: ::Array[Telnyx::PhoneNumbers::CsvDownload] }

      class CsvDownloadCreateResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::PhoneNumbers::CsvDownload]?

        def data=: (
          ::Array[Telnyx::PhoneNumbers::CsvDownload]
        ) -> ::Array[Telnyx::PhoneNumbers::CsvDownload]

        def initialize: (
          ?data: ::Array[Telnyx::PhoneNumbers::CsvDownload]
        ) -> void

        def to_hash: -> { data: ::Array[Telnyx::PhoneNumbers::CsvDownload] }
      end
    end
  end
end
