module Telnyx
  module Models
    module PhoneNumbers
      type job_list_params =
        {
          filter: Telnyx::PhoneNumbers::JobListParams::Filter,
          page_number: Integer,
          page_size: Integer,
          sort: Telnyx::Models::PhoneNumbers::JobListParams::sort
        }
        & Telnyx::Internal::Type::request_parameters

      class JobListParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_reader filter: Telnyx::PhoneNumbers::JobListParams::Filter?

        def filter=: (
          Telnyx::PhoneNumbers::JobListParams::Filter
        ) -> Telnyx::PhoneNumbers::JobListParams::Filter

        attr_reader page_number: Integer?

        def page_number=: (Integer) -> Integer

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        attr_reader sort: Telnyx::Models::PhoneNumbers::JobListParams::sort?

        def sort=: (
          Telnyx::Models::PhoneNumbers::JobListParams::sort
        ) -> Telnyx::Models::PhoneNumbers::JobListParams::sort

        def initialize: (
          ?filter: Telnyx::PhoneNumbers::JobListParams::Filter,
          ?page_number: Integer,
          ?page_size: Integer,
          ?sort: Telnyx::Models::PhoneNumbers::JobListParams::sort,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          filter: Telnyx::PhoneNumbers::JobListParams::Filter,
          page_number: Integer,
          page_size: Integer,
          sort: Telnyx::Models::PhoneNumbers::JobListParams::sort,
          request_options: Telnyx::RequestOptions
        }

        type filter =
          {
            phone_number: Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number,
            status: ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status],
            type: Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_
          }

        class Filter < Telnyx::Internal::Type::BaseModel
          attr_reader phone_number: Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number?

          def phone_number=: (
            Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number
          ) -> Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number

          attr_reader status: ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status]?

          def status=: (
            ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status]
          ) -> ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status]

          attr_reader type: Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_?

          def type=: (
            Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_
          ) -> Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_

          def initialize: (
            ?phone_number: Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number,
            ?status: ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status],
            ?type: Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_
          ) -> void

          def to_hash: -> {
            phone_number: Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number,
            status: ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status],
            type: Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_
          }

          type phone_number = String | ::Array[String]

          module PhoneNumber
            extend Telnyx::Internal::Type::Union

            def self?.variants: -> ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::phone_number]

            StringArray: Telnyx::Internal::Type::Converter
          end

          type status =
            :pending | :in_progress | :completed | :failed | :expired

          module Status
            extend Telnyx::Internal::Type::Enum

            PENDING: :pending
            IN_PROGRESS: :in_progress
            COMPLETED: :completed
            FAILED: :failed
            EXPIRED: :expired

            def self?.values: -> ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::status]
          end

          type type_ =
            :update_emergency_settings
            | :delete_phone_numbers
            | :update_phone_numbers

          module Type
            extend Telnyx::Internal::Type::Enum

            UPDATE_EMERGENCY_SETTINGS: :update_emergency_settings
            DELETE_PHONE_NUMBERS: :delete_phone_numbers
            UPDATE_PHONE_NUMBERS: :update_phone_numbers

            def self?.values: -> ::Array[Telnyx::Models::PhoneNumbers::JobListParams::Filter::type_]
          end
        end

        type sort = :created_at

        module Sort
          extend Telnyx::Internal::Type::Enum

          CREATED_AT: :created_at

          def self?.values: -> ::Array[Telnyx::Models::PhoneNumbers::JobListParams::sort]
        end
      end
    end
  end
end
