module Telnyx
  module Resources
    class Portouts
      class Reports
        def create: (
          params: Telnyx::Portouts::ExportPortoutsCsvReport,
          report_type: Telnyx::Models::Portouts::ReportCreateParams::report_type,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Portouts::ReportCreateResponse

        def retrieve: (
          String id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Portouts::ReportRetrieveResponse

        def list: (
          ?filter: Telnyx::Portouts::ReportListParams::Filter,
          ?page_number: Integer,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Portouts::PortoutReport]

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
