module Telnyx
  module Models
    module Whatsapp
      type user_data_retrieve_response =
        { data: Telnyx::Whatsapp::WhatsappUserData }

      class UserDataRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Whatsapp::WhatsappUserData?

        def data=: (
          Telnyx::Whatsapp::WhatsappUserData
        ) -> Telnyx::Whatsapp::WhatsappUserData

        def initialize: (?data: Telnyx::Whatsapp::WhatsappUserData) -> void

        def to_hash: -> { data: Telnyx::Whatsapp::WhatsappUserData }
      end
    end
  end
end
