module Telnyx
  module Resources
    class Dir
      class VerifyEmail
        def confirm: (
          String dir_id,
          code: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Dir::VerifyEmailConfirmResponse

        def send_: (
          String dir_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Dir::VerifyEmailSendResponse

        def status: (
          String dir_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::Dir::VerifyEmailStatusResponse

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
