module Telnyx
  module Resources
    class Dir
      class VerifyEmail
        def create: (
          String dir_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Dir::EmailVerificationStatusWrapped

        def list: (
          String dir_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Dir::EmailVerificationStatusWrapped

        def confirm: (
          String dir_id,
          code: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Dir::EmailVerificationStatusWrapped

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
