module Telnyx
  module Models
    module AI
      module Memory
        module Namespaces
          type profile_list_response =
            { memory_count: Integer, profile_id: String }

          class ProfileListResponse < Telnyx::Internal::Type::BaseModel
            attr_accessor memory_count: Integer

            attr_accessor profile_id: String

            def initialize: (memory_count: Integer, profile_id: String) -> void

            def to_hash: -> { memory_count: Integer, profile_id: String }
          end
        end
      end
    end
  end
end
