module Telnyx
  module Models
    module Enterprises
      type reputation_retrieve_response =
        { data: Telnyx::Enterprises::EnterpriseReputationPublic }

      class ReputationRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: Telnyx::Enterprises::EnterpriseReputationPublic

        def initialize: (
          data: Telnyx::Enterprises::EnterpriseReputationPublic
        ) -> void

        def to_hash: -> {
          data: Telnyx::Enterprises::EnterpriseReputationPublic
        }
      end
    end
  end
end
