module Telnyx
  module Models
    module Enterprises
      type reputation_enable_params =
        {
          enterprise_id: String,
          loa_document_id: String,
          check_frequency: Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency
        }
        & Telnyx::Internal::Type::request_parameters

      class ReputationEnableParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor enterprise_id: String

        attr_accessor loa_document_id: String

        attr_reader check_frequency: Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency?

        def check_frequency=: (
          Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency
        ) -> Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency

        def initialize: (
          enterprise_id: String,
          loa_document_id: String,
          ?check_frequency: Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          enterprise_id: String,
          loa_document_id: String,
          check_frequency: Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency,
          request_options: Telnyx::RequestOptions
        }

        type check_frequency =
          :business_daily | :daily | :weekly | :biweekly | :monthly | :never

        module CheckFrequency
          extend Telnyx::Internal::Type::Enum

          BUSINESS_DAILY: :business_daily
          DAILY: :daily
          WEEKLY: :weekly
          BIWEEKLY: :biweekly
          MONTHLY: :monthly
          NEVER: :never

          def self?.values: -> ::Array[Telnyx::Models::Enterprises::ReputationEnableParams::check_frequency]
        end
      end
    end
  end
end
