module Telnyx
  module Models
    module Portouts
      type comment_list_response =
        {
          data: ::Array[Telnyx::Portouts::PortoutComment],
          meta: Telnyx::Metadata
        }

      class CommentListResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::Portouts::PortoutComment]?

        def data=: (
          ::Array[Telnyx::Portouts::PortoutComment]
        ) -> ::Array[Telnyx::Portouts::PortoutComment]

        attr_reader meta: Telnyx::Metadata?

        def meta=: (Telnyx::Metadata) -> Telnyx::Metadata

        def initialize: (
          ?data: ::Array[Telnyx::Portouts::PortoutComment],
          ?meta: Telnyx::Metadata
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::Portouts::PortoutComment],
          meta: Telnyx::Metadata
        }
      end
    end
  end
end
