module Telnyx
  module Models
    module Portouts
      type event_retrieve_response =
        { data: Telnyx::Models::Portouts::EventRetrieveResponse::data }

      class EventRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Models::Portouts::EventRetrieveResponse::data?

        def data=: (
          Telnyx::Models::Portouts::EventRetrieveResponse::data
        ) -> Telnyx::Models::Portouts::EventRetrieveResponse::data

        def initialize: (
          ?data: Telnyx::Models::Portouts::EventRetrieveResponse::data
        ) -> void

        def to_hash: -> {
          data: Telnyx::Models::Portouts::EventRetrieveResponse::data
        }

        type data =
          Telnyx::Portouts::WebhookPortoutStatusChanged
          | Telnyx::Portouts::WebhookPortoutNewComment
          | Telnyx::Portouts::WebhookPortoutFocDateChanged

        module Data
          extend Telnyx::Internal::Type::Union

          def self?.variants: -> ::Array[Telnyx::Models::Portouts::EventRetrieveResponse::data]
        end
      end
    end
  end
end
