module Telnyx
  module Models
    module Portouts
      type event_retrieve_response =
        { data: Telnyx::Models::Portouts::portout_event }

      class EventRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Models::Portouts::portout_event?

        def data=: (
          Telnyx::Models::Portouts::portout_event
        ) -> Telnyx::Models::Portouts::portout_event

        def initialize: (?data: Telnyx::Models::Portouts::portout_event) -> void

        def to_hash: -> { data: Telnyx::Models::Portouts::portout_event }
      end
    end
  end
end
