module Telnyx
  module Resources
    class AccessIPRanges
      def create: (
        cidr_block: String,
        ?description: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::AccessIPRange

      def list: (
        ?filter: Telnyx::AccessIPRangeListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::AccessIPRange]

      def delete: (
        String access_ip_range_id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::AccessIPRange

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
