module Telnyx
  module Resources
    class AuditEvents
      def list: (
        ?filter: Telnyx::AuditEventListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort: Telnyx::Models::AuditEventListParams::sort,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::AuditEventListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
