module Telnyx
  module Resources
    class AuditEvents
      def list: (
        ?filter: Telnyx::AuditEventListParams::Filter,
        ?page: Telnyx::AuditEventListParams::Page,
        ?sort: Telnyx::Models::AuditEventListParams::sort,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::AuditEventListResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
