module Telnyx
  module Resources
    class Brand
      attr_reader external_vetting: Telnyx::Resources::Brand::ExternalVetting

      attr_reader sms_otp: Telnyx::Resources::Brand::SMSOtp

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
