module Telnyx
  module Resources
    class Campaign
      attr_reader usecase: Telnyx::Resources::Campaign::Usecase

      attr_reader osr: Telnyx::Resources::Campaign::Osr

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
