module Telnyx
  module Resources
    class ChannelZones
      def update: (
        String channel_zone_id,
        channels: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::ChannelZoneUpdateResponse

      def list: (
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::ChannelZoneListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
