module Telnyx
  module Resources
    class CustomStorageCredentials
      def create: (
        String connection_id,
        backend: Telnyx::Models::CustomStorageConfiguration::backend,
        configuration: Telnyx::Models::CustomStorageConfiguration::configuration,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::CustomStorageCredentialCreateResponse

      def retrieve: (
        String connection_id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::CustomStorageCredentialRetrieveResponse

      def update: (
        String connection_id,
        backend: Telnyx::Models::CustomStorageConfiguration::backend,
        configuration: Telnyx::Models::CustomStorageConfiguration::configuration,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::CustomStorageCredentialUpdateResponse

      def delete: (
        String connection_id,
        ?request_options: Telnyx::request_opts
      ) -> nil

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
