module Telnyx
  module Resources
    class DetailRecords
      def list: (
        ?filter: Telnyx::DetailRecordListParams::Filter,
        ?page: Telnyx::DetailRecordListParams::Page,
        ?sort: ::Array[String],
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DetailRecordListResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
