module Telnyx
  module Resources
    class DetailRecords
      def list: (
        ?filter: Telnyx::DetailRecordListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort: ::Array[String],
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::detail_record_list_response]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
