module Telnyx
  module Resources
    class Documents
      def retrieve: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentRetrieveResponse

      def update: (
        String document_id,
        ?customer_reference: String,
        ?filename: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentUpdateResponse

      def list: (
        ?filter: Telnyx::DocumentListParams::Filter,
        ?page: Telnyx::DocumentListParams::Page,
        ?sort: ::Array[Telnyx::Models::DocumentListParams::sort],
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultPagination[Telnyx::DocServiceDocument]

      def delete: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentDeleteResponse

      def download: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> StringIO

      def generate_download_link: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentGenerateDownloadLinkResponse

      def upload: (
        document: Telnyx::DocumentUploadParams::Document,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentUploadResponse

      def upload_json: (
        document: Telnyx::DocumentUploadJsonParams::Document,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::DocumentUploadJsonResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
