module Telnyx
  module Resources
    class Enum
      def retrieve: (
        Telnyx::Models::EnumRetrieveParams::endpoint endpoint,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::enum_retrieve_response

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
