module Telnyx
  module Resources
    class GlobalIPAssignments
      def create: (
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::GlobalIPAssignmentCreateResponse

      def retrieve: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::GlobalIPAssignmentRetrieveResponse

      def update: (
        String global_ip_assignment_id,
        global_ip_assignment_update_request: Telnyx::GlobalIPAssignmentUpdateParams::GlobalIPAssignmentUpdateRequest,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::GlobalIPAssignmentUpdateResponse

      def list: (
        ?page: Telnyx::GlobalIPAssignmentListParams::Page,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultPagination[Telnyx::GlobalIPAssignment]

      def delete: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::GlobalIPAssignmentDeleteResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
