module Telnyx
  module Resources
    class GlobalIPUsage
      def retrieve: (
        ?filter: Telnyx::GlobalIPUsageRetrieveParams::Filter,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::GlobalIPUsageRetrieveResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
