module Telnyx
  module Resources
    class IntegrationSecrets
      def create: (
        identifier: String,
        type: Telnyx::Models::IntegrationSecretCreateParams::type_,
        ?token: String,
        ?password: String,
        ?username: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::IntegrationSecretCreateResponse

      def list: (
        ?filter: Telnyx::IntegrationSecretListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::IntegrationSecret]

      def delete: (String id, ?request_options: Telnyx::request_opts) -> nil

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
