module Telnyx
  module Resources
    class MobilePushCredentials
      def create: (
        create_mobile_push_credential_request: Telnyx::Models::MobilePushCredentialCreateParams::create_mobile_push_credential_request,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::PushCredentialResponse

      def retrieve: (
        String push_credential_id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::PushCredentialResponse

      def list: (
        ?filter: Telnyx::MobilePushCredentialListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::PushCredential]

      def delete: (
        String push_credential_id,
        ?request_options: Telnyx::request_opts
      ) -> nil

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
