module Telnyx
  module Resources
    class NetworkCoverage
      def list: (
        ?filter: Telnyx::NetworkCoverageListParams::Filter,
        ?filters: Telnyx::NetworkCoverageListParams::Filters,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::NetworkCoverageListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
