module Telnyx
  module Resources
    class NotificationEvents
      def list: (
        ?page: Telnyx::NotificationEventListParams::Page,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultPagination[Telnyx::Models::NotificationEventListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
