module Telnyx
  module Resources
    class PortingPhoneNumbers
      def list: (
        ?filter: Telnyx::PortingPhoneNumberListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::PortingPhoneNumberListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
