module Telnyx
  module Resources
    class PronunciationDicts
      def create: (
        items: ::Array[Telnyx::Models::pronunciation_dict_item],
        name: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::PronunciationDictResponse

      def retrieve: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::PronunciationDictResponse

      def update: (
        String id,
        ?items: ::Array[Telnyx::Models::pronunciation_dict_item],
        ?name: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::PronunciationDictResponse

      def list: (
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::PronunciationDictData]

      def delete: (String id, ?request_options: Telnyx::request_opts) -> nil

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
