module Telnyx
  module Resources
    class Regions
      def list: (
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::RegionListResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
