module Telnyx
  module Resources
    class Requirements
      def retrieve: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::RequirementRetrieveResponse

      def list: (
        ?filter: Telnyx::RequirementListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort: ::Array[Telnyx::Models::RequirementListParams::sort],
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::RequirementListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
