module Telnyx
  module Resources
    class Texml
      attr_reader accounts: Telnyx::Resources::Texml::Accounts

      def initiate_ai_call: (
        String connection_id,
        ai_assistant_id: String,
        from: String,
        to: String,
        ?ai_assistant_dynamic_variables: ::Hash[Symbol, String],
        ?ai_assistant_version: String,
        ?async_amd: bool,
        ?async_amd_status_callback: String,
        ?async_amd_status_callback_method: Telnyx::Models::TexmlInitiateAICallParams::async_amd_status_callback_method,
        ?caller_id: String,
        ?conversation_callback: String,
        ?conversation_callback_method: Telnyx::Models::TexmlInitiateAICallParams::conversation_callback_method,
        ?conversation_callbacks: ::Array[String],
        ?custom_headers: ::Array[Telnyx::TexmlInitiateAICallParams::CustomHeader],
        ?detection_mode: Telnyx::Models::TexmlInitiateAICallParams::detection_mode,
        ?machine_detection: Telnyx::Models::TexmlInitiateAICallParams::machine_detection,
        ?machine_detection_silence_timeout: Integer,
        ?machine_detection_speech_end_threshold: Integer,
        ?machine_detection_speech_threshold: Integer,
        ?machine_detection_timeout: Integer,
        ?passports: String,
        ?preferred_codecs: String,
        ?record: bool,
        ?recording_channels: Telnyx::Models::TexmlInitiateAICallParams::recording_channels,
        ?recording_status_callback: String,
        ?recording_status_callback_event: String,
        ?recording_status_callback_method: Telnyx::Models::TexmlInitiateAICallParams::recording_status_callback_method,
        ?recording_timeout: Integer,
        ?recording_track: Telnyx::Models::TexmlInitiateAICallParams::recording_track,
        ?send_recording_url: bool,
        ?sip_auth_password: String,
        ?sip_auth_username: String,
        ?sip_region: Telnyx::Models::TexmlInitiateAICallParams::sip_region,
        ?status_callback: String,
        ?status_callback_event: String,
        ?status_callback_method: Telnyx::Models::TexmlInitiateAICallParams::status_callback_method,
        ?status_callbacks: ::Array[String],
        ?time_limit: Integer,
        ?timeout_seconds: Integer,
        ?trim: Telnyx::Models::TexmlInitiateAICallParams::trim,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::TexmlInitiateAICallResponse

      def secrets: (
        name: String,
        value: String,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::TexmlSecretsResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
