module Telnyx
  module Resources
    class UserTags
      def list: (
        ?filter: Telnyx::UserTagListParams::Filter,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::UserTagListResponse

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
