module Telnyx
  module Resources
    class VirtualCrossConnectsCoverage
      def list: (
        ?filter: Telnyx::VirtualCrossConnectsCoverageListParams::Filter,
        ?filters: Telnyx::VirtualCrossConnectsCoverageListParams::Filters,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::VirtualCrossConnectsCoverageListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
