module Telnyx
  module Resources
    class WebhookDeliveries
      def retrieve: (
        String id,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Models::WebhookDeliveryRetrieveResponse

      def list: (
        ?filter: Telnyx::WebhookDeliveryListParams::Filter,
        ?page_number: Integer,
        ?page_size: Integer,
        ?request_options: Telnyx::request_opts
      ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::Models::WebhookDeliveryListResponse]

      def initialize: (client: Telnyx::Client) -> void
    end
  end
end
