module Telnyx
  module Resources
    class TermsOfService
      class Agreements
        def retrieve: (
          String agreement_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::TermsOfService::TosAgreementWrapped

        def list: (
          ?page_number: Integer,
          ?page_size: Integer,
          ?product_type: Telnyx::Models::TermsOfService::tos_product_type,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Internal::DefaultFlatPagination[Telnyx::TermsOfService::TosAgreement]

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
