module Telnyx
  module Models
    module SimCards
      type action_set_standby_response =
        { data: Telnyx::SimCards::WirelessSimCardAction }

      class ActionSetStandbyResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::SimCards::WirelessSimCardAction?

        def data=: (
          Telnyx::SimCards::WirelessSimCardAction
        ) -> Telnyx::SimCards::WirelessSimCardAction

        def initialize: (?data: Telnyx::SimCards::WirelessSimCardAction) -> void

        def to_hash: -> { data: Telnyx::SimCards::WirelessSimCardAction }
      end
    end
  end
end
