module Telnyx
  module Models
    module SimCards
      type action_enable_response = { data: Telnyx::SimCards::SimCardAction }

      class ActionEnableResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::SimCards::SimCardAction?

        def data=: (
          Telnyx::SimCards::SimCardAction
        ) -> Telnyx::SimCards::SimCardAction

        def initialize: (?data: Telnyx::SimCards::SimCardAction) -> void

        def to_hash: -> { data: Telnyx::SimCards::SimCardAction }
      end
    end
  end
end
