module Telnyx
  module Internal
    class DefaultFlatPaginationTopLevelArray[Elem] < ::Array[Elem]
      include Telnyx::Internal::Type::BasePage[Elem]

      def next_page?: -> bool

      def next_page: -> instance

      def auto_paging_each: { (Elem arg0) -> void } -> void

      def inspect: -> String
    end
  end
end
