module Telnyx
  module Internal
    class DefaultPaginationForMessagingTollfree[Elem]
      include Telnyx::Internal::Type::BasePage[Elem]

      attr_accessor records: ::Array[Elem]?

      attr_accessor total_records: Integer

      def inspect: -> String
    end
  end
end
