module Telnyx
  module Internal
    class EmailCursorPagination[Elem]
      include Telnyx::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor meta: Meta

      def inspect: -> String

      type meta = { page_cursor: String }
      class Meta < Telnyx::Internal::Type::BaseModel
        attr_reader page_cursor: String?

        def page_cursor=: (String) -> String

        def initialize: (?page_cursor: String) -> void

        def to_hash: -> { page_cursor: String }
      end
    end
  end
end
