# frozen_string_literal: true

module Telnyx
  module Models
    module AI
      # The handoff tool allows the assistant to hand off control of the conversation to
      # another AI assistant. By default, this will happen transparently to the end
      # user.
      module AssistantTool
        extend Telnyx::Internal::Type::Union

        discriminator :type

        variant :webhook, -> { Telnyx::AI::InferenceEmbeddingWebhookToolParams }

        variant :retrieval, -> { Telnyx::AI::RetrievalTool }

        # The handoff tool allows the assistant to hand off control of the conversation to another AI assistant. By default, this will happen transparently to the end user.
        variant :handoff, -> { Telnyx::AI::AssistantTool::Handoff }

        variant :hangup, -> { Telnyx::AI::HangupTool }

        variant :transfer, -> { Telnyx::AI::AssistantTool::Transfer }

        variant :refer, -> { Telnyx::AI::AssistantTool::Refer }

        variant :send_dtmf, -> { Telnyx::AI::AssistantTool::SendDtmf }

        # The send_message tool allows the assistant to send SMS or MMS messages to the end user. The 'to' and 'from' addresses are automatically determined from the conversation context, and the message text is generated by the assistant.
        variant :send_message, -> { Telnyx::AI::AssistantTool::SendMessage }

        class Handoff < Telnyx::Internal::Type::BaseModel
          # @!attribute handoff
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Handoff::Handoff]
          required :handoff, -> { Telnyx::AI::AssistantTool::Handoff::Handoff }

          # @!attribute type
          #
          #   @return [Symbol, :handoff]
          required :type, const: :handoff

          # @!method initialize(handoff:, type: :handoff)
          #   The handoff tool allows the assistant to hand off control of the conversation to
          #   another AI assistant. By default, this will happen transparently to the end
          #   user.
          #
          #   @param handoff [Telnyx::Models::AI::AssistantTool::Handoff::Handoff]
          #   @param type [Symbol, :handoff]

          # @see Telnyx::Models::AI::AssistantTool::Handoff#handoff
          class Handoff < Telnyx::Internal::Type::BaseModel
            # @!attribute ai_assistants
            #   List of possible assistants that can receive a handoff.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Handoff::Handoff::AIAssistant>]
            required :ai_assistants,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Handoff::Handoff::AIAssistant] }

            # @!attribute voice_mode
            #   With the unified voice mode all assistants share the same voice, making the
            #   handoff transparent to the user. With the distinct voice mode all assistants
            #   retain their voice configuration, providing the experience of a conference call
            #   with a team of assistants.
            #
            #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Handoff::Handoff::VoiceMode, nil]
            optional :voice_mode, enum: -> { Telnyx::AI::AssistantTool::Handoff::Handoff::VoiceMode }

            # @!method initialize(ai_assistants:, voice_mode: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Handoff::Handoff} for more details.
            #
            #   @param ai_assistants [Array<Telnyx::Models::AI::AssistantTool::Handoff::Handoff::AIAssistant>] List of possible assistants that can receive a handoff.
            #
            #   @param voice_mode [Symbol, Telnyx::Models::AI::AssistantTool::Handoff::Handoff::VoiceMode] With the unified voice mode all assistants share the same voice, making the hand

            class AIAssistant < Telnyx::Internal::Type::BaseModel
              # @!attribute id
              #   The ID of the assistant to hand off to.
              #
              #   @return [String]
              required :id, String

              # @!attribute name
              #   Helpful name for giving context on when to handoff to the assistant.
              #
              #   @return [String]
              required :name, String

              # @!method initialize(id:, name:)
              #   @param id [String] The ID of the assistant to hand off to.
              #
              #   @param name [String] Helpful name for giving context on when to handoff to the assistant.
            end

            # With the unified voice mode all assistants share the same voice, making the
            # handoff transparent to the user. With the distinct voice mode all assistants
            # retain their voice configuration, providing the experience of a conference call
            # with a team of assistants.
            #
            # @see Telnyx::Models::AI::AssistantTool::Handoff::Handoff#voice_mode
            module VoiceMode
              extend Telnyx::Internal::Type::Enum

              UNIFIED = :unified
              DISTINCT = :distinct

              # @!method self.values
              #   @return [Array<Symbol>]
            end
          end
        end

        class Transfer < Telnyx::Internal::Type::BaseModel
          # @!attribute transfer
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer]
          required :transfer, -> { Telnyx::AI::AssistantTool::Transfer::Transfer }

          # @!attribute type
          #
          #   @return [Symbol, :transfer]
          required :type, const: :transfer

          # @!method initialize(transfer:, type: :transfer)
          #   @param transfer [Telnyx::Models::AI::AssistantTool::Transfer::Transfer]
          #   @param type [Symbol, :transfer]

          # @see Telnyx::Models::AI::AssistantTool::Transfer#transfer
          class Transfer < Telnyx::Internal::Type::BaseModel
            # @!attribute from
            #   Number or SIP URI placing the call.
            #
            #   @return [String]
            required :from, String

            # @!attribute targets
            #   The different possible targets of the transfer. The assistant will be able to
            #   choose one of the targets to transfer the call to.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::Target>]
            required :targets,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Transfer::Transfer::Target] }

            # @!attribute custom_headers
            #   Custom headers to be added to the SIP INVITE for the transfer command.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader>, nil]
            optional :custom_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Transfer::Transfer::CustomHeader] }

            # @!attribute voicemail_detection
            #   Configuration for voicemail detection (AMD - Answering Machine Detection) on the
            #   transferred call. Allows the assistant to detect when a voicemail system answers
            #   the transferred call and take appropriate action.
            #
            #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection, nil]
            optional :voicemail_detection, -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection }

            # @!attribute warm_transfer_instructions
            #   Natural language instructions for your agent for how to provide context for the
            #   transfer recipient.
            #
            #   @return [String, nil]
            optional :warm_transfer_instructions, String

            # @!method initialize(from:, targets:, custom_headers: nil, voicemail_detection: nil, warm_transfer_instructions: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer} for more details.
            #
            #   @param from [String] Number or SIP URI placing the call.
            #
            #   @param targets [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::Target>] The different possible targets of the transfer. The assistant will be able to ch
            #
            #   @param custom_headers [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader>] Custom headers to be added to the SIP INVITE for the transfer command.
            #
            #   @param voicemail_detection [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection] Configuration for voicemail detection (AMD - Answering Machine Detection) on the
            #
            #   @param warm_transfer_instructions [String] Natural language instructions for your agent for how to provide context for the

            class Target < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #   The name of the target.
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute to
              #   The destination number or SIP URI of the call.
              #
              #   @return [String, nil]
              optional :to, String

              # @!method initialize(name: nil, to: nil)
              #   @param name [String] The name of the target.
              #
              #   @param to [String] The destination number or SIP URI of the call.
            end

            class CustomHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader} for more
              #   details.
              #
              #   @param name [String]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.
            end

            # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer#voicemail_detection
            class VoicemailDetection < Telnyx::Internal::Type::BaseModel
              # @!attribute detection_config
              #   Advanced AMD detection configuration parameters. All values are optional -
              #   Telnyx will use defaults if not specified.
              #
              #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionConfig, nil]
              optional :detection_config,
                       -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionConfig }

              # @!attribute detection_mode
              #   The AMD detection mode to use. 'detect' enables answering machine detection
              #   (works best when warm transfer instructions are also set). 'disabled' turns off
              #   AMD detection.
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionMode, nil]
              optional :detection_mode,
                       enum: -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionMode }

              # @!attribute on_voicemail_detected
              #   Action to take when voicemail is detected on the transferred call.
              #
              #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected, nil]
              optional :on_voicemail_detected,
                       -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected }

              # @!method initialize(detection_config: nil, detection_mode: nil, on_voicemail_detected: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection} for
              #   more details.
              #
              #   Configuration for voicemail detection (AMD - Answering Machine Detection) on the
              #   transferred call. Allows the assistant to detect when a voicemail system answers
              #   the transferred call and take appropriate action.
              #
              #   @param detection_config [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionConfig] Advanced AMD detection configuration parameters. All values are optional - Telny
              #
              #   @param detection_mode [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionMode] The AMD detection mode to use. 'detect' enables answering machine detection (wor
              #
              #   @param on_voicemail_detected [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected] Action to take when voicemail is detected on the transferred call.

              # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection#detection_config
              class DetectionConfig < Telnyx::Internal::Type::BaseModel
                # @!attribute after_greeting_silence_millis
                #   Duration of silence after greeting detection before finalizing the result.
                #
                #   @return [Integer, nil]
                optional :after_greeting_silence_millis, Integer

                # @!attribute between_words_silence_millis
                #   Maximum silence duration between words during greeting.
                #
                #   @return [Integer, nil]
                optional :between_words_silence_millis, Integer

                # @!attribute greeting_duration_millis
                #   Expected duration of greeting speech.
                #
                #   @return [Integer, nil]
                optional :greeting_duration_millis, Integer

                # @!attribute greeting_silence_duration_millis
                #   Duration of silence after the greeting to wait before considering the greeting
                #   complete.
                #
                #   @return [Integer, nil]
                optional :greeting_silence_duration_millis, Integer

                # @!attribute greeting_total_analysis_time_millis
                #   Maximum time to spend analyzing the greeting.
                #
                #   @return [Integer, nil]
                optional :greeting_total_analysis_time_millis, Integer

                # @!attribute initial_silence_millis
                #   Maximum silence duration at the start of the call before speech.
                #
                #   @return [Integer, nil]
                optional :initial_silence_millis, Integer

                # @!attribute maximum_number_of_words
                #   Maximum number of words expected in a human greeting.
                #
                #   @return [Integer, nil]
                optional :maximum_number_of_words, Integer

                # @!attribute maximum_word_length_millis
                #   Maximum duration of a single word.
                #
                #   @return [Integer, nil]
                optional :maximum_word_length_millis, Integer

                # @!attribute min_word_length_millis
                #   Minimum duration for audio to be considered a word.
                #
                #   @return [Integer, nil]
                optional :min_word_length_millis, Integer

                # @!attribute silence_threshold
                #   Audio level threshold for silence detection.
                #
                #   @return [Integer, nil]
                optional :silence_threshold, Integer

                # @!attribute total_analysis_time_millis
                #   Total time allowed for AMD analysis.
                #
                #   @return [Integer, nil]
                optional :total_analysis_time_millis, Integer

                # @!method initialize(after_greeting_silence_millis: nil, between_words_silence_millis: nil, greeting_duration_millis: nil, greeting_silence_duration_millis: nil, greeting_total_analysis_time_millis: nil, initial_silence_millis: nil, maximum_number_of_words: nil, maximum_word_length_millis: nil, min_word_length_millis: nil, silence_threshold: nil, total_analysis_time_millis: nil)
                #   Some parameter documentations has been truncated, see
                #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::DetectionConfig}
                #   for more details.
                #
                #   Advanced AMD detection configuration parameters. All values are optional -
                #   Telnyx will use defaults if not specified.
                #
                #   @param after_greeting_silence_millis [Integer] Duration of silence after greeting detection before finalizing the result.
                #
                #   @param between_words_silence_millis [Integer] Maximum silence duration between words during greeting.
                #
                #   @param greeting_duration_millis [Integer] Expected duration of greeting speech.
                #
                #   @param greeting_silence_duration_millis [Integer] Duration of silence after the greeting to wait before considering the greeting c
                #
                #   @param greeting_total_analysis_time_millis [Integer] Maximum time to spend analyzing the greeting.
                #
                #   @param initial_silence_millis [Integer] Maximum silence duration at the start of the call before speech.
                #
                #   @param maximum_number_of_words [Integer] Maximum number of words expected in a human greeting.
                #
                #   @param maximum_word_length_millis [Integer] Maximum duration of a single word.
                #
                #   @param min_word_length_millis [Integer] Minimum duration for audio to be considered a word.
                #
                #   @param silence_threshold [Integer] Audio level threshold for silence detection.
                #
                #   @param total_analysis_time_millis [Integer] Total time allowed for AMD analysis.
              end

              # The AMD detection mode to use. 'detect' enables answering machine detection
              # (works best when warm transfer instructions are also set). 'disabled' turns off
              # AMD detection.
              #
              # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection#detection_mode
              module DetectionMode
                extend Telnyx::Internal::Type::Enum

                DISABLED = :disabled
                DETECT = :detect

                # @!method self.values
                #   @return [Array<Symbol>]
              end

              # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection#on_voicemail_detected
              class OnVoicemailDetected < Telnyx::Internal::Type::BaseModel
                # @!attribute action
                #   The action to take when voicemail is detected. 'stop_transfer' hangs up
                #   immediately. 'leave_message_and_stop_transfer' leaves a message then hangs up.
                #   'continue_transfer' bridges the call despite voicemail detection.
                #
                #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::Action, nil]
                optional :action,
                         enum: -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::Action }

                # @!attribute voicemail_message
                #   Configuration for the voicemail message to leave. Only applicable when action is
                #   'leave_message_and_stop_transfer'.
                #
                #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage, nil]
                optional :voicemail_message,
                         -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage }

                # @!method initialize(action: nil, voicemail_message: nil)
                #   Some parameter documentations has been truncated, see
                #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected}
                #   for more details.
                #
                #   Action to take when voicemail is detected on the transferred call.
                #
                #   @param action [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::Action] The action to take when voicemail is detected. 'stop_transfer' hangs up immediat
                #
                #   @param voicemail_message [Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage] Configuration for the voicemail message to leave. Only applicable when action is

                # The action to take when voicemail is detected. 'stop_transfer' hangs up
                # immediately. 'leave_message_and_stop_transfer' leaves a message then hangs up.
                # 'continue_transfer' bridges the call despite voicemail detection.
                #
                # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected#action
                module Action
                  extend Telnyx::Internal::Type::Enum

                  STOP_TRANSFER = :stop_transfer
                  LEAVE_MESSAGE_AND_STOP_TRANSFER = :leave_message_and_stop_transfer
                  CONTINUE_TRANSFER = :continue_transfer

                  # @!method self.values
                  #   @return [Array<Symbol>]
                end

                # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected#voicemail_message
                class VoicemailMessage < Telnyx::Internal::Type::BaseModel
                  # @!attribute message
                  #   The specific message to leave as voicemail (converted to speech). Only
                  #   applicable when type is 'message'.
                  #
                  #   @return [String, nil]
                  optional :message, String

                  # @!attribute type
                  #   The type of voicemail message. Use 'message' to leave a specific TTS message, or
                  #   'warm_transfer_instructions' to play the warm transfer audio.
                  #
                  #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage::Type, nil]
                  optional :type,
                           enum: -> { Telnyx::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage::Type }

                  # @!method initialize(message: nil, type: nil)
                  #   Some parameter documentations has been truncated, see
                  #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage}
                  #   for more details.
                  #
                  #   Configuration for the voicemail message to leave. Only applicable when action is
                  #   'leave_message_and_stop_transfer'.
                  #
                  #   @param message [String] The specific message to leave as voicemail (converted to speech). Only applicabl
                  #
                  #   @param type [Symbol, Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage::Type] The type of voicemail message. Use 'message' to leave a specific TTS message, or

                  # The type of voicemail message. Use 'message' to leave a specific TTS message, or
                  # 'warm_transfer_instructions' to play the warm transfer audio.
                  #
                  # @see Telnyx::Models::AI::AssistantTool::Transfer::Transfer::VoicemailDetection::OnVoicemailDetected::VoicemailMessage#type
                  module Type
                    extend Telnyx::Internal::Type::Enum

                    MESSAGE = :message
                    WARM_TRANSFER_INSTRUCTIONS = :warm_transfer_instructions

                    # @!method self.values
                    #   @return [Array<Symbol>]
                  end
                end
              end
            end
          end
        end

        class Refer < Telnyx::Internal::Type::BaseModel
          # @!attribute refer
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Refer::Refer]
          required :refer, -> { Telnyx::AI::AssistantTool::Refer::Refer }

          # @!attribute type
          #
          #   @return [Symbol, :refer]
          required :type, const: :refer

          # @!method initialize(refer:, type: :refer)
          #   @param refer [Telnyx::Models::AI::AssistantTool::Refer::Refer]
          #   @param type [Symbol, :refer]

          # @see Telnyx::Models::AI::AssistantTool::Refer#refer
          class Refer < Telnyx::Internal::Type::BaseModel
            # @!attribute targets
            #   The different possible targets of the SIP refer. The assistant will be able to
            #   choose one of the targets to refer the call to.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::Target>]
            required :targets, -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::Target] }

            # @!attribute custom_headers
            #   Custom headers to be added to the SIP REFER.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader>, nil]
            optional :custom_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::CustomHeader] }

            # @!attribute sip_headers
            #   SIP headers to be added to the SIP REFER. Currently only User-to-User and
            #   Diversion headers are supported.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader>, nil]
            optional :sip_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::SipHeader] }

            # @!method initialize(targets:, custom_headers: nil, sip_headers: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Refer::Refer} for more details.
            #
            #   @param targets [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::Target>] The different possible targets of the SIP refer. The assistant will be able to c
            #
            #   @param custom_headers [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader>] Custom headers to be added to the SIP REFER.
            #
            #   @param sip_headers [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader>] SIP headers to be added to the SIP REFER. Currently only User-to-User and Divers

            class Target < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #   The name of the target.
              #
              #   @return [String]
              required :name, String

              # @!attribute sip_address
              #   The SIP URI to which the call will be referred.
              #
              #   @return [String]
              required :sip_address, String

              # @!attribute sip_auth_password
              #   SIP Authentication password used for SIP challenges.
              #
              #   @return [String, nil]
              optional :sip_auth_password, String

              # @!attribute sip_auth_username
              #   SIP Authentication username used for SIP challenges.
              #
              #   @return [String, nil]
              optional :sip_auth_username, String

              # @!method initialize(name:, sip_address:, sip_auth_password: nil, sip_auth_username: nil)
              #   @param name [String] The name of the target.
              #
              #   @param sip_address [String] The SIP URI to which the call will be referred.
              #
              #   @param sip_auth_password [String] SIP Authentication password used for SIP challenges.
              #
              #   @param sip_auth_username [String] SIP Authentication username used for SIP challenges.
            end

            class CustomHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader} for more
              #   details.
              #
              #   @param name [String]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.
            end

            class SipHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader::Name, nil]
              optional :name, enum: -> { Telnyx::AI::AssistantTool::Refer::Refer::SipHeader::Name }

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader} for more details.
              #
              #   @param name [Symbol, Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader::Name]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.

              # @see Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader#name
              module Name
                extend Telnyx::Internal::Type::Enum

                USER_TO_USER = :"User-to-User"
                DIVERSION = :Diversion

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end
          end
        end

        class SendDtmf < Telnyx::Internal::Type::BaseModel
          # @!attribute send_dtmf
          #
          #   @return [Hash{Symbol=>Object}]
          required :send_dtmf, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

          # @!attribute type
          #
          #   @return [Symbol, :send_dtmf]
          required :type, const: :send_dtmf

          # @!method initialize(send_dtmf:, type: :send_dtmf)
          #   @param send_dtmf [Hash{Symbol=>Object}]
          #   @param type [Symbol, :send_dtmf]
        end

        class SendMessage < Telnyx::Internal::Type::BaseModel
          # @!attribute send_message
          #
          #   @return [Hash{Symbol=>Object}]
          required :send_message, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

          # @!attribute type
          #
          #   @return [Symbol, :send_message]
          required :type, const: :send_message

          # @!method initialize(send_message:, type: :send_message)
          #   The send_message tool allows the assistant to send SMS or MMS messages to the
          #   end user. The 'to' and 'from' addresses are automatically determined from the
          #   conversation context, and the message text is generated by the assistant.
          #
          #   @param send_message [Hash{Symbol=>Object}]
          #   @param type [Symbol, :send_message]
        end

        # @!method self.variants
        #   @return [Array(Telnyx::Models::AI::InferenceEmbeddingWebhookToolParams, Telnyx::Models::AI::RetrievalTool, Telnyx::Models::AI::AssistantTool::Handoff, Telnyx::Models::AI::HangupTool, Telnyx::Models::AI::AssistantTool::Transfer, Telnyx::Models::AI::AssistantTool::Refer, Telnyx::Models::AI::AssistantTool::SendDtmf, Telnyx::Models::AI::AssistantTool::SendMessage)]
      end
    end
  end
end
