# frozen_string_literal: true

module Telnyx
  module Models
    module AI
      # The handoff tool allows the assistant to hand off control of the conversation to
      # another AI assistant. By default, this will happen transparently to the end
      # user.
      module AssistantTool
        extend Telnyx::Internal::Type::Union

        discriminator :type

        variant :webhook, -> { Telnyx::AI::AssistantTool::Webhook }

        variant :retrieval, -> { Telnyx::AI::RetrievalTool }

        # The handoff tool allows the assistant to hand off control of the conversation to another AI assistant. By default, this will happen transparently to the end user.
        variant :handoff, -> { Telnyx::AI::AssistantTool::Handoff }

        variant :hangup, -> { Telnyx::AI::HangupTool }

        variant :transfer, -> { Telnyx::AI::AssistantTool::Transfer }

        variant :refer, -> { Telnyx::AI::AssistantTool::Refer }

        variant :send_dtmf, -> { Telnyx::AI::AssistantTool::SendDtmf }

        # The send_message tool allows the assistant to send SMS or MMS messages to the end user. The 'to' and 'from' addresses are automatically determined from the conversation context, and the message text is generated by the assistant.
        variant :send_message, -> { Telnyx::AI::AssistantTool::SendMessage }

        class Webhook < Telnyx::Internal::Type::BaseModel
          # @!attribute type
          #
          #   @return [Symbol, :webhook]
          required :type, const: :webhook

          # @!attribute webhook
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Webhook::Webhook]
          required :webhook, -> { Telnyx::AI::AssistantTool::Webhook::Webhook }

          # @!method initialize(webhook:, type: :webhook)
          #   @param webhook [Telnyx::Models::AI::AssistantTool::Webhook::Webhook]
          #   @param type [Symbol, :webhook]

          # @see Telnyx::Models::AI::AssistantTool::Webhook#webhook
          class Webhook < Telnyx::Internal::Type::BaseModel
            # @!attribute description
            #   The description of the tool.
            #
            #   @return [String]
            required :description, String

            # @!attribute name
            #   The name of the tool.
            #
            #   @return [String]
            required :name, String

            # @!attribute url
            #   The URL of the external tool to be called. This URL is going to be used by the
            #   assistant. The URL can be templated like: `https://example.com/api/v1/{id}`,
            #   where `{id}` is a placeholder for a value that will be provided by the assistant
            #   if `path_parameters` are provided with the `id` attribute.
            #
            #   @return [String]
            required :url, String

            # @!attribute async
            #   If async, the assistant will move forward without waiting for your server to
            #   respond.
            #
            #   @return [Boolean, nil]
            optional :async, Telnyx::Internal::Type::Boolean

            # @!attribute body_parameters
            #   The body parameters the webhook tool accepts, described as a JSON Schema object.
            #   These parameters will be passed to the webhook as the body of the request. See
            #   the [JSON Schema reference](https://json-schema.org/understanding-json-schema)
            #   for documentation about the format
            #
            #   @return [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::BodyParameters, nil]
            optional :body_parameters, -> { Telnyx::AI::AssistantTool::Webhook::Webhook::BodyParameters }

            # @!attribute headers
            #   The headers to be sent to the external tool.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Webhook::Webhook::Header>, nil]
            optional :headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Webhook::Webhook::Header] }

            # @!attribute method_
            #   The HTTP method to be used when calling the external tool.
            #
            #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::Method, nil]
            optional :method_,
                     enum: -> {
                       Telnyx::AI::AssistantTool::Webhook::Webhook::Method
                     },
                     api_name: :method

            # @!attribute path_parameters
            #   The path parameters the webhook tool accepts, described as a JSON Schema object.
            #   These parameters will be passed to the webhook as the path of the request if the
            #   URL contains a placeholder for a value. See the
            #   [JSON Schema reference](https://json-schema.org/understanding-json-schema) for
            #   documentation about the format
            #
            #   @return [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::PathParameters, nil]
            optional :path_parameters, -> { Telnyx::AI::AssistantTool::Webhook::Webhook::PathParameters }

            # @!attribute query_parameters
            #   The query parameters the webhook tool accepts, described as a JSON Schema
            #   object. These parameters will be passed to the webhook as the query of the
            #   request. See the
            #   [JSON Schema reference](https://json-schema.org/understanding-json-schema) for
            #   documentation about the format
            #
            #   @return [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::QueryParameters, nil]
            optional :query_parameters, -> { Telnyx::AI::AssistantTool::Webhook::Webhook::QueryParameters }

            # @!attribute timeout_ms
            #   The maximum number of milliseconds to wait for the webhook to respond. Only
            #   applicable when async is false.
            #
            #   @return [Integer, nil]
            optional :timeout_ms, Integer

            # @!method initialize(description:, name:, url:, async: nil, body_parameters: nil, headers: nil, method_: nil, path_parameters: nil, query_parameters: nil, timeout_ms: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Webhook::Webhook} for more details.
            #
            #   @param description [String] The description of the tool.
            #
            #   @param name [String] The name of the tool.
            #
            #   @param url [String] The URL of the external tool to be called. This URL is going to be used by the a
            #
            #   @param async [Boolean] If async, the assistant will move forward without waiting for your server to res
            #
            #   @param body_parameters [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::BodyParameters] The body parameters the webhook tool accepts, described as a JSON Schema object.
            #
            #   @param headers [Array<Telnyx::Models::AI::AssistantTool::Webhook::Webhook::Header>] The headers to be sent to the external tool.
            #
            #   @param method_ [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::Method] The HTTP method to be used when calling the external tool.
            #
            #   @param path_parameters [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::PathParameters] The path parameters the webhook tool accepts, described as a JSON Schema object.
            #
            #   @param query_parameters [Telnyx::Models::AI::AssistantTool::Webhook::Webhook::QueryParameters] The query parameters the webhook tool accepts, described as a JSON Schema object
            #
            #   @param timeout_ms [Integer] The maximum number of milliseconds to wait for the webhook to respond. Only appl

            # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook#body_parameters
            class BodyParameters < Telnyx::Internal::Type::BaseModel
              # @!attribute properties
              #   The properties of the body parameters.
              #
              #   @return [Hash{Symbol=>Object}, nil]
              optional :properties, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

              # @!attribute required
              #   The required properties of the body parameters.
              #
              #   @return [Array<String>, nil]
              optional :required, Telnyx::Internal::Type::ArrayOf[String]

              # @!attribute type
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::BodyParameters::Type, nil]
              optional :type, enum: -> { Telnyx::AI::AssistantTool::Webhook::Webhook::BodyParameters::Type }

              # @!method initialize(properties: nil, required: nil, type: nil)
              #   The body parameters the webhook tool accepts, described as a JSON Schema object.
              #   These parameters will be passed to the webhook as the body of the request. See
              #   the [JSON Schema reference](https://json-schema.org/understanding-json-schema)
              #   for documentation about the format
              #
              #   @param properties [Hash{Symbol=>Object}] The properties of the body parameters.
              #
              #   @param required [Array<String>] The required properties of the body parameters.
              #
              #   @param type [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::BodyParameters::Type]

              # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook::BodyParameters#type
              module Type
                extend Telnyx::Internal::Type::Enum

                OBJECT = :object

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end

            class Header < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `Bearer {{#integration_secret}}test-secret{{/integration_secret}}` to pass the
              #   value of the integration secret as the bearer token.
              #   [Telnyx signature headers](https://developers.telnyx.com/docs/voice/programmable-voice/voice-api-webhooks)
              #   will be automatically added to the request.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Webhook::Webhook::Header} for more details.
              #
              #   @param name [String]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.
            end

            # The HTTP method to be used when calling the external tool.
            #
            # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook#method_
            module Method
              extend Telnyx::Internal::Type::Enum

              GET = :GET
              POST = :POST
              PUT = :PUT
              DELETE = :DELETE
              PATCH = :PATCH

              # @!method self.values
              #   @return [Array<Symbol>]
            end

            # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook#path_parameters
            class PathParameters < Telnyx::Internal::Type::BaseModel
              # @!attribute properties
              #   The properties of the path parameters.
              #
              #   @return [Hash{Symbol=>Object}, nil]
              optional :properties, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

              # @!attribute required
              #   The required properties of the path parameters.
              #
              #   @return [Array<String>, nil]
              optional :required, Telnyx::Internal::Type::ArrayOf[String]

              # @!attribute type
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::PathParameters::Type, nil]
              optional :type, enum: -> { Telnyx::AI::AssistantTool::Webhook::Webhook::PathParameters::Type }

              # @!method initialize(properties: nil, required: nil, type: nil)
              #   The path parameters the webhook tool accepts, described as a JSON Schema object.
              #   These parameters will be passed to the webhook as the path of the request if the
              #   URL contains a placeholder for a value. See the
              #   [JSON Schema reference](https://json-schema.org/understanding-json-schema) for
              #   documentation about the format
              #
              #   @param properties [Hash{Symbol=>Object}] The properties of the path parameters.
              #
              #   @param required [Array<String>] The required properties of the path parameters.
              #
              #   @param type [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::PathParameters::Type]

              # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook::PathParameters#type
              module Type
                extend Telnyx::Internal::Type::Enum

                OBJECT = :object

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end

            # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook#query_parameters
            class QueryParameters < Telnyx::Internal::Type::BaseModel
              # @!attribute properties
              #   The properties of the query parameters.
              #
              #   @return [Hash{Symbol=>Object}, nil]
              optional :properties, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

              # @!attribute required
              #   The required properties of the query parameters.
              #
              #   @return [Array<String>, nil]
              optional :required, Telnyx::Internal::Type::ArrayOf[String]

              # @!attribute type
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::QueryParameters::Type, nil]
              optional :type, enum: -> { Telnyx::AI::AssistantTool::Webhook::Webhook::QueryParameters::Type }

              # @!method initialize(properties: nil, required: nil, type: nil)
              #   The query parameters the webhook tool accepts, described as a JSON Schema
              #   object. These parameters will be passed to the webhook as the query of the
              #   request. See the
              #   [JSON Schema reference](https://json-schema.org/understanding-json-schema) for
              #   documentation about the format
              #
              #   @param properties [Hash{Symbol=>Object}] The properties of the query parameters.
              #
              #   @param required [Array<String>] The required properties of the query parameters.
              #
              #   @param type [Symbol, Telnyx::Models::AI::AssistantTool::Webhook::Webhook::QueryParameters::Type]

              # @see Telnyx::Models::AI::AssistantTool::Webhook::Webhook::QueryParameters#type
              module Type
                extend Telnyx::Internal::Type::Enum

                OBJECT = :object

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end
          end
        end

        class Handoff < Telnyx::Internal::Type::BaseModel
          # @!attribute handoff
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Handoff::Handoff]
          required :handoff, -> { Telnyx::AI::AssistantTool::Handoff::Handoff }

          # @!attribute type
          #
          #   @return [Symbol, :handoff]
          required :type, const: :handoff

          # @!method initialize(handoff:, type: :handoff)
          #   The handoff tool allows the assistant to hand off control of the conversation to
          #   another AI assistant. By default, this will happen transparently to the end
          #   user.
          #
          #   @param handoff [Telnyx::Models::AI::AssistantTool::Handoff::Handoff]
          #   @param type [Symbol, :handoff]

          # @see Telnyx::Models::AI::AssistantTool::Handoff#handoff
          class Handoff < Telnyx::Internal::Type::BaseModel
            # @!attribute ai_assistants
            #   List of possible assistants that can receive a handoff.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Handoff::Handoff::AIAssistant>]
            required :ai_assistants,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Handoff::Handoff::AIAssistant] }

            # @!attribute voice_mode
            #   With the unified voice mode all assistants share the same voice, making the
            #   handoff transparent to the user. With the distinct voice mode all assistants
            #   retain their voice configuration, providing the experience of a conference call
            #   with a team of assistants.
            #
            #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Handoff::Handoff::VoiceMode, nil]
            optional :voice_mode, enum: -> { Telnyx::AI::AssistantTool::Handoff::Handoff::VoiceMode }

            # @!method initialize(ai_assistants:, voice_mode: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Handoff::Handoff} for more details.
            #
            #   @param ai_assistants [Array<Telnyx::Models::AI::AssistantTool::Handoff::Handoff::AIAssistant>] List of possible assistants that can receive a handoff.
            #
            #   @param voice_mode [Symbol, Telnyx::Models::AI::AssistantTool::Handoff::Handoff::VoiceMode] With the unified voice mode all assistants share the same voice, making the hand

            class AIAssistant < Telnyx::Internal::Type::BaseModel
              # @!attribute id
              #   The ID of the assistant to hand off to.
              #
              #   @return [String]
              required :id, String

              # @!attribute name
              #   Helpful name for giving context on when to handoff to the assistant.
              #
              #   @return [String]
              required :name, String

              # @!method initialize(id:, name:)
              #   @param id [String] The ID of the assistant to hand off to.
              #
              #   @param name [String] Helpful name for giving context on when to handoff to the assistant.
            end

            # With the unified voice mode all assistants share the same voice, making the
            # handoff transparent to the user. With the distinct voice mode all assistants
            # retain their voice configuration, providing the experience of a conference call
            # with a team of assistants.
            #
            # @see Telnyx::Models::AI::AssistantTool::Handoff::Handoff#voice_mode
            module VoiceMode
              extend Telnyx::Internal::Type::Enum

              UNIFIED = :unified
              DISTINCT = :distinct

              # @!method self.values
              #   @return [Array<Symbol>]
            end
          end
        end

        class Transfer < Telnyx::Internal::Type::BaseModel
          # @!attribute transfer
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Transfer::Transfer]
          required :transfer, -> { Telnyx::AI::AssistantTool::Transfer::Transfer }

          # @!attribute type
          #
          #   @return [Symbol, :transfer]
          required :type, const: :transfer

          # @!method initialize(transfer:, type: :transfer)
          #   @param transfer [Telnyx::Models::AI::AssistantTool::Transfer::Transfer]
          #   @param type [Symbol, :transfer]

          # @see Telnyx::Models::AI::AssistantTool::Transfer#transfer
          class Transfer < Telnyx::Internal::Type::BaseModel
            # @!attribute from
            #   Number or SIP URI placing the call.
            #
            #   @return [String]
            required :from, String

            # @!attribute targets
            #   The different possible targets of the transfer. The assistant will be able to
            #   choose one of the targets to transfer the call to.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::Target>]
            required :targets,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Transfer::Transfer::Target] }

            # @!attribute custom_headers
            #   Custom headers to be added to the SIP INVITE for the transfer command.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader>, nil]
            optional :custom_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Transfer::Transfer::CustomHeader] }

            # @!attribute warm_transfer_instructions
            #   Natural language instructions for your agent for how to provide context for the
            #   transfer recipient.
            #
            #   @return [String, nil]
            optional :warm_transfer_instructions, String

            # @!method initialize(from:, targets:, custom_headers: nil, warm_transfer_instructions: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer} for more details.
            #
            #   @param from [String] Number or SIP URI placing the call.
            #
            #   @param targets [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::Target>] The different possible targets of the transfer. The assistant will be able to ch
            #
            #   @param custom_headers [Array<Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader>] Custom headers to be added to the SIP INVITE for the transfer command.
            #
            #   @param warm_transfer_instructions [String] Natural language instructions for your agent for how to provide context for the

            class Target < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #   The name of the target.
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute to
              #   The destination number or SIP URI of the call.
              #
              #   @return [String, nil]
              optional :to, String

              # @!method initialize(name: nil, to: nil)
              #   @param name [String] The name of the target.
              #
              #   @param to [String] The destination number or SIP URI of the call.
            end

            class CustomHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Transfer::Transfer::CustomHeader} for more
              #   details.
              #
              #   @param name [String]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.
            end
          end
        end

        class Refer < Telnyx::Internal::Type::BaseModel
          # @!attribute refer
          #
          #   @return [Telnyx::Models::AI::AssistantTool::Refer::Refer]
          required :refer, -> { Telnyx::AI::AssistantTool::Refer::Refer }

          # @!attribute type
          #
          #   @return [Symbol, :refer]
          required :type, const: :refer

          # @!method initialize(refer:, type: :refer)
          #   @param refer [Telnyx::Models::AI::AssistantTool::Refer::Refer]
          #   @param type [Symbol, :refer]

          # @see Telnyx::Models::AI::AssistantTool::Refer#refer
          class Refer < Telnyx::Internal::Type::BaseModel
            # @!attribute targets
            #   The different possible targets of the SIP refer. The assistant will be able to
            #   choose one of the targets to refer the call to.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::Target>]
            required :targets, -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::Target] }

            # @!attribute custom_headers
            #   Custom headers to be added to the SIP REFER.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader>, nil]
            optional :custom_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::CustomHeader] }

            # @!attribute sip_headers
            #   SIP headers to be added to the SIP REFER. Currently only User-to-User and
            #   Diversion headers are supported.
            #
            #   @return [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader>, nil]
            optional :sip_headers,
                     -> { Telnyx::Internal::Type::ArrayOf[Telnyx::AI::AssistantTool::Refer::Refer::SipHeader] }

            # @!method initialize(targets:, custom_headers: nil, sip_headers: nil)
            #   Some parameter documentations has been truncated, see
            #   {Telnyx::Models::AI::AssistantTool::Refer::Refer} for more details.
            #
            #   @param targets [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::Target>] The different possible targets of the SIP refer. The assistant will be able to c
            #
            #   @param custom_headers [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader>] Custom headers to be added to the SIP REFER.
            #
            #   @param sip_headers [Array<Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader>] SIP headers to be added to the SIP REFER. Currently only User-to-User and Divers

            class Target < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #   The name of the target.
              #
              #   @return [String]
              required :name, String

              # @!attribute sip_address
              #   The SIP URI to which the call will be referred.
              #
              #   @return [String]
              required :sip_address, String

              # @!attribute sip_auth_password
              #   SIP Authentication password used for SIP challenges.
              #
              #   @return [String, nil]
              optional :sip_auth_password, String

              # @!attribute sip_auth_username
              #   SIP Authentication username used for SIP challenges.
              #
              #   @return [String, nil]
              optional :sip_auth_username, String

              # @!method initialize(name:, sip_address:, sip_auth_password: nil, sip_auth_username: nil)
              #   @param name [String] The name of the target.
              #
              #   @param sip_address [String] The SIP URI to which the call will be referred.
              #
              #   @param sip_auth_password [String] SIP Authentication password used for SIP challenges.
              #
              #   @param sip_auth_username [String] SIP Authentication username used for SIP challenges.
            end

            class CustomHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [String, nil]
              optional :name, String

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Refer::Refer::CustomHeader} for more
              #   details.
              #
              #   @param name [String]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.
            end

            class SipHeader < Telnyx::Internal::Type::BaseModel
              # @!attribute name
              #
              #   @return [Symbol, Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader::Name, nil]
              optional :name, enum: -> { Telnyx::AI::AssistantTool::Refer::Refer::SipHeader::Name }

              # @!attribute value
              #   The value of the header. Note that we support mustache templating for the value.
              #   For example you can use
              #   `{{#integration_secret}}test-secret{{/integration_secret}}` to pass the value of
              #   the integration secret.
              #
              #   @return [String, nil]
              optional :value, String

              # @!method initialize(name: nil, value: nil)
              #   Some parameter documentations has been truncated, see
              #   {Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader} for more details.
              #
              #   @param name [Symbol, Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader::Name]
              #
              #   @param value [String] The value of the header. Note that we support mustache templating for the value.

              # @see Telnyx::Models::AI::AssistantTool::Refer::Refer::SipHeader#name
              module Name
                extend Telnyx::Internal::Type::Enum

                USER_TO_USER = :"User-to-User"
                DIVERSION = :Diversion

                # @!method self.values
                #   @return [Array<Symbol>]
              end
            end
          end
        end

        class SendDtmf < Telnyx::Internal::Type::BaseModel
          # @!attribute send_dtmf
          #
          #   @return [Hash{Symbol=>Object}]
          required :send_dtmf, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

          # @!attribute type
          #
          #   @return [Symbol, :send_dtmf]
          required :type, const: :send_dtmf

          # @!method initialize(send_dtmf:, type: :send_dtmf)
          #   @param send_dtmf [Hash{Symbol=>Object}]
          #   @param type [Symbol, :send_dtmf]
        end

        class SendMessage < Telnyx::Internal::Type::BaseModel
          # @!attribute send_message
          #
          #   @return [Hash{Symbol=>Object}]
          required :send_message, Telnyx::Internal::Type::HashOf[Telnyx::Internal::Type::Unknown]

          # @!attribute type
          #
          #   @return [Symbol, :send_message]
          required :type, const: :send_message

          # @!method initialize(send_message:, type: :send_message)
          #   The send_message tool allows the assistant to send SMS or MMS messages to the
          #   end user. The 'to' and 'from' addresses are automatically determined from the
          #   conversation context, and the message text is generated by the assistant.
          #
          #   @param send_message [Hash{Symbol=>Object}]
          #   @param type [Symbol, :send_message]
        end

        # @!method self.variants
        #   @return [Array(Telnyx::Models::AI::AssistantTool::Webhook, Telnyx::Models::AI::RetrievalTool, Telnyx::Models::AI::AssistantTool::Handoff, Telnyx::Models::AI::HangupTool, Telnyx::Models::AI::AssistantTool::Transfer, Telnyx::Models::AI::AssistantTool::Refer, Telnyx::Models::AI::AssistantTool::SendDtmf, Telnyx::Models::AI::AssistantTool::SendMessage)]
      end
    end
  end
end
