module Telnyx
  module Models
    module EmailInboxes
      type email_message_response =
        {
          data: Telnyx::EmailInboxes::EmailMessage,
          suppressed: ::Array[Telnyx::SuppressedRecipient]
        }

      class EmailMessageResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: Telnyx::EmailInboxes::EmailMessage

        attr_reader suppressed: ::Array[Telnyx::SuppressedRecipient]?

        def suppressed=: (
          ::Array[Telnyx::SuppressedRecipient]
        ) -> ::Array[Telnyx::SuppressedRecipient]

        def initialize: (
          data: Telnyx::EmailInboxes::EmailMessage,
          ?suppressed: ::Array[Telnyx::SuppressedRecipient]
        ) -> void

        def to_hash: -> {
          data: Telnyx::EmailInboxes::EmailMessage,
          suppressed: ::Array[Telnyx::SuppressedRecipient]
        }
      end
    end
  end
end
