module Telnyx
  module Models
    module EmailInboxes
      type filter_list_response = { data: Telnyx::EmailInboxes::InboxFilters }

      class FilterListResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: Telnyx::EmailInboxes::InboxFilters

        def initialize: (data: Telnyx::EmailInboxes::InboxFilters) -> void

        def to_hash: -> { data: Telnyx::EmailInboxes::InboxFilters }
      end
    end
  end
end
