module Telnyx
  module Models
    module EmailInboxes
      type inbound_thread_list_response =
        {
          data: ::Array[Telnyx::EmailInboxes::InboundThread],
          meta: Telnyx::EmailInboxes::EmailPaginationMeta
        }

      class InboundThreadListResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: ::Array[Telnyx::EmailInboxes::InboundThread]

        attr_accessor meta: Telnyx::EmailInboxes::EmailPaginationMeta

        def initialize: (
          data: ::Array[Telnyx::EmailInboxes::InboundThread],
          meta: Telnyx::EmailInboxes::EmailPaginationMeta
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::EmailInboxes::InboundThread],
          meta: Telnyx::EmailInboxes::EmailPaginationMeta
        }
      end
    end
  end
end
