module Telnyx
  module Models
    module EmailInboxes
      type message_list_params =
        {
          inbox_id: String,
          filter_from: String,
          filter_label: String,
          filter_read: bool,
          filter_received_after: Time,
          filter_received_before: Time,
          filter_search: String,
          filter_subject: String,
          filter_unread: bool,
          page_after: String,
          page_size: Integer
        }
        & Telnyx::Internal::Type::request_parameters

      class MessageListParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor inbox_id: String

        attr_reader filter_from: String?

        def filter_from=: (String) -> String

        attr_reader filter_label: String?

        def filter_label=: (String) -> String

        attr_reader filter_read: bool?

        def filter_read=: (bool) -> bool

        attr_reader filter_received_after: Time?

        def filter_received_after=: (Time) -> Time

        attr_reader filter_received_before: Time?

        def filter_received_before=: (Time) -> Time

        attr_reader filter_search: String?

        def filter_search=: (String) -> String

        attr_reader filter_subject: String?

        def filter_subject=: (String) -> String

        attr_reader filter_unread: bool?

        def filter_unread=: (bool) -> bool

        attr_reader page_after: String?

        def page_after=: (String) -> String

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        def initialize: (
          inbox_id: String,
          ?filter_from: String,
          ?filter_label: String,
          ?filter_read: bool,
          ?filter_received_after: Time,
          ?filter_received_before: Time,
          ?filter_search: String,
          ?filter_subject: String,
          ?filter_unread: bool,
          ?page_after: String,
          ?page_size: Integer,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          inbox_id: String,
          filter_from: String,
          filter_label: String,
          filter_read: bool,
          filter_received_after: Time,
          filter_received_before: Time,
          filter_search: String,
          filter_subject: String,
          filter_unread: bool,
          page_after: String,
          page_size: Integer,
          request_options: Telnyx::RequestOptions
        }
      end
    end
  end
end
