module Telnyx
  module Models
    module Number10dlc
      module Brand
        type sms_otp_get_status_response =
          {
            brand_id: String,
            delivery_status: String,
            mobile_phone: String,
            reference_id: String,
            request_date: Time,
            delivery_status_date: Time,
            delivery_status_details: String,
            verify_date: Time
          }

        class SMSOtpGetStatusResponse < Telnyx::Internal::Type::BaseModel
          attr_accessor brand_id: String

          attr_accessor delivery_status: String

          attr_accessor mobile_phone: String

          attr_accessor reference_id: String

          attr_accessor request_date: Time

          attr_reader delivery_status_date: Time?

          def delivery_status_date=: (Time) -> Time

          attr_reader delivery_status_details: String?

          def delivery_status_details=: (String) -> String

          attr_reader verify_date: Time?

          def verify_date=: (Time) -> Time

          def initialize: (
            brand_id: String,
            delivery_status: String,
            mobile_phone: String,
            reference_id: String,
            request_date: Time,
            ?delivery_status_date: Time,
            ?delivery_status_details: String,
            ?verify_date: Time
          ) -> void

          def to_hash: -> {
            brand_id: String,
            delivery_status: String,
            mobile_phone: String,
            reference_id: String,
            request_date: Time,
            delivery_status_date: Time,
            delivery_status_details: String,
            verify_date: Time
          }
        end
      end
    end
  end
end
