# typed: strong

module Telnyx
  module Models
    module Calls
      class AssistantMessage < Telnyx::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(Telnyx::Calls::AssistantMessage, Telnyx::Internal::AnyHash)
          end

        # The role of the messages author, in this case `assistant`.
        sig { returns(Telnyx::Calls::AssistantMessage::Role::OrSymbol) }
        attr_accessor :role

        # The contents of the assistant message. Required unless `tool_calls`
        sig { returns(T.nilable(String)) }
        attr_reader :content

        sig { params(content: String).void }
        attr_writer :content

        # Metadata to add to the message
        sig { returns(T.nilable(T::Hash[Symbol, T.anything])) }
        attr_reader :metadata

        sig { params(metadata: T::Hash[Symbol, T.anything]).void }
        attr_writer :metadata

        # The tool calls generated by the model, such as function calls.
        sig do
          returns(
            T.nilable(T::Array[Telnyx::Calls::AssistantMessage::ToolCall])
          )
        end
        attr_reader :tool_calls

        sig do
          params(
            tool_calls:
              T::Array[Telnyx::Calls::AssistantMessage::ToolCall::OrHash]
          ).void
        end
        attr_writer :tool_calls

        # Messages sent by the model in response to user messages.
        sig do
          params(
            role: Telnyx::Calls::AssistantMessage::Role::OrSymbol,
            content: String,
            metadata: T::Hash[Symbol, T.anything],
            tool_calls:
              T::Array[Telnyx::Calls::AssistantMessage::ToolCall::OrHash]
          ).returns(T.attached_class)
        end
        def self.new(
          # The role of the messages author, in this case `assistant`.
          role:,
          # The contents of the assistant message. Required unless `tool_calls`
          content: nil,
          # Metadata to add to the message
          metadata: nil,
          # The tool calls generated by the model, such as function calls.
          tool_calls: nil
        )
        end

        sig do
          override.returns(
            {
              role: Telnyx::Calls::AssistantMessage::Role::OrSymbol,
              content: String,
              metadata: T::Hash[Symbol, T.anything],
              tool_calls: T::Array[Telnyx::Calls::AssistantMessage::ToolCall]
            }
          )
        end
        def to_hash
        end

        # The role of the messages author, in this case `assistant`.
        module Role
          extend Telnyx::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, Telnyx::Calls::AssistantMessage::Role)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          ASSISTANT =
            T.let(
              :assistant,
              Telnyx::Calls::AssistantMessage::Role::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[Telnyx::Calls::AssistantMessage::Role::TaggedSymbol]
            )
          end
          def self.values
          end
        end

        class ToolCall < Telnyx::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                Telnyx::Calls::AssistantMessage::ToolCall,
                Telnyx::Internal::AnyHash
              )
            end

          # The ID of the tool call.
          sig { returns(String) }
          attr_accessor :id

          # The function that the model called.
          sig { returns(Telnyx::Calls::AssistantMessage::ToolCall::Function) }
          attr_reader :function

          sig do
            params(
              function:
                Telnyx::Calls::AssistantMessage::ToolCall::Function::OrHash
            ).void
          end
          attr_writer :function

          # The type of the tool. Currently, only `function` is supported.
          sig do
            returns(Telnyx::Calls::AssistantMessage::ToolCall::Type::OrSymbol)
          end
          attr_accessor :type

          # A call to a function tool created by the model.
          sig do
            params(
              id: String,
              function:
                Telnyx::Calls::AssistantMessage::ToolCall::Function::OrHash,
              type: Telnyx::Calls::AssistantMessage::ToolCall::Type::OrSymbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The ID of the tool call.
            id:,
            # The function that the model called.
            function:,
            # The type of the tool. Currently, only `function` is supported.
            type:
          )
          end

          sig do
            override.returns(
              {
                id: String,
                function: Telnyx::Calls::AssistantMessage::ToolCall::Function,
                type: Telnyx::Calls::AssistantMessage::ToolCall::Type::OrSymbol
              }
            )
          end
          def to_hash
          end

          class Function < Telnyx::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  Telnyx::Calls::AssistantMessage::ToolCall::Function,
                  Telnyx::Internal::AnyHash
                )
              end

            # The name of the function to call.
            sig { returns(String) }
            attr_accessor :name

            # The function that the model called.
            sig { params(name: String).returns(T.attached_class) }
            def self.new(
              # The name of the function to call.
              name:
            )
            end

            sig { override.returns({ name: String }) }
            def to_hash
            end
          end

          # The type of the tool. Currently, only `function` is supported.
          module Type
            extend Telnyx::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, Telnyx::Calls::AssistantMessage::ToolCall::Type)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            FUNCTION =
              T.let(
                :function,
                Telnyx::Calls::AssistantMessage::ToolCall::Type::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  Telnyx::Calls::AssistantMessage::ToolCall::Type::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end
      end
    end
  end
end
