# typed: strong

module Telnyx
  module Models
    module Calls
      # Language to use for speech recognition
      module TelnyxTranscriptionLanguage
        extend Telnyx::Internal::Type::Enum

        TaggedSymbol =
          T.type_alias do
            T.all(Symbol, Telnyx::Calls::TelnyxTranscriptionLanguage)
          end
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        EN =
          T.let(:en, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        ZH =
          T.let(:zh, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        DE =
          T.let(:de, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        ES =
          T.let(:es, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        RU =
          T.let(:ru, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        KO =
          T.let(:ko, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        FR =
          T.let(:fr, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        JA =
          T.let(:ja, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        PT =
          T.let(:pt, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TR =
          T.let(:tr, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        PL =
          T.let(:pl, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        CA =
          T.let(:ca, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        NL =
          T.let(:nl, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AR =
          T.let(:ar, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SV =
          T.let(:sv, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        IT =
          T.let(:it, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        ID =
          T.let(:id, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HI =
          T.let(:hi, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        FI =
          T.let(:fi, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        VI =
          T.let(:vi, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HE =
          T.let(:he, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        UK =
          T.let(:uk, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        EL =
          T.let(:el, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MS =
          T.let(:ms, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        CS =
          T.let(:cs, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        RO =
          T.let(:ro, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        DA =
          T.let(:da, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HU =
          T.let(:hu, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TA =
          T.let(:ta, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        NO =
          T.let(:no, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TH =
          T.let(:th, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        UR =
          T.let(:ur, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HR =
          T.let(:hr, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BG =
          T.let(:bg, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LT =
          T.let(:lt, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LA =
          T.let(:la, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MI =
          T.let(:mi, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        ML =
          T.let(:ml, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        CY =
          T.let(:cy, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SK =
          T.let(:sk, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TE =
          T.let(:te, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        FA =
          T.let(:fa, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LV =
          T.let(:lv, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BN =
          T.let(:bn, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SR =
          T.let(:sr, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AZ =
          T.let(:az, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SL =
          T.let(:sl, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        KN =
          T.let(:kn, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        ET =
          T.let(:et, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MK =
          T.let(:mk, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BR =
          T.let(:br, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        EU =
          T.let(:eu, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        IS =
          T.let(:is, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HY =
          T.let(:hy, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        NE =
          T.let(:ne, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MN =
          T.let(:mn, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BS =
          T.let(:bs, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        KK =
          T.let(:kk, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SQ =
          T.let(:sq, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SW =
          T.let(:sw, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        GL =
          T.let(:gl, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MR =
          T.let(:mr, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        PA =
          T.let(:pa, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SI =
          T.let(:si, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        KM =
          T.let(:km, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SN =
          T.let(:sn, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        YO =
          T.let(:yo, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SO =
          T.let(:so, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AF =
          T.let(:af, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        OC =
          T.let(:oc, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        KA =
          T.let(:ka, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BE =
          T.let(:be, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TG =
          T.let(:tg, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SD =
          T.let(:sd, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        GU =
          T.let(:gu, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AM =
          T.let(:am, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        YI =
          T.let(:yi, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LO =
          T.let(:lo, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        UZ =
          T.let(:uz, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        FO =
          T.let(:fo, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HT =
          T.let(:ht, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        PS =
          T.let(:ps, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TK =
          T.let(:tk, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        NN =
          T.let(:nn, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MT =
          T.let(:mt, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SA =
          T.let(:sa, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LB =
          T.let(:lb, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MY =
          T.let(:my, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BO =
          T.let(:bo, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TL =
          T.let(:tl, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        MG =
          T.let(:mg, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AS =
          T.let(:as, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        TT =
          T.let(:tt, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HAW =
          T.let(:haw, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        LN =
          T.let(:ln, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        HA =
          T.let(:ha, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        BA =
          T.let(:ba, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        JW =
          T.let(:jw, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        SU =
          T.let(:su, Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol)
        AUTO_DETECT =
          T.let(
            :auto_detect,
            Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol
          )

        sig do
          override.returns(
            T::Array[Telnyx::Calls::TelnyxTranscriptionLanguage::TaggedSymbol]
          )
        end
        def self.values
        end
      end
    end
  end
end
