module Telnyx
  module Models
    module MobilePhoneNumbers
      type messaging_retrieve_response =
        {
          data: Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings
        }

      class MessagingRetrieveResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings?

        def data=: (
          Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings
        ) -> Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings

        def initialize: (
          ?data: Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings
        ) -> void

        def to_hash: -> {
          data: Telnyx::MobilePhoneNumbers::MobilePhoneNumberWithMessagingSettings
        }
      end
    end
  end
end
