# frozen_string_literal: true

module Telnyx
  module Models
    # @see Telnyx::Resources::CampaignBuilder#create
    class CampaignBuilderCreateParams < Telnyx::Internal::Type::BaseModel
      extend Telnyx::Internal::Type::RequestParameters::Converter
      include Telnyx::Internal::Type::RequestParameters

      # @!attribute brand_id
      #   Alphanumeric identifier of the brand associated with this campaign.
      #
      #   @return [String]
      required :brand_id, String, api_name: :brandId

      # @!attribute description
      #   Summary description of this campaign.
      #
      #   @return [String]
      required :description, String

      # @!attribute usecase
      #   Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase`
      #   operation to retrieve usecases available for given brand.
      #
      #   @return [String]
      required :usecase, String

      # @!attribute age_gated
      #   Age gated message content in campaign.
      #
      #   @return [Boolean, nil]
      optional :age_gated, Telnyx::Internal::Type::Boolean, api_name: :ageGated

      # @!attribute auto_renewal
      #   Campaign subscription auto-renewal option. If set to true, then campaign will
      #   automatically renewal at end of billing cycle.
      #
      #   @return [Boolean, nil]
      optional :auto_renewal, Telnyx::Internal::Type::Boolean, api_name: :autoRenewal

      # @!attribute direct_lending
      #   Direct lending or loan arrangement
      #
      #   @return [Boolean, nil]
      optional :direct_lending, Telnyx::Internal::Type::Boolean, api_name: :directLending

      # @!attribute embedded_link
      #   Does message generated by the campaign include URL link in SMS?
      #
      #   @return [Boolean, nil]
      optional :embedded_link, Telnyx::Internal::Type::Boolean, api_name: :embeddedLink

      # @!attribute embedded_link_sample
      #   Sample of an embedded link that will be sent to subscribers.
      #
      #   @return [String, nil]
      optional :embedded_link_sample, String, api_name: :embeddedLinkSample

      # @!attribute embedded_phone
      #   Does message generated by the campaign include phone number in SMS?
      #
      #   @return [Boolean, nil]
      optional :embedded_phone, Telnyx::Internal::Type::Boolean, api_name: :embeddedPhone

      # @!attribute help_keywords
      #   Subscriber help keywords. Multiple keywords are comma separated without space.
      #
      #   @return [String, nil]
      optional :help_keywords, String, api_name: :helpKeywords

      # @!attribute help_message
      #   Help message of the campaign.
      #
      #   @return [String, nil]
      optional :help_message, String, api_name: :helpMessage

      # @!attribute message_flow
      #   Message flow description.
      #
      #   @return [String, nil]
      optional :message_flow, String, api_name: :messageFlow

      # @!attribute mno_ids
      #   Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs
      #   if no value provided.
      #
      #   @return [Array<Integer>, nil]
      optional :mno_ids, Telnyx::Internal::Type::ArrayOf[Integer], api_name: :mnoIds

      # @!attribute number_pool
      #   Does campaign utilize pool of phone numbers?
      #
      #   @return [Boolean, nil]
      optional :number_pool, Telnyx::Internal::Type::Boolean, api_name: :numberPool

      # @!attribute optin_keywords
      #   Subscriber opt-in keywords. Multiple keywords are comma separated without space.
      #
      #   @return [String, nil]
      optional :optin_keywords, String, api_name: :optinKeywords

      # @!attribute optin_message
      #   Subscriber opt-in message.
      #
      #   @return [String, nil]
      optional :optin_message, String, api_name: :optinMessage

      # @!attribute optout_keywords
      #   Subscriber opt-out keywords. Multiple keywords are comma separated without
      #   space.
      #
      #   @return [String, nil]
      optional :optout_keywords, String, api_name: :optoutKeywords

      # @!attribute optout_message
      #   Subscriber opt-out message.
      #
      #   @return [String, nil]
      optional :optout_message, String, api_name: :optoutMessage

      # @!attribute privacy_policy_link
      #   Link to the campaign's privacy policy.
      #
      #   @return [String, nil]
      optional :privacy_policy_link, String, api_name: :privacyPolicyLink

      # @!attribute reference_id
      #   Caller supplied campaign reference ID. If supplied, the value must be unique
      #   across all submitted campaigns. Can be used to prevent duplicate campaign
      #   registrations.
      #
      #   @return [String, nil]
      optional :reference_id, String, api_name: :referenceId

      # @!attribute reseller_id
      #   Alphanumeric identifier of the reseller that you want to associate with this
      #   campaign.
      #
      #   @return [String, nil]
      optional :reseller_id, String, api_name: :resellerId

      # @!attribute sample1
      #   Message sample. Some campaign tiers require 1 or more message samples.
      #
      #   @return [String, nil]
      optional :sample1, String

      # @!attribute sample2
      #   Message sample. Some campaign tiers require 2 or more message samples.
      #
      #   @return [String, nil]
      optional :sample2, String

      # @!attribute sample3
      #   Message sample. Some campaign tiers require 3 or more message samples.
      #
      #   @return [String, nil]
      optional :sample3, String

      # @!attribute sample4
      #   Message sample. Some campaign tiers require 4 or more message samples.
      #
      #   @return [String, nil]
      optional :sample4, String

      # @!attribute sample5
      #   Message sample. Some campaign tiers require 5 or more message samples.
      #
      #   @return [String, nil]
      optional :sample5, String

      # @!attribute subscriber_help
      #   Does campaign responds to help keyword(s)?
      #
      #   @return [Boolean, nil]
      optional :subscriber_help, Telnyx::Internal::Type::Boolean, api_name: :subscriberHelp

      # @!attribute subscriber_optin
      #   Does campaign require subscriber to opt-in before SMS is sent to subscriber?
      #
      #   @return [Boolean, nil]
      optional :subscriber_optin, Telnyx::Internal::Type::Boolean, api_name: :subscriberOptin

      # @!attribute subscriber_optout
      #   Does campaign support subscriber opt-out keyword(s)?
      #
      #   @return [Boolean, nil]
      optional :subscriber_optout, Telnyx::Internal::Type::Boolean, api_name: :subscriberOptout

      # @!attribute sub_usecases
      #   Campaign sub-usecases. Must be of defined valid sub-usecase types. Use
      #   `/registry/enum/usecase` operation to retrieve list of valid sub-usecases
      #
      #   @return [Array<String>, nil]
      optional :sub_usecases, Telnyx::Internal::Type::ArrayOf[String], api_name: :subUsecases

      # @!attribute tag
      #   Tags to be set on the Campaign.
      #
      #   @return [Array<String>, nil]
      optional :tag, Telnyx::Internal::Type::ArrayOf[String]

      # @!attribute terms_and_conditions
      #   Is terms and conditions accepted?
      #
      #   @return [Boolean, nil]
      optional :terms_and_conditions, Telnyx::Internal::Type::Boolean, api_name: :termsAndConditions

      # @!attribute terms_and_conditions_link
      #   Link to the campaign's terms and conditions.
      #
      #   @return [String, nil]
      optional :terms_and_conditions_link, String, api_name: :termsAndConditionsLink

      # @!attribute webhook_failover_url
      #   Failover webhook to which campaign status updates are sent.
      #
      #   @return [String, nil]
      optional :webhook_failover_url, String, api_name: :webhookFailoverURL

      # @!attribute webhook_url
      #   Webhook to which campaign status updates are sent.
      #
      #   @return [String, nil]
      optional :webhook_url, String, api_name: :webhookURL

      # @!method initialize(brand_id:, description:, usecase:, age_gated: nil, auto_renewal: nil, direct_lending: nil, embedded_link: nil, embedded_link_sample: nil, embedded_phone: nil, help_keywords: nil, help_message: nil, message_flow: nil, mno_ids: nil, number_pool: nil, optin_keywords: nil, optin_message: nil, optout_keywords: nil, optout_message: nil, privacy_policy_link: nil, reference_id: nil, reseller_id: nil, sample1: nil, sample2: nil, sample3: nil, sample4: nil, sample5: nil, subscriber_help: nil, subscriber_optin: nil, subscriber_optout: nil, sub_usecases: nil, tag: nil, terms_and_conditions: nil, terms_and_conditions_link: nil, webhook_failover_url: nil, webhook_url: nil, request_options: {})
      #   Some parameter documentations has been truncated, see
      #   {Telnyx::Models::CampaignBuilderCreateParams} for more details.
      #
      #   @param brand_id [String] Alphanumeric identifier of the brand associated with this campaign.
      #
      #   @param description [String] Summary description of this campaign.
      #
      #   @param usecase [String] Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` o
      #
      #   @param age_gated [Boolean] Age gated message content in campaign.
      #
      #   @param auto_renewal [Boolean] Campaign subscription auto-renewal option. If set to true, then campaign will au
      #
      #   @param direct_lending [Boolean] Direct lending or loan arrangement
      #
      #   @param embedded_link [Boolean] Does message generated by the campaign include URL link in SMS?
      #
      #   @param embedded_link_sample [String] Sample of an embedded link that will be sent to subscribers.
      #
      #   @param embedded_phone [Boolean] Does message generated by the campaign include phone number in SMS?
      #
      #   @param help_keywords [String] Subscriber help keywords. Multiple keywords are comma separated without space.
      #
      #   @param help_message [String] Help message of the campaign.
      #
      #   @param message_flow [String] Message flow description.
      #
      #   @param mno_ids [Array<Integer>] Submit campaign to given list of MNOs by MNO's network ID. Default is all MNOs i
      #
      #   @param number_pool [Boolean] Does campaign utilize pool of phone numbers?
      #
      #   @param optin_keywords [String] Subscriber opt-in keywords. Multiple keywords are comma separated without space.
      #
      #   @param optin_message [String] Subscriber opt-in message.
      #
      #   @param optout_keywords [String] Subscriber opt-out keywords. Multiple keywords are comma separated without space
      #
      #   @param optout_message [String] Subscriber opt-out message.
      #
      #   @param privacy_policy_link [String] Link to the campaign's privacy policy.
      #
      #   @param reference_id [String] Caller supplied campaign reference ID. If supplied, the value must be unique acr
      #
      #   @param reseller_id [String] Alphanumeric identifier of the reseller that you want to associate with this cam
      #
      #   @param sample1 [String] Message sample. Some campaign tiers require 1 or more message samples.
      #
      #   @param sample2 [String] Message sample. Some campaign tiers require 2 or more message samples.
      #
      #   @param sample3 [String] Message sample. Some campaign tiers require 3 or more message samples.
      #
      #   @param sample4 [String] Message sample. Some campaign tiers require 4 or more message samples.
      #
      #   @param sample5 [String] Message sample. Some campaign tiers require 5 or more message samples.
      #
      #   @param subscriber_help [Boolean] Does campaign responds to help keyword(s)?
      #
      #   @param subscriber_optin [Boolean] Does campaign require subscriber to opt-in before SMS is sent to subscriber?
      #
      #   @param subscriber_optout [Boolean] Does campaign support subscriber opt-out keyword(s)?
      #
      #   @param sub_usecases [Array<String>] Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/registr
      #
      #   @param tag [Array<String>] Tags to be set on the Campaign.
      #
      #   @param terms_and_conditions [Boolean] Is terms and conditions accepted?
      #
      #   @param terms_and_conditions_link [String] Link to the campaign's terms and conditions.
      #
      #   @param webhook_failover_url [String] Failover webhook to which campaign status updates are sent.
      #
      #   @param webhook_url [String] Webhook to which campaign status updates are sent.
      #
      #   @param request_options [Telnyx::RequestOptions, Hash{Symbol=>Object}]
    end
  end
end
