# frozen_string_literal: true

module Telnyx
  module Models
    # Campaign is generated by the 10DLC registry once the corresponding campaign
    # request is approved. Each campaign is assigned a unique identifier -
    # **campaignId**. Once a campaign is activated, limited information is published
    # to the NetNumber OSR service for consumption by members of the ecosystem. When a
    # campaign is suspended(reversible) or expired(non-reversible), campaign data is
    # deleted from the OSR service. Most attributes of campaignare immutable,
    # including **usecase**, **vertical**, **brandId** and **cspId**.
    #
    # @see Telnyx::Resources::CampaignBuilder#create
    module CampaignBuilderCreateResponse
      extend Telnyx::Internal::Type::Union

      variant Telnyx::Internal::Type::Unknown

      # Campaign is generated by the 10DLC registry once the corresponding campaign request is approved. Each campaign is assigned a unique identifier - **campaignId**. Once a campaign is activated, limited information is published to the NetNumber OSR service for consumption by members of the ecosystem. When a campaign is suspended(reversible) or expired(non-reversible), campaign data is deleted from the OSR service. Most attributes of campaignare immutable, including **usecase**, **vertical**, **brandId** and **cspId**.
      variant -> { Telnyx::TelnyxCampaignCsp }

      # @!method self.variants
      #   @return [Array(Object, Telnyx::Models::TelnyxCampaignCsp)]
    end
  end
end
