# frozen_string_literal: true

module Telnyx
  module Models
    class MessagingProfile < Telnyx::Internal::Type::BaseModel
      # @!attribute alpha_sender
      #   The alphanumeric sender ID to use when sending to destinations that require an
      #   alphanumeric sender ID.
      #
      #   @return [String, nil]
      optional :alpha_sender, String, nil?: true

      # @!attribute daily_spend_limit
      #   The maximum amount of money (in USD) that can be spent by this profile before
      #   midnight UTC.
      #
      #   @return [String, nil]
      optional :daily_spend_limit, String

      # @!attribute daily_spend_limit_enabled
      #   Whether to enforce the value configured by `daily_spend_limit`.
      #
      #   @return [Boolean, nil]
      optional :daily_spend_limit_enabled, Telnyx::Internal::Type::Boolean

      # @!attribute enabled
      #   Specifies whether the messaging profile is enabled or not.
      #
      #   @return [Boolean, nil]
      optional :enabled, Telnyx::Internal::Type::Boolean

      # @!attribute mms_fall_back_to_sms
      #   enables SMS fallback for MMS messages.
      #
      #   @return [Boolean, nil]
      optional :mms_fall_back_to_sms, Telnyx::Internal::Type::Boolean

      # @!attribute mms_transcoding
      #   enables automated resizing of MMS media.
      #
      #   @return [Boolean, nil]
      optional :mms_transcoding, Telnyx::Internal::Type::Boolean

      # @!attribute mobile_only
      #   Send messages only to mobile phone numbers.
      #
      #   @return [Boolean, nil]
      optional :mobile_only, Telnyx::Internal::Type::Boolean

      # @!attribute name
      #   A user friendly name for the messaging profile.
      #
      #   @return [String, nil]
      optional :name, String

      # @!attribute number_pool_settings
      #   Number Pool allows you to send messages from a pool of numbers of different
      #   types, assigning weights to each type. The pool consists of all the long code
      #   and toll free numbers assigned to the messaging profile.
      #
      #   To disable this feature, set the object field to `null`.
      #
      #   @return [Telnyx::Models::NumberPoolSettings, nil]
      optional :number_pool_settings, -> { Telnyx::NumberPoolSettings }, nil?: true

      # @!attribute url_shortener_settings
      #   The URL shortener feature allows automatic replacement of URLs that were
      #   generated using a public URL shortener service. Some examples include bit.do,
      #   bit.ly, goo.gl, ht.ly, is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com.
      #   Such URLs are replaced with with links generated by Telnyx. The use of custom
      #   links can improve branding and message deliverability.
      #
      #   To disable this feature, set the object field to `null`.
      #
      #   @return [Telnyx::Models::URLShortenerSettings, nil]
      optional :url_shortener_settings, -> { Telnyx::URLShortenerSettings }, nil?: true

      # @!attribute v1_secret
      #   Secret used to authenticate with v1 endpoints.
      #
      #   @return [String, nil]
      optional :v1_secret, String

      # @!attribute webhook_api_version
      #   Determines which webhook format will be used, Telnyx API v1, v2, or a legacy
      #   2010-04-01 format.
      #
      #   @return [Symbol, Telnyx::Models::MessagingProfile::WebhookAPIVersion, nil]
      optional :webhook_api_version, enum: -> { Telnyx::MessagingProfile::WebhookAPIVersion }

      # @!attribute webhook_failover_url
      #   The failover URL where webhooks related to this messaging profile will be sent
      #   if sending to the primary URL fails.
      #
      #   @return [String, nil]
      optional :webhook_failover_url, String, nil?: true

      # @!attribute webhook_url
      #   The URL where webhooks related to this messaging profile will be sent.
      #
      #   @return [String, nil]
      optional :webhook_url, String, nil?: true

      # @!attribute whitelisted_destinations
      #   Destinations to which the messaging profile is allowed to send. The elements in
      #   the list must be valid ISO 3166-1 alpha-2 country codes. If set to `["*"]`, all
      #   destinations will be allowed.
      #
      #   @return [Array<String>, nil]
      optional :whitelisted_destinations, Telnyx::Internal::Type::ArrayOf[String]

      response_only do
        # @!attribute id
        #   Identifies the type of resource.
        #
        #   @return [String, nil]
        optional :id, String

        # @!attribute created_at
        #   ISO 8601 formatted date indicating when the resource was created.
        #
        #   @return [Time, nil]
        optional :created_at, Time

        # @!attribute record_type
        #   Identifies the type of the resource.
        #
        #   @return [Symbol, Telnyx::Models::MessagingProfile::RecordType, nil]
        optional :record_type, enum: -> { Telnyx::MessagingProfile::RecordType }

        # @!attribute updated_at
        #   ISO 8601 formatted date indicating when the resource was updated.
        #
        #   @return [Time, nil]
        optional :updated_at, Time
      end

      # @!method initialize(id: nil, alpha_sender: nil, created_at: nil, daily_spend_limit: nil, daily_spend_limit_enabled: nil, enabled: nil, mms_fall_back_to_sms: nil, mms_transcoding: nil, mobile_only: nil, name: nil, number_pool_settings: nil, record_type: nil, updated_at: nil, url_shortener_settings: nil, v1_secret: nil, webhook_api_version: nil, webhook_failover_url: nil, webhook_url: nil, whitelisted_destinations: nil)
      #   Some parameter documentations has been truncated, see
      #   {Telnyx::Models::MessagingProfile} for more details.
      #
      #   @param id [String] Identifies the type of resource.
      #
      #   @param alpha_sender [String, nil] The alphanumeric sender ID to use when sending to destinations that require an a
      #
      #   @param created_at [Time] ISO 8601 formatted date indicating when the resource was created.
      #
      #   @param daily_spend_limit [String] The maximum amount of money (in USD) that can be spent by this profile before mi
      #
      #   @param daily_spend_limit_enabled [Boolean] Whether to enforce the value configured by `daily_spend_limit`.
      #
      #   @param enabled [Boolean] Specifies whether the messaging profile is enabled or not.
      #
      #   @param mms_fall_back_to_sms [Boolean] enables SMS fallback for MMS messages.
      #
      #   @param mms_transcoding [Boolean] enables automated resizing of MMS media.
      #
      #   @param mobile_only [Boolean] Send messages only to mobile phone numbers.
      #
      #   @param name [String] A user friendly name for the messaging profile.
      #
      #   @param number_pool_settings [Telnyx::Models::NumberPoolSettings, nil] Number Pool allows you to send messages from a pool of numbers of different type
      #
      #   @param record_type [Symbol, Telnyx::Models::MessagingProfile::RecordType] Identifies the type of the resource.
      #
      #   @param updated_at [Time] ISO 8601 formatted date indicating when the resource was updated.
      #
      #   @param url_shortener_settings [Telnyx::Models::URLShortenerSettings, nil] The URL shortener feature allows automatic replacement of URLs that were generat
      #
      #   @param v1_secret [String] Secret used to authenticate with v1 endpoints.
      #
      #   @param webhook_api_version [Symbol, Telnyx::Models::MessagingProfile::WebhookAPIVersion] Determines which webhook format will be used, Telnyx API v1, v2, or a legacy 201
      #
      #   @param webhook_failover_url [String, nil] The failover URL where webhooks related to this messaging profile will be sent i
      #
      #   @param webhook_url [String, nil] The URL where webhooks related to this messaging profile will be sent.
      #
      #   @param whitelisted_destinations [Array<String>] Destinations to which the messaging profile is allowed to send. The elements in

      # Identifies the type of the resource.
      #
      # @see Telnyx::Models::MessagingProfile#record_type
      module RecordType
        extend Telnyx::Internal::Type::Enum

        MESSAGING_PROFILE = :messaging_profile

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # Determines which webhook format will be used, Telnyx API v1, v2, or a legacy
      # 2010-04-01 format.
      #
      # @see Telnyx::Models::MessagingProfile#webhook_api_version
      module WebhookAPIVersion
        extend Telnyx::Internal::Type::Enum

        WEBHOOK_API_VERSION_1 = :"1"
        WEBHOOK_API_VERSION_2 = :"2"
        WEBHOOK_API_VERSION_2010_04_01 = :"2010-04-01"

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
