# frozen_string_literal: true

module Telnyx
  module Models
    # @see Telnyx::Resources::PartnerCampaigns#list_shared_by_me
    class PartnerCampaignListSharedByMeResponse < Telnyx::Internal::Type::BaseModel
      # @!attribute page
      #
      #   @return [Integer, nil]
      optional :page, Integer

      # @!attribute records
      #
      #   @return [Array<Telnyx::Models::PartnerCampaignListSharedByMeResponse::Record>, nil]
      optional :records,
               -> { Telnyx::Internal::Type::ArrayOf[Telnyx::Models::PartnerCampaignListSharedByMeResponse::Record] }

      # @!attribute total_records
      #
      #   @return [Integer, nil]
      optional :total_records, Integer, api_name: :totalRecords

      # @!method initialize(page: nil, records: nil, total_records: nil)
      #   @param page [Integer]
      #   @param records [Array<Telnyx::Models::PartnerCampaignListSharedByMeResponse::Record>]
      #   @param total_records [Integer]

      class Record < Telnyx::Internal::Type::BaseModel
        # @!attribute brand_id
        #   Alphanumeric identifier of the brand associated with this campaign.
        #
        #   @return [String]
        required :brand_id, String, api_name: :brandId

        # @!attribute campaign_id
        #   Alphanumeric identifier assigned by the registry for a campaign. This identifier
        #   is required by the NetNumber OSR SMS enabling process of 10DLC.
        #
        #   @return [String]
        required :campaign_id, String, api_name: :campaignId

        # @!attribute usecase
        #   Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase`
        #   operation to retrieve usecases available for given brand.
        #
        #   @return [String]
        required :usecase, String

        # @!attribute create_date
        #   Unix timestamp when campaign was created.
        #
        #   @return [String, nil]
        optional :create_date, String, api_name: :createDate

        # @!attribute status
        #   Current campaign status. Possible values: ACTIVE, EXPIRED. A newly created
        #   campaign defaults to ACTIVE status.
        #
        #   @return [String, nil]
        optional :status, String

        # @!method initialize(brand_id:, campaign_id:, usecase:, create_date: nil, status: nil)
        #   Some parameter documentations has been truncated, see
        #   {Telnyx::Models::PartnerCampaignListSharedByMeResponse::Record} for more
        #   details.
        #
        #   Campaign is generated by the 10DLC registry once the corresponding campaign
        #   request is approved. Each campaign is assigned a unique identifier -
        #   **campaignId**. Once a campaign is activated, limited information is published
        #   to the NetNumber OSR service for consumption by members of the ecosystem. When a
        #   campaign is suspended(reversible) or expired(non-reversible), campaign data is
        #   deleted from the OSR service. Most attributes of campaignare immutable,
        #   including **usecase**, **vertical**, **brandId** and **cspId**.
        #
        #   @param brand_id [String] Alphanumeric identifier of the brand associated with this campaign.
        #
        #   @param campaign_id [String] Alphanumeric identifier assigned by the registry for a campaign. This identifier
        #
        #   @param usecase [String] Campaign usecase. Must be of defined valid types. Use `/registry/enum/usecase` o
        #
        #   @param create_date [String] Unix timestamp when campaign was created.
        #
        #   @param status [String] Current campaign status. Possible values: ACTIVE, EXPIRED. A newly created campa
      end
    end
  end
end
