module Telnyx
  module Resources
    class AI
      class Assistants
        attr_reader tests: Telnyx::Resources::AI::Assistants::Tests

        attr_reader canary_deploys: Telnyx::Resources::AI::Assistants::CanaryDeploys

        attr_reader scheduled_events: Telnyx::Resources::AI::Assistants::ScheduledEvents

        attr_reader tools: Telnyx::Resources::AI::Assistants::Tools

        attr_reader versions: Telnyx::Resources::AI::Assistants::Versions

        def create: (
          instructions: String,
          model: String,
          name: String,
          ?description: String,
          ?dynamic_variables: ::Hash[Symbol, top],
          ?dynamic_variables_webhook_url: String,
          ?enabled_features: ::Array[Telnyx::Models::AI::enabled_features],
          ?greeting: String,
          ?insight_settings: Telnyx::AI::InsightSettings,
          ?llm_api_key_ref: String,
          ?messaging_settings: Telnyx::AI::MessagingSettings,
          ?privacy_settings: Telnyx::AI::PrivacySettings,
          ?telephony_settings: Telnyx::AI::TelephonySettings,
          ?tools: ::Array[Telnyx::Models::AI::assistant_tool],
          ?transcription: Telnyx::AI::TranscriptionSettings,
          ?voice_settings: Telnyx::AI::VoiceSettings,
          ?widget_settings: Telnyx::AI::AssistantCreateParams::WidgetSettings,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::InferenceEmbedding

        def retrieve: (
          String assistant_id,
          ?call_control_id: String,
          ?fetch_dynamic_variables_from_webhook: bool,
          ?from: String,
          ?to: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::InferenceEmbedding

        def update: (
          String assistant_id,
          ?description: String,
          ?dynamic_variables: ::Hash[Symbol, top],
          ?dynamic_variables_webhook_url: String,
          ?enabled_features: ::Array[Telnyx::Models::AI::enabled_features],
          ?greeting: String,
          ?insight_settings: Telnyx::AI::InsightSettings,
          ?instructions: String,
          ?llm_api_key_ref: String,
          ?messaging_settings: Telnyx::AI::MessagingSettings,
          ?model: String,
          ?name: String,
          ?privacy_settings: Telnyx::AI::PrivacySettings,
          ?promote_to_main: bool,
          ?telephony_settings: Telnyx::AI::TelephonySettings,
          ?tools: ::Array[Telnyx::Models::AI::assistant_tool],
          ?transcription: Telnyx::AI::TranscriptionSettings,
          ?voice_settings: Telnyx::AI::VoiceSettings,
          ?widget_settings: Telnyx::AI::AssistantUpdateParams::WidgetSettings,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::InferenceEmbedding

        def list: (
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::AssistantsList

        def delete: (
          String assistant_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::AI::AssistantDeleteResponse

        def chat: (
          String assistant_id,
          content: String,
          conversation_id: String,
          ?name: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::AI::AssistantChatResponse

        def clone_: (
          String assistant_id,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::InferenceEmbedding

        def get_texml: (
          String assistant_id,
          ?request_options: Telnyx::request_opts
        ) -> String

        def imports: (
          api_key_ref: String,
          provider: Telnyx::Models::AI::AssistantImportsParams::provider,
          ?import_ids: ::Array[String],
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::AI::AssistantsList

        def send_sms: (
          String assistant_id,
          from: String,
          to: String,
          ?conversation_metadata: ::Hash[Symbol, Telnyx::Models::AI::AssistantSendSMSParams::conversation_metadata],
          ?should_create_conversation: bool,
          ?text: String,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::AI::AssistantSendSMSResponse

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
