module Telnyx
  module Resources
    class AI
      class Audio
        def transcribe: (
          model: Telnyx::Models::AI::AudioTranscribeParams::model,
          ?file: Telnyx::Internal::file_input,
          ?file_url: String,
          ?language: String,
          ?model_config: ::Hash[Symbol, top],
          ?response_format: Telnyx::Models::AI::AudioTranscribeParams::response_format,
          ?timestamp_granularities: Telnyx::Models::AI::AudioTranscribeParams::timestamp_granularities,
          ?request_options: Telnyx::request_opts
        ) -> Telnyx::Models::AI::AudioTranscribeResponse

        def initialize: (client: Telnyx::Client) -> void
      end
    end
  end
end
