module Telnyx
  module Models
    module Enterprises
      module Reputation
        type loa_render_params =
          {
            enterprise_id: String,
            agent: Telnyx::Enterprises::Reputation::AgentInput,
            signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature
          }
          & Telnyx::Internal::Type::request_parameters

        class LoaRenderParams < Telnyx::Internal::Type::BaseModel
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          attr_accessor enterprise_id: String

          attr_reader agent: Telnyx::Enterprises::Reputation::AgentInput?

          def agent=: (
            Telnyx::Enterprises::Reputation::AgentInput
          ) -> Telnyx::Enterprises::Reputation::AgentInput

          attr_reader signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature?

          def signature=: (
            Telnyx::Enterprises::Reputation::LoaRenderParams::Signature
          ) -> Telnyx::Enterprises::Reputation::LoaRenderParams::Signature

          def initialize: (
            enterprise_id: String,
            ?agent: Telnyx::Enterprises::Reputation::AgentInput,
            ?signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature,
            ?request_options: Telnyx::request_opts
          ) -> void

          def to_hash: -> {
            enterprise_id: String,
            agent: Telnyx::Enterprises::Reputation::AgentInput,
            signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature,
            request_options: Telnyx::RequestOptions
          }

          type signature = { :image_base64 => String, signer_name: String? }

          class Signature < Telnyx::Internal::Type::BaseModel
            attr_accessor image_base64: String

            attr_accessor signer_name: String?

            def initialize: (
              image_base64: String,
              ?signer_name: String?
            ) -> void

            def to_hash: -> { :image_base64 => String, signer_name: String? }
          end
        end
      end
    end
  end
end
