module Telnyx
  module Models
    module Enterprises
      module Reputation
        type loa_render_params =
          {
            enterprise_id: String,
            agent: Telnyx::Enterprises::Reputation::LoaRenderParams::Agent,
            signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature
          }
          & Telnyx::Internal::Type::request_parameters

        class LoaRenderParams < Telnyx::Internal::Type::BaseModel
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          attr_accessor enterprise_id: String

          attr_reader agent: Telnyx::Enterprises::Reputation::LoaRenderParams::Agent?

          def agent=: (
            Telnyx::Enterprises::Reputation::LoaRenderParams::Agent
          ) -> Telnyx::Enterprises::Reputation::LoaRenderParams::Agent

          attr_reader signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature?

          def signature=: (
            Telnyx::Enterprises::Reputation::LoaRenderParams::Signature
          ) -> Telnyx::Enterprises::Reputation::LoaRenderParams::Signature

          def initialize: (
            enterprise_id: String,
            ?agent: Telnyx::Enterprises::Reputation::LoaRenderParams::Agent,
            ?signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature,
            ?request_options: Telnyx::request_opts
          ) -> void

          def to_hash: -> {
            enterprise_id: String,
            agent: Telnyx::Enterprises::Reputation::LoaRenderParams::Agent,
            signature: Telnyx::Enterprises::Reputation::LoaRenderParams::Signature,
            request_options: Telnyx::RequestOptions
          }

          type agent =
            {
              administrative_area: String,
              city: String,
              contact_email: String,
              contact_name: String,
              contact_phone: String,
              contact_title: String,
              country: String,
              legal_name: String,
              postal_code: String,
              street_address: String,
              dba: String?,
              extended_address: String?
            }

          class Agent < Telnyx::Internal::Type::BaseModel
            attr_accessor administrative_area: String

            attr_accessor city: String

            attr_accessor contact_email: String

            attr_accessor contact_name: String

            attr_accessor contact_phone: String

            attr_accessor contact_title: String

            attr_accessor country: String

            attr_accessor legal_name: String

            attr_accessor postal_code: String

            attr_accessor street_address: String

            attr_accessor dba: String?

            attr_accessor extended_address: String?

            def initialize: (
              administrative_area: String,
              city: String,
              contact_email: String,
              contact_name: String,
              contact_phone: String,
              contact_title: String,
              country: String,
              legal_name: String,
              postal_code: String,
              street_address: String,
              ?dba: String?,
              ?extended_address: String?
            ) -> void

            def to_hash: -> {
              administrative_area: String,
              city: String,
              contact_email: String,
              contact_name: String,
              contact_phone: String,
              contact_title: String,
              country: String,
              legal_name: String,
              postal_code: String,
              street_address: String,
              dba: String?,
              extended_address: String?
            }
          end

          type signature = { :image_base64 => String, signer_name: String? }

          class Signature < Telnyx::Internal::Type::BaseModel
            attr_accessor image_base64: String

            attr_accessor signer_name: String?

            def initialize: (
              image_base64: String,
              ?signer_name: String?
            ) -> void

            def to_hash: -> { :image_base64 => String, signer_name: String? }
          end
        end
      end
    end
  end
end
