module Telnyx
  module Models
    module Enterprises
      module Reputation
        type loa_patch_all_params =
          { enterprise_id: String, loa_document_id: String }
          & Telnyx::Internal::Type::request_parameters

        class LoaPatchAllParams < Telnyx::Internal::Type::BaseModel
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          attr_accessor enterprise_id: String

          attr_accessor loa_document_id: String

          def initialize: (
            enterprise_id: String,
            loa_document_id: String,
            ?request_options: Telnyx::request_opts
          ) -> void

          def to_hash: -> {
            enterprise_id: String,
            loa_document_id: String,
            request_options: Telnyx::RequestOptions
          }
        end
      end
    end
  end
end
