module Telnyx
  module Models
    module Enterprises
      module Reputation
        type remediation_list_response =
          {
            id: String,
            call_purpose: String,
            created_at: Time,
            phone_numbers_count: Integer,
            status: Telnyx::Models::Enterprises::Reputation::remediation_status,
            updated_at: Time,
            :tier1_completed_at => Time?,
            :tier2_completed_at => Time?
          }

        class RemediationListResponse < Telnyx::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor call_purpose: String

          attr_accessor created_at: Time

          attr_accessor phone_numbers_count: Integer

          attr_accessor status: Telnyx::Models::Enterprises::Reputation::remediation_status

          attr_accessor updated_at: Time

          attr_accessor tier1_completed_at: Time?

          attr_accessor tier2_completed_at: Time?

          def initialize: (
            id: String,
            call_purpose: String,
            created_at: Time,
            phone_numbers_count: Integer,
            status: Telnyx::Models::Enterprises::Reputation::remediation_status,
            updated_at: Time,
            ?tier1_completed_at: Time?,
            ?tier2_completed_at: Time?
          ) -> void

          def to_hash: -> {
            id: String,
            call_purpose: String,
            created_at: Time,
            phone_numbers_count: Integer,
            status: Telnyx::Models::Enterprises::Reputation::remediation_status,
            updated_at: Time,
            :tier1_completed_at => Time?,
            :tier2_completed_at => Time?
          }
        end
      end
    end
  end
end
