module Telnyx
  module Models
    module Enterprises
      module Reputation
        type remediation_request_wrapped =
          { data: Telnyx::Enterprises::Reputation::RemediationRequest }

        class RemediationRequestWrapped < Telnyx::Internal::Type::BaseModel
          attr_accessor data: Telnyx::Enterprises::Reputation::RemediationRequest

          def initialize: (
            data: Telnyx::Enterprises::Reputation::RemediationRequest
          ) -> void

          def to_hash: -> {
            data: Telnyx::Enterprises::Reputation::RemediationRequest
          }
        end
      end
    end
  end
end
