module Telnyx
  module Models
    module Legacy
      module Reporting
        module UsageReports
          type voice_retrieve_response =
            {
              data: Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy
            }

          class VoiceRetrieveResponse < Telnyx::Internal::Type::BaseModel
            attr_reader data: Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy?

            def data=: (
              Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy
            ) -> Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy

            def initialize: (
              ?data: Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy
            ) -> void

            def to_hash: -> {
              data: Telnyx::Legacy::Reporting::UsageReports::CdrUsageReportResponseLegacy
            }
          end
        end
      end
    end
  end
end
