module Telnyx
  module Models
    module Storage
      type cloudfs_filesystem_response_wrapper =
        { data: Telnyx::Storage::CloudfsFilesystem }

      class CloudfsFilesystemResponseWrapper < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::Storage::CloudfsFilesystem?

        def data=: (
          Telnyx::Storage::CloudfsFilesystem
        ) -> Telnyx::Storage::CloudfsFilesystem

        def initialize: (?data: Telnyx::Storage::CloudfsFilesystem) -> void

        def to_hash: -> { data: Telnyx::Storage::CloudfsFilesystem }
      end
    end
  end
end
