module Telnyx
  module Models
    module Messaging10dlc
      module Brand
        type external_vetting_order_params =
          { evp_id: String, vetting_class: String }
          & Telnyx::Internal::Type::request_parameters

        class ExternalVettingOrderParams < Telnyx::Internal::Type::BaseModel
          extend Telnyx::Internal::Type::RequestParameters::Converter
          include Telnyx::Internal::Type::RequestParameters

          attr_accessor evp_id: String

          attr_accessor vetting_class: String

          def initialize: (
            evp_id: String,
            vetting_class: String,
            ?request_options: Telnyx::request_opts
          ) -> void

          def to_hash: -> {
            evp_id: String,
            vetting_class: String,
            request_options: Telnyx::RequestOptions
          }
        end
      end
    end
  end
end
