module Telnyx
  module Models
    module PortingOrders
      type action_confirm_response =
        {
          data: Telnyx::PortingOrder,
          meta: Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta
        }

      class ActionConfirmResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::PortingOrder?

        def data=: (Telnyx::PortingOrder) -> Telnyx::PortingOrder

        attr_reader meta: Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta?

        def meta=: (
          Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta
        ) -> Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta

        def initialize: (
          ?data: Telnyx::PortingOrder,
          ?meta: Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta
        ) -> void

        def to_hash: -> {
          data: Telnyx::PortingOrder,
          meta: Telnyx::Models::PortingOrders::ActionConfirmResponse::Meta
        }

        type meta = { phone_numbers_url: String }

        class Meta < Telnyx::Internal::Type::BaseModel
          attr_reader phone_numbers_url: String?

          def phone_numbers_url=: (String) -> String

          def initialize: (?phone_numbers_url: String) -> void

          def to_hash: -> { phone_numbers_url: String }
        end
      end
    end
  end
end
