module Telnyx
  module Models
    module PortingOrders
      type activation_job_update_params =
        { id: String, activate_at: Time }
        & Telnyx::Internal::Type::request_parameters

      class ActivationJobUpdateParams < Telnyx::Internal::Type::BaseModel
        extend Telnyx::Internal::Type::RequestParameters::Converter
        include Telnyx::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader activate_at: Time?

        def activate_at=: (Time) -> Time

        def initialize: (
          id: String,
          ?activate_at: Time,
          ?request_options: Telnyx::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          activate_at: Time,
          request_options: Telnyx::RequestOptions
        }
      end
    end
  end
end
