module Telnyx
  module Models
    module PortingOrders
      type comment_create_response =
        { data: Telnyx::PortingOrders::PortingOrdersComment }

      class CommentCreateResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: Telnyx::PortingOrders::PortingOrdersComment?

        def data=: (
          Telnyx::PortingOrders::PortingOrdersComment
        ) -> Telnyx::PortingOrders::PortingOrdersComment

        def initialize: (
          ?data: Telnyx::PortingOrders::PortingOrdersComment
        ) -> void

        def to_hash: -> { data: Telnyx::PortingOrders::PortingOrdersComment }
      end
    end
  end
end
