module Telnyx
  module Models
    module PortingOrders
      type phone_number_configuration_create_response =
        {
          data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]
        }

      class PhoneNumberConfigurationCreateResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]?

        def data=: (
          ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]
        ) -> ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]

        def initialize: (
          ?data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberConfiguration]
        }
      end
    end
  end
end
