module Telnyx
  module Models
    module PortingOrders
      type phone_number_block_list_response =
        {
          data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock],
          meta: Telnyx::PaginationMeta
        }

      class PhoneNumberBlockListResponse < Telnyx::Internal::Type::BaseModel
        attr_reader data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock]?

        def data=: (
          ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock]
        ) -> ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock]

        attr_reader meta: Telnyx::PaginationMeta?

        def meta=: (Telnyx::PaginationMeta) -> Telnyx::PaginationMeta

        def initialize: (
          ?data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock],
          ?meta: Telnyx::PaginationMeta
        ) -> void

        def to_hash: -> {
          data: ::Array[Telnyx::PortingOrders::PortingPhoneNumberBlock],
          meta: Telnyx::PaginationMeta
        }
      end
    end
  end
end
