module Telnyx
  module Models
    class EmailBlockImportResponse = EmailBlocks::EmailBlockImportResponse

    module EmailBlocks
      type email_block_import_response =
        { data: Telnyx::EmailBlocks::EmailBlockImport }

      class EmailBlockImportResponse < Telnyx::Internal::Type::BaseModel
        attr_accessor data: Telnyx::EmailBlocks::EmailBlockImport

        def initialize: (data: Telnyx::EmailBlocks::EmailBlockImport) -> void

        def to_hash: -> { data: Telnyx::EmailBlocks::EmailBlockImport }
      end
    end
  end
end
